Repository trueforge-org/truecharts, pull requests merged in 2021-02, with the labels that each got.

#60 Add Common Chart
  .test/charts/common-test_spec.rb
  library/common-test/Chart.yaml
  library/common-test/ci/basic-values.yaml
  library/common-test/ci/codeserver-values.yaml
  library/common-test/templates/common.yaml
  library/common-test/values.yaml
  library/common/.helmignore
  library/common/CHANGELOG.md
  library/common/Chart.yaml
  library/common/LICENSE
  library/common/README.md
  library/common/_ingress.tpl
  library/common/templates/_all.tpl
  library/common/templates/_daemonset.tpl
  library/common/templates/_deployment.tpl
  library/common/templates/_ingress.tpl
  library/common/templates/_notes.tpl
  library/common/templates/_pvc.tpl
  library/common/templates/_service.tpl
  library/common/templates/_serviceaccount.tpl
  library/common/templates/_statefulset.tpl
  library/common/templates/addons/code-server/_codeserver.tpl
  library/common/templates/addons/code-server/_container.tpl
  library/common/templates/addons/vpn/_configmap.tpl
  library/common/templates/addons/vpn/_networkpolicy.tpl
  library/common/templates/addons/vpn/_volume.tpl
  library/common/templates/addons/vpn/_vpn.tpl
  library/common/templates/addons/vpn/openvpn/_addon.tpl
  library/common/templates/addons/vpn/openvpn/_container.tpl
  library/common/templates/addons/vpn/openvpn/_secret.tpl
  library/common/templates/addons/vpn/wireguard/_addon.tpl
  library/common/templates/addons/vpn/wireguard/_container.tpl
  library/common/templates/classes/_ingress.tpl
  library/common/templates/classes/_pvc.tpl
  library/common/templates/classes/_service.tpl
  library/common/templates/classes/_service_ports.tpl
  library/common/templates/custom/_appService.tpl
  library/common/templates/custom/_appStorage.tpl
  library/common/templates/custom/_appingress.tpl
  library/common/templates/custom/classes/_appAuthForward.tpl
  library/common/templates/custom/classes/_appIngressHTTP.tpl
  library/common/templates/custom/classes/_appIngressTCP.tpl
  library/common/templates/custom/classes/_appIngressUDP.tpl
  library/common/templates/lib/chart/_capabilities.tpl
  library/common/templates/lib/chart/_labels.tpl
  library/common/templates/lib/chart/_names.tpl
  library/common/templates/lib/chart/_values.tpl
  library/common/templates/lib/controller/_container.tpl
  library/common/templates/lib/controller/_pod.tpl
  library/common/templates/lib/controller/_ports.tpl
  library/common/templates/lib/controller/_probes.tpl
  library/common/templates/lib/controller/_volumes.tpl
  library/common/values.yaml
Labels: enhancement

#69 Update and clean common chart
  .test/charts/common-test_spec.rb
  library/common/CHANGELOG.md
  library/common/Chart.yaml
  library/common/_ingress.tpl
  library/common/templates/lib/controller/_container.tpl
  library/common/values.yaml
Labels: enhancement

#75 Fix traefik portal
  charts/traefik/0.1.1/Chart.lock
  charts/traefik/0.2.0/.helmignore
  charts/traefik/0.2.0/Chart.lock
  charts/traefik/0.2.0/Chart.yaml
  charts/traefik/0.2.0/Guidelines.md
  charts/traefik/0.2.0/LICENSE
  charts/traefik/0.2.0/README.md
  charts/traefik/0.2.0/app-readme.md
  charts/traefik/0.2.0/charts/cert-manager-v1.1.0.tgz
  charts/traefik/0.2.0/charts/reflector-5.4.17.tgz
  charts/traefik/0.2.0/crds/ingressroute.yaml
  charts/traefik/0.2.0/crds/ingressroutetcp.yaml
  charts/traefik/0.2.0/crds/ingressrouteudp.yaml
  charts/traefik/0.2.0/crds/middlewares.yaml
  charts/traefik/0.2.0/crds/serverstransports.yaml
  charts/traefik/0.2.0/crds/tlsoptions.yaml
  charts/traefik/0.2.0/crds/tlsstores.yaml
  charts/traefik/0.2.0/crds/traefikservices.yaml
  charts/traefik/0.2.0/questions.yaml
  charts/traefik/0.2.0/templates/_helpers.tpl
  charts/traefik/0.2.0/templates/_podtemplate.tpl
  charts/traefik/0.2.0/templates/custom/_appStorage.tpl
  charts/traefik/0.2.0/templates/custom/appingress.yaml
  charts/traefik/0.2.0/templates/custom/clusterissuer.yaml
  charts/traefik/0.2.0/templates/custom/delay_postinstall.yaml
  charts/traefik/0.2.0/templates/custom/middlewares.yaml
  charts/traefik/0.2.0/templates/custom/tlsoptions.yaml
  charts/traefik/0.2.0/templates/custom/wildcard.yaml
  charts/traefik/0.2.0/templates/daemonset.yaml
  charts/traefik/0.2.0/templates/dashboard-hook-ingressroute.yaml
  charts/traefik/0.2.0/templates/deployment.yaml
  charts/traefik/0.2.0/templates/gateway.yaml
  charts/traefik/0.2.0/templates/gatewayclass.yaml
  charts/traefik/0.2.0/templates/hpa.yaml
  charts/traefik/0.2.0/templates/ingressclass.yaml
  charts/traefik/0.2.0/templates/poddisruptionbudget.yaml
  charts/traefik/0.2.0/templates/pvc.yaml
  charts/traefik/0.2.0/templates/rbac/clusterrole.yaml
  charts/traefik/0.2.0/templates/rbac/clusterrolebinding.yaml
  charts/traefik/0.2.0/templates/rbac/podsecuritypolicy.yaml
  charts/traefik/0.2.0/templates/rbac/role.yaml
  charts/traefik/0.2.0/templates/rbac/rolebinding.yaml
  charts/traefik/0.2.0/templates/rbac/serviceaccount.yaml
  charts/traefik/0.2.0/templates/service.yaml
  charts/traefik/0.2.0/templates/tlsoption.yaml
  charts/traefik/0.2.0/test_values.yaml
  charts/traefik/0.2.0/values.yaml
  library/common/Chart.yaml
  library/common/templates/custom/classes/_appIngressHTTP.tpl
  library/common/templates/custom/classes/_appIngressTCP.tpl
Labels: bug

#80 Small Tests and repo fixes
  .github/PULL_REQUEST_TEMPLATE.md
  .github/SECURITY.md
  .gitignore
  .pre-commit-config.yaml
  features_capability.json
  library/common-test/Chart.yaml
  library/common-test/ci/basic-values.yaml
  library/common-test/ci/codeserver-values.yaml
  library/common-test/values.yaml
  update_dependencies
Labels: enhancement

#78 rename all custom scripts to common.custom.*
  library/common/Chart.yaml
  library/common/templates/_all.tpl
  library/common/templates/custom/_appService.tpl
  library/common/templates/custom/_appStorage.tpl
  library/common/templates/custom/_appingress.tpl
  library/common/templates/custom/classes/_appAuthForward.tpl
  library/common/templates/custom/classes/_appIngressHTTP.tpl
  library/common/templates/custom/classes/_appIngressTCP.tpl
  library/common/templates/custom/classes/_appIngressUDP.tpl
  library/common/templates/lib/controller/_container.tpl
  library/common/templates/lib/controller/_volumes.tpl
Labels: enhancement

#79 Initial integration of bitnami/common
  library/common/Bitnami_README.md
  library/common/Chart.yaml
  library/common/templates/bitnami/_affinities.tpl
  library/common/templates/bitnami/_capabilities.tpl
  library/common/templates/bitnami/_errors.tpl
  library/common/templates/bitnami/_images.tpl
  library/common/templates/bitnami/_ingress.tpl
  library/common/templates/bitnami/_labels.tpl
  library/common/templates/bitnami/_names.tpl
  library/common/templates/bitnami/_secrets.tpl
  library/common/templates/bitnami/_storage.tpl
  library/common/templates/bitnami/_tplvalues.tpl
  library/common/templates/bitnami/_utils.tpl
  library/common/templates/bitnami/_warnings.tpl
  library/common/templates/bitnami/validations/_cassandra.tpl
  library/common/templates/bitnami/validations/_mariadb.tpl
  library/common/templates/bitnami/validations/_mongodb.tpl
  library/common/templates/bitnami/validations/_postgresql.tpl
  library/common/templates/bitnami/validations/_redis.tpl
  library/common/templates/bitnami/validations/_validations.tpl
Labels: enhancement

#90 fix 2 broken icons
  charts/jellyfin/0.3.1/.helmignore
  charts/jellyfin/0.3.1/Chart.lock
  charts/jellyfin/0.3.1/Chart.yaml
  charts/jellyfin/0.3.1/LICENSE
  charts/jellyfin/0.3.1/README.md
  charts/jellyfin/0.3.1/app-readme.md
  charts/jellyfin/0.3.1/charts/common-0.12.0.tgz
  charts/jellyfin/0.3.1/questions.yaml
  charts/jellyfin/0.3.1/templates/common.yaml
  charts/jellyfin/0.3.1/test_values.yaml
  charts/jellyfin/0.3.1/values.yaml
  charts/jellyfin/item.yaml
  charts/kms/0.3.1/.helmignore
  charts/kms/0.3.1/Chart.lock
  charts/kms/0.3.1/Chart.yaml
  charts/kms/0.3.1/LICENSE
  charts/kms/0.3.1/README.md
  charts/kms/0.3.1/app-readme.md
  charts/kms/0.3.1/charts/common-0.12.0.tgz
  charts/kms/0.3.1/questions.yaml
  charts/kms/0.3.1/templates/common.yaml
  charts/kms/0.3.1/test_values.yaml
  charts/kms/0.3.1/values.yaml
  charts/kms/item.yaml
Labels: bug

#98 removes appVolumesEnabled
  library/common/Chart.yaml
  library/common/templates/custom/_appStorage.tpl
Labels: bug

#108 Add Collabora App
  charts/collabora-online/0.0.1/Chart.yaml
  charts/collabora-online/0.0.1/README.md
  charts/collabora-online/0.0.1/app-readme.md
  charts/collabora-online/0.0.1/charts/common-0.12.2.tgz
  charts/collabora-online/0.0.1/questions.yaml
  charts/collabora-online/0.0.1/templates/NOTES.txt
  charts/collabora-online/0.0.1/templates/common.yaml
  charts/collabora-online/0.0.1/test_values.yaml
  charts/collabora-online/0.0.1/values.yaml
  charts/collabora-online/icon.png
  charts/collabora-online/item.yaml
Labels: New App Request

#112 Update common 3.0.1
  library/common-test/Chart.yaml
  library/common-test/ci/basic-values.yaml
  library/common-test/ci/codeserver-values.yaml
  library/common-test/values.yaml
  library/common/CHANGELOG.md
  library/common/Chart.yaml
  library/common/templates/_notes.tpl
  library/common/templates/_service.tpl
  library/common/templates/classes/_ingress.tpl
  library/common/values.yaml
Labels: enhancement

#131 fix-up some questions for volume mounts
  charts/node-red/1.0.1/.helmignore
  charts/node-red/1.0.1/Chart.lock
  charts/node-red/1.0.1/Chart.yaml
  charts/node-red/1.0.1/LICENSE
  charts/node-red/1.0.1/README.md
  charts/node-red/1.0.1/app-readme.md
  charts/node-red/1.0.1/charts/common-1.0.0.tgz
  charts/node-red/1.0.1/questions.yaml
  charts/node-red/1.0.1/templates/common.yaml
  charts/node-red/1.0.1/test_values.yaml
  charts/node-red/1.0.1/values.yaml
  charts/nzbget/1.0.1/.helmignore
  charts/nzbget/1.0.1/Chart.lock
  charts/nzbget/1.0.1/Chart.yaml
  charts/nzbget/1.0.1/LICENSE
  charts/nzbget/1.0.1/README.md
  charts/nzbget/1.0.1/app-readme.md
  charts/nzbget/1.0.1/charts/common-1.0.0.tgz
  charts/nzbget/1.0.1/questions.yaml
  charts/nzbget/1.0.1/templates/NOTES.txt
  charts/nzbget/1.0.1/templates/common.yaml
  charts/nzbget/1.0.1/test_values.yaml
  charts/nzbget/1.0.1/values.yaml
  charts/nzbhydra/1.0.1/.helmignore
  charts/nzbhydra/1.0.1/Chart.lock
  charts/nzbhydra/1.0.1/Chart.yaml
  charts/nzbhydra/1.0.1/LICENSE
  charts/nzbhydra/1.0.1/README.md
  charts/nzbhydra/1.0.1/app-readme.md
  charts/nzbhydra/1.0.1/charts/common-1.0.0.tgz
  charts/nzbhydra/1.0.1/questions.yaml
  charts/nzbhydra/1.0.1/templates/NOTES.txt
  charts/nzbhydra/1.0.1/templates/common.yaml
  charts/nzbhydra/1.0.1/test_values.yaml
  charts/nzbhydra/1.0.1/values.yaml
  charts/sabnzbd/1.0.1/.helmignore
  charts/sabnzbd/1.0.1/Chart.lock
  charts/sabnzbd/1.0.1/Chart.yaml
  charts/sabnzbd/1.0.1/LICENSE
  charts/sabnzbd/1.0.1/README.md
  charts/sabnzbd/1.0.1/app-readme.md
  charts/sabnzbd/1.0.1/charts/common-1.0.0.tgz
  charts/sabnzbd/1.0.1/questions.yaml
  charts/sabnzbd/1.0.1/templates/NOTES.txt
  charts/sabnzbd/1.0.1/templates/common.yaml
  charts/sabnzbd/1.0.1/test_values.yaml
  charts/sabnzbd/1.0.1/values.yaml
Labels: bug

#144 Add PGID and PUID options
  .test/charts/common-test_spec.rb
  library/common/Chart.yaml
  library/common/templates/lib/controller/_container.tpl
  library/common/values.yaml
Labels: bug

#149 Fix 1.1.0
  .test/charts/common-test_spec.rb
  library/common/Chart.yaml
  library/common/templates/lib/controller/_container.tpl
Labels: bug

#134 Set mounted folder permissions
  library/common-test/Chart.yaml
  library/common-test/ci/basic-values.yaml
  library/common-test/ci/codeserver-values.yaml
  library/common-test/values.yaml
  library/common/Chart.yaml
  library/common/templates/_all.tpl
  library/common/templates/custom/_mountPermissions.yaml
  library/common/templates/custom/_mountPermissionsJob.yaml
  library/common/values.yaml
Labels: bug, enhancement

#160 Makes common correctly process TZ, UMASK and lists of env-vars
  .test/charts/common-test_spec.rb
  library/common/Chart.yaml
  library/common/templates/lib/controller/_container.tpl
  library/common/values.yaml
Labels: bug, enhancement

#179 Create wiki update CI
  .github/workflows/wiki-create-docs.yaml
Labels: documentation, enhancement

#175 Adds Handbrake
  charts/handbrake/1.0.0/Chart.yaml
  charts/handbrake/1.0.0/README.md
  charts/handbrake/1.0.0/app-readme.md
  charts/handbrake/1.0.0/charts/common-1.3.0.tgz
  charts/handbrake/1.0.0/questions.yaml
  charts/handbrake/1.0.0/templates/NOTES.txt
  charts/handbrake/1.0.0/templates/common.yaml
  charts/handbrake/1.0.0/test_values.yaml
  charts/handbrake/1.0.0/values.yaml
  charts/handbrake/item.yaml
Labels: New App Request

#191 [Common] Cert and Storage rework
  .tools/fixfolders.sh
  .tools/update_dependencies
  features_capability.json
  library/common/Chart.yaml
  library/common/templates/_all.tpl
  library/common/templates/bitnami/_capabilities.tpl
  library/common/templates/bitnami/_labels.tpl
  library/common/templates/bitnami/_names.tpl
  library/common/templates/classes/_pvc.tpl
  library/common/templates/classes/ingress/_appAuthForward.tpl
  library/common/templates/classes/ingress/_appIngressHTTP.tpl
  library/common/templates/classes/ingress/_appIngressTCP.tpl
  library/common/templates/classes/ingress/_appIngressUDP.tpl
  library/common/templates/classes/ingress/_ingress.tpl
  library/common/templates/lib/bitnamiCompat/_affinities.tpl
  library/common/templates/lib/bitnamiCompat/_ingressBackend.tpl
  library/common/templates/lib/bitnamiCompat/_secrets.tpl
  library/common/templates/lib/bitnamiCompat/_tplvalues.tpl
  library/common/templates/lib/chart/_capabilities.tpl
  library/common/templates/lib/chart/_errors.tpl
  library/common/templates/lib/chart/_images.tpl
  library/common/templates/lib/chart/_labels.tpl
  library/common/templates/lib/chart/_names.tpl
  library/common/templates/lib/chart/_utils.tpl
  library/common/templates/lib/chart/_warnings.tpl
  library/common/templates/lib/controller/_container.tpl
  library/common/templates/lib/controller/_volumes.tpl
  library/common/templates/lib/resources/_appService.tpl
  library/common/templates/lib/resources/_appingress.tpl
  library/common/templates/lib/resources/_certHelpers.tpl
  library/common/templates/lib/resources/_certSecret.yaml
  library/common/templates/lib/resources/_certs.tpl
  library/common/templates/lib/storage/_appStorage.tpl
  library/common/templates/lib/storage/_ixVolumes.tpl
  library/common/templates/lib/storage/_mountPermissions.tpl
  library/common/templates/lib/storage/_mountPermissionsJob.tpl
  library/common/templates/lib/storage/_storageclass.tpl
  library/common/templates/lib/validations/_cassandra.tpl
  library/common/templates/lib/validations/_mariadb.tpl
  library/common/templates/lib/validations/_mongodb.tpl
  library/common/templates/lib/validations/_postgresql.tpl
  library/common/templates/lib/validations/_redis.tpl
  library/common/templates/lib/validations/_validations.tpl
Labels: enhancement

#195 Abstract away certificate creation to support ingress
  library/common/Chart.yaml
  library/common/templates/_all.tpl
  library/common/templates/classes/ingress/_appIngressHTTP.tpl
  library/common/templates/classes/ingress/_appIngressTCP.tpl
  library/common/templates/lib/resources/_appingress.tpl
  library/common/templates/lib/resources/_certHelpers.tpl
  library/common/templates/lib/resources/_certSecret.yaml
Labels: enhancement
