Repository trueforge-org/truecharts, pull requests merged in 2021-12, with the labels that each got.

#1445 fix(transmission): ensure port settings are correct inside transmission
  charts/stable/transmission/Chart.yaml
  charts/stable/transmission/questions.yaml
  charts/stable/transmission/values.yaml
Labels: bug

#1451 feat(security): Render security scan results during build
  .devcontainer/devcontainer.json
  .github/workflows/apps.release.yaml
  .github/workflows/apps.test.yaml
  .github/workflows/common.test.yaml
  .gitignore
  charts/stable/jackett/Chart.yaml
  tools/build-release.sh
Labels: enhancement

#1452 chore(deps): bump common on dependency train
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/promtail/Chart.yaml
  charts/dependency/redis/Chart.yaml
Labels: enhancement

#1461 fix(tests): use GHCR for install tests
  .github/workflows/apps.release.yaml
  .github/workflows/apps.test.yaml
  .github/workflows/common.test.yaml
  charts/stable/jackett/Chart.yaml
  tools/build-release.sh
Labels: bug, enhancement

#1462 feat(ci): generate correct md/html output from trivy
  docs/_static/trivy.css
  output.md
  results.html
  templates/trivy.tpl
  tools/build-release.sh
Labels: enhancement

#1463 feat(ci): Run release pipeline in parallel
  .github/workflows/apps.test.yaml
  tools/build-release.sh
Labels: enhancement

#1473 fix(code-server): correct code-server persistence
  charts/stable/code-server/Chart.yaml
  charts/stable/code-server/questions.yaml
  charts/stable/code-server/values.yaml
Labels: bug

#1470 feat(fireflyiii): add cron support
  charts/stable/fireflyiii/Chart.yaml
  charts/stable/fireflyiii/questions.yaml
  charts/stable/fireflyiii/templates/_cronjob.tpl
  charts/stable/fireflyiii/templates/_secrets.tpl
  charts/stable/fireflyiii/templates/common.yaml
  charts/stable/fireflyiii/values.yaml
Labels: enhancement

#1480 fix(apps): enable redis on 2 apps
  charts/incubator/anonaddy/Chart.yaml
  charts/incubator/friendica/Chart.yaml
Labels: bug

#1478 feat(fireflyiii): enable redis
  charts/stable/fireflyiii/Chart.yaml
  charts/stable/fireflyiii/values.yaml
Labels: enhancement

#1483 feat(code-server): enable persistence and disable password
  charts/stable/code-server/Chart.yaml
  charts/stable/code-server/questions.yaml
  charts/stable/code-server/values.yaml
Labels: bug

#1503 fix(apps): remove `UMASK` as this is taken care from common
  charts/stable/aria2/questions.yaml
  charts/stable/aria2/values.yaml
  charts/stable/calibre-web/values.yaml
  charts/stable/calibre/questions.yaml
  charts/stable/calibre/values.yaml
  charts/stable/photoprism/values.yaml
  charts/stable/qbittorrent/values.yaml
  charts/stable/resilio-sync/values.yaml
Labels: enhancement

#1548 fix(apps): enable secondary services on some new apps
  charts/stable/domoticz/Chart.yaml
  charts/stable/domoticz/values.yaml
  charts/stable/emulatorjs/Chart.yaml
  charts/stable/emulatorjs/values.yaml
  charts/stable/foldingathome/Chart.yaml
  charts/stable/foldingathome/values.yaml
  charts/stable/habridge/Chart.yaml
  charts/stable/habridge/values.yaml
  charts/stable/ipfs/Chart.yaml
  charts/stable/ipfs/values.yaml
  charts/stable/kodi-headless/Chart.yaml
  charts/stable/kodi-headless/values.yaml
  charts/stable/minisatip/Chart.yaml
  charts/stable/minisatip/values.yaml
  charts/stable/pydio-cells/Chart.yaml
  charts/stable/pydio-cells/values.yaml
  charts/stable/quassel-core/Chart.yaml
  charts/stable/quassel-core/values.yaml
  charts/stable/syslog-ng/Chart.yaml
  charts/stable/syslog-ng/values.yaml
Labels: bug

#1549 fix(paperless-ng): app needs r/w access to rootfs
  charts/incubator/tdarr-node/Chart.yaml
  charts/incubator/tdarr-node/questions.yaml
  charts/incubator/tdarr/Chart.yaml
  charts/incubator/tdarr/questions.yaml
  charts/stable/paperless-ng/Chart.yaml
  charts/stable/paperless-ng/questions.yaml
  charts/stable/paperless-ng/values.yaml
Labels: bug

#1601 feat(traefik): allow port-based redirect and move redirect to advanced settings.
  charts/core/traefik/questions.yaml
  charts/core/traefik/templates/_args.tpl
  charts/core/traefik/values.yaml
Labels: bug, enhancement

#1614 fix(traefik): fix default ingress on traefik
  charts/core/prometheus/Chart.yaml
  charts/core/traefik/questions.yaml
Labels: bug

#1627 feat(common): add support for a, renovate compatible, image selector
  charts/library/common/Chart.yaml
  charts/library/common/templates/lib/controller/_container.tpl
  charts/library/common/templates/lib/utils/_images.tpl
  charts/library/common/values.yaml
Labels: enhancement

#1628 feat(deepstack): create deepstack cpu+gpu app as multi-container PoC
  charts/incubator/deepstack/.helmignore
  charts/incubator/deepstack/Chart.yaml
  charts/incubator/deepstack/ci/gpu-values.yaml
  charts/incubator/deepstack/questions.yaml
  charts/incubator/deepstack/templates/common.yaml
  charts/incubator/deepstack/values.yaml
  docs/_static/img/appicons/deepstack-icon.png
Labels: enhancement
