Repository trueforge-org/truecharts, pull requests merged in 2021-09, with the labels that each got.

#882 remove externalInterfaces + add RBAC and networkPolicy support
  charts/library/common/Chart.yaml
  charts/library/common/templates/_HorizontalPodAutoscaler.tpl
  charts/library/common/templates/_all.tpl
  charts/library/common/templates/_networkPolicy.tpl
  charts/library/common/templates/_rbac.tpl
  charts/library/common/templates/classes/_externalInterfaces.tpl
  charts/library/common/templates/configmaps/_portal.tpl
  charts/library/common/templates/jobs/_mountPermissions.tpl
  charts/library/common/values.yaml
  charts/stable/authelia/SCALE/questions.yaml
Labels: enhancement

#884 Add labels to more common objects and add names.fqdn
  charts/library/common/Chart.yaml
  charts/library/common/templates/_networkPolicy.tpl
  charts/library/common/templates/_rbac.tpl
  charts/library/common/templates/configmaps/_portal.tpl
  charts/library/common/templates/lib/chart/_names.tpl
Labels: enhancement

#883 add k8s-gateway
  charts/incubator/k8s-gateway/.helmignore
  charts/incubator/k8s-gateway/CONFIG.md
  charts/incubator/k8s-gateway/Chart.yaml
  charts/incubator/k8s-gateway/README.md
  charts/incubator/k8s-gateway/SCALE/item.yaml
  charts/incubator/k8s-gateway/SCALE/ix_values.yaml
  charts/incubator/k8s-gateway/SCALE/questions.yaml
  charts/incubator/k8s-gateway/app-readme.md
  charts/incubator/k8s-gateway/helm-values.md
  charts/incubator/k8s-gateway/templates/_configmap.tpl
  charts/incubator/k8s-gateway/templates/common.yaml
  charts/incubator/k8s-gateway/values.yaml
Labels: enhancement

#885 Traefik Update Project
  charts/incubator/traefik/.helmignore
  charts/incubator/traefik/CONFIG.md
  charts/incubator/traefik/Chart.yaml
  charts/incubator/traefik/README.md
  charts/incubator/traefik/SCALE/item.yaml
  charts/incubator/traefik/SCALE/ix_values.yaml
  charts/incubator/traefik/SCALE/questions.yaml
  charts/incubator/traefik/app-readme.md
  charts/incubator/traefik/crds/ingressroute.yaml
  charts/incubator/traefik/crds/ingressroutetcp.yaml
  charts/incubator/traefik/crds/ingressrouteudp.yaml
  charts/incubator/traefik/crds/middlewares.yaml
  charts/incubator/traefik/crds/middlewarestcp.yaml
  charts/incubator/traefik/crds/serverstransports.yaml
  charts/incubator/traefik/crds/tlsoptions.yaml
  charts/incubator/traefik/crds/tlsstores.yaml
  charts/incubator/traefik/crds/traefikservices.yaml
  charts/incubator/traefik/helm-values.md
  charts/incubator/traefik/templates/_args.tpl
  charts/incubator/traefik/templates/_helpers.tpl
  charts/incubator/traefik/templates/_ingressclass.tpl
  charts/incubator/traefik/templates/_ingressroute.tpl
  charts/incubator/traefik/templates/_tlsoptions.tpl
  charts/incubator/traefik/templates/common.yaml
  charts/incubator/traefik/templates/middleware-namespace.yaml
  charts/incubator/traefik/templates/middlewares/basic-middleware.yaml
  charts/incubator/traefik/templates/middlewares/basicauth.yaml
  charts/incubator/traefik/templates/middlewares/chain.yaml
  charts/incubator/traefik/templates/middlewares/forwardauth.yaml
  charts/incubator/traefik/templates/middlewares/ratelimit.yaml
  charts/incubator/traefik/templates/middlewares/redirectScheme.yaml
  charts/incubator/traefik/values.yaml
Labels: enhancement

#889 update portal configmap code
  charts/library/common/Chart.yaml
  charts/library/common/templates/configmaps/_portal.tpl
Labels: bug, enhancement

#890 move default middleware location to default namespace
  charts/library/common/Chart.yaml
  charts/library/common/templates/classes/_ingress.tpl
  charts/library/common/templates/configmaps/_portal.tpl
  charts/stable/traefik/Chart.yaml
  charts/stable/traefik/templates/_portalhook.tpl
  charts/stable/traefik/templates/middleware-namespace.yaml
  charts/stable/traefik/templates/middlewares/basic-middleware.yaml
  charts/stable/traefik/templates/middlewares/basicauth.yaml
  charts/stable/traefik/templates/middlewares/chain.yaml
  charts/stable/traefik/templates/middlewares/forwardauth.yaml
  charts/stable/traefik/templates/middlewares/ratelimit.yaml
  charts/stable/traefik/templates/middlewares/redirectScheme.yaml
Labels: bug, enhancement

#901 Add SOGO to Incubator
  charts/incubator/sogo/.helmignore
  charts/incubator/sogo/CONFIG.md
  charts/incubator/sogo/Chart.yaml
  charts/incubator/sogo/README.md
  charts/incubator/sogo/SCALE/item.yaml
  charts/incubator/sogo/SCALE/ix_values.yaml
  charts/incubator/sogo/SCALE/questions.yaml
  charts/incubator/sogo/app-readme.md
  charts/incubator/sogo/helm-values.md
  charts/incubator/sogo/templates/_config.tpl
  charts/incubator/sogo/templates/common.yaml
  charts/incubator/sogo/values.yaml
  docs/_static/img/sogo-icon.png
Labels: enhancement

#904 Add BETA OIDC support to Authelia
  charts/stable/authelia/SCALE/questions.yaml
Labels: enhancement

#919 Setup new test and release system
  .github/workflows/apps.release.yaml
  .github/workflows/apps.test.yaml
  .github/workflows/docs.deploy.yaml
  charts/incubator/custom-app/Chart.yaml
  containers/apps/sogo/latest-version.sh
  containers/apps/truecharts-release/latest-base.sh
  tools/build-release.sh
  tools/process.sh
Labels: bug, enhancement

#923 feat: Changelog project
  .chglog/CHANGELOG.tpl.md
  .chglog/config.yml
  .github/workflows/apps.release.yaml
  .github/workflows/apps.test.yaml
  tools/build-release.sh
Labels: enhancement

#921 Feature/unifi guest portal and speedtest
  charts/stable/unifi/Chart.yaml
  charts/stable/unifi/SCALE/questions.yaml
  charts/stable/unifi/values.yaml
Labels: enhancement

#929 feat: Add IPWhitelist, redirectRegex and nextcloud middlewares to traefik
  charts/stable/nextcloud/templates/_cronjob.tpl
  charts/stable/nextcloud/templates/common.yaml
  charts/stable/traefik/Chart.yaml
  charts/stable/traefik/SCALE/questions.yaml
  charts/stable/traefik/templates/middlewares/ipwhitelist.yaml
  charts/stable/traefik/templates/middlewares/redirectregex.yaml
  charts/stable/traefik/templates/middlewares/tc-nextcloud.yaml
  charts/stable/traefik/values.yaml
Labels: bug, enhancement

#931 feat: Move autopermissions to Initcontainer
  charts/library/common/Chart.yaml
  charts/library/common/templates/_all.tpl
  charts/library/common/templates/jobs/_mountPermissions.tpl
  charts/library/common/templates/lib/controller/_autopermissions.yaml
  charts/library/common/templates/lib/controller/_pod.tpl
  charts/library/common/tests/permissions_job_test.go
Labels: enhancement

#930 fix: Add initcontainer to force refresh TRUSTED_DOMAINS
  charts/stable/nextcloud/Chart.yaml
  charts/stable/nextcloud/templates/_configmap.tpl
  charts/stable/nextcloud/values.yaml
Labels: bug

#942 fix: ensure supplementalgroups when using devices are actually added
  charts/library/common/Chart.yaml
  charts/library/common/templates/lib/chart/_values.tpl
Labels: bug

#937 Add validation doc
  docs/manual/indepth/validation.md
Labels: documentation, enhancement

#945 fix: correct fireflyiii ports and services
  charts/stable/fireflyiii/SCALE/questions.yaml
  charts/stable/fireflyiii/values.yaml
Labels: bug

#946 fix: Inject vaultwarden websocket part into ingress
  charts/stable/vaultwarden/templates/common.yaml
  charts/stable/vaultwarden/values.yaml
Labels: bug

#947 fix: correct unifi port names to be unique
  charts/stable/unifi/Chart.yaml
  charts/stable/unifi/SCALE/questions.yaml
  charts/stable/unifi/values.yaml
Labels: bug, enhancement

#949 chore: update common test dependencies
  charts/library/common/tests/container_test.go
  charts/library/common/tests/horizontal_pod_autoscaler_test.go
  charts/library/common/tests/ingress_test.go
  charts/library/common/tests/pod_test.go
  charts/library/common/tests/service_test.go
  go.mod
  go.sum
  tests/helmunit/manifestCollection.go
  tests/helmunit/utils.go
Labels: enhancement

#948 Feat: port addons from k8s-at-home to common
  charts/library/common/Chart.yaml
  charts/library/common/templates/_all.tpl
  charts/library/common/templates/addons/code-server/_codeserver.tpl
  charts/library/common/templates/addons/code-server/_container.tpl
  charts/library/common/templates/addons/code-server/_secret.tpl
  charts/library/common/templates/addons/code-server/_volume.tpl
  charts/library/common/templates/addons/netshoot/_container.tpl
  charts/library/common/templates/addons/netshoot/_netshoot.tpl
  charts/library/common/templates/addons/promtail/_configmap.tpl
  charts/library/common/templates/addons/promtail/_container.tpl
  charts/library/common/templates/addons/promtail/_promtail.tpl
  charts/library/common/templates/addons/promtail/_volume.tpl
  charts/library/common/templates/addons/vpn/_configmap.tpl
  charts/library/common/templates/addons/vpn/_secret.tpl
  charts/library/common/templates/addons/vpn/_volume.tpl
  charts/library/common/templates/addons/vpn/_vpn.tpl
  charts/library/common/templates/addons/vpn/openvpn/_addon.tpl
  charts/library/common/templates/addons/vpn/openvpn/_container.tpl
  charts/library/common/templates/addons/vpn/openvpn/_secret.tpl
  charts/library/common/templates/addons/vpn/wireguard/_addon.tpl
  charts/library/common/templates/addons/vpn/wireguard/_container.tpl
  charts/library/common/tests/addon_codeserver_test.go
  charts/library/common/tests/addon_netshoot_test.go
  charts/library/common/tests/addon_vpn_test.go
  charts/library/common/values.yaml
Labels: enhancement

#950 refactor: Restructure common init and additional container layout to dicts
  charts/library/common/Chart.yaml
  charts/library/common/templates/_all.tpl
  charts/library/common/templates/addons/code-server/_codeserver.tpl
  charts/library/common/templates/addons/netshoot/_netshoot.tpl
  charts/library/common/templates/addons/promtail/_promtail.tpl
  charts/library/common/templates/addons/vpn/openvpn/_addon.tpl
  charts/library/common/templates/addons/vpn/wireguard/_addon.tpl
  charts/library/common/templates/classes/_service_ports.tpl
  charts/library/common/templates/lib/controller/_container.tpl
  charts/library/common/templates/lib/controller/_pod.tpl
  charts/library/common/templates/lib/controller/_ports.tpl
  charts/library/common/values.yaml
Labels: enhancement

#951 chore: update postrgresql to common 7.0.0
  charts/stable/postgresql/Chart.yaml
Labels: enhancement

#952 chore: update Apps containing initcontainers -not breaking on SCALE-
  charts/incubator/sogo/Chart.yaml
  charts/incubator/sogo/values.yaml
  charts/stable/authelia/Chart.yaml
  charts/stable/authelia/SCALE/ix_values.yaml
  charts/stable/authelia/values.yaml
  charts/stable/fireflyiii/Chart.yaml
  charts/stable/fireflyiii/SCALE/ix_values.yaml
  charts/stable/fireflyiii/values.yaml
  charts/stable/nextcloud/Chart.yaml
  charts/stable/nextcloud/values.yaml
  charts/stable/vaultwarden/Chart.yaml
  charts/stable/vaultwarden/SCALE/ix_values.yaml
  charts/stable/vaultwarden/values.yaml
Labels: enhancement

#953 feat: have VPN use a hostPath for the configfile instead of configmap
  charts/library/common/templates/addons/vpn/_secret.tpl
  charts/library/common/templates/addons/vpn/_vpn.tpl
  charts/library/common/templates/addons/vpn/openvpn/_container.tpl
  charts/library/common/templates/addons/vpn/wireguard/_container.tpl
  charts/library/common/tests/addon_vpn_test.go
  charts/library/common/tests/pod_test.go
  charts/library/common/values.yaml
Labels: bug, enhancement

#955 refactor: change image layout to enable renovate updates of sidecarts
  charts/incubator/sogo/Chart.yaml
  charts/incubator/sogo/SCALE/ix_values.yaml
  charts/incubator/sogo/values.yaml
  charts/library/common/templates/addons/code-server/_container.tpl
  charts/library/common/templates/addons/netshoot/_container.tpl
  charts/library/common/templates/addons/promtail/_container.tpl
  charts/library/common/templates/addons/vpn/openvpn/_container.tpl
  charts/library/common/templates/addons/vpn/wireguard/_container.tpl
  charts/library/common/templates/lib/controller/_autopermissions.yaml
  charts/library/common/values.yaml
  charts/stable/authelia/SCALE/ix_values.yaml
  charts/stable/authelia/values.yaml
  charts/stable/fireflyiii/SCALE/ix_values.yaml
  charts/stable/fireflyiii/values.yaml
  charts/stable/nextcloud/SCALE/ix_values.yaml
  charts/stable/nextcloud/values.yaml
  charts/stable/vaultwarden/SCALE/ix_values.yaml
  charts/stable/vaultwarden/values.yaml
  tools/build-release.sh
Labels: enhancement

#957 chore: move all LSIO containers to github registry
  charts/stable/airsonic/SCALE/ix_values.yaml
  charts/stable/airsonic/values.yaml
  charts/stable/calibre-web/SCALE/ix_values.yaml
  charts/stable/calibre-web/values.yaml
  charts/stable/calibre/SCALE/ix_values.yaml
  charts/stable/calibre/values.yaml
  charts/stable/deluge/SCALE/ix_values.yaml
  charts/stable/deluge/values.yaml
  charts/stable/freshrss/SCALE/ix_values.yaml
  charts/stable/freshrss/values.yaml
  charts/stable/grocy/SCALE/ix_values.yaml
  charts/stable/grocy/values.yaml
  charts/stable/healthchecks/SCALE/ix_values.yaml
  charts/stable/healthchecks/values.yaml
  charts/stable/heimdall/SCALE/ix_values.yaml
  charts/stable/heimdall/values.yaml
  charts/stable/lazylibrarian/SCALE/ix_values.yaml
  charts/stable/lazylibrarian/values.yaml
  charts/stable/librespeed/SCALE/ix_values.yaml
  charts/stable/librespeed/values.yaml
  charts/stable/tvheadend/SCALE/ix_values.yaml
  charts/stable/tvheadend/values.yaml
Labels: enhancement

#958 chore: move more dockerhub containers to GHCR mirror
  charts/library/common-test/values.yaml
  charts/library/common/values.yaml
  charts/stable/esphome/SCALE/ix_values.yaml
  charts/stable/esphome/values.yaml
  charts/stable/flood/SCALE/ix_values.yaml
  charts/stable/flood/values.yaml
  charts/stable/focalboard/SCALE/ix_values.yaml
  charts/stable/focalboard/values.yaml
  charts/stable/gaps/SCALE/ix_values.yaml
  charts/stable/gaps/values.yaml
  charts/stable/gonic/SCALE/ix_values.yaml
  charts/stable/gonic/values.yaml
  charts/stable/handbrake/SCALE/ix_values.yaml
  charts/stable/handbrake/values.yaml
  charts/stable/home-assistant/SCALE/ix_values.yaml
  charts/stable/home-assistant/values.yaml
  charts/stable/jdownloader2/SCALE/ix_values.yaml
  charts/stable/jdownloader2/values.yaml
  charts/stable/jellyfin/SCALE/ix_values.yaml
  charts/stable/jellyfin/values.yaml
  charts/stable/komga/SCALE/ix_values.yaml
  charts/stable/komga/values.yaml
  charts/stable/lychee/SCALE/ix_values.yaml
  charts/stable/lychee/values.yaml
  charts/stable/mealie/SCALE/ix_values.yaml
  charts/stable/mealie/values.yaml
  charts/stable/mosquitto/SCALE/ix_values.yaml
  charts/stable/mosquitto/values.yaml
  charts/stable/node-red/SCALE/ix_values.yaml
  charts/stable/node-red/values.yaml
  charts/stable/owncast/SCALE/ix_values.yaml
  charts/stable/owncast/values.yaml
  charts/stable/phpldapadmin/SCALE/ix_values.yaml
  charts/stable/phpldapadmin/values.yaml
  charts/stable/podgrab/SCALE/ix_values.yaml
  charts/stable/podgrab/values.yaml
  charts/stable/reg/SCALE/ix_values.yaml
  charts/stable/reg/values.yaml
  charts/stable/stash/SCALE/ix_values.yaml
  charts/stable/stash/values.yaml
  charts/stable/traefik/SCALE/ix_values.yaml
  charts/stable/traefik/values.yaml
  charts/stable/truecommand/SCALE/ix_values.yaml
  charts/stable/truecommand/values.yaml
  charts/stable/unifi/SCALE/ix_values.yaml
  charts/stable/unifi/values.yaml
  charts/stable/unpackerr/SCALE/ix_values.yaml
  charts/stable/unpackerr/values.yaml
  charts/stable/vaultwarden/SCALE/ix_values.yaml
  charts/stable/vaultwarden/values.yaml
  test.txt
Labels: enhancement

#959 chore: move most remaining Apps to GHCR mirror
  charts/stable/collabora-online/SCALE/ix_values.yaml
  charts/stable/collabora-online/values.yaml
  charts/stable/deconz/SCALE/ix_values.yaml
  charts/stable/deconz/values.yaml
  charts/stable/dizquetv/SCALE/ix_values.yaml
  charts/stable/dizquetv/values.yaml
  charts/stable/mosquitto/SCALE/ix_values.yaml
  charts/stable/mosquitto/values.yaml
  charts/stable/navidrome/SCALE/ix_values.yaml
  charts/stable/navidrome/values.yaml
  charts/stable/octoprint/SCALE/ix_values.yaml
  charts/stable/octoprint/values.yaml
  charts/stable/openldap/SCALE/ix_values.yaml
  charts/stable/openldap/values.yaml
  charts/stable/owncloud-ocis/SCALE/ix_values.yaml
  charts/stable/owncloud-ocis/values.yaml
  charts/stable/piaware/SCALE/ix_values.yaml
  charts/stable/piaware/values.yaml
  charts/stable/pihole/SCALE/ix_values.yaml
  charts/stable/pihole/values.yaml
  charts/stable/syncthing/SCALE/ix_values.yaml
  charts/stable/syncthing/values.yaml
  charts/stable/thelounge/SCALE/ix_values.yaml
  charts/stable/thelounge/values.yaml
  charts/stable/traefik/SCALE/ix_values.yaml
  charts/stable/traefik/values.yaml
  charts/stable/zwavejs2mqtt/SCALE/ix_values.yaml
  charts/stable/zwavejs2mqtt/values.yaml
Labels: enhancement

#960 chore: Use bitnami instead of stock postgresql container
  charts/incubator/sogo/SCALE/ix_values.yaml
  charts/incubator/sogo/values.yaml
  charts/stable/authelia/SCALE/ix_values.yaml
  charts/stable/authelia/values.yaml
  charts/stable/fireflyiii/SCALE/ix_values.yaml
  charts/stable/fireflyiii/values.yaml
  charts/stable/nextcloud/SCALE/ix_values.yaml
  charts/stable/nextcloud/values.yaml
  charts/stable/postgresql/Chart.yaml
  charts/stable/postgresql/SCALE/ix_values.yaml
  charts/stable/postgresql/SCALE/questions.yaml
  charts/stable/postgresql/values.yaml
  charts/stable/vaultwarden/SCALE/ix_values.yaml
  charts/stable/vaultwarden/values.yaml
Labels: enhancement

#970 improv: improve dns and vpn values.yaml syntaxis
  charts/library/common/Chart.yaml
  charts/library/common/templates/_all.tpl
  charts/library/common/templates/addons/vpn/_vpn.tpl
  charts/library/common/templates/addons/vpn/openvpn/_container.tpl
  charts/library/common/templates/addons/vpn/wireguard/_container.tpl
  charts/library/common/templates/lib/controller/_pod.tpl
  charts/library/common/tests/addon_vpn_test.go
  charts/library/common/values.yaml
Labels: enhancement

#971 fix: don't get process annotationLists and labelLists for disabled objects
  charts/library/common/Chart.yaml
  charts/library/common/templates/lib/chart/_values.tpl
Labels: bug

#985 Add TeamSpeak3 Server
  charts/incubator/teamspeak3/CHANGELOG.md
  charts/incubator/teamspeak3/CONFIG.md
  charts/incubator/teamspeak3/Chart.yaml
  charts/incubator/teamspeak3/README.md
  charts/incubator/teamspeak3/SCALE/CHANGELOG.md
  charts/incubator/teamspeak3/SCALE/item.yaml
  charts/incubator/teamspeak3/SCALE/ix_values.yaml
  charts/incubator/teamspeak3/SCALE/questions.yaml
  charts/incubator/teamspeak3/app-readme.md
  charts/incubator/teamspeak3/helm-values.md
  charts/incubator/teamspeak3/templates/common.yaml
  charts/incubator/teamspeak3/values.yaml
  docs/manual/default-ports.md
Labels: enhancement

#994 fix: make sure autopermissions sets the group owner correctly
  charts/library/common-test/Chart.yaml
  charts/library/common/Chart.yaml
  charts/library/common/templates/lib/controller/_autopermissions.yaml
  charts/library/common/tests/persistentvolumeclaim_test.go
Labels: bug

#1029 Fix remaining VPN addon issues
  charts/library/common/Chart.yaml
  charts/library/common/templates/addons/vpn/openvpn/_container.tpl
  charts/library/common/templates/addons/vpn/openvpn/_secret.tpl
  charts/library/common/templates/addons/vpn/wireguard/_container.tpl
  charts/library/common/templates/lib/controller/_autopermissions.yaml
  charts/library/common/tests/persistentvolumeclaim_test.go
  charts/library/common/values.yaml
  templates/questions/addons.yaml
Labels: bug, enhancement

#1030 Add ReadOnlyRoot mitigation for S6 overlay
  charts/library/common/Chart.yaml
  charts/library/common/templates/lib/controller/_container.tpl
  charts/library/common/tests/container_test.go
Labels: bug, enhancement

#1032 add a special /var/run tmpfs mountpoint to common
  charts/library/common/Chart.yaml
  charts/library/common/tests/persistentvolumeclaim_test.go
  charts/library/common/values.yaml
Labels: enhancement

#1035 (docs) add system requirements
  docs/manual/systemrequirements.md
Labels: documentation

#1036 (chore) increase default resource limits
  templates/questions/resources.yaml
Labels: enhancement

#1037 (fix) Disable varrun for Lychee and phpldapadmin
  charts/stable/lychee/SCALE/questions.yaml
  charts/stable/lychee/values.yaml
  charts/stable/phpldapadmin/SCALE/questions.yaml
  charts/stable/phpldapadmin/values.yaml
Labels: bug

#1053 (tests) Rework tests using dev container and ruby unit-tests
  .github/workflows/apps.release.yaml
  .github/workflows/apps.test.yaml
  .github/workflows/common.test.yaml
  charts/library/common-test/Chart.yaml
  charts/library/common-test/ci/basic-values.yaml
  charts/library/common-test/values.yaml
  charts/library/common/Chart.yaml
  charts/library/common/templates/classes/_pvc.tpl
  charts/library/common/templates/classes/_service.tpl
  charts/library/common/tests/addon_codeserver_test.go
  charts/library/common/tests/addon_netshoot_test.go
  charts/library/common/tests/addon_vpn_test.go
  charts/library/common/tests/container_test.go
  charts/library/common/tests/controller_test.go
  charts/library/common/tests/horizontal_pod_autoscaler_test.go
  charts/library/common/tests/ingress_test.go
  charts/library/common/tests/persistentvolumeclaim_test.go
  charts/library/common/tests/pod_test.go
  charts/library/common/tests/service_test.go
  charts/library/common/values.yaml
  tests/library/common/autoPermissions_spec.rb
  tests/library/common/cert_spec.rb
  tests/library/common/container_resources_spec.rb
  tests/library/common/container_spec.rb
  tests/library/common/controller_spec.rb
  tests/library/common/ingress_spec.rb
  tests/library/common/persistence_spec.rb
  tests/library/common/pod_spec.rb
  tests/library/common/portal_spec.rb
  tests/library/common/pvc_spec.rb
  tests/library/common/service_spec.rb
Labels: enhancement

#1054 (tests) add basic VPN and code-server addon unittests
  .github/workflows/common.test.yaml
  tests/library/common/addon_codeserver_spec.rb
  tests/library/common/addon_vpn_spec.rb
Labels: enhancement

#1057 (tests) Add more common tests
  charts/library/common-test/ci/ingress-values.yaml
  charts/library/common-test/ci/persistence-values.yaml
Labels: enhancement

#1058 (feat) Add Promtail and Netshoot addons
  charts/library/common/Chart.yaml
  charts/library/common/templates/addons/code-server/_container.tpl
  charts/library/common/templates/addons/netshoot/_container.tpl
  charts/library/common/templates/addons/promtail/_container.tpl
  charts/library/common/values.yaml
  templates/questions/addons.yaml
  tests/library/common/addon_netshoot_spec.rb
  tests/library/common/addon_promtail_spec.rb
Labels: enhancement

#1059 (feat) add CodeServer addon and addon improvements
  charts/library/common-test/ci/codeserver-values.yaml
  charts/library/common-test/ci/netshoot-values.yaml
  charts/library/common/Chart.yaml
  charts/library/common/templates/addons/code-server/_container.tpl
  charts/library/common/templates/addons/netshoot/_container.tpl
  charts/library/common/templates/addons/promtail/_container.tpl
  charts/library/common/templates/addons/vpn/openvpn/_container.tpl
  charts/library/common/templates/addons/vpn/wireguard/_container.tpl
  charts/library/common/values.yaml
  docs/manual/default-ports.md
  templates/questions/addons.yaml
  tests/library/common/addon_codeserver_spec.rb
  tests/library/common/addon_promtail_spec.rb
Labels: enhancement
