Repository trueforge-org/truecharts, pull requests merged in 2021-04, with the labels that each got.

#318 Add dev train and excluded common-test chart.lock
  .github/workflows/apps.test.yaml
  .github/workflows/charts.renovate.yaml
  .gitignore
  .tools/copy-common.sh
  .tools/fixfolders.sh
  .tools/gen-helm-docs.sh
  dev/placeholder/6.6.6/.helmignore
  dev/placeholder/6.6.6/Chart.yaml
  dev/placeholder/6.6.6/README.md
  dev/placeholder/6.6.6/app-readme.md
  dev/placeholder/6.6.6/ix_values.yaml
  dev/placeholder/6.6.6/questions.yaml
  dev/placeholder/6.6.6/templates/placeholder.yaml
  dev/placeholder/6.6.6/test_values.yaml
  dev/placeholder/6.6.6/values.yaml
  dev/placeholder/item.yaml
Labels: enhancement

#315 Add url option to portal configmap
  .tools/tests/charts/common-test_spec.rb
  library/common/Chart.yaml
  library/common/templates/lib/resources/_portal_config.tpl
Labels: enhancement

#304 Add phpmyadmin
  dev/phpmyadmin/0.0.3/.helmignore
  dev/phpmyadmin/0.0.3/CONFIG.md
  dev/phpmyadmin/0.0.3/Chart.lock
  dev/phpmyadmin/0.0.3/Chart.yaml
  dev/phpmyadmin/0.0.3/README.md
  dev/phpmyadmin/0.0.3/app-readme.md
  dev/phpmyadmin/0.0.3/charts/common-2.0.2.tgz
  dev/phpmyadmin/0.0.3/ix_values.yaml
  dev/phpmyadmin/0.0.3/questions.yaml
  dev/phpmyadmin/0.0.3/templates/common.yaml
  dev/phpmyadmin/0.0.3/test_values.yaml
  dev/phpmyadmin/0.0.3/values.yaml
  dev/phpmyadmin/item.yaml
Labels: New App Request

#303 Add postgres-operator and basic common postgres-manifest
  .github/ct-install.yaml
  .github/ct-lint.yaml
  dev/postgres-operator/0.0.1/.helmignore
  dev/postgres-operator/0.0.1/CONFIG.md
  dev/postgres-operator/0.0.1/Chart.lock
  dev/postgres-operator/0.0.1/Chart.yaml
  dev/postgres-operator/0.0.1/README.md
  dev/postgres-operator/0.0.1/app-readme.md
  dev/postgres-operator/0.0.1/charts/common-2.0.2.tgz
  dev/postgres-operator/0.0.1/charts/postgres-operator-1.6.2.tgz
  dev/postgres-operator/0.0.1/charts/postgres-operator-ui-1.6.2.tgz
  dev/postgres-operator/0.0.1/ix_values.yaml
  dev/postgres-operator/0.0.1/questions.yaml
  dev/postgres-operator/0.0.1/templates/common.yaml
  dev/postgres-operator/0.0.1/templates/envconfig.yaml
  dev/postgres-operator/0.0.1/test_values.yaml
  dev/postgres-operator/0.0.1/values.yaml
  dev/postgres-operator/item.yaml
  docs/_static/img/postgres-operator-icon.png
  library/common/Chart.yaml
  library/common/templates/_all.tpl
  library/common/templates/_pvc.tpl
  library/common/templates/classes/_pvc.tpl
  library/common/templates/classes/ingress/_ingress.tpl
  library/common/templates/lib/resources/_postgres.tpl
  library/common/values.yaml
Labels: New App Request, enhancement

#327 Add Syncthing
  .github/CODEOWNERS
  stable/syncthing/2.1.0/.helmignore
  stable/syncthing/2.1.0/CONFIG.md
  stable/syncthing/2.1.0/Chart.lock
  stable/syncthing/2.1.0/Chart.yaml
  stable/syncthing/2.1.0/README.md
  stable/syncthing/2.1.0/app-readme.md
  stable/syncthing/2.1.0/charts/common-2.1.4.tgz
  stable/syncthing/2.1.0/ix_values.yaml
  stable/syncthing/2.1.0/questions.yaml
  stable/syncthing/2.1.0/templates/common.yaml
  stable/syncthing/2.1.0/test_values.yaml
  stable/syncthing/2.1.0/values.yaml
  stable/syncthing/item.yaml
Labels: New App Request

#332 Remove Postgres-Operator from common-chart (for now)
  library/common/Chart.yaml
  library/common/templates/_all.tpl
  library/common/templates/lib/resources/_postgres.tpl
  library/common/values.yaml
Labels: enhancement

#334 Don't create volume mounts for unmountable PVC's
  library/common/Chart.yaml
  library/common/templates/lib/controller/_container.tpl
Labels: bug, enhancement

#338 Refactor traefik to directly use the official chart
  .github/ct-install.yaml
  .github/ct-lint.yaml
  stable/traefik/2.2.2/Chart.lock
  stable/traefik/2.2.2/LICENSE
  stable/traefik/2.2.2/ix_values.yaml
  stable/traefik/2.2.2/questions.yaml
  stable/traefik/2.2.2/templates/_helpers.tpl
  stable/traefik/2.2.2/templates/_podtemplate.tpl
  stable/traefik/2.2.2/templates/daemonset.yaml
  stable/traefik/2.2.2/templates/dashboard-hook-ingressroute.yaml
  stable/traefik/2.2.2/templates/deployment.yaml
  stable/traefik/2.2.2/templates/gateway.yaml
  stable/traefik/2.2.2/templates/gatewayclass.yaml
  stable/traefik/2.2.2/templates/hpa.yaml
  stable/traefik/2.2.2/templates/ingressclass.yaml
  stable/traefik/2.2.2/templates/poddisruptionbudget.yaml
  stable/traefik/2.2.2/templates/pvc.yaml
  stable/traefik/2.2.2/templates/rbac/clusterrole.yaml
  stable/traefik/2.2.2/templates/rbac/clusterrolebinding.yaml
  stable/traefik/2.2.2/templates/rbac/podsecuritypolicy.yaml
  stable/traefik/2.2.2/templates/rbac/role.yaml
  stable/traefik/2.2.2/templates/rbac/rolebinding.yaml
  stable/traefik/2.2.2/templates/rbac/serviceaccount.yaml
  stable/traefik/2.2.2/templates/service.yaml
  stable/traefik/2.2.2/templates/tlsoption.yaml
  stable/traefik/2.2.2/test_values.yaml
  stable/traefik/3.0.0/.helmignore
  stable/traefik/3.0.0/CONFIG.md
  stable/traefik/3.0.0/Chart.lock
  stable/traefik/3.0.0/Chart.yaml
  stable/traefik/3.0.0/Guidelines.md
  stable/traefik/3.0.0/README.md
  stable/traefik/3.0.0/app-readme.md
  stable/traefik/3.0.0/charts/common-2.2.2.tgz
  stable/traefik/3.0.0/charts/traefik-9.18.2.tgz
  stable/traefik/3.0.0/crds/ingressroute.yaml
  stable/traefik/3.0.0/crds/ingressroutetcp.yaml
  stable/traefik/3.0.0/crds/ingressrouteudp.yaml
  stable/traefik/3.0.0/crds/middlewares.yaml
  stable/traefik/3.0.0/crds/serverstransports.yaml
  stable/traefik/3.0.0/crds/tlsoptions.yaml
  stable/traefik/3.0.0/crds/tlsstores.yaml
  stable/traefik/3.0.0/crds/traefikservices.yaml
  stable/traefik/3.0.0/ix_values.yaml
  stable/traefik/3.0.0/questions.yaml
  stable/traefik/3.0.0/templates/common.yaml
  stable/traefik/3.0.0/templates/middlewares.yaml
  stable/traefik/3.0.0/templates/tlsoptions.yaml
  stable/traefik/3.0.0/test_values.yaml
  stable/traefik/3.0.0/values.yaml
Labels: enhancement

#316 Add Bitwarden
  .github/ct-install.yaml
  .github/ct-lint.yaml
  stable/bitwarden/1.0.0/.helmignore
  stable/bitwarden/1.0.0/CONFIG.md
  stable/bitwarden/1.0.0/Chart.lock
  stable/bitwarden/1.0.0/Chart.yaml
  stable/bitwarden/1.0.0/README.md
  stable/bitwarden/1.0.0/app-readme.md
  stable/bitwarden/1.0.0/charts/common-2.2.2.tgz
  stable/bitwarden/1.0.0/charts/postgresql-10.3.15.tgz
  stable/bitwarden/1.0.0/ix_values.yaml
  stable/bitwarden/1.0.0/questions.yaml
  stable/bitwarden/1.0.0/templates/_specialingress.tpl
  stable/bitwarden/1.0.0/templates/_validate.tpl
  stable/bitwarden/1.0.0/templates/common.yaml
  stable/bitwarden/1.0.0/templates/configmap.yaml
  stable/bitwarden/1.0.0/templates/secrets.yaml
  stable/bitwarden/1.0.0/test_values.yaml
  stable/bitwarden/1.0.0/values.yaml
  stable/bitwarden/item.yaml
Labels: New App Request

#342 Document and Fix NodePort related Bitwarden issues
  docs/apps/stable/bitwarden/notes.md
  stable/bitwarden/1.0.1/.helmignore
  stable/bitwarden/1.0.1/CONFIG.md
  stable/bitwarden/1.0.1/Chart.lock
  stable/bitwarden/1.0.1/Chart.yaml
  stable/bitwarden/1.0.1/README.md
  stable/bitwarden/1.0.1/app-readme.md
  stable/bitwarden/1.0.1/charts/common-2.2.2.tgz
  stable/bitwarden/1.0.1/charts/postgresql-10.3.15.tgz
  stable/bitwarden/1.0.1/ix_values.yaml
  stable/bitwarden/1.0.1/questions.yaml
  stable/bitwarden/1.0.1/templates/_specialingress.tpl
  stable/bitwarden/1.0.1/templates/_validate.tpl
  stable/bitwarden/1.0.1/templates/common.yaml
  stable/bitwarden/1.0.1/templates/configmap.yaml
  stable/bitwarden/1.0.1/templates/secrets.yaml
  stable/bitwarden/1.0.1/test_values.yaml
  stable/bitwarden/1.0.1/values.yaml
Labels: bug

#344 Common part of Storage Part 2
  .tools/tests/charts/common-test_spec.rb
  library/common-test/templates/NOTES.txt
  library/common-test/values.yaml
  library/common/Chart.yaml
  library/common/templates/_all.tpl
  library/common/templates/_notes.tpl
  library/common/templates/_pvc.tpl
  library/common/templates/_serviceaccount.tpl
  library/common/templates/lib/bitnamiCompat/_affinities.tpl
  library/common/templates/lib/bitnamiCompat/_ingressBackend.tpl
  library/common/templates/lib/bitnamiCompat/_secrets.tpl
  library/common/templates/lib/bitnamiCompat/_tplvalues.tpl
  library/common/templates/lib/chart/_warnings.tpl
  library/common/templates/lib/controller/_container.tpl
  library/common/templates/lib/controller/_pod.tpl
  library/common/templates/lib/controller/_volumeMounts.tpl
  library/common/templates/lib/controller/_volumes.tpl
  library/common/templates/lib/storage/_appStorage.tpl
  library/common/templates/lib/storage/_ixVolumes.tpl
  library/common/templates/lib/storage/_mountPermissions.tpl
  library/common/templates/lib/storage/_mountPermissionsJob.tpl
  library/common/templates/lib/storage/_storageclass.tpl
  library/common/templates/lib/validations/_cassandra.tpl
  library/common/templates/lib/validations/_mariadb.tpl
  library/common/templates/lib/validations/_mongodb.tpl
  library/common/templates/lib/validations/_postgresql.tpl
  library/common/templates/lib/validations/_redis.tpl
  library/common/templates/lib/validations/_validations.tpl
  library/common/values.yaml
Labels: enhancement

#355 Fixup the permissions script and make it more efficient
  library/common-test/Chart.yaml
  library/common-test/ci/default-values.yaml
  library/common-test/values.yaml
  library/common/Chart.yaml
  library/common/templates/lib/storage/_mountPermissions.tpl
Labels: bug, enhancement

#356 Make host and container devicePath the same.
  .tools/tests/charts/common-test_spec.rb
  library/common-test/Chart.yaml
  library/common-test/ci/default-values.yaml
  library/common-test/values.yaml
  library/common/Chart.yaml
  library/common/templates/lib/controller/_volumeMounts.tpl
  library/common/templates/lib/controller/_volumes.tpl
  library/common/values.yaml
Labels: enhancement

#357 allow setting readOnly on customStorage and limit permissionsmounts
  library/common-test/Chart.yaml
  library/common-test/values.yaml
  library/common/Chart.yaml
  library/common/templates/lib/controller/_volumeMounts.tpl
  library/common/templates/lib/storage/_mountPermissions.tpl
  library/common/values.yaml
Labels: enhancement

#362 Fix zwavejs2mqtt typo
  stable/zwavejs2mqtt/3.1.1/test_values.yaml
Labels: bug

#361 Fix Collabora
  stable/collabora-online/3.1.1/ix_values.yaml
  stable/collabora-online/3.1.1/questions.yaml
  stable/collabora-online/3.1.1/test_values.yaml
Labels: bug

#363 Cleanup devicemounts a bit
  dev/phpmyadmin/1.1.1/questions.yaml
  docs/development/app development/questions-yaml.md
  incubator/bazarr/3.1.1/questions.yaml
  incubator/calibre-web/3.1.1/questions.yaml
  incubator/deluge/3.1.1/questions.yaml
  incubator/freshrss/3.1.1/questions.yaml
  incubator/gaps/3.1.1/questions.yaml
  incubator/grocy/3.1.1/questions.yaml
  incubator/heimdall/3.1.1/questions.yaml
  incubator/lazylibrarian/3.1.1/questions.yaml
  incubator/lychee/3.1.1/questions.yaml
  incubator/navidrome/3.1.1/questions.yaml
  incubator/node-red/3.1.1/questions.yaml
  incubator/nzbget/3.1.1/questions.yaml
  incubator/nzbhydra/3.1.1/questions.yaml
  incubator/organizr/3.1.1/questions.yaml
  incubator/qbittorrent/3.1.1/questions.yaml
  incubator/readarr/3.1.1/questions.yaml
  incubator/sabnzbd/3.1.1/questions.yaml
  incubator/truecommand/3.1.1/questions.yaml
  incubator/tvheadend/4.1.1/questions.yaml
  incubator/unifi/3.1.1/questions.yaml
  stable/bitwarden/1.1.1/questions.yaml
  stable/collabora-online/3.1.1/questions.yaml
  stable/emby/3.1.1/questions.yaml
  stable/esphome/3.1.1/questions.yaml
  stable/handbrake/3.1.1/questions.yaml
  stable/home-assistant/3.1.1/questions.yaml
  stable/jackett/3.1.1/questions.yaml
  stable/jellyfin/3.1.1/questions.yaml
  stable/kms/3.1.1/questions.yaml
  stable/lidarr/3.1.1/questions.yaml
  stable/ombi/3.1.1/questions.yaml
  stable/plex/2.1.1/questions.yaml
  stable/radarr/3.1.1/questions.yaml
  stable/sonarr/3.1.1/questions.yaml
  stable/syncthing/3.1.1/questions.yaml
  stable/tautulli/3.1.1/questions.yaml
  stable/traefik/3.1.1/questions.yaml
  stable/transmission/3.1.1/questions.yaml
  stable/zwavejs2mqtt/3.1.1/questions.yaml
Labels: enhancement

#364 Ingress GUI rework
  .tools/tests/charts/common-test_spec.rb
  dev/phpmyadmin/1.1.1/questions.yaml
  incubator/bazarr/3.1.1/questions.yaml
  incubator/calibre-web/3.1.1/questions.yaml
  incubator/deluge/3.1.1/questions.yaml
  incubator/freshrss/3.1.1/questions.yaml
  incubator/gaps/3.1.1/questions.yaml
  incubator/grocy/3.1.1/questions.yaml
  incubator/heimdall/3.1.1/questions.yaml
  incubator/lazylibrarian/3.1.1/questions.yaml
  incubator/lychee/3.1.1/questions.yaml
  incubator/navidrome/3.1.1/questions.yaml
  incubator/node-red/3.1.1/questions.yaml
  incubator/nzbget/3.1.1/questions.yaml
  incubator/nzbhydra/3.1.1/questions.yaml
  incubator/organizr/3.1.1/questions.yaml
  incubator/qbittorrent/3.1.1/questions.yaml
  incubator/readarr/3.1.1/questions.yaml
  incubator/sabnzbd/3.1.1/questions.yaml
  incubator/truecommand/3.1.1/questions.yaml
  incubator/tvheadend/4.1.1/questions.yaml
  incubator/unifi/3.1.1/questions.yaml
  library/common-test/Chart.yaml
  library/common-test/ci/default-values.yaml
  library/common-test/values.yaml
  library/common/Chart.yaml
  library/common/templates/_ingress.tpl
  stable/bitwarden/1.1.1/questions.yaml
  stable/collabora-online/3.1.1/questions.yaml
  stable/emby/3.1.1/questions.yaml
  stable/esphome/3.1.1/questions.yaml
  stable/handbrake/3.1.1/questions.yaml
  stable/home-assistant/3.1.1/questions.yaml
  stable/jackett/3.1.1/questions.yaml
  stable/jellyfin/3.1.1/questions.yaml
  stable/lidarr/3.1.1/questions.yaml
  stable/ombi/3.1.1/questions.yaml
  stable/radarr/3.1.1/questions.yaml
  stable/sonarr/3.1.1/questions.yaml
  stable/syncthing/3.1.1/questions.yaml
  stable/tautulli/3.1.1/questions.yaml
  stable/transmission/3.1.1/questions.yaml
  stable/zwavejs2mqtt/3.1.1/questions.yaml
Labels: enhancement

#369 re-Add custom Env Vars on Handbrake
  stable/handbrake/3.1.2/questions.yaml
Labels: bug

#372 Adds youtubeDL-Material
  .github/CODEOWNERS
  docs/_static/img/youtubedl-material-icon.png
  docs/apps/stable/youtubedl-material/CONFIG.md
  docs/apps/stable/youtubedl-material/index.md
  docs/apps/stable/youtubedl-material/notes.md
  stable/youtubedl-material/1.0.0/.helmignore
  stable/youtubedl-material/1.0.0/CONFIG.md
  stable/youtubedl-material/1.0.0/Chart.yaml
  stable/youtubedl-material/1.0.0/README.md
  stable/youtubedl-material/1.0.0/app-readme.md
  stable/youtubedl-material/1.0.0/charts/common-3.5.2.tgz
  stable/youtubedl-material/1.0.0/ix_values.yaml
  stable/youtubedl-material/1.0.0/questions.yaml
  stable/youtubedl-material/1.0.0/templates/common.yaml
  stable/youtubedl-material/1.0.0/test_values.yaml
  stable/youtubedl-material/1.0.0/values.yaml
  stable/youtubedl-material/item.yaml
Labels: New App Request

#384 Adds deepstack-cpu
  docs/apps/stable/deepstack-cpu/CONFIG.md
  docs/apps/stable/deepstack-cpu/index.md
  docs/apps/stable/deepstack-cpu/notes.md
  stable/deepstack-cpu/1.0.0/.helmignore
  stable/deepstack-cpu/1.0.0/CONFIG.md
  stable/deepstack-cpu/1.0.0/Chart.yaml
  stable/deepstack-cpu/1.0.0/README.md
  stable/deepstack-cpu/1.0.0/app-readme.md
  stable/deepstack-cpu/1.0.0/charts/common-3.5.2.tgz
  stable/deepstack-cpu/1.0.0/ix_values.yaml
  stable/deepstack-cpu/1.0.0/questions.yaml
  stable/deepstack-cpu/1.0.0/templates/common.yaml
  stable/deepstack-cpu/1.0.0/test_values.yaml
  stable/deepstack-cpu/1.0.0/values.yaml
  stable/deepstack-cpu/item.yaml
Labels: New App Request

#397 Remove duplicate forward auth url in questions yaml
  stable/radarr/3.1.2/questions.yaml
Labels: bug

#368 Appdaemon
  .github/CODEOWNERS
  incubator/appdaemon/0.1.0/CONFIG.md
  incubator/appdaemon/0.1.0/Chart.yaml
  incubator/appdaemon/0.1.0/README.md
  incubator/appdaemon/0.1.0/app-readme.md
  incubator/appdaemon/0.1.0/charts/common-3.5.2.tgz
  incubator/appdaemon/0.1.0/ix_values.yaml
  incubator/appdaemon/0.1.0/questions.yaml
  incubator/appdaemon/0.1.0/templates/common.yaml
  incubator/appdaemon/0.1.0/test_values.yaml
  incubator/appdaemon/0.1.0/values.yaml
  incubator/appdaemon/item.yaml
Labels: New App Request
