Repository trueforge-org/truecharts, pull requests merged in 2021-03, with the labels that each got.

#201 Make storage more flexible
  .github/docs/development/unlimited-storage-mounts.md
  .github/docs/general/storage.md
  library/common-test/Chart.yaml
  library/common-test/ci/basic-values.yaml
  library/common-test/ci/codeserver-values.yaml
  library/common-test/values.yaml
  library/common/Chart.yaml
  library/common/templates/lib/controller/_container.tpl
  library/common/templates/lib/controller/_volumes.tpl
  library/common/templates/lib/storage/_appStorage.tpl
  library/common/templates/lib/storage/_mountPermissionsJob.tpl
  library/common/values.yaml
Labels: documentation, enhancement

#204 Fix issues when running multiple Ingresses
  library/common/Chart.yaml
  library/common/templates/lib/resources/_appingress.tpl
Labels: bug

#208 More Development documentation and code-snippets
  .github/docs/development/chart-structure.md
  .github/docs/development/questions-yaml.md
  .github/docs/development/storage.md
  .github/docs/development/unlimited-storage-mounts.md
  features_capability.json
Labels: documentation

#218 Cleanup storage and add storage unittests
  .github/docs/development/storage.md
  .tools/tests/charts/common-test_spec.rb
  library/common-test/values.yaml
  library/common/templates/lib/storage/_appStorage.tpl
  library/common/values.yaml
Labels: documentation, enhancement

#223 move docs from .github to project root
  .github/workflows/wiki-create-docs.yaml
  charts/traefik/2.0.0/Chart.lock
  docs/FAQ.md
  docs/development/chart-structure.md
  docs/development/chart-yaml-structure.md
  docs/development/common-libary.md
  docs/development/getting-started.md
  docs/development/ingress.md
  docs/development/questions-yaml.md
  docs/development/services.md
  docs/development/storage.md
  docs/development/unit-tests.md
  docs/general/reverse-proxy.md
  docs/general/storage.md
  docs/legal/Apach2-licence.md
  docs/legal/License-headers.md
  docs/maintainers-wanted.md
  library/common-test/charts/common-2.0.0.tgz
Labels: documentation

#226 Fix FAQ link, add issue tracker link
  .github/README.md
Labels: bug, documentation

#245 Cleanup versioning and add auto-updater
  .github/renovate.json5
  charts/bazarr/2.0.0/Chart.yaml
  charts/calibre-web/2.0.0/Chart.yaml
  charts/collabora-online/2.0.0/Chart.yaml
  charts/deluge/2.0.0/Chart.yaml
  charts/deluge/2.0.0/ix_values.yaml
  charts/deluge/2.0.0/test_values.yaml
  charts/esphome/2.0.0/Chart.yaml
  charts/freshrss/2.0.0/Chart.yaml
  charts/gaps/2.0.0/Chart.yaml
  charts/gaps/2.0.0/ix_values.yaml
  charts/gaps/2.0.0/test_values.yaml
  charts/grocy/2.0.0/Chart.yaml
  charts/handbrake/2.0.0/Chart.yaml
  charts/handbrake/2.0.0/ix_values.yaml
  charts/heimdall/2.0.0/Chart.yaml
  charts/home-assistant/2.0.0/Chart.yaml
  charts/jackett/2.0.0/Chart.yaml
  charts/jellyfin/2.0.0/Chart.yaml
  charts/kms/2.0.0/Chart.yaml
  charts/lazylibrarian/2.0.0/Chart.yaml
  charts/lazylibrarian/2.0.0/ix_values.yaml
  charts/lazylibrarian/2.0.0/test_values.yaml
  charts/lidarr/2.0.0/Chart.yaml
  charts/lychee/2.0.0/Chart.yaml
  charts/navidrome/2.0.0/Chart.yaml
  charts/node-red/2.0.0/Chart.yaml
  charts/nzbget/2.0.0/Chart.yaml
  charts/nzbhydra/2.0.0/Chart.yaml
  charts/nzbhydra/2.0.0/ix_values.yaml
  charts/ombi/2.0.0/Chart.yaml
  charts/organizr/2.0.0/Chart.yaml
  charts/qbittorrent/2.0.0/Chart.yaml
  charts/qbittorrent/2.0.0/ix_values.yaml
  charts/qbittorrent/2.0.0/test_values.yaml
  charts/radarr/2.0.0/Chart.yaml
  charts/radarr/2.0.0/ix_values.yaml
  charts/readarr/2.0.0/Chart.yaml
  charts/sabnzbd/2.0.0/Chart.yaml
  charts/sonarr/2.0.0/Chart.yaml
  charts/sonarr/2.0.0/ix_values.yaml
  charts/tautulli/2.0.0/Chart.yaml
  charts/traefik/2.0.0/Chart.yaml
  charts/traefik/2.0.0/ix_values.yaml
  charts/traefik/2.0.0/test_values.yaml
  charts/transmission/2.0.0/Chart.yaml
  charts/truecommand/2.0.0/Chart.yaml
  charts/unifi/2.0.0/Chart.yaml
  charts/unifi/2.0.0/ix_values.yaml
  charts/unifi/2.0.0/test_values.yaml
  charts/zwavejs2mqtt/2.0.0/Chart.yaml
  charts/zwavejs2mqtt/2.0.0/ix_values.yaml
  library/common-test/values.yaml
  library/common/Chart.yaml
Labels: enhancement

#221 Add Emby
  .github/CODEOWNERS
  .github/README.md
  charts/emby/2.0.0/.helmignore
  charts/emby/2.0.0/Chart.yaml
  charts/emby/2.0.0/README.md
  charts/emby/2.0.0/app-readme.md
  charts/emby/2.0.0/charts/common-2.0.0.tgz
  charts/emby/2.0.0/docs/CONFIG.md
  charts/emby/2.0.0/docs/CONFIG.md.gotmpl
  charts/emby/2.0.0/ix_values.yaml
  charts/emby/2.0.0/questions.yaml
  charts/emby/2.0.0/templates/common.yaml
  charts/emby/2.0.0/test_values.yaml
  charts/emby/2.0.0/values.yaml
  charts/emby/icon.png
  charts/emby/item.yaml
Labels: New App Request

#258 Move to truecharts containers
  charts/bazarr/2.0.0/ix_values.yaml
  charts/bazarr/2.0.0/test_values.yaml
  charts/jackett/2.0.0/ix_values.yaml
  charts/jackett/2.0.0/test_values.yaml
  charts/lidarr/2.0.0/ix_values.yaml
  charts/lidarr/2.0.0/test_values.yaml
  charts/nzbget/2.0.0/ix_values.yaml
  charts/nzbget/2.0.0/test_values.yaml
  charts/nzbhydra/2.0.0/ix_values.yaml
  charts/nzbhydra/2.0.0/test_values.yaml
  charts/qbittorrent/2.0.0/ix_values.yaml
  charts/qbittorrent/2.0.0/test_values.yaml
  charts/radarr/2.0.0/ix_values.yaml
  charts/radarr/2.0.0/test_values.yaml
  charts/sabnzbd/2.0.0/ix_values.yaml
  charts/sabnzbd/2.0.0/test_values.yaml
  charts/sonarr/2.0.0/ix_values.yaml
  charts/sonarr/2.0.0/test_values.yaml
  charts/tautulli/2.0.0/ix_values.yaml
  charts/tautulli/2.0.0/test_values.yaml
Labels: enhancement
