Repository trueforge-org/truecharts, pull requests merged in 2022-10, with the labels that each got.

#3972 chore(deps): update helm chart common to v10.6.8
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/promtail/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
Labels: size/S, lint:ok, precommit:ok

#3974 chore(deps): update actions/github-script digest to 7dff1a8
  .github/workflows/meta-label-pr-ci-status.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3961 feat(authentik): cleanup GUI from unnecessary services/ingresses and add serviceMonitor and prometheusRule
  charts/enterprise/authentik/Chart.yaml
  charts/enterprise/authentik/questions.yaml
  charts/enterprise/authentik/templates/_ldap.tpl
  charts/enterprise/authentik/templates/_proxy.tpl
  charts/enterprise/authentik/templates/common.yaml
  charts/enterprise/authentik/templates/prometheusrules.yaml
  charts/enterprise/authentik/templates/servicemonitor.yaml
  charts/enterprise/authentik/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3976 chore(deps): update helm chart common to v10.6.8
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3826 feat(kavitaemail): Add kavitaemail
  charts/incubator/kavitaemail/.helmignore
  charts/incubator/kavitaemail/Chart.yaml
  charts/incubator/kavitaemail/README.md
  charts/incubator/kavitaemail/docs/installation_notes.md
  charts/incubator/kavitaemail/icon.png
  charts/incubator/kavitaemail/questions.yaml
  charts/incubator/kavitaemail/templates/common.yaml
  charts/incubator/kavitaemail/values.yaml
  cspell.config.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3978 chore(authentik): move to stable
  charts/incubator/immich/values.yaml
  charts/stable/authentik/.helmignore
  charts/stable/authentik/CHANGELOG.md
  charts/stable/authentik/Chart.yaml
  charts/stable/authentik/README.md
  charts/stable/authentik/docs/installation_notes.md
  charts/stable/authentik/icon.png
  charts/stable/authentik/questions.yaml
  charts/stable/authentik/templates/_config.tpl
  charts/stable/authentik/templates/_geoip.tpl
  charts/stable/authentik/templates/_ldap.tpl
  charts/stable/authentik/templates/_proxy.tpl
  charts/stable/authentik/templates/_secret.tpl
  charts/stable/authentik/templates/_worker.tpl
  charts/stable/authentik/templates/common.yaml
  charts/stable/authentik/values.yaml
  cspell.config.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3977 chore(deps): update renovatebot/github-action action to v32.211.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3981 chore(deps): update renovatebot/github-action action to v32.211.1
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3980 fix(redisinsight) code clean up
  charts/incubator/redisinsight/Chart.yaml
  charts/incubator/redisinsight/docs/installation_notes.md
  charts/incubator/redisinsight/questions.yaml
  charts/incubator/redisinsight/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3983 fix(authentik): move some files that left behind
  charts/stable/authentik/Chart.yaml
  charts/stable/authentik/templates/prometheusrules.yaml
  charts/stable/authentik/templates/servicemonitor.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3982 fix(kavitaemail) fix description.
  charts/incubator/kavitaemail/Chart.yaml
  charts/incubator/kavitaemail/questions.yaml
  charts/incubator/kavitaemail/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#3987 fix(adguard-home): Change port on main service
  charts/stable/adguard-home/Chart.yaml
  charts/stable/adguard-home/questions.yaml
  charts/stable/adguard-home/values.yaml
  cspell.config.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3991 chore(deps): update renovatebot/github-action action to v32.213.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3988 chore(deps): update docker general non-major
  charts/dependency/redis/values.yaml
  charts/incubator/appsmith/values.yaml
  charts/incubator/batnoter/values.yaml
  charts/incubator/cryptpad/values.yaml
  charts/incubator/cups-server/values.yaml
  charts/incubator/jupyter/values.yaml
  charts/incubator/kavitaemail/values.yaml
  charts/incubator/kdenlive/values.yaml
  charts/incubator/obs-ndi/values.yaml
  charts/incubator/passwordpusherephemeral/values.yaml
  charts/incubator/plextraktsync/values.yaml
  charts/incubator/prpdf/values.yaml
  charts/incubator/redisinsight/values.yaml
  charts/incubator/rimgo/values.yaml
  charts/incubator/rustpad/values.yaml
  charts/incubator/searx/values.yaml
  charts/incubator/searxng/values.yaml
  charts/incubator/telethon-downloader/values.yaml
  charts/incubator/timetagger/values.yaml
  charts/incubator/traktarr/values.yaml
  charts/incubator/ts-dnsserver/values.yaml
  charts/incubator/vertex/values.yaml
  charts/incubator/virt-manager/values.yaml
  charts/incubator/webtop/values.yaml
  charts/stable/boinc/values.yaml
  charts/stable/calibre/values.yaml
  charts/stable/code-server/values.yaml
  charts/stable/custom-app/ci/test-values.yaml
  charts/stable/custom-app/values.yaml
  charts/stable/cyberchef/values.yaml
  charts/stable/emby/values.yaml
  charts/stable/hedgedoc/values.yaml
  charts/stable/homepage/values.yaml
  charts/stable/jackett/values.yaml
  charts/stable/lazylibrarian/values.yaml
  charts/stable/littlelink/values.yaml
  charts/stable/nextcloud/values.yaml
  charts/stable/ombi/values.yaml
  charts/stable/prometheus/values.yaml
  charts/stable/rsshub/values.yaml
  charts/stable/wger/values.yaml
  charts/stable/zigbee2mqtt/values.yaml
Labels: size/M, precommit:ok

#3993 feat(microbin): add microbin
  charts/incubator/microbin/.helmignore
  charts/incubator/microbin/Chart.yaml
  charts/incubator/microbin/README.md
  charts/incubator/microbin/icon.png
  charts/incubator/microbin/questions.yaml
  charts/incubator/microbin/templates/_args.tpl
  charts/incubator/microbin/templates/common.yaml
  charts/incubator/microbin/values.yaml
  cspell.config.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3994 chore(deps): update docker general non-major
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/mariadb/values.yaml
  charts/incubator/chromium/Chart.yaml
  charts/incubator/chromium/values.yaml
  charts/incubator/crafty-4/Chart.yaml
  charts/incubator/crafty-4/values.yaml
  charts/incubator/rimgo/Chart.yaml
  charts/incubator/rimgo/values.yaml
  charts/incubator/telethon-downloader/Chart.yaml
  charts/incubator/telethon-downloader/values.yaml
  charts/incubator/virt-manager/Chart.yaml
  charts/incubator/virt-manager/values.yaml
  charts/stable/cyberchef/Chart.yaml
  charts/stable/cyberchef/values.yaml
  charts/stable/rsshub/Chart.yaml
  charts/stable/rsshub/values.yaml
Labels: size/S, lint:ok, precommit:ok

#3997 chore(deps): update renovatebot/github-action action to v32.213.2
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3996 feat(money-balancer): add money-balancer
  charts/incubator/money-balancer/.helmignore
  charts/incubator/money-balancer/Chart.yaml
  charts/incubator/money-balancer/README.md
  charts/incubator/money-balancer/icon.png
  charts/incubator/money-balancer/questions.yaml
  charts/incubator/money-balancer/templates/_secrets.tpl
  charts/incubator/money-balancer/templates/common.yaml
  charts/incubator/money-balancer/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3998 fix(immich): actually spin up microservices contaienr
  charts/incubator/immich/Chart.yaml
  charts/incubator/immich/templates/_microservices.tpl
  charts/incubator/immich/templates/common.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4000 chore(deps): update ghcr.io/truecharts/devcontainer:v2.6.0 docker digest to a82c7d3
  .github/workflows/catalog-test.yaml
  .github/workflows/charts-release.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4002 chore(deps): update container image tccr.io/truecharts/flatnotes to v2.0.0
  charts/incubator/flatnotes/Chart.yaml
  charts/incubator/flatnotes/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4004 chore(deps): update actions/checkout action to v3.1.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4006 chore(deps): update actions/checkout digest to 93ea575
  .github/workflows/catalog-test.yaml
  .github/workflows/charts-changelog.yaml
  .github/workflows/charts-lint.yaml
  .github/workflows/charts-release.yaml
  .github/workflows/charts-test.yaml
  .github/workflows/general.security-scan.yaml
  .github/workflows/meta-label-pr-ci-status.yaml
  .github/workflows/metadata-label-commenter.yaml
  .github/workflows/pr-metadata.yaml
  .github/workflows/prune.yaml
  .github/workflows/renovate-bump.yaml
  .github/workflows/schedule-sync-labels.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#4007 chore(deps): update renovatebot/github-action action to v32.214.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4005 fix(authentik): fix UI for nested subquestions
  charts/stable/authentik/Chart.yaml
  charts/stable/authentik/questions.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#4012 chore(deps): update renovatebot/github-action action to v32.216.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4010 chore(deps): update docker general non-major
  charts/dependency/redis/Chart.yaml
  charts/dependency/redis/values.yaml
  charts/incubator/adguardhome-sync/Chart.yaml
  charts/incubator/adguardhome-sync/values.yaml
  charts/incubator/chronograf/Chart.yaml
  charts/incubator/chronograf/values.yaml
  charts/incubator/cryptpad/Chart.yaml
  charts/incubator/cryptpad/values.yaml
  charts/incubator/filestash/Chart.yaml
  charts/incubator/filestash/values.yaml
  charts/incubator/kasm/Chart.yaml
  charts/incubator/kasm/values.yaml
  charts/incubator/passwordpusherephemeral/Chart.yaml
  charts/incubator/passwordpusherephemeral/values.yaml
  charts/incubator/rimgo/Chart.yaml
  charts/incubator/rimgo/values.yaml
  charts/incubator/vertex/Chart.yaml
  charts/incubator/vertex/values.yaml
  charts/incubator/virt-manager/Chart.yaml
  charts/incubator/virt-manager/values.yaml
  charts/stable/calibre-web/Chart.yaml
  charts/stable/calibre-web/values.yaml
  charts/stable/cyberchef/Chart.yaml
  charts/stable/cyberchef/values.yaml
  charts/stable/hedgedoc/Chart.yaml
  charts/stable/hedgedoc/values.yaml
  charts/stable/lazylibrarian/Chart.yaml
  charts/stable/lazylibrarian/values.yaml
  charts/stable/prometheus/Chart.yaml
  charts/stable/prometheus/values.yaml
  charts/stable/rsshub/Chart.yaml
  charts/stable/rsshub/values.yaml
  charts/stable/syncthing/Chart.yaml
  charts/stable/syncthing/values.yaml
  charts/stable/zwavejs2mqtt/Chart.yaml
  charts/stable/zwavejs2mqtt/values.yaml
Labels: lint:ok, size/M, precommit:ok

#4016 chore(deps): update renovatebot/github-action action to v32.217.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4022 chore(deps): update helm chart common to v10.6.11
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4020 chore(deps): update github/codeql-action digest to 8075783
  .github/workflows/general.security-scan.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4023 chore(deps): update renovatebot/github-action action to v32.221.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4021 chore(deps): update helm chart common to v10.6.11
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/promtail/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
Labels: size/S, lint:ok, precommit:ok

#4024 chore(deps): update renovatebot/github-action action to v32.221.1
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4025 chore(deps): update ghcr.io/truecharts/devcontainer:v2.6.0 docker digest to 5029ebe
  .github/workflows/catalog-test.yaml
  .github/workflows/charts-release.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4026 chore(deps): update actions/stale digest to 5ebf00e
  .github/workflows/stale.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4030 chore(deps): update docker general non-major
  charts/incubator/adminer/Chart.yaml
  charts/incubator/adminer/values.yaml
  charts/incubator/cryptpad/Chart.yaml
  charts/incubator/cryptpad/values.yaml
  charts/incubator/jitsi/Chart.yaml
  charts/incubator/jitsi/values.yaml
  charts/incubator/livebook/Chart.yaml
  charts/incubator/livebook/values.yaml
  charts/incubator/maloja/Chart.yaml
  charts/incubator/maloja/values.yaml
  charts/incubator/passwordpusherephemeral/Chart.yaml
  charts/incubator/passwordpusherephemeral/values.yaml
  charts/incubator/rickroll/Chart.yaml
  charts/incubator/rickroll/values.yaml
  charts/incubator/rimgo/Chart.yaml
  charts/incubator/rimgo/values.yaml
  charts/stable/alist/Chart.yaml
  charts/stable/alist/values.yaml
  charts/stable/focalboard/Chart.yaml
  charts/stable/focalboard/values.yaml
  charts/stable/hedgedoc/Chart.yaml
  charts/stable/hedgedoc/values.yaml
  charts/stable/koel/Chart.yaml
  charts/stable/koel/values.yaml
  charts/stable/lazylibrarian/Chart.yaml
  charts/stable/lazylibrarian/values.yaml
  charts/stable/matomo/Chart.yaml
  charts/stable/matomo/values.yaml
  charts/stable/minecraft-java/Chart.yaml
  charts/stable/minecraft-java/ci/j11-values.yaml
  charts/stable/minecraft-java/values.yaml
  charts/stable/nextcloud/Chart.yaml
  charts/stable/nextcloud/values.yaml
  charts/stable/ombi/Chart.yaml
  charts/stable/ombi/values.yaml
  charts/stable/prometheus/Chart.yaml
  charts/stable/prometheus/values.yaml
  charts/stable/redmine/Chart.yaml
  charts/stable/redmine/values.yaml
  charts/stable/rsshub/Chart.yaml
  charts/stable/rsshub/values.yaml
  charts/stable/snapdrop/Chart.yaml
  charts/stable/snapdrop/values.yaml
Labels: size/M, precommit:ok

#4031 chore(deps): update renovatebot/github-action action to v32.225.1
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4035 chore(rss-bridge): manual update and fix renovate
  .github/renovate.json5
  charts/stable/rss-bridge/Chart.yaml
  charts/stable/rss-bridge/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4036 feat(Joplin-Server): Add Email config for users
  charts/stable/joplin-server/Chart.yaml
  charts/stable/joplin-server/questions.yaml
  charts/stable/joplin-server/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#4011 feat(fidi) add fireflyiii-data-importer
  charts/incubator/fireflyiii-data-importer/.helmignore
  charts/incubator/fireflyiii-data-importer/Chart.yaml
  charts/incubator/fireflyiii-data-importer/README.md
  charts/incubator/fireflyiii-data-importer/icon.png
  charts/incubator/fireflyiii-data-importer/questions.yaml
  charts/incubator/fireflyiii-data-importer/templates/common.yaml
  charts/incubator/fireflyiii-data-importer/values.yaml
  cspell.config.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3999 feat(docspell): add docspell
  charts/incubator/docspell/.helmignore
  charts/incubator/docspell/Chart.yaml
  charts/incubator/docspell/README.md
  charts/incubator/docspell/icon.png
  charts/incubator/docspell/questions.yaml
  charts/incubator/docspell/templates/_dsc.tpl
  charts/incubator/docspell/templates/_joex.tpl
  charts/incubator/docspell/templates/_secret.tpl
  charts/incubator/docspell/templates/common.yaml
  charts/incubator/docspell/values.yaml
  cspell.config.yaml
Labels: install:ok, lint:ok, size/XXL, precommit:ok

#4037 chore(joplin-server): fix show-if's
  charts/stable/joplin-server/Chart.yaml
  charts/stable/joplin-server/questions.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4038 chore(deps): update docker general non-major
  charts/incubator/adminer/values.yaml
  charts/incubator/apprise-api/values.yaml
  charts/incubator/chromium-desktop-g3/values.yaml
  charts/incubator/crypto-exchanges-gateway/values.yaml
  charts/incubator/cryptpad/values.yaml
  charts/incubator/docspell/values.yaml
  charts/incubator/firefox-desktop-g3/values.yaml
  charts/incubator/icloudpd/values.yaml
  charts/incubator/kdenlive/values.yaml
  charts/incubator/passwordpusherephemeral/values.yaml
  charts/incubator/rimgo/values.yaml
  charts/incubator/searxng/values.yaml
  charts/incubator/traktarr/values.yaml
  charts/incubator/ts-dnsserver/values.yaml
  charts/incubator/vertex/values.yaml
  charts/incubator/virt-manager/values.yaml
  charts/incubator/yourls/values.yaml
  charts/stable/adguard-home/values.yaml
  charts/stable/audiobookshelf/values.yaml
  charts/stable/boinc/values.yaml
  charts/stable/calibre/values.yaml
  charts/stable/cloudflareddns/values.yaml
  charts/stable/custom-app/ci/test-values.yaml
  charts/stable/custom-app/values.yaml
  charts/stable/cyberchef/values.yaml
  charts/stable/flexget/values.yaml
  charts/stable/homepage/values.yaml
  charts/stable/ispy-agent-dvr/values.yaml
  charts/stable/jackett/values.yaml
  charts/stable/minecraft-java/ci/j11-values.yaml
  charts/stable/minecraft-java/ci/j8-values.yaml
  charts/stable/minecraft-java/values.yaml
  charts/stable/mosdns/values.yaml
  charts/stable/nextcloud/values.yaml
  charts/stable/prometheus/values.yaml
  charts/stable/rsshub/values.yaml
  charts/stable/synclounge/values.yaml
  charts/stable/tinymediamanager/values.yaml
  charts/stable/traefik/values.yaml
  charts/stable/wger/values.yaml
  charts/stable/xwiki/values.yaml
Labels: size/M, precommit:ok

#4040 fix(docspell): fix solr ulr
  charts/dependency/solr/Chart.yaml
  charts/dependency/solr/questions.yaml
  charts/dependency/solr/values.yaml
  charts/incubator/docspell/Chart.yaml
  charts/incubator/docspell/docs/installation-notes.md
  charts/incubator/docspell/templates/_joex.tpl
  charts/incubator/docspell/templates/_secret.tpl
  charts/incubator/docspell/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#4042 fix(docspell): disable solr auth for now
  charts/incubator/docspell/Chart.yaml
  charts/incubator/docspell/templates/_secret.tpl
  charts/incubator/docspell/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4044 fix(docspell): fix dsc binary location
  charts/incubator/docspell/Chart.yaml
  charts/incubator/docspell/templates/_dsc.tpl
  charts/incubator/docspell/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4048 feat(speedtest-tracker): add speedtest-tracker
  charts/incubator/speedtest-tracker/.helmignore
  charts/incubator/speedtest-tracker/Chart.yaml
  charts/incubator/speedtest-tracker/README.md
  charts/incubator/speedtest-tracker/docs/credentials.md
  charts/incubator/speedtest-tracker/icon.png
  charts/incubator/speedtest-tracker/questions.yaml
  charts/incubator/speedtest-tracker/templates/common.yaml
  charts/incubator/speedtest-tracker/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#4047 feat(xen-orchestra): add xen-orchestra
  charts/incubator/speedtest-tracker/Chart.yaml
  charts/incubator/speedtest-tracker/values.yaml
  charts/incubator/xen-orchestra/.helmignore
  charts/incubator/xen-orchestra/Chart.yaml
  charts/incubator/xen-orchestra/README.md
  charts/incubator/xen-orchestra/docs/credentials.md
  charts/incubator/xen-orchestra/icon.png
  charts/incubator/xen-orchestra/questions.yaml
  charts/incubator/xen-orchestra/templates/common.yaml
  charts/incubator/xen-orchestra/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#4050 chore(deps): update renovatebot/github-action action to v32.226.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4051 fix(homelablabelmaker): Cleanup to work with SCALE
  charts/incubator/homelablabelmaker/Chart.yaml
  charts/incubator/homelablabelmaker/questions.yaml
  charts/incubator/homelablabelmaker/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#4049 chore(deps): update docker general non-major
  charts/incubator/cloudcommander/Chart.yaml
  charts/incubator/cloudcommander/values.yaml
  charts/incubator/cups-server/Chart.yaml
  charts/incubator/cups-server/values.yaml
  charts/incubator/docspell/Chart.yaml
  charts/incubator/docspell/values.yaml
  charts/incubator/kasm/Chart.yaml
  charts/incubator/kasm/values.yaml
  charts/incubator/livebook/Chart.yaml
  charts/incubator/livebook/values.yaml
  charts/incubator/passwordpusherephemeral/Chart.yaml
  charts/incubator/passwordpusherephemeral/values.yaml
  charts/incubator/rimgo/Chart.yaml
  charts/incubator/rimgo/values.yaml
  charts/incubator/webp-server/Chart.yaml
  charts/incubator/webp-server/values.yaml
  charts/stable/dokuwiki/Chart.yaml
  charts/stable/dokuwiki/values.yaml
  charts/stable/grafana/Chart.yaml
  charts/stable/grafana/values.yaml
  charts/stable/homer/Chart.yaml
  charts/stable/homer/values.yaml
  charts/stable/ispy-agent-dvr/Chart.yaml
  charts/stable/ispy-agent-dvr/values.yaml
  charts/stable/kanboard/Chart.yaml
  charts/stable/kanboard/values.yaml
  charts/stable/minio/Chart.yaml
  charts/stable/minio/values.yaml
  charts/stable/picoshare/Chart.yaml
  charts/stable/picoshare/values.yaml
  charts/stable/prometheus/Chart.yaml
  charts/stable/prometheus/values.yaml
  charts/stable/rsshub/Chart.yaml
  charts/stable/rsshub/values.yaml
  charts/stable/uptime-kuma/Chart.yaml
  charts/stable/uptime-kuma/values.yaml
Labels: lint:ok, size/M, precommit:ok

#4054 fix(Phoenixstats): Deprecate Chart
  charts/incubator/phoenixstats/Chart.yaml
Labels: size/XS

#4064 chore(deps): update helm chart common to v10.7.0
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4063 chore(deps): update helm chart common to v10.7.0
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/promtail/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
Labels: size/S, lint:ok, precommit:ok

#4067 feat(prometheus): Filter veth from (duplicate) network device metrics
  charts/stable/prometheus/Chart.yaml
  charts/stable/prometheus/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4065 chore(deps): update renovatebot/github-action action to v32.229.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4062 chore(deps): update stefanzweifel/git-auto-commit-action digest to fd157da
  .github/workflows/charts-changelog.yaml
  .github/workflows/charts-release.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4061 chore(deps): update actions/setup-python digest to 13ae5bb
  .github/workflows/charts-lint.yaml
  .github/workflows/charts-test.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#4058 fix(browserless-chrome) allow user to set CONNECTION_TIMEOUT in gui.
  charts/stable/browserless-chrome/Chart.yaml
  charts/stable/browserless-chrome/questions.yaml
  charts/stable/browserless-chrome/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4074 chore(deps): update renovatebot/github-action action to v32.232.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4077 chore(deps): update actions/github-script digest to 1005277
  .github/workflows/meta-label-pr-ci-status.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4078 chore(deps): update juliangruber/read-file-action action to v1.1.5
  .github/workflows/meta-label-pr-ci-status.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4079 fix(lancache) move monolithic + dns to stable.
  charts/incubator/lancache-monolithic/docs/installation_notes.md
  charts/stable/lancache-dns/.helmignore
  charts/stable/lancache-dns/CHANGELOG.md
  charts/stable/lancache-dns/Chart.yaml
  charts/stable/lancache-dns/README.md
  charts/stable/lancache-dns/docs/installation_notes.md
  charts/stable/lancache-dns/icon.png
  charts/stable/lancache-dns/questions.yaml
  charts/stable/lancache-dns/templates/common.yaml
  charts/stable/lancache-dns/values.yaml
  charts/stable/lancache-monolithic/.helmignore
  charts/stable/lancache-monolithic/CHANGELOG.md
  charts/stable/lancache-monolithic/Chart.yaml
  charts/stable/lancache-monolithic/README.md
  charts/stable/lancache-monolithic/docs/installation_notes.md
  charts/stable/lancache-monolithic/icon.png
  charts/stable/lancache-monolithic/questions.yaml
  charts/stable/lancache-monolithic/templates/common.yaml
  charts/stable/lancache-monolithic/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#4080 feat(Omada-Controller): Add additional ENV VARS
  charts/stable/omada-controller/Chart.yaml
  charts/stable/omada-controller/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4081 chore(deps): update renovatebot/github-action action to v32.234.2
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4082 chore(deps): update juliangruber/read-file-action action to v1.1.6
  .github/workflows/meta-label-pr-ci-status.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4083 chore(deps): update renovatebot/github-action action to v32.236.1
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4088 chore(deps): update renovatebot/github-action action to v32.236.2
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4091 chore(deps): update renovatebot/github-action action to v32.236.4
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4095 chore(deps): update actions/github-script digest to d556fea
  .github/workflows/meta-label-pr-ci-status.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4094 feat(Immich): Move to Stable
  charts/stable/immich/.helmignore
  charts/stable/immich/CHANGELOG.md
  charts/stable/immich/Chart.yaml
  charts/stable/immich/README.md
  charts/stable/immich/icon.png
  charts/stable/immich/questions.yaml
  charts/stable/immich/templates/_configmap.tpl
  charts/stable/immich/templates/_microservices.tpl
  charts/stable/immich/templates/_ml.tpl
  charts/stable/immich/templates/_proxy.tpl
  charts/stable/immich/templates/_secret.tpl
  charts/stable/immich/templates/_web.tpl
  charts/stable/immich/templates/common.yaml
  charts/stable/immich/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4092 chore(deps): update container image tccr.io/truecharts/dupeguru to v22.10.1
  charts/stable/dupeguru/Chart.yaml
  charts/stable/dupeguru/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4086 feat(retrobot) add retrobot.
  charts/incubator/retrobot/.helmignore
  charts/incubator/retrobot/Chart.yaml
  charts/incubator/retrobot/README.md
  charts/incubator/retrobot/icon.png
  charts/incubator/retrobot/questions.yaml
  charts/incubator/retrobot/templates/common.yaml
  charts/incubator/retrobot/values.yaml
  cspell.config.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#4097 chore(deps): update renovatebot/github-action action to v32.238.1
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4098 chore(deps): update container image tccr.io/truecharts/mediainfo to v22.10.1
  charts/stable/mediainfo/Chart.yaml
  charts/stable/mediainfo/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4100 chore(deps): update helm chart common to v10.7.1
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/promtail/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
Labels: size/S, lint:ok, precommit:ok

#4102 chore(deps): update dawidd6/action-download-artifact action to v2.24.0
  .github/workflows/meta-label-pr-ci-status.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4106 feat(grist): BREAKING CHANGE - rework, adds postgres and more options
  charts/stable/grist/Chart.yaml
  charts/stable/grist/questions.yaml
  charts/stable/grist/templates/_config.tpl
  charts/stable/grist/templates/_secret.tpl
  charts/stable/grist/templates/common.yaml
  charts/stable/grist/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#4105 chore(deps): update renovatebot/github-action action to v32.238.2
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4101 chore(deps): update helm chart common to v10.7.1
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4109 chore(deps): update renovatebot/github-action action to v32.238.3
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4107 fix(Omada): Switch internal https port to 443, to stop redirection to 8043 on ingress
  charts/stable/omada-controller/Chart.yaml
  charts/stable/omada-controller/questions.yaml
  charts/stable/omada-controller/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4110 chore(deps): update tj-actions/branch-names action to v6.2
  .github/workflows/pr-metadata.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4108 chore(deps): update docker general non-major
  charts/incubator/cryptpad/Chart.yaml
  charts/incubator/cryptpad/values.yaml
  charts/incubator/ghost/Chart.yaml
  charts/incubator/ghost/values.yaml
  charts/incubator/kdenlive/Chart.yaml
  charts/incubator/kdenlive/values.yaml
  charts/incubator/passwordpusherephemeral/Chart.yaml
  charts/incubator/passwordpusherephemeral/values.yaml
  charts/incubator/rdesktop/Chart.yaml
  charts/incubator/rdesktop/values.yaml
  charts/incubator/rimgo/Chart.yaml
  charts/incubator/rimgo/values.yaml
  charts/incubator/traktarr/Chart.yaml
  charts/incubator/traktarr/values.yaml
  charts/incubator/vertex/Chart.yaml
  charts/incubator/vertex/values.yaml
  charts/incubator/virt-manager/Chart.yaml
  charts/incubator/virt-manager/values.yaml
  charts/incubator/xen-orchestra/Chart.yaml
  charts/incubator/xen-orchestra/values.yaml
  charts/stable/bazarr/Chart.yaml
  charts/stable/bazarr/values.yaml
  charts/stable/boinc/Chart.yaml
  charts/stable/boinc/values.yaml
  charts/stable/calibre/Chart.yaml
  charts/stable/calibre/values.yaml
  charts/stable/cyberchef/Chart.yaml
  charts/stable/cyberchef/values.yaml
  charts/stable/flexget/Chart.yaml
  charts/stable/flexget/values.yaml
  charts/stable/gitea/Chart.yaml
  charts/stable/gitea/values.yaml
  charts/stable/grafana/Chart.yaml
  charts/stable/grafana/values.yaml
  charts/stable/lanraragi/Chart.yaml
  charts/stable/lanraragi/values.yaml
  charts/stable/mediainfo/Chart.yaml
  charts/stable/mediainfo/values.yaml
  charts/stable/minio-console/Chart.yaml
  charts/stable/minio-console/values.yaml
  charts/stable/minio/Chart.yaml
  charts/stable/minio/values.yaml
  charts/stable/n8n/Chart.yaml
  charts/stable/n8n/values.yaml
  charts/stable/overseerr/Chart.yaml
  charts/stable/overseerr/values.yaml
  charts/stable/promcord/Chart.yaml
  charts/stable/promcord/ci/no-values.yaml
  charts/stable/prometheus/Chart.yaml
  charts/stable/prometheus/values.yaml
  charts/stable/rsshub/Chart.yaml
  charts/stable/rsshub/values.yaml
  charts/stable/satisfactory/Chart.yaml
  charts/stable/satisfactory/values.yaml
  charts/stable/vaultwarden/Chart.yaml
  charts/stable/vaultwarden/values.yaml
Labels: size/M, precommit:ok

#4111 chore(deps): update renovatebot/github-action action to v32.238.4
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4115 fix(docker-compose): remove /root for bluefin
  charts/stable/docker-compose/Chart.yaml
  charts/stable/docker-compose/questions.yaml
  charts/stable/docker-compose/values.yaml
Labels: size/M

#4046 feat(zabbix): rework
  charts/incubator/zabbix-server/CHANGELOG.md
  charts/incubator/zabbix-server/README.md
  charts/incubator/zabbix-server/questions.yaml
  charts/incubator/zabbix-server/templates/common.yaml
  charts/incubator/zabbix-server/values.yaml
  charts/incubator/zabbix/.helmignore
  charts/incubator/zabbix/CHANGELOG.md
  charts/incubator/zabbix/Chart.yaml
  charts/incubator/zabbix/README.md
  charts/incubator/zabbix/icon.png
  charts/incubator/zabbix/questions.yaml
  charts/incubator/zabbix/templates/_agent.tpl
  charts/incubator/zabbix/templates/_config.tpl
  charts/incubator/zabbix/templates/_frontend.tpl
  charts/incubator/zabbix/templates/_javagateway.tpl
  charts/incubator/zabbix/templates/_secret.tpl
  charts/incubator/zabbix/templates/_snmp.tpl
  charts/incubator/zabbix/templates/_webservice.tpl
  charts/incubator/zabbix/templates/common.yaml
  charts/incubator/zabbix/values.yaml
  cspell.config.yaml
Labels: install:ok, lint:ok, size/XXL, precommit:ok

#4112 add(nginx-proxy-manager): add nginx-proxy-manager
  charts/incubator/nginx-proxy-manager/.helmignore
  charts/incubator/nginx-proxy-manager/Chart.yaml
  charts/incubator/nginx-proxy-manager/README.md
  charts/incubator/nginx-proxy-manager/docs/credentials.md
  charts/incubator/nginx-proxy-manager/docs/disclaimer.md
  charts/incubator/nginx-proxy-manager/icon.png
  charts/incubator/nginx-proxy-manager/questions.yaml
  charts/incubator/nginx-proxy-manager/templates/common.yaml
  charts/incubator/nginx-proxy-manager/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#4116 feat(piwigo): Add persistance for Gallery dir
  charts/incubator/piwigo/Chart.yaml
  charts/incubator/piwigo/questions.yaml
  charts/incubator/piwigo/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#4119 chore(deps): update docker general non-major
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/mariadb/values.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/memcached/values.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/mongodb/values.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/postgresql/values.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/redis/values.yaml
  charts/dependency/solr/Chart.yaml
  charts/dependency/solr/values.yaml
  charts/incubator/apprise-api/Chart.yaml
  charts/incubator/apprise-api/values.yaml
  charts/incubator/cryptpad/Chart.yaml
  charts/incubator/cryptpad/values.yaml
  charts/incubator/cups-server/Chart.yaml
  charts/incubator/cups-server/values.yaml
  charts/incubator/nginx-proxy-manager/Chart.yaml
  charts/incubator/nginx-proxy-manager/values.yaml
  charts/incubator/passwordpusherephemeral/Chart.yaml
  charts/incubator/passwordpusherephemeral/values.yaml
  charts/incubator/rimgo/Chart.yaml
  charts/incubator/rimgo/values.yaml
  charts/incubator/virt-manager/Chart.yaml
  charts/incubator/virt-manager/values.yaml
  charts/incubator/webtop/Chart.yaml
  charts/incubator/webtop/values.yaml
  charts/stable/booksonic-air/Chart.yaml
  charts/stable/booksonic-air/values.yaml
  charts/stable/custom-app/Chart.yaml
  charts/stable/custom-app/ci/test-values.yaml
  charts/stable/custom-app/values.yaml
  charts/stable/cyberchef/Chart.yaml
  charts/stable/cyberchef/values.yaml
  charts/stable/homepage/Chart.yaml
  charts/stable/homepage/values.yaml
  charts/stable/jackett/Chart.yaml
  charts/stable/jackett/values.yaml
  charts/stable/minecraft-java/Chart.yaml
  charts/stable/minecraft-java/ci/j11-values.yaml
  charts/stable/minecraft-java/ci/j8-values.yaml
  charts/stable/minecraft-java/values.yaml
  charts/stable/prometheus/Chart.yaml
  charts/stable/prometheus/values.yaml
  charts/stable/tvheadend/Chart.yaml
  charts/stable/tvheadend/values.yaml
Labels: size/M, precommit:ok

#4123 chore(deps): update container image tccr.io/truecharts/mkvtoolnix to v22.10.1
  charts/stable/mkvtoolnix/Chart.yaml
  charts/stable/mkvtoolnix/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4121 chore(deps): update endbug/label-sync digest to 3478705
  .github/workflows/schedule-sync-labels.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4120 chore(deps): update docker general non-major
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/postgresql/values.yaml
  charts/incubator/neko/Chart.yaml
  charts/incubator/neko/values.yaml
  charts/incubator/vertex/Chart.yaml
  charts/incubator/vertex/values.yaml
  charts/stable/dokuwiki/Chart.yaml
  charts/stable/dokuwiki/values.yaml
  charts/stable/minecraft-java/Chart.yaml
  charts/stable/minecraft-java/ci/j11-values.yaml
  charts/stable/minecraft-java/ci/j8-values.yaml
  charts/stable/minecraft-java/values.yaml
  charts/stable/miniflux/Chart.yaml
  charts/stable/miniflux/values.yaml
  charts/stable/navidrome/Chart.yaml
  charts/stable/navidrome/values.yaml
  charts/stable/prometheus/Chart.yaml
  charts/stable/prometheus/values.yaml
  charts/stable/synapse/Chart.yaml
  charts/stable/synapse/values.yaml
Labels: size/S, lint:ok, precommit:ok

#4124 chore(deps): update renovatebot/github-action action to v32.240.2
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4129 chore(deps): update renovatebot/github-action action to v32.240.4
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4135 fix(wireshark): run privileged by default
  charts/stable/wireshark/Chart.yaml
  charts/stable/wireshark/questions.yaml
  charts/stable/wireshark/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#4136 chore(filebrowser): Update and rename credentials.md to installation_notes.md
  charts/stable/filebrowser/Chart.yaml
  charts/stable/filebrowser/docs/credentials.md
  charts/stable/filebrowser/docs/installation_notes.md
Labels: size/S, precommit:failed, install:ok, lint:ok

#4134 chore(deps): update renovatebot/github-action action to v32.240.5
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4140 fix(minecraft-bungeecord) set rcon to the actual rcon port
  charts/incubator/minecraft-bungeecord/Chart.yaml
  charts/incubator/minecraft-bungeecord/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4144 chore(deps): update helm chart common to v10.7.2
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4145 chore(deps): update renovatebot/github-action action to v32.241.5
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4143 chore(deps): update helm chart common to v10.7.2
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/promtail/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
Labels: size/S, lint:ok, precommit:ok

#4147 chore(deps): update helm chart common to v10.7.4
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/promtail/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
Labels: size/S, lint:ok, precommit:ok

#4148 chore(deps): update helm chart common to v10.7.4
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4149 fix(traefik): fix CRD update and common update
  charts/stable/traefik/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4153 Update Common library URL
  templates/docs/README.md.gotmpl
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4150 chore(deps): update helm chart common to v10.7.6
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/promtail/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
Labels: size/S, lint:ok, precommit:ok

#4152 chore(deps): update renovatebot/github-action action to v32.241.7
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4154 chore(deps): update actions/upload-artifact digest to 83fd05a
  .github/workflows/pr-metadata.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4157 chore(deps): update renovatebot/github-action action to v32.241.8
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4151 chore(deps): update helm chart common to v10.7.6
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4146 fix(minecraft-bungeecord) how-to
  charts/incubator/minecraft-bungeecord/Chart.yaml
  charts/incubator/minecraft-bungeecord/docs/How-To.md
Labels: install:ok, lint:ok, size/L, precommit:ok

#4162 chore(deps): update helm chart common to v10.7.7
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/promtail/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
Labels: size/S, lint:ok, precommit:ok

#4163 chore(deps): update helm chart common to v10.7.7
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4161 chore(deps): update stefanzweifel/git-auto-commit-action digest to 2fde6fc
  .github/workflows/charts-changelog.yaml
  .github/workflows/charts-release.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4158 fix(protonmail-bridge) add installations docs + added imap port.
  charts/stable/protonmail-bridge/Chart.yaml
  charts/stable/protonmail-bridge/docs/installation_notes.md
  charts/stable/protonmail-bridge/questions.yaml
  charts/stable/protonmail-bridge/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#4156 fix(minecraft-java) added Custom type and removed portal and fix variable type
  charts/stable/minecraft-java/Chart.yaml
  charts/stable/minecraft-java/questions.yaml
  charts/stable/minecraft-java/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#4164 chore(deps): update renovatebot/github-action action to v32.241.10
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4165 chore(deps): update docker general non-major
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/mariadb/values.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/memcached/values.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/mongodb/values.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/redis/values.yaml
  charts/dependency/solr/Chart.yaml
  charts/dependency/solr/values.yaml
  charts/incubator/blender-desktop-g3/Chart.yaml
  charts/incubator/blender-desktop-g3/values.yaml
  charts/incubator/dontstarvetogether/Chart.yaml
  charts/incubator/dontstarvetogether/values.yaml
  charts/incubator/kdenlive/Chart.yaml
  charts/incubator/kdenlive/values.yaml
  charts/incubator/opengl-desktop-g3/Chart.yaml
  charts/incubator/opengl-desktop-g3/values.yaml
  charts/incubator/passwordpusherephemeral/Chart.yaml
  charts/incubator/passwordpusherephemeral/values.yaml
  charts/incubator/rdesktop/Chart.yaml
  charts/incubator/rdesktop/values.yaml
  charts/incubator/troddit/Chart.yaml
  charts/incubator/troddit/values.yaml
  charts/incubator/vertex/Chart.yaml
  charts/incubator/vertex/values.yaml
  charts/incubator/virt-manager/Chart.yaml
  charts/incubator/virt-manager/values.yaml
  charts/stable/boinc/Chart.yaml
  charts/stable/boinc/values.yaml
  charts/stable/calibre-web/Chart.yaml
  charts/stable/calibre-web/values.yaml
  charts/stable/calibre/Chart.yaml
  charts/stable/calibre/values.yaml
  charts/stable/cyberchef/Chart.yaml
  charts/stable/cyberchef/values.yaml
  charts/stable/ddclient/Chart.yaml
  charts/stable/ddclient/values.yaml
  charts/stable/freshrss/Chart.yaml
  charts/stable/freshrss/values.yaml
  charts/stable/kavita/Chart.yaml
  charts/stable/kavita/values.yaml
  charts/stable/littlelink/Chart.yaml
  charts/stable/littlelink/values.yaml
  charts/stable/minecraft-java/Chart.yaml
  charts/stable/minecraft-java/ci/j11-values.yaml
  charts/stable/minecraft-java/ci/j8-values.yaml
  charts/stable/minecraft-java/values.yaml
  charts/stable/ombi/Chart.yaml
  charts/stable/ombi/values.yaml
  charts/stable/prometheus/Chart.yaml
  charts/stable/prometheus/values.yaml
  charts/stable/rsshub/Chart.yaml
  charts/stable/rsshub/values.yaml
  charts/stable/trilium-notes/Chart.yaml
  charts/stable/trilium-notes/values.yaml
Labels: size/M, precommit:ok

#4168 chore(deps): update renovatebot/github-action action to v32.241.11
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4173 fix(minecraft-bedrock) add OPS variable + How-To
  charts/stable/minecraft-bedrock/Chart.yaml
  charts/stable/minecraft-bedrock/docs/How-To.md
  charts/stable/minecraft-bedrock/docs/imgs/console.png
  charts/stable/minecraft-bedrock/docs/imgs/xuids.png
  charts/stable/minecraft-bedrock/questions.yaml
  charts/stable/minecraft-bedrock/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#4169 chore(deps): update renovatebot/github-action action to v33
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4137 feat(meshcentral): BREAKING CHANGE - Rework to add support for (almost) all configuration options
  charts/incubator/meshcentral/Chart.yaml
  charts/incubator/meshcentral/docs/installation-instructions.md
  charts/incubator/meshcentral/questions.yaml
  charts/incubator/meshcentral/templates/_secret.tpl
  charts/incubator/meshcentral/templates/common.yaml
  charts/incubator/meshcentral/values.yaml
  cspell.config.yaml
Labels: size/XL, install:ok, lint:ok, precommit:ok

#4179 chore(deps): update yokawasa/action-setup-kube-tools action to v0.8.3
  .github/workflows/charts-changelog.yaml
  .github/workflows/charts-lint.yaml
  .github/workflows/charts-release.yaml
  .github/workflows/charts-test.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#4180 chore(deps): update renovatebot/github-action action to v33.2.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4183 fix(ddns-updater) add How-To
  charts/stable/ddns-updater/Chart.yaml
  charts/stable/ddns-updater/docs/How-To.md
Labels: install:ok, lint:ok, size/M, precommit:ok

#4172 docs(Authentik): Added How-To Guide with built-in Proxy Provider
  charts/stable/authentik/Chart.yaml
  charts/stable/authentik/docs/how_to.md
  charts/stable/authentik/docs/img/Applications-Screen.png
  charts/stable/authentik/docs/img/Create-Applications-2.png
  charts/stable/authentik/docs/img/Create-Applications-3.png
  charts/stable/authentik/docs/img/Create-Applications.png
  charts/stable/authentik/docs/img/Ingress-Auth.png
  charts/stable/authentik/docs/img/New-Provider-1.png
  charts/stable/authentik/docs/img/New-Provider-2.png
  charts/stable/authentik/docs/img/Outposts.png
  charts/stable/authentik/docs/img/Providers.png
  charts/stable/authentik/docs/img/Traefik-Middleware.png
  charts/stable/authentik/docs/img/Traefik-forwardAuth.png
  charts/stable/authentik/docs/img/Update-Outpost.png
  charts/stable/authentik/docs/img/Verify-2.png
  charts/stable/authentik/docs/img/Verify-Outpost.png
  charts/stable/authentik/docs/img/Verify.png
Labels: install:ok, lint:ok, size/M, precommit:ok

#4184 fix(meshcentral): use transitioning variable tcdefaultdomain in scale GUI
  charts/incubator/meshcentral/Chart.yaml
  charts/incubator/meshcentral/questions.yaml
  charts/incubator/meshcentral/templates/_secret.tpl
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4090 fix(ring-mqtt) disable probes for now
  charts/stable/ring-mqtt/Chart.yaml
  charts/stable/ring-mqtt/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4069 feat(raspberrymatic) add raspberrymatic
  charts/incubator/raspberrymatic/.helmignore
  charts/incubator/raspberrymatic/Chart.yaml
  charts/incubator/raspberrymatic/README.md
  charts/incubator/raspberrymatic/icon.png
  charts/incubator/raspberrymatic/templates/common.yaml
  charts/incubator/raspberrymatic/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#4185 fix(meshcentral): fix typo
  charts/incubator/meshcentral/Chart.yaml
  charts/incubator/meshcentral/templates/_secret.tpl
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4188 feat(webNUT): add webNUT
  charts/incubator/webnut/.helmignore
  charts/incubator/webnut/Chart.yaml
  charts/incubator/webnut/README.md
  charts/incubator/webnut/docs/img/nut-scanner.png
  charts/incubator/webnut/docs/img/ups-other.png
  charts/incubator/webnut/docs/img/ups-server.png
  charts/incubator/webnut/docs/img/ups-shutdown.png
  charts/incubator/webnut/docs/installation_notes.md
  charts/incubator/webnut/icon.png
  charts/incubator/webnut/questions.yaml
  charts/incubator/webnut/templates/common.yaml
  charts/incubator/webnut/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#4187 chore(deps): update renovatebot/github-action action to v33.2.4
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4194 chore(deps): update container image tccr.io/truecharts/qdirstat to v22.10.1
  charts/stable/qdirstat/Chart.yaml
  charts/stable/qdirstat/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4191 chore(deps): update container image tccr.io/truecharts/firefox to v101.0.1
  charts/stable/firefox/Chart.yaml
  charts/stable/firefox/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4190 chore(deps): update yokawasa/action-setup-kube-tools action to v0.9.0
  .github/workflows/charts-changelog.yaml
  .github/workflows/charts-lint.yaml
  .github/workflows/charts-release.yaml
  .github/workflows/charts-test.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#4196 fix(meshcentral): http port and probe
  charts/incubator/meshcentral/docs/installation-instructions.md
  charts/incubator/meshcentral/questions.yaml
  charts/incubator/meshcentral/templates/_secret.tpl
  charts/incubator/meshcentral/templates/common.yaml
  charts/incubator/meshcentral/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#4197 fix(meshcentral): default to HTTP for service
  charts/incubator/meshcentral/Chart.yaml
  charts/incubator/meshcentral/ci/ci-values.yaml
  charts/incubator/meshcentral/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4195 chore(deps): update renovatebot/github-action action to v34
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4198 chore(deps): update github/codeql-action digest to ec3cf9c
  .github/workflows/general.security-scan.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4199 fix(webNUT) move to stable
  charts/stable/webnut/.helmignore
  charts/stable/webnut/CHANGELOG.md
  charts/stable/webnut/Chart.yaml
  charts/stable/webnut/README.md
  charts/stable/webnut/docs/img/nut-scanner.png
  charts/stable/webnut/docs/img/ups-other.png
  charts/stable/webnut/docs/img/ups-server.png
  charts/stable/webnut/docs/img/ups-shutdown.png
  charts/stable/webnut/docs/installation_notes.md
  charts/stable/webnut/icon.png
  charts/stable/webnut/questions.yaml
  charts/stable/webnut/templates/common.yaml
  charts/stable/webnut/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4200 fix(actualserver) moved to stable
  charts/stable/actualserver/.helmignore
  charts/stable/actualserver/CHANGELOG.md
  charts/stable/actualserver/Chart.yaml
  charts/stable/actualserver/README.md
  charts/stable/actualserver/icon.png
  charts/stable/actualserver/questions.yaml
  charts/stable/actualserver/templates/common.yaml
  charts/stable/actualserver/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4204 chore(deps): update helm chart common to v10.7.8
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4203 chore(deps): update helm chart common to v10.7.8
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/promtail/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
Labels: size/S, lint:ok, precommit:ok

#4205 fix(meshcentral): remove --cert from run command
  charts/incubator/meshcentral/Chart.yaml
  charts/incubator/meshcentral/questions.yaml
  charts/incubator/meshcentral/templates/_secret.tpl
  charts/incubator/meshcentral/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#4207 fix(meshcentral): fix secret
  charts/incubator/meshcentral/Chart.yaml
  charts/incubator/meshcentral/templates/_secret.tpl
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4206 chore(deps): update renovatebot/github-action action to v34.2.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4211 fix(meshcentral): correctly merge custom domain for scale gui
  charts/incubator/meshcentral/Chart.yaml
  charts/incubator/meshcentral/questions.yaml
  charts/incubator/meshcentral/templates/_secret.tpl
  charts/incubator/meshcentral/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#4215 fix(meshcentral): remove maintenancemode config because if set to any value enables it
  charts/incubator/meshcentral/Chart.yaml
  charts/incubator/meshcentral/questions.yaml
  charts/incubator/meshcentral/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4208 fix(kasm): rework
  charts/incubator/kasm/Chart.yaml
  charts/incubator/kasm/questions.yaml
  charts/incubator/kasm/values.yaml
  charts/incubator/meshcentral/Chart.yaml
  charts/incubator/meshcentral/questions.yaml
  charts/incubator/meshcentral/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok
