Repository trueforge-org/truecharts, pull requests merged in 2022-11, with the labels that each got.

#4255 chore(deps): update renovatebot/github-action action to v34.10.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4263 feat(Youtube-dl): Move to Stable
  charts/stable/youtubedl-material/.helmignore
  charts/stable/youtubedl-material/CHANGELOG.md
  charts/stable/youtubedl-material/Chart.yaml
  charts/stable/youtubedl-material/README.md
  charts/stable/youtubedl-material/icon.png
  charts/stable/youtubedl-material/questions.yaml
  charts/stable/youtubedl-material/templates/common.yaml
  charts/stable/youtubedl-material/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#4262 feat(Zusam): Move to Stable
  charts/stable/zusam/.helmignore
  charts/stable/zusam/CHANGELOG.md
  charts/stable/zusam/Chart.yaml
  charts/stable/zusam/README.md
  charts/stable/zusam/icon.png
  charts/stable/zusam/questions.yaml
  charts/stable/zusam/templates/common.yaml
  charts/stable/zusam/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#4266 fix(retrobot) move to stable
  charts/stable/retrobot/.helmignore
  charts/stable/retrobot/CHANGELOG.md
  charts/stable/retrobot/Chart.yaml
  charts/stable/retrobot/README.md
  charts/stable/retrobot/icon.png
  charts/stable/retrobot/questions.yaml
  charts/stable/retrobot/templates/common.yaml
  charts/stable/retrobot/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4269 chore(deps): update helm chart common to v10.7.13
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4265 fix(quiz-game) added persistence + nw service
  charts/incubator/quiz-game/Chart.yaml
  charts/incubator/quiz-game/questions.yaml
  charts/incubator/quiz-game/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#4271 fix(quiz-game) add target port + probes
  charts/incubator/quiz-game/Chart.yaml
  charts/incubator/quiz-game/questions.yaml
  charts/incubator/quiz-game/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#4268 chore(deps): update helm chart common to v10.7.13
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/promtail/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
Labels: size/S, lint:ok, precommit:ok

#4278 docs(Omada-Controller): Add Installation Notes
  charts/stable/omada-controller/Chart.yaml
  charts/stable/omada-controller/docs/img/Omada-Discovery-Utility.png
  charts/stable/omada-controller/docs/img/Omada-HTTPS-8043.png
  charts/stable/omada-controller/docs/installation_notes.md
Labels: size/S, install:ok, lint:ok, precommit:ok

#4273 fix(searx + searxng) code refactoring
  charts/incubator/searx/Chart.yaml
  charts/incubator/searx/questions.yaml
  charts/incubator/searx/values.yaml
  charts/incubator/searxng/Chart.yaml
  charts/incubator/searxng/questions.yaml
  charts/incubator/searxng/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#4274 chore(deps): update renovatebot/github-action action to v34.12.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4272 fix(ra-rom-processor) refactor code
  charts/incubator/ra-rom-processor/Chart.yaml
  charts/incubator/ra-rom-processor/questions.yaml
  charts/incubator/ra-rom-processor/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#4281 chore(deps): update renovatebot/github-action action to v34.12.1
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4280 chore(deps): update docker general non-major
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/clickhouse/values.yaml
  charts/incubator/convos/Chart.yaml
  charts/incubator/convos/values.yaml
  charts/incubator/ghost/Chart.yaml
  charts/incubator/ghost/values.yaml
  charts/incubator/passwordpusherephemeral/Chart.yaml
  charts/incubator/passwordpusherephemeral/values.yaml
  charts/incubator/pyload-ng/Chart.yaml
  charts/incubator/pyload-ng/values.yaml
  charts/incubator/raneto/Chart.yaml
  charts/incubator/raneto/values.yaml
  charts/incubator/rimgo/Chart.yaml
  charts/incubator/rimgo/values.yaml
  charts/incubator/tasmocompiler/Chart.yaml
  charts/incubator/tasmocompiler/values.yaml
  charts/incubator/ts-dnsserver/Chart.yaml
  charts/incubator/ts-dnsserver/values.yaml
  charts/incubator/umami/Chart.yaml
  charts/incubator/umami/values.yaml
  charts/incubator/vertex/Chart.yaml
  charts/incubator/vertex/values.yaml
  charts/incubator/virt-manager/Chart.yaml
  charts/incubator/virt-manager/values.yaml
  charts/stable/alist/Chart.yaml
  charts/stable/alist/values.yaml
  charts/stable/budge/Chart.yaml
  charts/stable/budge/values.yaml
  charts/stable/calibre-web/Chart.yaml
  charts/stable/calibre-web/values.yaml
  charts/stable/custom-app/Chart.yaml
  charts/stable/custom-app/ci/test-values.yaml
  charts/stable/custom-app/values.yaml
  charts/stable/cyberchef/Chart.yaml
  charts/stable/cyberchef/values.yaml
  charts/stable/dokuwiki/Chart.yaml
  charts/stable/dokuwiki/values.yaml
  charts/stable/grafana/Chart.yaml
  charts/stable/grafana/values.yaml
  charts/stable/impostor-server/Chart.yaml
  charts/stable/impostor-server/ci/values.yaml
  charts/stable/impostor-server/values.yaml
  charts/stable/ispy-agent-dvr/Chart.yaml
  charts/stable/ispy-agent-dvr/values.yaml
  charts/stable/jackett/Chart.yaml
  charts/stable/jackett/values.yaml
  charts/stable/jellyfin/Chart.yaml
  charts/stable/jellyfin/values.yaml
  charts/stable/libreddit/Chart.yaml
  charts/stable/libreddit/values.yaml
  charts/stable/meshcentral/Chart.yaml
  charts/stable/meshcentral/values.yaml
  charts/stable/prometheus/Chart.yaml
  charts/stable/prometheus/values.yaml
  charts/stable/rsshub/Chart.yaml
  charts/stable/rsshub/values.yaml
  charts/stable/synclounge/Chart.yaml
  charts/stable/synclounge/values.yaml
Labels: size/M, precommit:ok

#4284 chore(deps): update github/codeql-action digest to 18fe527
  .github/workflows/general.security-scan.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4282 fix(invitarr) code clean up + docs
  charts/incubator/invitarr/Chart.yaml
  charts/incubator/invitarr/docs/installation_notes.md
  charts/incubator/invitarr/questions.yaml
  charts/incubator/invitarr/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#4247 feat(traefik): add support for insecureForwardAuth
  charts/stable/traefik/Chart.yaml
  charts/stable/traefik/templates/middlewares/forwardauth.yaml
  templates/questions/traefik/forwardAuthMiddleware.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#4285 docs(Omada-Controller): Add DHCP Option 138 for APs
  charts/stable/omada-controller/Chart.yaml
  charts/stable/omada-controller/docs/img/dhcp-option-138.png
  charts/stable/omada-controller/docs/installation_notes.md
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4287 chore(deps): update renovatebot/github-action action to v34.13.2
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4290 chore(deps): update yokawasa/action-setup-kube-tools action to v0.9.2
  .github/workflows/charts-changelog.yaml
  .github/workflows/charts-lint.yaml
  .github/workflows/charts-release.yaml
  .github/workflows/charts-test.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#4289 chore(deps): update docker general non-major
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/collabora-online/values.yaml
  charts/incubator/filestash/Chart.yaml
  charts/incubator/filestash/values.yaml
  charts/incubator/obs-ndi/Chart.yaml
  charts/incubator/obs-ndi/values.yaml
  charts/incubator/passwordpusherephemeral/Chart.yaml
  charts/incubator/passwordpusherephemeral/values.yaml
  charts/incubator/redisinsight/Chart.yaml
  charts/incubator/redisinsight/values.yaml
  charts/incubator/rimgo/Chart.yaml
  charts/incubator/rimgo/values.yaml
  charts/stable/prometheus/Chart.yaml
  charts/stable/prometheus/values.yaml
  charts/stable/sickchill/Chart.yaml
  charts/stable/sickchill/values.yaml
  charts/stable/webnut/Chart.yaml
  charts/stable/webnut/values.yaml
Labels: size/S, lint:ok, precommit:ok

#4283 fix(cloudflared) remove port + persistence
  charts/stable/cloudflared/Chart.yaml
  charts/stable/cloudflared/questions.yaml
  charts/stable/cloudflared/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#4291 chore(deps): update helm chart common to v10.7.14
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/promtail/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
Labels: size/S, lint:ok, precommit:ok

#4295 chore(deps): update renovatebot/github-action action to v34.17.1
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4292 chore(deps): update helm chart common to v10.7.14
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4293 chore(deps): update docker general non-major
  charts/dependency/memcached/Chart.yaml
  charts/dependency/memcached/values.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/mongodb/values.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/redis/values.yaml
  charts/dependency/solr/Chart.yaml
  charts/dependency/solr/values.yaml
  charts/incubator/adguardhome-sync/Chart.yaml
  charts/incubator/adguardhome-sync/values.yaml
  charts/incubator/speedtest-tracker/Chart.yaml
  charts/incubator/speedtest-tracker/values.yaml
  charts/incubator/twonky-server/Chart.yaml
  charts/incubator/twonky-server/values.yaml
  charts/stable/adminer/Chart.yaml
  charts/stable/adminer/values.yaml
  charts/stable/beets/Chart.yaml
  charts/stable/beets/values.yaml
  charts/stable/digikam/Chart.yaml
  charts/stable/digikam/values.yaml
  charts/stable/filezilla/Chart.yaml
  charts/stable/filezilla/values.yaml
  charts/stable/freshrss/Chart.yaml
  charts/stable/freshrss/values.yaml
  charts/stable/grocy/Chart.yaml
  charts/stable/grocy/values.yaml
  charts/stable/littlelink/Chart.yaml
  charts/stable/littlelink/values.yaml
  charts/stable/rsshub/Chart.yaml
  charts/stable/rsshub/values.yaml
  charts/stable/tailscale/Chart.yaml
  charts/stable/tailscale/values.yaml
Labels: lint:ok, size/M, precommit:ok

#4298 chore(deps): update helm chart common to v10.7.15
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/promtail/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
Labels: size/S, lint:ok, precommit:ok

#4300 chore(deps): update github/codeql-action digest to c3b6fce
  .github/workflows/general.security-scan.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4302 chore(deps): update renovatebot/github-action action to v34.18.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4142 chore(deps): update container image tccr.io/truecharts/nextcloud-fpm to v25.0.1
  charts/stable/nextcloud/Chart.yaml
  charts/stable/nextcloud/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4304 chore(deps): update stefanzweifel/git-auto-commit-action digest to 0b007fb
  .github/workflows/charts-changelog.yaml
  .github/workflows/charts-release.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4306 chore(deps): update renovatebot/github-action action to v34.19.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4299 chore(deps): update helm chart common to v10.7.19
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4307 fix(tailscale): switch to the new golang binary
  charts/stable/tailscale/Chart.yaml
  charts/stable/tailscale/questions.yaml
  charts/stable/tailscale/templates/_configmap.tpl
  charts/stable/tailscale/templates/_secret.tpl
  charts/stable/tailscale/values.yaml
  cspell.config.yaml
  templates/questions/addons/vpn.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#4309 exclude auto commit action for updates
  .github/renovate.json5
Labels: size/XS

#4310 chore(deps): update helm chart common to v10.8.0
  templates/chart/Chart.yaml
Labels: size/XS

#4305 chore(deps): update helm chart common to v10.8.0
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/promtail/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#4312 chore(deps): update docker general non-major
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/mariadb/values.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/memcached/values.yaml
  charts/incubator/apprise-api/Chart.yaml
  charts/incubator/apprise-api/values.yaml
  charts/incubator/cryptpad/Chart.yaml
  charts/incubator/cryptpad/values.yaml
  charts/incubator/etesync/Chart.yaml
  charts/incubator/etesync/values.yaml
  charts/incubator/hexchat/Chart.yaml
  charts/incubator/hexchat/values.yaml
  charts/incubator/kdenlive/Chart.yaml
  charts/incubator/kdenlive/values.yaml
  charts/incubator/rdesktop/Chart.yaml
  charts/incubator/rdesktop/values.yaml
  charts/incubator/rimgo/Chart.yaml
  charts/incubator/rimgo/values.yaml
  charts/incubator/searxng/Chart.yaml
  charts/incubator/searxng/values.yaml
  charts/incubator/virt-manager/Chart.yaml
  charts/incubator/virt-manager/values.yaml
  charts/incubator/wordle/Chart.yaml
  charts/incubator/wordle/values.yaml
  charts/incubator/zabbix/Chart.yaml
  charts/incubator/zabbix/values.yaml
  charts/stable/boinc/Chart.yaml
  charts/stable/boinc/values.yaml
  charts/stable/cyberchef/Chart.yaml
  charts/stable/cyberchef/values.yaml
  charts/stable/libreddit/Chart.yaml
  charts/stable/libreddit/values.yaml
  charts/stable/logitech-media-server/Chart.yaml
  charts/stable/logitech-media-server/values.yaml
  charts/stable/matomo/Chart.yaml
  charts/stable/matomo/values.yaml
  charts/stable/ombi/Chart.yaml
  charts/stable/ombi/values.yaml
  charts/stable/prometheus/Chart.yaml
  charts/stable/prometheus/values.yaml
  charts/stable/rsshub/Chart.yaml
  charts/stable/rsshub/values.yaml
  charts/stable/wger/Chart.yaml
  charts/stable/wger/values.yaml
Labels: size/M, precommit:ok

#4313 fix(joplin-server) add docs
  charts/stable/joplin-server/Chart.yaml
  charts/stable/joplin-server/docs/installation_notes.md
  charts/stable/joplin-server/questions.yaml
Labels: lint:ok, size/M, precommit:ok

#4319 feat(subchart): add subchart dependency
  .github/ct-install.yaml
  charts/dependency/subchart/.helmignore
  charts/dependency/subchart/Chart.yaml
  charts/dependency/subchart/README.md
  charts/dependency/subchart/icon.png
  charts/dependency/subchart/templates/common.yaml
  charts/dependency/subchart/values.yaml
Labels: size/M

#4320 feat(metallb): rework metallb to use manifest-included metallb
  charts/enterprise/metallb/Chart.yaml
  charts/enterprise/metallb/ci/basic-values.yaml
  charts/enterprise/metallb/ci/pool-values.yaml
  charts/enterprise/metallb/templates/_bgpadvertisement.tpl
  charts/enterprise/metallb/templates/_community.tpl
  charts/enterprise/metallb/templates/_ipaddresspool.tpl
  charts/enterprise/metallb/templates/_l2advertisement.tpl
  charts/enterprise/metallb/templates/_peers.tpl
  charts/enterprise/metallb/templates/common.yaml
  charts/enterprise/metallb/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#4321 fix(metallb): Ensure metallb is running before creating resources
  charts/enterprise/metallb/Chart.yaml
  charts/enterprise/metallb/templates/_wait.tpl
  charts/enterprise/metallb/templates/common.yaml
Labels: size/M

#4322 don't try to look for updates on "subchart" image
  .github/renovate.json5
Labels: size/XS

#4133 chore(deps): update ghcr.io/truecharts/devcontainer:v2.6.0 docker digest to 479b7ce
  .github/workflows/catalog-test.yaml
  .github/workflows/charts-release.yaml
Labels: size/XS, lint:ok, precommit:ok

#4323 Revert "chore(deps): update ghcr.io/truecharts/devcontainer:v2.6.0 docker digest to 479b7ce"
  .github/workflows/catalog-test.yaml
  .github/workflows/charts-release.yaml
Labels: size/XS

#4324 fix(cloudflared): remove persistence on GUI aswell
  charts/stable/cloudflared/Chart.yaml
  charts/stable/cloudflared/questions.yaml
Labels: size/XS, lint:ok, precommit:ok

#4327 chore(deps): update helm chart common to v10.8.1
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4328 chore(deps): update renovatebot/github-action action to v34.19.3
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4326 chore(deps): update helm chart common to v10.8.1
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/promtail/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
  charts/dependency/subchart/Chart.yaml
Labels: size/S, update/helm/dependency/non-major

#4330 feat(strapi) change version to v4
  charts/stable/strapi/Chart.yaml
  charts/stable/strapi/questions.yaml
  charts/stable/strapi/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#4333 chore(deps): update renovatebot/github-action action to v34.20.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4338 chore(deps): update helm chart common to v10.9.0
  templates/chart/Chart.yaml
Labels: size/XS

#4337 chore(deps): update helm chart common to v10.9.0
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/promtail/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
  charts/dependency/subchart/Chart.yaml
Labels: size/S, update/helm/dependency/non-major

#4340 chore(deps): update helm chart common to v10.9.1
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4339 chore(deps): update helm chart common to v10.9.1
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/promtail/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
  charts/dependency/subchart/Chart.yaml
Labels: size/S, lint:ok, precommit:ok

#4343 chore(deps): update docker general non-major
  charts/incubator/cloudbeaver/Chart.yaml
  charts/incubator/cloudbeaver/values.yaml
  charts/incubator/convos/Chart.yaml
  charts/incubator/convos/values.yaml
  charts/incubator/neko/Chart.yaml
  charts/incubator/neko/values.yaml
  charts/incubator/plextraktsync/Chart.yaml
  charts/incubator/plextraktsync/values.yaml
  charts/incubator/shortipy/Chart.yaml
  charts/incubator/shortipy/values.yaml
  charts/incubator/virt-manager/Chart.yaml
  charts/incubator/virt-manager/values.yaml
  charts/stable/calibre/Chart.yaml
  charts/stable/calibre/values.yaml
  charts/stable/custom-app/Chart.yaml
  charts/stable/custom-app/ci/test-values.yaml
  charts/stable/custom-app/values.yaml
  charts/stable/cyberchef/Chart.yaml
  charts/stable/cyberchef/values.yaml
  charts/stable/darktable/Chart.yaml
  charts/stable/darktable/values.yaml
  charts/stable/dokuwiki/Chart.yaml
  charts/stable/dokuwiki/values.yaml
  charts/stable/grafana/Chart.yaml
  charts/stable/grafana/values.yaml
  charts/stable/jackett/Chart.yaml
  charts/stable/jackett/values.yaml
  charts/stable/ombi/Chart.yaml
  charts/stable/ombi/values.yaml
  charts/stable/prometheus/Chart.yaml
  charts/stable/prometheus/values.yaml
  charts/stable/rsshub/Chart.yaml
  charts/stable/rsshub/values.yaml
  charts/stable/sabnzbd/Chart.yaml
  charts/stable/sabnzbd/values.yaml
  charts/stable/storj-node/Chart.yaml
  charts/stable/storj-node/values.yaml
  charts/stable/strapi/Chart.yaml
  charts/stable/strapi/values.yaml
  charts/stable/tailscale/Chart.yaml
  charts/stable/tailscale/values.yaml
  charts/stable/tsmuxer/Chart.yaml
  charts/stable/tsmuxer/values.yaml
Labels: size/M, precommit:ok, update/docker/general/non-major

#4347 chore(deps): update docker general non-major
  charts/incubator/adguardhome-sync/Chart.yaml
  charts/incubator/adguardhome-sync/values.yaml
  charts/incubator/virt-manager/Chart.yaml
  charts/incubator/virt-manager/values.yaml
  charts/incubator/webp-server/Chart.yaml
  charts/incubator/webp-server/values.yaml
  charts/stable/anonaddy/Chart.yaml
  charts/stable/anonaddy/values.yaml
  charts/stable/code-server/Chart.yaml
  charts/stable/code-server/values.yaml
  charts/stable/drawio/Chart.yaml
  charts/stable/drawio/values.yaml
  charts/stable/littlelink/Chart.yaml
  charts/stable/littlelink/values.yaml
  charts/stable/mylar/Chart.yaml
  charts/stable/mylar/values.yaml
  charts/stable/rsshub/Chart.yaml
  charts/stable/rsshub/values.yaml
  charts/stable/tautulli/Chart.yaml
  charts/stable/tautulli/values.yaml
  charts/stable/wireshark/Chart.yaml
  charts/stable/wireshark/values.yaml
Labels: size/S, lint:ok, precommit:ok

#4348 chore(deps): update helm chart common to v10.9.3
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/promtail/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
  charts/dependency/subchart/Chart.yaml
Labels: size/S

#4350 chore(deps): update helm chart common to v10.9.3
  templates/chart/Chart.yaml
Labels: size/XS

#4334 feat(uptimekuma): create servicemonitor for uptimekuma
  charts/stable/uptime-kuma/Chart.yaml
  charts/stable/uptime-kuma/questions.yaml
  charts/stable/uptime-kuma/templates/servicemonitor.yaml
  charts/stable/uptime-kuma/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#4351 chore(deps): update renovatebot/github-action action to v34.20.4
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4352 chore(deps): update helm chart common to v10.9.4
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/promtail/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
  charts/dependency/subchart/Chart.yaml
Labels: size/S, lint:ok, precommit:ok

#4353 chore(deps): update helm chart common to v10.9.4
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4356 chore(deps): update dawidd6/action-download-artifact action to v2.24.1
  .github/workflows/meta-label-pr-ci-status.yaml
Labels: size/XS

#4357 chore(deps): update renovatebot/github-action action to v34.21.2
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4315 feat(Misskey): Add Misskey
  charts/incubator/misskey/.helmignore
  charts/incubator/misskey/CHANGELOG.md
  charts/incubator/misskey/Chart.yaml
  charts/incubator/misskey/README.md
  charts/incubator/misskey/icon.png
  charts/incubator/misskey/questions.yaml
  charts/incubator/misskey/templates/_configmap.tpl
  charts/incubator/misskey/templates/common.yaml
  charts/incubator/misskey/values.yaml
  cspell.config.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#4362 fix(recyclarr) add installation notes
  charts/stable/recyclarr/Chart.yaml
  charts/stable/recyclarr/docs/installation_notes.md
  charts/stable/recyclarr/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4360 chore(deps): update helm chart common to v10.9.5
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/promtail/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
  charts/dependency/subchart/Chart.yaml
Labels: size/S, lint:ok, precommit:ok

#4363 chore(deps): update dawidd6/action-download-artifact action to v2.24.2
  .github/workflows/meta-label-pr-ci-status.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4364 chore(deps): update renovatebot/github-action action to v34.21.4
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4361 chore(deps): update helm chart common to v10.9.5
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4345 feat(magicmirror-2) add magicmirror-2
  charts/incubator/magicmirror2/.helmignore
  charts/incubator/magicmirror2/Chart.yaml
  charts/incubator/magicmirror2/README.md
  charts/incubator/magicmirror2/icon.png
  charts/incubator/magicmirror2/questions.yaml
  charts/incubator/magicmirror2/templates/_config.tpl
  charts/incubator/magicmirror2/templates/common.yaml
  charts/incubator/magicmirror2/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#4365 WIP Cleanup configuration options
  .github/ct-install.yaml
  .github/ct-lint.yaml
  .github/scripts/build-catalog.sh
  .github/scripts/gen-docs.sh
  .github/workflows/charts-release.yaml
  .github/workflows/daily.yaml
  .github/workflows/renovate-bump.yaml
  .gitignore
  charts/stable/jackett/Chart.yaml
  templates/README.md.tpl
  templates/docs/README.md
  templates/questions/addons/netshoot.yaml
  templates/questions/addons/promtail.yaml
  templates/questions/controller/controller.yaml
  templates/questions/controller/controllerDaemonset.yaml
  templates/questions/controller/controllerDeployment.yaml
  templates/questions/controller/controllerExpert.yaml
  templates/questions/controller/controllerExpertCommand.yaml
  templates/questions/controller/controllerExpertExtraArgs.yaml
  templates/questions/controller/controllerStatefullset.yaml
  templates/questions/general/containerConfig.yaml
  templates/questions/general/controllerTypes.yaml
  templates/questions/general/global.yaml
  templates/questions/general/groups.yaml
  templates/questions/general/resources.yaml
  templates/questions/ingress/ingressExpert.yaml
  templates/questions/ingress/ingressList.yaml
  templates/questions/ingress/ingressTraefik.yaml
  templates/questions/persistence/persistenceAdvanced.yaml
  templates/questions/persistence/persistenceBasic.yaml
  templates/questions/persistence/persistenceList.yaml
  templates/questions/replicas/replica1.yaml
  templates/questions/replicas/replica2.yaml
  templates/questions/replicas/replica3.yaml
  templates/questions/replicas/replicas.yaml
  templates/questions/security/securityContextAdvanced.yaml
  templates/questions/service/advancedPortHTTPS.yaml
  templates/questions/service/advancedPortTCP.yaml
  templates/questions/service/advancedPortUDP.yaml
  templates/questions/service/serviceExpert.yaml
  templates/questions/service/serviceSelectorExtras.yaml
  templates/questions/strategy/recreate.yaml
  templates/questions/strategy/rollingupdate.yaml
  templates/questions/strategy/strategy.yaml
  tools/build-release.sh
Labels: size/XL, install:ok, lint:ok, precommit:ok

#4370 feat(ci): move changelog directly to website
  .github/scripts/build-catalog.sh
  .github/scripts/changelog.sh
  .github/scripts/gen-docs.sh
  .github/workflows/charts-release.yaml
Labels: size/L

#4367 fix(misskey): configmap mounting improperly on TrueNAS
  charts/incubator/misskey/Chart.yaml
  charts/incubator/misskey/questions.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4368 fix(netbox): fix subquestions
  charts/incubator/netbox/Chart.yaml
  charts/incubator/netbox/questions.yaml
Labels: size/M

#4371 fix some questions
  charts/enterprise/metallb/Chart.yaml
  charts/enterprise/metallb/questions.yaml
  charts/incubator/mineos/Chart.yaml
  charts/incubator/mineos/questions.yaml
  charts/stable/external-service/Chart.yaml
  charts/stable/external-service/questions.yaml
  charts/stable/promcord/Chart.yaml
  charts/stable/promcord/questions.yaml
  charts/stable/speedtest-exporter/Chart.yaml
  charts/stable/speedtest-exporter/questions.yaml
  charts/stable/unpoller/Chart.yaml
  charts/stable/unpoller/questions.yaml
  charts/stable/uptimerobot-prometheus/Chart.yaml
  charts/stable/uptimerobot-prometheus/questions.yaml
Labels: size/S, size/M

#4369 chore(deps): update renovatebot/github-action action to v34.22.1
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4375 fix(traefik): fix questions. Remove protocol selector globally
  charts/stable/traefik/Chart.yaml
  charts/stable/traefik/questions.yaml
  templates/questions/persistence/persistenceAdvanced.yaml
  templates/questions/persistence/persistenceBasic.yaml
  templates/questions/service/advancedPortHTTP.yaml
  templates/questions/service/advancedPortHTTPS.yaml
  templates/questions/service/advancedPortTCP.yaml
  templates/questions/service/advancedPortUDP.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#4378 feat(prometheus): remove operator due to move to included manifest
  charts/stable/prometheus/Chart.yaml
  charts/stable/prometheus/templates/_helpers.tpl
  charts/stable/prometheus/templates/common.yaml
  charts/stable/prometheus/templates/operator/_args.tpl
  charts/stable/prometheus/templates/operator/configmap.yaml
  charts/stable/prometheus/templates/operator/servicemonitor.yaml
  charts/stable/prometheus/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#4381 feat(traefik): move traefik CRDs to manifest manager
  charts/stable/traefik/Chart.yaml
  charts/stable/traefik/crds/ingressroute.yaml
  charts/stable/traefik/crds/ingressroutetcp.yaml
  charts/stable/traefik/crds/ingressrouteudp.yaml
  charts/stable/traefik/crds/middlewares.yaml
  charts/stable/traefik/crds/middlewarestcp.yaml
  charts/stable/traefik/crds/serverstransports.yaml
  charts/stable/traefik/crds/tlsoptions.yaml
  charts/stable/traefik/crds/tlsstores.yaml
  charts/stable/traefik/crds/traefikservices.yaml
  charts/stable/traefik/values.yaml
Labels: size/XL

#4379 chore(deps): update renovatebot/github-action action to v34.22.2
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4372 chore(deps): update docker general non-major
  charts/dependency/promtail/values.yaml
  charts/incubator/adguardhome-sync/values.yaml
  charts/incubator/blender/values.yaml
  charts/incubator/chromium/values.yaml
  charts/incubator/cryptpad/values.yaml
  charts/incubator/cura-novnc/values.yaml
  charts/incubator/docspell/values.yaml
  charts/incubator/duplicacy/values.yaml
  charts/incubator/factorio/values.yaml
  charts/incubator/firefox-desktop-g3/values.yaml
  charts/incubator/ghost/values.yaml
  charts/incubator/h5ai/values.yaml
  charts/incubator/passwordpusherephemeral/values.yaml
  charts/incubator/plex-meta-manager/values.yaml
  charts/incubator/plextraktsync/values.yaml
  charts/incubator/qflood/values.yaml
  charts/incubator/rflood/values.yaml
  charts/incubator/rimgo/values.yaml
  charts/incubator/speedtest-tracker/values.yaml
  charts/incubator/twonky-server/values.yaml
  charts/incubator/vertex/values.yaml
  charts/incubator/virt-manager/values.yaml
  charts/stable/adminer/values.yaml
  charts/stable/autoscan/values.yaml
  charts/stable/beets/values.yaml
  charts/stable/cloudflareddns/values.yaml
  charts/stable/custom-app/ci/test-values.yaml
  charts/stable/custom-app/values.yaml
  charts/stable/cyberchef/values.yaml
  charts/stable/deconz/values.yaml
  charts/stable/digikam/values.yaml
  charts/stable/docker-compose/values.yaml
  charts/stable/dokuwiki/values.yaml
  charts/stable/domoticz/values.yaml
  charts/stable/emby/values.yaml
  charts/stable/filebrowser/values.yaml
  charts/stable/filezilla/values.yaml
  charts/stable/freshrss/values.yaml
  charts/stable/grocy/values.yaml
  charts/stable/home-assistant/values.yaml
  charts/stable/jackett/values.yaml
  charts/stable/lazylibrarian/values.yaml
  charts/stable/libreddit/values.yaml
  charts/stable/logitech-media-server/values.yaml
  charts/stable/loki/values.yaml
  charts/stable/matomo/values.yaml
  charts/stable/minecraft-java/ci/j11-values.yaml
  charts/stable/minecraft-java/ci/j8-values.yaml
  charts/stable/minecraft-java/values.yaml
  charts/stable/mosquitto/values.yaml
  charts/stable/n8n/values.yaml
  charts/stable/nextcloud/values.yaml
  charts/stable/prusaslicer-novnc/values.yaml
  charts/stable/rsshub/values.yaml
  charts/stable/sickchill/values.yaml
  charts/stable/snapdrop/values.yaml
  charts/stable/synapse/values.yaml
  charts/stable/wger/values.yaml
Labels: size/L, precommit:ok

#4385 chore(deps): update renovatebot/github-action action to v34.23.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4386 feat(ci): add fetch helm deps script
  .github/scripts/fetch_helm_deps.sh
Labels: install:ok, lint:ok, size/M, precommit:ok

#4387 chore(ci): fix cp path
  .github/scripts/fetch_helm_deps.sh
  .github/workflows/charts-release.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#4383 chore(deps): update helm chart common to v10.9.6
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4388 fix(ci): fix a check
  .github/scripts/fetch_helm_deps.sh
Labels: size/XS

#4390 chore(deps): update helm chart common to v10.9.7
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4389 chore(deps): update helm chart common to v10.9.7
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/promtail/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
  charts/dependency/subchart/Chart.yaml
Labels: size/S, lint:ok, precommit:ok, update/helm/dependency/non-major

#4391 chore(deps): update renovatebot/github-action action to v34.23.1
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4393 feat(ci): Download each dep to each own repo dir, and use a cached index instead of fetch each time
  .github/scripts/fetch_helm_deps.sh
  .gitignore
Labels: size/S, install:ok, lint:ok, precommit:ok

#4394 chore(deps): update docker general non-major
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/mariadb/values.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/memcached/values.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/mongodb/values.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/redis/values.yaml
  charts/dependency/solr/Chart.yaml
  charts/dependency/solr/values.yaml
  charts/incubator/chromium-desktop-g3/values.yaml
  charts/incubator/cryptpad/values.yaml
  charts/incubator/duplicacy/values.yaml
  charts/incubator/kdenlive/values.yaml
  charts/incubator/microbin/Chart.yaml
  charts/incubator/microbin/values.yaml
  charts/incubator/plextraktsync/values.yaml
  charts/incubator/qflood/values.yaml
  charts/incubator/restreamer/Chart.yaml
  charts/incubator/restreamer/values.yaml
  charts/incubator/rflood/values.yaml
  charts/incubator/rimgo/values.yaml
  charts/incubator/virt-manager/values.yaml
  charts/incubator/xen-orchestra/Chart.yaml
  charts/incubator/xen-orchestra/values.yaml
  charts/stable/adminer/values.yaml
  charts/stable/alist/Chart.yaml
  charts/stable/alist/values.yaml
  charts/stable/autobrr/Chart.yaml
  charts/stable/autobrr/values.yaml
  charts/stable/autoscan/values.yaml
  charts/stable/boinc/values.yaml
  charts/stable/cloudflareddns/values.yaml
  charts/stable/custom-app/Chart.yaml
  charts/stable/custom-app/ci/test-values.yaml
  charts/stable/custom-app/values.yaml
  charts/stable/cyberchef/Chart.yaml
  charts/stable/cyberchef/values.yaml
  charts/stable/grafana/values.yaml
  charts/stable/hedgedoc/values.yaml
  charts/stable/homarr/Chart.yaml
  charts/stable/homarr/values.yaml
  charts/stable/jackett/Chart.yaml
  charts/stable/jackett/values.yaml
  charts/stable/leantime/Chart.yaml
  charts/stable/leantime/values.yaml
  charts/stable/minio/values.yaml
  charts/stable/mosquitto/values.yaml
  charts/stable/openvscode-server/Chart.yaml
  charts/stable/openvscode-server/values.yaml
  charts/stable/prometheus/Chart.yaml
  charts/stable/prometheus/values.yaml
  charts/stable/rsshub/values.yaml
  charts/stable/strapi/Chart.yaml
  charts/stable/strapi/values.yaml
  charts/stable/wger/values.yaml
  charts/stable/zwavejs2mqtt/Chart.yaml
  charts/stable/zwavejs2mqtt/values.yaml
Labels: size/M, update/docker/general/non-major

#4399 chore(deps): update tj-actions/branch-names action to v6.3
  .github/workflows/pr-metadata.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4401 chore(deps): update container image tccr.io/truecharts/putty to v22.11.1
  charts/stable/putty/Chart.yaml
  charts/stable/putty/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, update/docker/general/major

#4398 chore(deps): update docker general non-major
  charts/incubator/debian-apt-mirror/Chart.yaml
  charts/incubator/debian-apt-mirror/values.yaml
  charts/incubator/passwordpusherephemeral/Chart.yaml
  charts/incubator/passwordpusherephemeral/values.yaml
  charts/incubator/rdesktop/Chart.yaml
  charts/incubator/rdesktop/values.yaml
  charts/incubator/rimgo/Chart.yaml
  charts/incubator/rimgo/values.yaml
  charts/incubator/sftpgo/Chart.yaml
  charts/incubator/sftpgo/values.yaml
  charts/stable/adminer/Chart.yaml
  charts/stable/adminer/values.yaml
  charts/stable/bazarr/Chart.yaml
  charts/stable/bazarr/values.yaml
  charts/stable/calibre/Chart.yaml
  charts/stable/calibre/values.yaml
  charts/stable/hedgedoc/Chart.yaml
  charts/stable/hedgedoc/values.yaml
  charts/stable/lancache-monolithic/Chart.yaml
  charts/stable/lancache-monolithic/values.yaml
  charts/stable/logitech-media-server/Chart.yaml
  charts/stable/logitech-media-server/values.yaml
  charts/stable/photoprism/Chart.yaml
  charts/stable/photoprism/values.yaml
  charts/stable/prometheus/Chart.yaml
  charts/stable/prometheus/values.yaml
  charts/stable/rcon-webadmin/Chart.yaml
  charts/stable/rcon-webadmin/values.yaml
Labels: lint:ok, size/M, precommit:ok

#4396 feat(traefik): add geoblock middleware
  .github/scripts/updateTraefikMiddlewareVersions.sh
  charts/stable/traefik/Chart.yaml
  charts/stable/traefik/questions.yaml
  charts/stable/traefik/templates/_args.tpl
  charts/stable/traefik/templates/middlewares/geoblock.yaml
  charts/stable/traefik/values.yaml
  templates/questions/traefik/geoBlockMiddleware.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#4404 chore(deps): update helm general non-major
  charts/enterprise/blocky/Chart.yaml
  charts/incubator/appsmith/Chart.yaml
  charts/incubator/docspell/Chart.yaml
  charts/incubator/etesync/Chart.yaml
  charts/incubator/ghost/Chart.yaml
  charts/incubator/misskey/Chart.yaml
  charts/incubator/netbox/Chart.yaml
  charts/incubator/nginx-proxy-manager/Chart.yaml
  charts/stable/anonaddy/Chart.yaml
  charts/stable/authelia/Chart.yaml
  charts/stable/authentik/Chart.yaml
  charts/stable/baserow/Chart.yaml
  charts/stable/bookstack/Chart.yaml
  charts/stable/chevereto/Chart.yaml
  charts/stable/clarkson/Chart.yaml
  charts/stable/filerun/Chart.yaml
  charts/stable/fireflyiii/Chart.yaml
  charts/stable/fleet/Chart.yaml
  charts/stable/friendica/Chart.yaml
  charts/stable/gitea/Chart.yaml
  charts/stable/grist/Chart.yaml
  charts/stable/icinga2/Chart.yaml
  charts/stable/immich/Chart.yaml
  charts/stable/inventree/Chart.yaml
  charts/stable/kimai/Chart.yaml
  charts/stable/koel/Chart.yaml
  charts/stable/kutt/Chart.yaml
  charts/stable/leantime/Chart.yaml
  charts/stable/librephotos/Chart.yaml
  charts/stable/linkace/Chart.yaml
  charts/stable/lychee/Chart.yaml
  charts/stable/matomo/Chart.yaml
  charts/stable/meshcentral/Chart.yaml
  charts/stable/monica/Chart.yaml
  charts/stable/n8n/Chart.yaml
  charts/stable/nextcloud/Chart.yaml
  charts/stable/nocodb/Chart.yaml
  charts/stable/onlyoffice-document-server/Chart.yaml
  charts/stable/outline/Chart.yaml
  charts/stable/paperless-ng/Chart.yaml
  charts/stable/papermerge/Chart.yaml
  charts/stable/photoprism/Chart.yaml
  charts/stable/projectsend/Chart.yaml
  charts/stable/pydio-cells/Chart.yaml
  charts/stable/rsshub/Chart.yaml
  charts/stable/shlink/Chart.yaml
  charts/stable/snipe-it/Chart.yaml
  charts/stable/typecho/Chart.yaml
  charts/stable/vikunja/Chart.yaml
  charts/stable/weblate/Chart.yaml
  charts/stable/wekan/Chart.yaml
  charts/stable/wger/Chart.yaml
  charts/stable/xbackbone/Chart.yaml
  charts/stable/youtubedl-material/Chart.yaml
Labels: size/L, precommit:ok

#4405 chore(deps): update renovatebot/github-action action to v34.24.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4403 feat(Cura-novnc): Move to Stable
  charts/stable/cura-novnc/.helmignore
  charts/stable/cura-novnc/CHANGELOG.md
  charts/stable/cura-novnc/Chart.yaml
  charts/stable/cura-novnc/README.md
  charts/stable/cura-novnc/icon.png
  charts/stable/cura-novnc/questions.yaml
  charts/stable/cura-novnc/templates/common.yaml
  charts/stable/cura-novnc/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#4411 chore(audiobookshelf): set opencors middleware
  charts/stable/audiobookshelf/Chart.yaml
  charts/stable/audiobookshelf/questions.yaml
  charts/stable/audiobookshelf/templates/common.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#4415 feat(watchyourlan): Run as root
  charts/incubator/watchyourlan/Chart.yaml
  charts/incubator/watchyourlan/questions.yaml
  charts/incubator/watchyourlan/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4413 feat(Incubator): Cleanup some charts
  charts/incubator/altitude/CHANGELOG.md
  charts/incubator/altitude/Chart.yaml
  charts/incubator/altitude/README.md
  charts/incubator/altitude/icon.png
  charts/incubator/altitude/questions.yaml
  charts/incubator/altitude/templates/common.yaml
  charts/incubator/altitude/values.yaml
  charts/incubator/healthchecksdashboard/.helmignore
  charts/incubator/healthchecksdashboard/CHANGELOG.md
  charts/incubator/healthchecksdashboard/Chart.yaml
  charts/incubator/healthchecksdashboard/README.md
  charts/incubator/healthchecksdashboard/icon.png
  charts/incubator/healthchecksdashboard/questions.yaml
  charts/incubator/healthchecksdashboard/templates/common.yaml
  charts/incubator/healthchecksdashboard/values.yaml
  charts/incubator/wordle/.helmignore
  charts/incubator/wordle/CHANGELOG.md
  charts/incubator/wordle/Chart.yaml
  charts/incubator/wordle/README.md
  charts/incubator/wordle/icon.png
  charts/incubator/wordle/questions.yaml
  charts/incubator/wordle/templates/common.yaml
  charts/incubator/wordle/values.yaml
  charts/incubator/xen-orchestra/.helmignore
  charts/stable/xen-orchestra/.helmignore
  charts/stable/xen-orchestra/CHANGELOG.md
  charts/stable/xen-orchestra/Chart.yaml
  charts/stable/xen-orchestra/README.md
  charts/stable/xen-orchestra/docs/credentials.md
  charts/stable/xen-orchestra/icon.png
  charts/stable/xen-orchestra/questions.yaml
  charts/stable/xen-orchestra/templates/common.yaml
  charts/stable/xen-orchestra/values.yaml
Labels: lint:ok, size/XXL, precommit:ok

#4412 fix(plex): When ClusterIP, only advertise ingress host if any
  charts/stable/plex/Chart.yaml
  charts/stable/plex/questions.yaml
  charts/stable/plex/templates/common.yaml
  charts/stable/plex/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#4419 chore(deps): update github/codeql-action digest to 4238421
  .github/workflows/general.security-scan.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4420 chore(deps): update helm chart common to v11
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/promtail/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
  charts/dependency/subchart/Chart.yaml
Labels: size/S, lint:ok, precommit:ok

#4421 chore(deps): update helm chart common to v11
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4423 chore(deps): update docker general non-major
  charts/incubator/fireshare/Chart.yaml
  charts/incubator/fireshare/values.yaml
  charts/incubator/neko/Chart.yaml
  charts/incubator/neko/values.yaml
  charts/incubator/tasmocompiler/Chart.yaml
  charts/incubator/tasmocompiler/values.yaml
  charts/incubator/umami/Chart.yaml
  charts/incubator/umami/values.yaml
  charts/incubator/vertex/Chart.yaml
  charts/incubator/vertex/values.yaml
  charts/incubator/virt-manager/Chart.yaml
  charts/incubator/virt-manager/values.yaml
  charts/stable/cyberchef/Chart.yaml
  charts/stable/cyberchef/values.yaml
  charts/stable/emby/Chart.yaml
  charts/stable/emby/values.yaml
  charts/stable/kanboard/Chart.yaml
  charts/stable/kanboard/values.yaml
  charts/stable/logitech-media-server/Chart.yaml
  charts/stable/logitech-media-server/values.yaml
  charts/stable/lychee/Chart.yaml
  charts/stable/lychee/values.yaml
  charts/stable/matomo/Chart.yaml
  charts/stable/matomo/values.yaml
  charts/stable/miniflux/Chart.yaml
  charts/stable/miniflux/values.yaml
  charts/stable/prowlarr/Chart.yaml
  charts/stable/prowlarr/values.yaml
  charts/stable/rsshub/Chart.yaml
  charts/stable/rsshub/values.yaml
Labels: lint:ok, size/M, precommit:ok, automerge

#4427 chore(deps): update container image tccr.io/truecharts/website-shot to latest
  charts/stable/website-shot/Chart.yaml
  charts/stable/website-shot/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#4426 chore(deps): update container image tccr.io/truecharts/passwordpusherephemeral to latest
  charts/incubator/passwordpusherephemeral/Chart.yaml
  charts/incubator/passwordpusherephemeral/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#4429 chore(deps): update container image tccr.io/truecharts/qinglong to v2.15.0
  charts/stable/qinglong/Chart.yaml
  charts/stable/qinglong/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#4425 chore(deps): update container image tccr.io/truecharts/nginx-unprivileged to 1.23.2
  charts/stable/nextcloud/Chart.yaml
  charts/stable/nextcloud/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#4435 Update container image tccr.io/truecharts/wireshark to 3.6.5
  charts/stable/wireshark/Chart.yaml
  charts/stable/wireshark/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#4434 Update container image tccr.io/truecharts/cryptpad to latest
  charts/incubator/cryptpad/Chart.yaml
  charts/incubator/cryptpad/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#4433 Update container image tccr.io/truecharts/alertmanager to v0.24.0
  charts/stable/prometheus/Chart.yaml
  charts/stable/prometheus/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#4422 Pin actions/checkout action to 93ea575
  .github/workflows/pr-validate.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4431 fix(Omada): Re-add conditional nodeport for Ingress
  charts/stable/omada-controller/Chart.yaml
  charts/stable/omada-controller/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4440 fix(omada): set also targetPort to the same port so everything works …
  charts/stable/omada-controller/Chart.yaml
  charts/stable/omada-controller/templates/common.yaml
  charts/stable/omada-controller/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#4442 chore(deps): update container image tccr.io/truecharts/grafana to 9.2.4
  charts/stable/grafana/Chart.yaml
  charts/stable/grafana/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#4441 chore(deps): update container image tccr.io/truecharts/ciao to latest
  charts/incubator/ciao/Chart.yaml
  charts/incubator/ciao/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#4445 chore(deps): update container image tccr.io/truecharts/virt-manager to latest
  charts/incubator/virt-manager/Chart.yaml
  charts/incubator/virt-manager/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#4444 chore(deps): update container image tccr.io/truecharts/mylar3 to 0.6.9
  charts/stable/mylar/Chart.yaml
  charts/stable/mylar/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#4450 chore(deps): update container image tccr.io/truecharts/mariadb to 10.9.4
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/mariadb/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#4452 chore(deps): update container image tccr.io/truecharts/poste to latest
  charts/incubator/poste/Chart.yaml
  charts/incubator/poste/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#4448 chore(deps): update container image tccr.io/truecharts/chronograf to latest
  charts/incubator/chronograf/Chart.yaml
  charts/incubator/chronograf/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#4451 chore(deps): update container image tccr.io/truecharts/nextcloud-fpm to 25.0.1
  charts/stable/nextcloud/Chart.yaml
  charts/stable/nextcloud/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#4439 chore(testwarden): some tryouts
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/promtail/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
  charts/dependency/subchart/Chart.yaml
  charts/enterprise/testwarden/Chart.yaml
  charts/enterprise/testwarden/ci/default-values.yaml
  charts/enterprise/testwarden/ci/ingress-values.yaml
  charts/enterprise/testwarden/values.yaml
Labels: size/S, lint:ok, precommit:ok

#4455 chore(deps): update container image tccr.io/truecharts/redis to 7.0.5
  charts/dependency/redis/Chart.yaml
  charts/dependency/redis/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#4457 chore(deps): update container image tccr.io/truecharts/solr to v9.0.0
  charts/dependency/solr/Chart.yaml
  charts/dependency/solr/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#4459 chore(deps): update helm chart common to v11.0.3
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/promtail/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
  charts/dependency/subchart/Chart.yaml
Labels: size/S, lint:ok, precommit:ok

#4460 chore(deps): update helm chart common to v11.0.3
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#4462 chore(deps): update container image tccr.io/truecharts/ombi to v4.29.3
  charts/stable/ombi/Chart.yaml
  charts/stable/ombi/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#4446 chore(deps): update container image tccr.io/truecharts/freshrss to v1.20.1
  charts/stable/freshrss/Chart.yaml
  charts/stable/freshrss/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#4449 chore(deps): update container image tccr.io/truecharts/clamav to 0.105.1
  charts/stable/clamav/Chart.yaml
  charts/stable/clamav/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#4469 chore(deps): update container image tccr.io/truecharts/storj-node to v1.67.1
  charts/stable/storj-node/Chart.yaml
  charts/stable/storj-node/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#4464 chore(deps): update container image tccr.io/truecharts/budge to v0.0.9
  charts/stable/budge/Chart.yaml
  charts/stable/budge/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#4465 chore(deps): update container image tccr.io/truecharts/cryptpad to latest
  charts/incubator/cryptpad/Chart.yaml
  charts/incubator/cryptpad/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#4467 chore(deps): update container image tccr.io/truecharts/restreamer to v2.4.1
  charts/incubator/restreamer/Chart.yaml
  charts/incubator/restreamer/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#4470 chore(deps): update container image tccr.io/truecharts/rimgo to latest
  charts/incubator/rimgo/Chart.yaml
  charts/incubator/rimgo/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#4475 chore(deps): update container image tccr.io/truecharts/cloudflareddns to latest
  charts/stable/cloudflareddns/Chart.yaml
  charts/stable/cloudflareddns/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#4474 chore(deps): update container image tccr.io/truecharts/calibre-web to 0.6.19
  charts/stable/calibre-web/Chart.yaml
  charts/stable/calibre-web/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#4473 chore(deps): update container image tccr.io/truecharts/apprise-api to latest
  charts/incubator/apprise-api/Chart.yaml
  charts/incubator/apprise-api/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#4461 chore(deps): update container image tccr.io/truecharts/ghost to v5.22.10
  charts/incubator/ghost/Chart.yaml
  charts/incubator/ghost/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#4477 chore(deps): update container image tccr.io/truecharts/cyberchef to 9.49.0
  charts/stable/cyberchef/Chart.yaml
  charts/stable/cyberchef/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#4480 chore(deps): update container image tccr.io/truecharts/libreddit to latest
  charts/stable/libreddit/Chart.yaml
  charts/stable/libreddit/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#4479 chore(deps): update container image tccr.io/truecharts/jelu to latest
  charts/incubator/jelu/Chart.yaml
  charts/incubator/jelu/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#4478 chore(deps): update container image tccr.io/truecharts/ghost to 5.22.10
  charts/incubator/ghost/Chart.yaml
  charts/incubator/ghost/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#4481 Update container image tccr.io/truecharts/chronograf to latest
  charts/incubator/chronograf/Chart.yaml
  charts/incubator/chronograf/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#4484 Update container image tccr.io/truecharts/filestash to latest
  charts/incubator/filestash/Chart.yaml
  charts/incubator/filestash/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#4485 Update container image tccr.io/truecharts/littlelink-server to latest
  charts/stable/littlelink/Chart.yaml
  charts/stable/littlelink/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major
