Repository trueforge-org/truecharts, pull requests merged in 2022-08, with the labels that each got.

#3354 fix(openproject): Add DB and main service port
  charts/incubator/openproject/Chart.yaml
  charts/incubator/openproject/questions.yaml
  charts/incubator/openproject/templates/_secrets.tpl
  charts/incubator/openproject/templates/common.yaml
  charts/incubator/openproject/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3368 feat(nexus): Nexus
  charts/incubator/nexus-oss/.helmignore
  charts/incubator/nexus-oss/CHANGELOG.md
  charts/incubator/nexus-oss/Chart.yaml
  charts/incubator/nexus-oss/README.md
  charts/incubator/nexus-oss/icon.png
  charts/incubator/nexus-oss/questions.yaml
  charts/incubator/nexus-oss/templates/common.yaml
  charts/incubator/nexus-oss/values.yaml
  cspell.config.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3370 fix(Openserver) - Change internal port 80
  charts/incubator/openproject/Chart.yaml
  charts/incubator/openproject/questions.yaml
  charts/incubator/openproject/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3371 fix(Kitchenowl): Specify FRONT_URL env var
  charts/incubator/kitchenowl/Chart.yaml
  charts/incubator/kitchenowl/questions.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3373 fix(chart-icons): move all chart-icons under hotlink-ok dir
  .github/scripts/gen-docs.sh
  .github/workflows/charts-release.yaml
  tools/build-release.sh
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3372 fix(thunderbird): cleanup
  charts/incubator/thunderbird/Chart.yaml
  charts/incubator/thunderbird/questions.yaml
  charts/incubator/thunderbird/values.yaml
  cspell.config.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#3405 chore(deps): update actions/setup-python digest to b55428b
  .github/workflows/charts-lint.yaml
  .github/workflows/charts-test.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#3407 chore(deps): update renovatebot/github-action action to v32.151.2
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3406 chore(deps): update github/codeql-action digest to 2ca79b6
  .github/workflows/general.security-scan.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3362 fix(docs): fix links
  .chglog/config.yml
  .github/README.md
  .github/cr.yaml
  .github/scripts/build-catalog.sh
  .github/scripts/gen-docs.sh
  .github/workflows/catalog-test.yaml
  .github/workflows/charts-lint.yaml
  .github/workflows/charts-test.yaml
  .github/workflows/renovate-bump.yaml
  templates/chart/Chart.yaml
  templates/docs/README.md.gotmpl
  templates/questions/resources.yaml
  templates/questions/security.yaml
  tools/build-release.sh
Labels: install:ok, lint:ok, size/M, precommit:ok

#3411 chore(deps): update renovatebot/github-action action to v32.152.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3401 fix(nextcloud): Imaginary widescreen image preview fix
  charts/stable/nextcloud/questions.yaml
  charts/stable/nextcloud/templates/_hpb.tpl
  charts/stable/nextcloud/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3399 chore(plex): add valid_chars and docs
  charts/stable/plex/docs/validation.md
  charts/stable/plex/questions.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#3385 fix(flame): cleanup and attempt to enable k8s integration
  charts/incubator/flame/Chart.yaml
  charts/incubator/flame/questions.yaml
  charts/incubator/flame/templates/_integration.tpl
  charts/incubator/flame/templates/common.yaml
  charts/incubator/flame/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#3387 fix(obisidian): cleanup
  charts/incubator/obsidian/Chart.yaml
  charts/incubator/obsidian/questions.yaml
  charts/incubator/obsidian/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#3388 fix(actualserver): cleanup
  charts/incubator/actualserver/Chart.yaml
  charts/incubator/actualserver/questions.yaml
  charts/incubator/actualserver/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#3389 fix(baikal): cleanup
  charts/incubator/baikal/Chart.yaml
  charts/incubator/baikal/questions.yaml
  charts/incubator/baikal/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#3391 fix(treafik): make trustedIPs vars to string
  charts/stable/traefik/questions.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3400 fix(rickroll): Add rickroll images and network
  charts/incubator/rickroll/ci/basic-values.yaml
  charts/incubator/rickroll/ci/fhd-values.yaml
  charts/incubator/rickroll/ci/fhdgame-values.yaml
  charts/incubator/rickroll/ci/fhdonclick-values.yaml
  charts/incubator/rickroll/ci/onclick-values.yaml
  charts/incubator/rickroll/questions.yaml
  charts/incubator/rickroll/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#3404 feat(mymediaforalexa): Add mymediaforalexa
  charts/incubator/mymediaforalexa/Chart.yaml
  charts/incubator/mymediaforalexa/README.md
  charts/incubator/mymediaforalexa/docs/installation_notes.md
  charts/incubator/mymediaforalexa/icon.png
  charts/incubator/mymediaforalexa/questions.yaml
  charts/incubator/mymediaforalexa/templates/common.yaml
  charts/incubator/mymediaforalexa/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3409 fix(zoneminder): Add path for open button
  charts/incubator/zoneminder/Chart.yaml
  charts/incubator/zoneminder/questions.yaml
  charts/incubator/zoneminder/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#3414 fix(mymediaforalexa): enable second service
  charts/incubator/mymediaforalexa/Chart.yaml
  charts/incubator/mymediaforalexa/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3412 hint about the default service port
  charts/stable/vikunja/questions.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3417 fix(mymediaforalexa): mod main port for web access
  charts/incubator/mymediaforalexa/Chart.yaml
  charts/incubator/mymediaforalexa/questions.yaml
  charts/incubator/mymediaforalexa/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3380 feat(authentik): BREAKING CHANGE - Modularize it and add LDAP outpost
  charts/incubator/authentik/Chart.yaml
  charts/incubator/authentik/questions.yaml
  charts/incubator/authentik/templates/_config.tpl
  charts/incubator/authentik/templates/_cronjob.tpl
  charts/incubator/authentik/templates/_geoip.tpl
  charts/incubator/authentik/templates/_ldap.tpl
  charts/incubator/authentik/templates/_secret.tpl
  charts/incubator/authentik/templates/_secrets.tpl
  charts/incubator/authentik/templates/_worker.tpl
  charts/incubator/authentik/templates/common.yaml
  charts/incubator/authentik/values.yaml
  cspell.config.yaml
Labels: size/XL, install:ok, lint:ok, precommit:ok

#3418 chore(deps): update dawidd6/action-download-artifact action to v2.22.0
  .github/workflows/meta-label-pr-ci-status.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3419 chore(deps): update renovatebot/github-action action to v32.153.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3425 chore(deps): update renovatebot/github-action action to v32.153.4
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3424 fix(authentik): enable services/ports and disable geoip by default
  charts/incubator/authentik/Chart.yaml
  charts/incubator/authentik/questions.yaml
  charts/incubator/authentik/templates/_ldap.tpl
  charts/incubator/authentik/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3426 chore(plex): set advertise_ip to required
  charts/stable/plex/Chart.yaml
  charts/stable/plex/questions.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3430 fix(plex): Adjust input validation for comma separated list
  charts/stable/plex/Chart.yaml
  charts/stable/plex/docs/validation.md
  charts/stable/plex/questions.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#3429 chore(deps): update helm chart common to v10.4.11
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3428 chore(deps): update helm chart common to v10.4.11
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/promtail/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
Labels: size/S, lint:ok, precommit:ok

#3432 fix(authentik): only set ints when are defined
  charts/incubator/authentik/Chart.yaml
  charts/incubator/authentik/templates/_config.tpl
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3433 fix(authentik): fix ldap outpost settings not showing, and make mail port an int
  charts/incubator/authentik/Chart.yaml
  charts/incubator/authentik/questions.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3431 chore(deps): update renovatebot/github-action action to v32.154.7
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3438 fix(question): Fix a mistake
  templates/questions/persistence/persistenceBasic.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3439 fix(jekins): Fix permission
  charts/incubator/jenkins/Chart.yaml
  charts/incubator/jenkins/questions.yaml
  charts/incubator/jenkins/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3437 fix(plex): allow empty advertise IP
  charts/stable/plex/Chart.yaml
  charts/stable/plex/docs/validation.md
  charts/stable/plex/questions.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3435 chore(deps): update container image tccr.io/truecharts/jitsi-jicofo to v7577
  charts/incubator/jitsi/Chart.yaml
  charts/incubator/jitsi/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3440 chore(deps): update helm/chart-testing-action action to v2.3.0
  .github/workflows/charts-lint.yaml
  .github/workflows/charts-test.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#3442 chore(deps): update renovatebot/github-action action to v32.154.9
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3434 chore(deps): update docker general non-major
  charts/stable/freeradius/Chart.yaml
  charts/stable/freeradius/values.yaml
  charts/stable/ombi/Chart.yaml
  charts/stable/ombi/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3446 fix(custom-app): Move command from .Values.controller.command to .Values.command
  charts/stable/custom-app/Chart.yaml
  charts/stable/custom-app/questions.yaml
  templates/questions/controller/controllerExpertCommand.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#3445 chore(deps): update renovatebot/github-action action to v32.156.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3448 fix(plex): accept `-` and capital letters in ADVERTISE_IP
  charts/stable/plex/Chart.yaml
  charts/stable/plex/docs/validation.md
  charts/stable/plex/questions.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3449 chore(deps): update helm chart common to v10.4.12
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/promtail/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
Labels: size/S, lint:ok, precommit:ok

#3450 chore(deps): update helm chart common to v10.4.12
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3451 chore(deps): update actions/github-script digest to d50f485
  .github/workflows/meta-label-pr-ci-status.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3390 fix(neko): cleanup
  charts/incubator/authentik/Chart.yaml
  charts/incubator/authentik/values.yaml
  charts/incubator/neko/Chart.yaml
  charts/incubator/neko/ci/basic-values.yaml
  charts/incubator/neko/ci/brave-values.yaml
  charts/incubator/neko/ci/chrome-values.yaml
  charts/incubator/neko/ci/chromium-values.yaml
  charts/incubator/neko/ci/edge-values.yaml
  charts/incubator/neko/ci/remmina-values.yaml
  charts/incubator/neko/ci/tor-values.yaml
  charts/incubator/neko/ci/vivaldi-values.yaml
  charts/incubator/neko/ci/vlc-values.yaml
  charts/incubator/neko/ci/vncviewer-values.yaml
  charts/incubator/neko/ci/xfce-values.yaml
  charts/incubator/neko/questions.yaml
  charts/incubator/neko/values.yaml
  charts/incubator/rickroll/Chart.yaml
  charts/incubator/rickroll/values.yaml
  cspell.config.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3423 fix(mymediaforalexa): moved to stable and mod docs
  charts/incubator/mymediaforalexa/docs/installation_notes.md
  charts/stable/mymediaforalexa/.helmignore
  charts/stable/mymediaforalexa/CHANGELOG.md
  charts/stable/mymediaforalexa/Chart.yaml
  charts/stable/mymediaforalexa/README.md
  charts/stable/mymediaforalexa/docs/img/listeningIPAddress.png
  charts/stable/mymediaforalexa/docs/installation_notes.md
  charts/stable/mymediaforalexa/icon.png
  charts/stable/mymediaforalexa/questions.yaml
  charts/stable/mymediaforalexa/templates/common.yaml
  charts/stable/mymediaforalexa/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#3454 fix(mc-bungeecord): fix service ports
  charts/incubator/minecraft-bungeecord/Chart.yaml
  charts/incubator/minecraft-bungeecord/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3457 fix(Docs): Add info to Support.md
  .github/SUPPORT.md
Labels: install:ok, lint:ok, size/M, precommit:ok

#3459 fix(docs): typo
  charts/stable/mymediaforalexa/Chart.yaml
  charts/stable/mymediaforalexa/docs/installation_notes.md
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3461 Update installation_notes.md
  charts/stable/mymediaforalexa/Chart.yaml
  charts/stable/mymediaforalexa/docs/installation_notes.md
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3463 fix(gitea): Add WebHook config
  charts/stable/gitea/Chart.yaml
  charts/stable/gitea/questions.yaml
  charts/stable/gitea/templates/_secrets.tpl
  charts/stable/gitea/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3472 fix(renovate): treat jitsi updates better
  .github/renovate.json5
Labels: size/S, install:ok, lint:ok, precommit:ok

#3469 chore(deps): update container image tccr.io/truecharts/jitsi-web to v7648
  charts/incubator/jitsi/Chart.yaml
  charts/incubator/jitsi/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3470 chore(deps): update container image tccr.io/truecharts/mosdns to v4.1.9
  charts/stable/mosdns/Chart.yaml
  charts/stable/mosdns/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3466 chore(deps): update container image tccr.io/truecharts/fileflows to v1.0.0
  charts/stable/fileflows/Chart.yaml
  charts/stable/fileflows/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3473 chore(netdata): add some more default confs
  charts/stable/netdata/Chart.yaml
  charts/stable/netdata/values.yaml
  cspell.config.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#3474 fix(mc-bungeecord): fix identation on services
  charts/incubator/minecraft-bungeecord/Chart.yaml
  charts/incubator/minecraft-bungeecord/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3479 chore(deps): update renovatebot/github-action action to v32.159.1
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3485 chore(deps): update renovatebot/github-action action to v32.159.5
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3487 chore(deps): update renovatebot/github-action action to v32.161.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3498 chore(deps): update helm chart common to v10.4.13
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/promtail/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
Labels: size/S, lint:ok, precommit:ok

#3488 feat(tailscale): add tailscale
  charts/incubator/tailscale/.helmignore
  charts/incubator/tailscale/Chart.yaml
  charts/incubator/tailscale/README.md
  charts/incubator/tailscale/docs/installation_notes.md
  charts/incubator/tailscale/icon.png
  charts/incubator/tailscale/questions.yaml
  charts/incubator/tailscale/templates/_configmap.tpl
  charts/incubator/tailscale/templates/_privelegednet.tpl
  charts/incubator/tailscale/templates/_secret.tpl
  charts/incubator/tailscale/templates/common.yaml
  charts/incubator/tailscale/values.yaml
  cspell.config.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3500 chore(deps): update renovatebot/github-action action to v32.161.2
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3505 chore(deps): update renovatebot/github-action action to v32.163.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3508 chore(deps): update renovatebot/github-action action to v32.164.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3499 chore(deps): update helm chart common to v10.4.13
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3509 chore(tailscale): default to rootless
  charts/incubator/tailscale/Chart.yaml
  charts/incubator/tailscale/questions.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3464 feat(plex): Pre-fill ADVERTISE_IP with the server ip and ingress
  charts/stable/plex/Chart.yaml
  charts/stable/plex/questions.yaml
  charts/stable/plex/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#3489 feat(drone-runner): Add drone-runner
  charts/incubator/drone-runner/.helmignore
  charts/incubator/drone-runner/Chart.yaml
  charts/incubator/drone-runner/README.md
  charts/incubator/drone-runner/icon.png
  charts/incubator/drone-runner/questions.yaml
  charts/incubator/drone-runner/templates/_rolebinding.tpl
  charts/incubator/drone-runner/templates/common.yaml
  charts/incubator/drone-runner/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3511 chore(tailscale): update temporary to upstream image repo
  charts/incubator/tailscale/Chart.yaml
  charts/incubator/tailscale/values.yaml
Labels: size/XS

#3513 chore(deps): update renovatebot/github-action action to v32.165.1
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3514 fix(drone-runner): Fix some mistakes
  charts/incubator/drone-runner/Chart.yaml
  charts/incubator/drone-runner/questions.yaml
  charts/incubator/drone-runner/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#3515 fix(plex): fix tpl error
  charts/stable/plex/Chart.yaml
  charts/stable/plex/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3516 chore(deps): update github/codeql-action digest to f5d217b
  .github/workflows/general.security-scan.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3517 chore(deps): update renovatebot/github-action action to v32.168.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3519 fix(tailscale): adds tun device and runs as root by default
  charts/incubator/tailscale/Chart.yaml
  charts/incubator/tailscale/docs/installation_notes.md
  charts/incubator/tailscale/questions.yaml
  charts/incubator/tailscale/templates/_configmap.tpl
  charts/incubator/tailscale/templates/_privelegednet.tpl
  charts/incubator/tailscale/templates/common.yaml
  charts/incubator/tailscale/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#3521 feat(traefik) update theme.park plugin to support addons
  charts/stable/traefik/Chart.yaml
  charts/stable/traefik/questions.yaml
  charts/stable/traefik/templates/middlewares/theme-park.yaml
  charts/stable/traefik/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#3528 chore(deps): update tj-actions/branch-names action to v5.5
  .github/workflows/pr-metadata.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3526 chore(deps): update renovatebot/github-action action to v32.169.1
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3529 fix(stdt): rename 7daystodie to stdt and cleanup
  charts/incubator/sdtd/.helmignore
  charts/incubator/sdtd/CHANGELOG.md
  charts/incubator/sdtd/Chart.yaml
  charts/incubator/sdtd/README.md
  charts/incubator/sdtd/icon.png
  charts/incubator/sdtd/questions.yaml
  charts/incubator/sdtd/templates/common.yaml
  charts/incubator/sdtd/values.yaml
  cspell.config.yaml
  templates/questions/documentation.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#3532 fix(tailscale): don't override varrun
  charts/incubator/tailscale/Chart.yaml
  charts/incubator/tailscale/values.yaml
Labels: size/XS

#3530 chore(deps): update docker general non-major
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/postgresql/values.yaml
  charts/incubator/apprise-api/Chart.yaml
  charts/incubator/apprise-api/values.yaml
  charts/incubator/core-keeper-dedicated-server/Chart.yaml
  charts/incubator/core-keeper-dedicated-server/values.yaml
  charts/incubator/cryptpad/Chart.yaml
  charts/incubator/cryptpad/values.yaml
  charts/incubator/kasm/Chart.yaml
  charts/incubator/kasm/values.yaml
  charts/incubator/passwordpusherephemeral/Chart.yaml
  charts/incubator/passwordpusherephemeral/values.yaml
  charts/incubator/virt-manager/Chart.yaml
  charts/incubator/virt-manager/values.yaml
  charts/stable/babybuddy/Chart.yaml
  charts/stable/babybuddy/values.yaml
  charts/stable/booksonic-air/Chart.yaml
  charts/stable/booksonic-air/values.yaml
  charts/stable/custom-app/Chart.yaml
  charts/stable/custom-app/ci/test-values.yaml
  charts/stable/custom-app/values.yaml
  charts/stable/cyberchef/Chart.yaml
  charts/stable/cyberchef/values.yaml
  charts/stable/heimdall/Chart.yaml
  charts/stable/heimdall/values.yaml
  charts/stable/jackett/Chart.yaml
  charts/stable/jackett/values.yaml
  charts/stable/minecraft-java/Chart.yaml
  charts/stable/minecraft-java/ci/j11-values.yaml
  charts/stable/minecraft-java/ci/j8-values.yaml
  charts/stable/minecraft-java/values.yaml
  charts/stable/piaware/Chart.yaml
  charts/stable/piaware/values.yaml
  charts/stable/prometheus/Chart.yaml
  charts/stable/prometheus/values.yaml
Labels: lint:ok, size/M, precommit:ok

#3338 fix(mineos): add docs and update chart.yaml
  charts/incubator/mineos/Chart.yaml
  charts/incubator/mineos/docs/installation_notes.md
  charts/incubator/mineos/questions.yaml
  charts/incubator/mineos/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3533 feat(drone-runner): Move to stable
  charts/stable/drone-runner/.helmignore
  charts/stable/drone-runner/CHANGELOG.md
  charts/stable/drone-runner/Chart.yaml
  charts/stable/drone-runner/README.md
  charts/stable/drone-runner/icon.png
  charts/stable/drone-runner/questions.yaml
  charts/stable/drone-runner/templates/_rolebinding.tpl
  charts/stable/drone-runner/templates/common.yaml
  charts/stable/drone-runner/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3536 fix(traefik) update traefik theme.park plugin
  charts/stable/traefik/Chart.yaml
  charts/stable/traefik/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3537 fix(tailscale): use role and rolebind instead of clusterrole
  charts/incubator/tailscale/Chart.yaml
  charts/incubator/tailscale/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3535 chore(deps): update github/codeql-action digest to 7fee4ca
  .github/workflows/general.security-scan.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3534 fix(docs): correctly set the train in link
  .github/scripts/gen-docs.sh
  templates/docs/README.md.gotmpl
  tools/build-release.sh
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3538 fix(guacamole-client): fix quoted true and cleanup a bit
  charts/stable/guacamole-client/Chart.yaml
  charts/stable/guacamole-client/templates/_configmap.tpl
  charts/stable/guacamole-client/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3539 fix(tailscale): use different ports for targetPort and port
  charts/incubator/tailscale/Chart.yaml
  charts/incubator/tailscale/questions.yaml
  charts/incubator/tailscale/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3540 chore(deps): update renovatebot/github-action action to v32.171.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3543 chore(deps): update ghcr.io/truecharts/devcontainer:v2.6.0 docker digest to 0eca784
  .github/workflows/catalog-test.yaml
  .github/workflows/charts-release.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3547 chore(deps): update helm chart common to v10.5.0
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3548 chore(deps): update renovatebot/github-action action to v32.172.1
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3549 fix(guac-client): booleans don't work the same with `with`
  charts/stable/guacamole-client/Chart.yaml
  charts/stable/guacamole-client/templates/_configmap.tpl
Labels: size/S, install:ok, lint:ok, precommit:ok

#3550 chore(etherpad): expose some env-vars
  charts/stable/etherpad/Chart.yaml
  charts/stable/etherpad/questions.yaml
  charts/stable/etherpad/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#3546 chore(deps): update helm chart common to v10.5.0
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/promtail/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
Labels: size/S, lint:ok, precommit:ok

#3553 chore(deps): update renovatebot/github-action action to v32.173.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3556 feat(Tailscale): Move to stable and add How-To Guide
  charts/stable/tailscale/.helmignore
  charts/stable/tailscale/CHANGELOG.md
  charts/stable/tailscale/Chart.yaml
  charts/stable/tailscale/README.md
  charts/stable/tailscale/docs/How-To-Guide.md
  charts/stable/tailscale/docs/img/How-To-Image-1.png
  charts/stable/tailscale/docs/img/How-To-Image-2.png
  charts/stable/tailscale/docs/img/How-To-Image-3.png
  charts/stable/tailscale/docs/img/Sysctl.png
  charts/stable/tailscale/icon.png
  charts/stable/tailscale/questions.yaml
  charts/stable/tailscale/templates/_configmap.tpl
  charts/stable/tailscale/templates/_secret.tpl
  charts/stable/tailscale/templates/common.yaml
  charts/stable/tailscale/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#3501 feat(questions): add tailscale addon questions
  templates/questions/addons.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#3541 chore(nextcloud): set overwrite.cli.url
  charts/stable/nextcloud/Chart.yaml
  charts/stable/nextcloud/templates/_hpb.tpl
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3557 fix(nextcloud): Add port on non-ingressed installs to overwrite.cli.url
  charts/stable/nextcloud/Chart.yaml
  charts/stable/nextcloud/templates/_hpb.tpl
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3558 chore(questions): remove required from configFile
  templates/questions/addons.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3563 chore(deps): update helm chart common to v10.5.1
  templates/chart/Chart.yaml
Labels: size/XS

#3562 chore(deps): update helm chart common to v10.5.1
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/promtail/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
Labels: size/S, lint:ok, precommit:ok

#3564 docs(Tailscale): Add more info to How-To guide and another example of Extra Args
  charts/stable/tailscale/Chart.yaml
  charts/stable/tailscale/docs/How-To-Guide.md
  charts/stable/tailscale/docs/img/Hostname.png
Labels: size/S, precommit:failed, install:ok, lint:ok

#3571 fix(tdarr): enable portal button
  charts/stable/tdarr/Chart.yaml
  charts/stable/tdarr/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3566 chore(deps): update renovatebot/github-action action to v32.174.2
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3570 fix(traefik) remove deprecated references from default headers
  charts/stable/traefik/Chart.yaml
  charts/stable/traefik/templates/middlewares/basic-middleware.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3568 feat(filerun): run app as apps user and set id and gid according to P…
  charts/incubator/filerun/Chart.yaml
  charts/incubator/filerun/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3572 chore(deps): update github/codeql-action digest to c7f292e
  .github/workflows/general.security-scan.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3574 chore(deps): update renovatebot/github-action action to v32.177.1
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3576 fix(rflood): remove duplicate vars and cleanup
  charts/incubator/rflood/Chart.yaml
  charts/incubator/rflood/questions.yaml
  charts/incubator/rflood/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#3578 feat(nextcloud): set default phone region
  charts/stable/nextcloud/Chart.yaml
  charts/stable/nextcloud/docs/validation.md
  charts/stable/nextcloud/questions.yaml
  charts/stable/nextcloud/templates/_hpb.tpl
  charts/stable/nextcloud/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#3583 chore(deps): update helm chart common to v10.5.2
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/promtail/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
Labels: size/S, lint:ok, precommit:ok

#3584 chore(deps): update helm chart common to v10.5.2
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3582 chore(deps): update actions/github-script digest to c713e51
  .github/workflows/meta-label-pr-ci-status.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3588 chore(deps): update renovatebot/github-action action to v32.179.1
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3591 chore(deps): update endbug/label-sync digest to 2155ba2
  .github/workflows/schedule-sync-labels.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3592 chore(recipes): expose CSRF_TRUSTED_ORIGINS to gui
  charts/stable/recipes/Chart.yaml
  charts/stable/recipes/questions.yaml
  charts/stable/recipes/values.yaml
  cspell.config.yaml
Labels: size/XS

#3589 feat(Docusaurus): Add Docusaurus
  charts/incubator/docusaurus/.helmignore
  charts/incubator/docusaurus/Chart.yaml
  charts/incubator/docusaurus/README.md
  charts/incubator/docusaurus/icon.png
  charts/incubator/docusaurus/questions.yaml
  charts/incubator/docusaurus/templates/common.yaml
  charts/incubator/docusaurus/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3596 chore(deps): update tj-actions/branch-names action to v5.6
  .github/workflows/pr-metadata.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3593 feat(traefik): add support for proxyProtocol
  .github/scripts/build-catalog.sh
  charts/stable/traefik/Chart.yaml
  charts/stable/traefik/questions.yaml
  charts/stable/traefik/templates/_args.tpl
  charts/stable/traefik/values.yaml
  cspell.config.yaml
  templates/questions/traefik/forwardedHeaders.yaml
  templates/questions/traefik/proxyProtocol.yaml
  tools/build-release.sh
Labels: install:ok, lint:ok, size/L, precommit:ok

#3597 feat(plex): disable GDM by default
  charts/stable/plex/Chart.yaml
  charts/stable/plex/questions.yaml
  charts/stable/plex/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3598 fix(plex): init script quotes it automatically
  charts/stable/plex/Chart.yaml
  charts/stable/plex/values.yaml
Labels: size/XS

#3599 fix(nextcloud): prevent ownership init timeouts
  charts/stable/nextcloud/Chart.yaml
  charts/stable/nextcloud/values.yaml
Labels: size/XS

#3594 fix(inventree): fix errors and restructure chart to be readable
  charts/stable/inventree/Chart.yaml
  charts/stable/inventree/questions.yaml
  charts/stable/inventree/templates/_configmap.tpl
  charts/stable/inventree/templates/_init.tpl
  charts/stable/inventree/templates/_nginx.tpl
  charts/stable/inventree/templates/_secrets.tpl
  charts/stable/inventree/templates/_worker.tpl
  charts/stable/inventree/templates/common.yaml
  charts/stable/inventree/values.yaml
  cspell.config.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3600 chore(deps): update docker general non-major
  charts/incubator/amtd/Chart.yaml
  charts/incubator/amtd/values.yaml
  charts/incubator/conreq/Chart.yaml
  charts/incubator/conreq/values.yaml
  charts/incubator/crafty-4/Chart.yaml
  charts/incubator/crafty-4/values.yaml
  charts/incubator/ghost/Chart.yaml
  charts/incubator/ghost/values.yaml
  charts/incubator/googlephotossync/Chart.yaml
  charts/incubator/googlephotossync/values.yaml
  charts/incubator/icloudpd/Chart.yaml
  charts/incubator/icloudpd/values.yaml
  charts/incubator/passwordpusherephemeral/Chart.yaml
  charts/incubator/passwordpusherephemeral/values.yaml
  charts/incubator/qbitmanage/Chart.yaml
  charts/incubator/qbitmanage/values.yaml
  charts/incubator/ra-rom-processor/Chart.yaml
  charts/incubator/ra-rom-processor/values.yaml
  charts/incubator/rdesktop/Chart.yaml
  charts/incubator/rdesktop/values.yaml
  charts/incubator/rimgo/Chart.yaml
  charts/incubator/rimgo/values.yaml
  charts/incubator/virt-manager/Chart.yaml
  charts/incubator/virt-manager/values.yaml
  charts/stable/custom-app/Chart.yaml
  charts/stable/custom-app/ci/test-values.yaml
  charts/stable/custom-app/values.yaml
  charts/stable/cyberchef/Chart.yaml
  charts/stable/cyberchef/values.yaml
  charts/stable/homer/Chart.yaml
  charts/stable/homer/values.yaml
  charts/stable/inventree/Chart.yaml
  charts/stable/inventree/values.yaml
  charts/stable/jackett/Chart.yaml
  charts/stable/jackett/values.yaml
  charts/stable/lazylibrarian/Chart.yaml
  charts/stable/lazylibrarian/values.yaml
  charts/stable/rsshub/Chart.yaml
  charts/stable/rsshub/values.yaml
  charts/stable/trilium-notes/Chart.yaml
  charts/stable/trilium-notes/values.yaml
Labels: size/M, precommit:ok

#3601 chore(deps): update renovatebot/github-action action to v32.180.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3602 fix(cloudflared): update the docs.
  charts/stable/cloudflared/Chart.yaml
  charts/stable/cloudflared/docs/imgs/cf-tunnel-access.png
  charts/stable/cloudflared/docs/imgs/cf-tunnel-create.png
  charts/stable/cloudflared/docs/imgs/cf-tunnel-hostname.png
  charts/stable/cloudflared/docs/imgs/cf-tunnel-priv-network.png
  charts/stable/cloudflared/docs/imgs/cf-tunnel-token.png
  charts/stable/cloudflared/docs/installation_notes.md
Labels: size/S, install:ok, lint:ok, precommit:ok

#3575 feat(wireguard): add standalone wireguard
  charts/incubator/wireguard/.helmignore
  charts/incubator/wireguard/Chart.yaml
  charts/incubator/wireguard/README.md
  charts/incubator/wireguard/icon.png
  charts/incubator/wireguard/questions.yaml
  charts/incubator/wireguard/templates/_configfilemount.tpl
  charts/incubator/wireguard/templates/_configmap.tpl
  charts/incubator/wireguard/templates/_secret.tpl
  charts/incubator/wireguard/templates/common.yaml
  charts/incubator/wireguard/values.yaml
  cspell.config.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3607 chore(deps): update renovatebot/github-action action to v32.180.1
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3606 chore(deps): update docker general non-major
  charts/incubator/amtd/Chart.yaml
  charts/incubator/amtd/values.yaml
  charts/incubator/apprise-api/Chart.yaml
  charts/incubator/apprise-api/values.yaml
  charts/incubator/cryptpad/Chart.yaml
  charts/incubator/cryptpad/values.yaml
  charts/incubator/cups-server/Chart.yaml
  charts/incubator/cups-server/values.yaml
  charts/incubator/filestash/Chart.yaml
  charts/incubator/filestash/values.yaml
  charts/incubator/googlephotossync/Chart.yaml
  charts/incubator/googlephotossync/values.yaml
  charts/incubator/icloudpd/Chart.yaml
  charts/incubator/icloudpd/values.yaml
  charts/incubator/kasm/Chart.yaml
  charts/incubator/kasm/values.yaml
  charts/incubator/lancache-monolithic/Chart.yaml
  charts/incubator/lancache-monolithic/values.yaml
  charts/incubator/meshcentral/Chart.yaml
  charts/incubator/meshcentral/values.yaml
  charts/incubator/plextraktsync/Chart.yaml
  charts/incubator/plextraktsync/values.yaml
  charts/incubator/ra-rom-processor/Chart.yaml
  charts/incubator/ra-rom-processor/values.yaml
  charts/incubator/raneto/Chart.yaml
  charts/incubator/raneto/values.yaml
  charts/incubator/rimgo/Chart.yaml
  charts/incubator/rimgo/values.yaml
  charts/incubator/searxng/Chart.yaml
  charts/incubator/searxng/values.yaml
  charts/incubator/virt-manager/Chart.yaml
  charts/incubator/virt-manager/values.yaml
  charts/incubator/webtop/Chart.yaml
  charts/incubator/webtop/values.yaml
  charts/stable/babybuddy/Chart.yaml
  charts/stable/babybuddy/values.yaml
  charts/stable/booksonic-air/Chart.yaml
  charts/stable/booksonic-air/values.yaml
  charts/stable/custom-app/Chart.yaml
  charts/stable/custom-app/ci/test-values.yaml
  charts/stable/custom-app/values.yaml
  charts/stable/dashdot/Chart.yaml
  charts/stable/dashdot/values.yaml
  charts/stable/fluidd/Chart.yaml
  charts/stable/fluidd/values.yaml
  charts/stable/heimdall/Chart.yaml
  charts/stable/heimdall/values.yaml
  charts/stable/jackett/Chart.yaml
  charts/stable/jackett/values.yaml
  charts/stable/lazylibrarian/Chart.yaml
  charts/stable/lazylibrarian/values.yaml
  charts/stable/omada-controller/Chart.yaml
  charts/stable/omada-controller/values.yaml
  charts/stable/rsshub/Chart.yaml
  charts/stable/rsshub/values.yaml
  charts/stable/tvheadend/Chart.yaml
  charts/stable/tvheadend/values.yaml
  charts/stable/wekan/Chart.yaml
  charts/stable/wekan/values.yaml
Labels: size/M, precommit:ok

#3605 feat(Docusaurs): Move to stable and add how-to
  charts/stable/docusaurus/.helmignore
  charts/stable/docusaurus/CHANGELOG.md
  charts/stable/docusaurus/Chart.yaml
  charts/stable/docusaurus/README.md
  charts/stable/docusaurus/docs/How-To.md
  charts/stable/docusaurus/docs/img/Container-Config.png
  charts/stable/docusaurus/docs/img/Storage.png
  charts/stable/docusaurus/icon.png
  charts/stable/docusaurus/questions.yaml
  charts/stable/docusaurus/templates/common.yaml
  charts/stable/docusaurus/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#3609 chore(deps): update renovatebot/github-action action to v32.181.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3608 fix(mongodb): use new mongo shell
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/mongodb/values.yaml
  cspell.config.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3610 chore(deps): update helm chart common to v10.5.3
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/promtail/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
Labels: size/S, lint:ok, precommit:ok

#3611 chore(deps): update helm chart common to v10.5.3
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3614 chore(deps): update helm chart common to v10.5.4
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3617 chore(deps): update helm chart mongodb to v2
  charts/incubator/meshcentral/Chart.yaml
  charts/incubator/youtubedl-material/Chart.yaml
  charts/stable/wekan/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3618 chore(deps): update renovatebot/github-action action to v32.182.1
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3623 chore(deps): update docker general non-major
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/clickhouse/values.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/memcached/values.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/mongodb/values.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/redis/values.yaml
  charts/dependency/solr/Chart.yaml
  charts/dependency/solr/values.yaml
  charts/incubator/cryptpad/Chart.yaml
  charts/incubator/cryptpad/values.yaml
  charts/incubator/rimgo/Chart.yaml
  charts/incubator/rimgo/values.yaml
  charts/incubator/searxng/Chart.yaml
  charts/incubator/searxng/values.yaml
  charts/incubator/sonarqube/Chart.yaml
  charts/incubator/sonarqube/values.yaml
  charts/incubator/sourcegraph/Chart.yaml
  charts/incubator/sourcegraph/values.yaml
  charts/incubator/thunderbird/Chart.yaml
  charts/incubator/thunderbird/values.yaml
  charts/incubator/virt-manager/Chart.yaml
  charts/incubator/virt-manager/values.yaml
  charts/incubator/z80pack/Chart.yaml
  charts/incubator/z80pack/values.yaml
  charts/stable/grafana/Chart.yaml
  charts/stable/grafana/values.yaml
  charts/stable/impostor-server/Chart.yaml
  charts/stable/impostor-server/ci/values.yaml
  charts/stable/impostor-server/values.yaml
  charts/stable/littlelink/Chart.yaml
  charts/stable/littlelink/values.yaml
  charts/stable/matomo/Chart.yaml
  charts/stable/matomo/values.yaml
  charts/stable/minio/Chart.yaml
  charts/stable/minio/values.yaml
  charts/stable/pihole/Chart.yaml
  charts/stable/pihole/values.yaml
  charts/stable/plex/Chart.yaml
  charts/stable/plex/values.yaml
  charts/stable/prometheus/Chart.yaml
  charts/stable/prometheus/values.yaml
  charts/stable/rsshub/Chart.yaml
  charts/stable/rsshub/values.yaml
  charts/stable/sickchill/Chart.yaml
  charts/stable/sickchill/values.yaml
  charts/stable/syslog-ng/Chart.yaml
  charts/stable/syslog-ng/values.yaml
  charts/stable/tailscale/Chart.yaml
  charts/stable/tailscale/values.yaml
  charts/stable/xwiki/Chart.yaml
  charts/stable/xwiki/values.yaml
  charts/stable/zwavejs2mqtt/Chart.yaml
  charts/stable/zwavejs2mqtt/values.yaml
Labels: size/M, precommit:ok

#3624 chore(deps): update helm general non-major
  charts/incubator/appsmith/Chart.yaml
  charts/incubator/authentik/Chart.yaml
  charts/incubator/meshcentral/Chart.yaml
  charts/incubator/plausible/Chart.yaml
  charts/incubator/wger/Chart.yaml
  charts/incubator/youtubedl-material/Chart.yaml
  charts/stable/anonaddy/Chart.yaml
  charts/stable/authelia/Chart.yaml
  charts/stable/baserow/Chart.yaml
  charts/stable/fireflyiii/Chart.yaml
  charts/stable/friendica/Chart.yaml
  charts/stable/gitea/Chart.yaml
  charts/stable/grist/Chart.yaml
  charts/stable/inventree/Chart.yaml
  charts/stable/kutt/Chart.yaml
  charts/stable/librephotos/Chart.yaml
  charts/stable/linkace/Chart.yaml
  charts/stable/lychee/Chart.yaml
  charts/stable/n8n/Chart.yaml
  charts/stable/nextcloud/Chart.yaml
  charts/stable/nocodb/Chart.yaml
  charts/stable/onlyoffice-document-server/Chart.yaml
  charts/stable/outline/Chart.yaml
  charts/stable/paperless-ng/Chart.yaml
  charts/stable/papermerge/Chart.yaml
  charts/stable/rsshub/Chart.yaml
  charts/stable/shlink/Chart.yaml
  charts/stable/snipe-it/Chart.yaml
  charts/stable/vikunja/Chart.yaml
  charts/stable/weblate/Chart.yaml
  charts/stable/wekan/Chart.yaml
Labels: size/M, precommit:ok

#3625 chore(deps): update helm chart common to v10.5.5
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/promtail/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
Labels: size/S, lint:ok, precommit:ok

#3628 chore(deps): update dawidd6/action-download-artifact action to v2.23.0
  .github/workflows/meta-label-pr-ci-status.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok
