Repository trueforge-org/truecharts, pull requests merged in 2022-09, with the labels that each got.

#3648 chore(deps): update renovatebot/github-action action to v32.185.3
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3650 feat(recyclarr): actually move it to stable
  charts/stable/recyclarr/.helmignore
  charts/stable/recyclarr/CHANGELOG.md
  charts/stable/recyclarr/Chart.yaml
  charts/stable/recyclarr/README.md
  charts/stable/recyclarr/icon.png
  charts/stable/recyclarr/questions.yaml
  charts/stable/recyclarr/templates/common.yaml
  charts/stable/recyclarr/values.yaml
Labels: size/XS

#3651 fix(authentik): geoip disable rofs
  charts/incubator/authentik/Chart.yaml
  charts/incubator/authentik/templates/_geoip.tpl
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3649 chore(deps): update docker general non-major
  .github/ct-install.yaml
  charts/incubator/cryptpad/Chart.yaml
  charts/incubator/cryptpad/values.yaml
  charts/incubator/filestash/Chart.yaml
  charts/incubator/filestash/values.yaml
  charts/incubator/lancache-dns/Chart.yaml
  charts/incubator/lancache-dns/values.yaml
  charts/incubator/lancache-monolithic/Chart.yaml
  charts/incubator/lancache-monolithic/values.yaml
  charts/incubator/obs-ndi/Chart.yaml
  charts/incubator/obs-ndi/values.yaml
  charts/incubator/openproject/Chart.yaml
  charts/incubator/openproject/values.yaml
  charts/incubator/passwordpusherephemeral/Chart.yaml
  charts/incubator/passwordpusherephemeral/values.yaml
  charts/incubator/rimgo/Chart.yaml
  charts/incubator/rimgo/values.yaml
  charts/incubator/ring-mqtt/Chart.yaml
  charts/incubator/ring-mqtt/values.yaml
  charts/incubator/vertex/Chart.yaml
  charts/incubator/vertex/values.yaml
  charts/incubator/virt-manager/Chart.yaml
  charts/incubator/virt-manager/values.yaml
  charts/incubator/wger/Chart.yaml
  charts/incubator/wger/values.yaml
  charts/incubator/zabbix-server/Chart.yaml
  charts/incubator/zabbix-server/values.yaml
  charts/stable/clamav/Chart.yaml
  charts/stable/clamav/values.yaml
  charts/stable/cyberchef/Chart.yaml
  charts/stable/cyberchef/values.yaml
  charts/stable/grafana/Chart.yaml
  charts/stable/grafana/values.yaml
  charts/stable/impostor-server/Chart.yaml
  charts/stable/impostor-server/values.yaml
  charts/stable/littlelink/Chart.yaml
  charts/stable/littlelink/values.yaml
  charts/stable/n8n/Chart.yaml
  charts/stable/n8n/values.yaml
  charts/stable/rsshub/Chart.yaml
  charts/stable/rsshub/values.yaml
  charts/stable/synapse/Chart.yaml
  charts/stable/synapse/values.yaml
  charts/stable/tailscale/Chart.yaml
  charts/stable/tailscale/values.yaml
  charts/stable/tvheadend/Chart.yaml
  charts/stable/tvheadend/values.yaml
Labels: size/M, precommit:ok

#3653 chore(deps): update renovatebot/github-action action to v32.186.1
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3654 chore(deps): update github/codeql-action digest to b398f52
  .github/workflows/general.security-scan.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3655 chore(deps): update renovatebot/github-action action to v32.186.2
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3652 feat(wger): BREAKING-CHANGE big cleanup - move to configmap
  charts/incubator/wger/Chart.yaml
  charts/incubator/wger/questions.yaml
  charts/incubator/wger/templates/_configmap.tpl
  charts/incubator/wger/templates/_nginx.tpl
  charts/incubator/wger/templates/_secrets.tpl
  charts/incubator/wger/templates/common.yaml
  charts/incubator/wger/values.yaml
  cspell.config.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3657 chore(questions): links only work in tooltips
  templates/questions/documentation.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3658 feat(wger): move to stable
  charts/stable/wger/.helmignore
  charts/stable/wger/CHANGELOG.md
  charts/stable/wger/Chart.yaml
  charts/stable/wger/README.md
  charts/stable/wger/docs/credentials.md
  charts/stable/wger/icon.png
  charts/stable/wger/questions.yaml
  charts/stable/wger/templates/_configmap.tpl
  charts/stable/wger/templates/_nginx.tpl
  charts/stable/wger/templates/_secrets.tpl
  charts/stable/wger/templates/common.yaml
  charts/stable/wger/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3659 chore(deps): update ghcr.io/truecharts/devcontainer:v2.6.0 docker digest to fd70a76
  .github/workflows/catalog-test.yaml
  .github/workflows/charts-release.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3661 chore(deps): update renovatebot/github-action action to v32.187.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3664 chore(deps): update renovatebot/github-action action to v32.187.1
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3666 chore(incubator): remove duplicate apps
  charts/incubator/fileflows-node/.helmignore
  charts/incubator/fileflows-node/CHANGELOG.md
  charts/incubator/fileflows-node/Chart.yaml
  charts/incubator/fileflows-node/README.md
  charts/incubator/fileflows-node/icon.png
  charts/incubator/fileflows-node/questions.yaml
  charts/incubator/fileflows-node/templates/common.yaml
  charts/incubator/fileflows-node/values.yaml
  charts/incubator/satisfactory-server/.helmignore
  charts/incubator/satisfactory-server/CHANGELOG.md
  charts/incubator/satisfactory-server/Chart.yaml
  charts/incubator/satisfactory-server/README.md
  charts/incubator/satisfactory-server/icon.png
  charts/incubator/satisfactory-server/questions.yaml
  charts/incubator/satisfactory-server/templates/common.yaml
  charts/incubator/satisfactory-server/values.yaml
  charts/incubator/skyrimtogetherrebornserver/.helmignore
  charts/incubator/skyrimtogetherrebornserver/CHANGELOG.md
  charts/incubator/skyrimtogetherrebornserver/Chart.yaml
  charts/incubator/skyrimtogetherrebornserver/README.md
  charts/incubator/skyrimtogetherrebornserver/icon.png
  charts/incubator/skyrimtogetherrebornserver/questions.yaml
  charts/incubator/skyrimtogetherrebornserver/templates/common.yaml
  charts/incubator/skyrimtogetherrebornserver/values.yaml
Labels: size/XL

#3663 fix(owncloud-ocis): Save init logs
  charts/stable/owncloud-ocis/Chart.yaml
  charts/stable/owncloud-ocis/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3667 fix(pasta): cleanup and fix service
  charts/incubator/pasta/Chart.yaml
  charts/incubator/pasta/questions.yaml
  charts/incubator/pasta/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#3669 chore(deps): update renovatebot/github-action action to v32.189.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3670 chore(deps): update container image tccr.io/truecharts/zwavejs2mqtt to v7.0.0
  charts/stable/zwavejs2mqtt/Chart.yaml
  charts/stable/zwavejs2mqtt/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3656 fix(inventree): update nginx.conf mount method
  charts/stable/inventree/Chart.yaml
  charts/stable/inventree/templates/_configmap.tpl
  charts/stable/inventree/templates/_nginx.tpl
  charts/stable/inventree/values.yaml
  charts/stable/wger/Chart.yaml
  charts/stable/wger/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#3671 fix(wger,inventree): revert configmap mount method
  charts/stable/inventree/Chart.yaml
  charts/stable/inventree/values.yaml
  charts/stable/wger/Chart.yaml
  charts/stable/wger/values.yaml
Labels: size/S

#3672 chore(digikam): update image tag
  charts/stable/digikam/Chart.yaml
  charts/stable/digikam/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3674 feat(pasta): move to stable
  charts/stable/pasta/.helmignore
  charts/stable/pasta/CHANGELOG.md
  charts/stable/pasta/Chart.yaml
  charts/stable/pasta/README.md
  charts/stable/pasta/icon.png
  charts/stable/pasta/questions.yaml
  charts/stable/pasta/templates/common.yaml
  charts/stable/pasta/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3665 fix(apps): fix serviceaccount creation on few apps
  charts/dependency/promtail/Chart.yaml
  charts/dependency/promtail/values.yaml
  charts/stable/drone-runner/Chart.yaml
  charts/stable/drone-runner/values.yaml
  charts/stable/k8s-gateway/Chart.yaml
  charts/stable/k8s-gateway/values.yaml
  charts/stable/netdata/Chart.yaml
  charts/stable/netdata/values.yaml
  charts/stable/prometheus/Chart.yaml
  charts/stable/prometheus/values.yaml
  charts/stable/tailscale/Chart.yaml
  charts/stable/tailscale/values.yaml
  charts/stable/traefik/Chart.yaml
  charts/stable/traefik/values.yaml
Labels: size/S, lint:ok, precommit:ok

#3673 feat(authentik): BREAKING CHANGE move to k8s integration instead of manual
  charts/incubator/authentik/Chart.yaml
  charts/incubator/authentik/questions.yaml
  charts/incubator/authentik/templates/_config.tpl
  charts/incubator/authentik/templates/_ldap.tpl
  charts/incubator/authentik/templates/_secret.tpl
  charts/incubator/authentik/templates/common.yaml
  charts/incubator/authentik/values.yaml
  cspell.config.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3676 chore(deps): update helm chart common to v10.5.7
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
Labels: size/S, lint:ok, precommit:ok

#3677 chore(deps): update helm chart common to v10.5.7
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3678 Revert "feat(authentik): BREAKING CHANGE move to k8s integration inst…
  charts/incubator/authentik/Chart.yaml
  charts/incubator/authentik/questions.yaml
  charts/incubator/authentik/templates/_config.tpl
  charts/incubator/authentik/templates/_ldap.tpl
  charts/incubator/authentik/templates/_secret.tpl
  charts/incubator/authentik/templates/common.yaml
  charts/incubator/authentik/values.yaml
  cspell.config.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3682 chore(deps): update renovatebot/github-action action to v32.190.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3681 chore(deps): update docker general non-major
  charts/incubator/humhub/Chart.yaml
  charts/incubator/humhub/values.yaml
  charts/incubator/qflood/Chart.yaml
  charts/incubator/qflood/values.yaml
  charts/incubator/tasmocompiler/Chart.yaml
  charts/incubator/tasmocompiler/values.yaml
  charts/incubator/tracks/Chart.yaml
  charts/incubator/tracks/values.yaml
  charts/incubator/tubesync/Chart.yaml
  charts/incubator/tubesync/values.yaml
  charts/incubator/virt-manager/Chart.yaml
  charts/incubator/virt-manager/values.yaml
  charts/incubator/yourls/Chart.yaml
  charts/incubator/yourls/values.yaml
  charts/stable/boinc/Chart.yaml
  charts/stable/boinc/values.yaml
  charts/stable/custom-app/Chart.yaml
  charts/stable/custom-app/ci/test-values.yaml
  charts/stable/custom-app/values.yaml
  charts/stable/cyberchef/Chart.yaml
  charts/stable/cyberchef/values.yaml
  charts/stable/flexget/Chart.yaml
  charts/stable/flexget/values.yaml
  charts/stable/icinga2/Chart.yaml
  charts/stable/icinga2/values.yaml
  charts/stable/jackett/Chart.yaml
  charts/stable/jackett/values.yaml
  charts/stable/kavita/Chart.yaml
  charts/stable/kavita/values.yaml
  charts/stable/lazylibrarian/Chart.yaml
  charts/stable/lazylibrarian/values.yaml
  charts/stable/minecraft-java/Chart.yaml
  charts/stable/minecraft-java/ci/j11-values.yaml
  charts/stable/minecraft-java/ci/j8-values.yaml
  charts/stable/minecraft-java/values.yaml
  charts/stable/omada-controller/Chart.yaml
  charts/stable/omada-controller/values.yaml
  charts/stable/qinglong/Chart.yaml
  charts/stable/qinglong/values.yaml
  charts/stable/ring-mqtt/Chart.yaml
  charts/stable/ring-mqtt/values.yaml
  charts/stable/rsshub/Chart.yaml
  charts/stable/rsshub/values.yaml
  charts/stable/traefik/Chart.yaml
  charts/stable/traefik/values.yaml
  charts/stable/xwiki/Chart.yaml
  charts/stable/xwiki/values.yaml
Labels: size/M, precommit:ok

#3683 chore(deps): update container image tccr.io/truecharts/mattermost to v7.3
  charts/stable/mattermost/Chart.yaml
  charts/stable/mattermost/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3686 fix(ring-mqtt): enable ports
  charts/stable/ring-mqtt/Chart.yaml
  charts/stable/ring-mqtt/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3687 feat(apps): move to stable
  charts/stable/chronos/.helmignore
  charts/stable/chronos/CHANGELOG.md
  charts/stable/chronos/Chart.yaml
  charts/stable/chronos/README.md
  charts/stable/chronos/icon.png
  charts/stable/chronos/questions.yaml
  charts/stable/chronos/templates/common.yaml
  charts/stable/chronos/values.yaml
  charts/stable/filerun/.helmignore
  charts/stable/filerun/CHANGELOG.md
  charts/stable/filerun/Chart.yaml
  charts/stable/filerun/README.md
  charts/stable/filerun/icon.png
  charts/stable/filerun/questions.yaml
  charts/stable/filerun/templates/common.yaml
  charts/stable/filerun/values.yaml
  charts/stable/kitchenowl/.helmignore
  charts/stable/kitchenowl/CHANGELOG.md
  charts/stable/kitchenowl/Chart.yaml
  charts/stable/kitchenowl/README.md
  charts/stable/kitchenowl/icon.png
  charts/stable/kitchenowl/questions.yaml
  charts/stable/kitchenowl/templates/_secrets.tpl
  charts/stable/kitchenowl/templates/common.yaml
  charts/stable/kitchenowl/values.yaml
  cspell.config.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#3688 fix(apps): hexo-blog, hexchat, qbitmanage, whisparr
  charts/incubator/hexchat/Chart.yaml
  charts/incubator/hexchat/questions.yaml
  charts/incubator/hexchat/values.yaml
  charts/incubator/hexo-blog/Chart.yaml
  charts/incubator/hexo-blog/questions.yaml
  charts/incubator/hexo-blog/values.yaml
  charts/incubator/qbitmanage/Chart.yaml
  charts/incubator/qbitmanage/questions.yaml
  charts/incubator/qbitmanage/values.yaml
  charts/incubator/whisparr/Chart.yaml
  charts/incubator/whisparr/questions.yaml
  charts/incubator/whisparr/values.yaml
  cspell.config.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3689 feat(whisparr): move to stable
  charts/stable/whisparr/.helmignore
  charts/stable/whisparr/CHANGELOG.md
  charts/stable/whisparr/Chart.yaml
  charts/stable/whisparr/README.md
  charts/stable/whisparr/icon.png
  charts/stable/whisparr/questions.yaml
  charts/stable/whisparr/templates/common.yaml
  charts/stable/whisparr/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3690 Add description for flashpaper
  charts/incubator/flashpaper/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3692 chore(deps): update renovatebot/github-action action to v32.190.2
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3694 fix(arkserver): add some default params
  charts/incubator/arksurvivalevolved/Chart.yaml
  charts/incubator/arksurvivalevolved/questions.yaml
  charts/incubator/arksurvivalevolved/values.yaml
  cspell.config.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3701 chore(deps): update renovatebot/github-action action to v32.190.3
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3703 feat(adguard-home): move to stable and cleanup ports a bit
  charts/stable/adguard-home/.helmignore
  charts/stable/adguard-home/CHANGELOG.md
  charts/stable/adguard-home/Chart.yaml
  charts/stable/adguard-home/README.md
  charts/stable/adguard-home/icon.png
  charts/stable/adguard-home/questions.yaml
  charts/stable/adguard-home/templates/common.yaml
  charts/stable/adguard-home/values.yaml
Labels: size/S

#3698 feat(Zerotier): Add How-To guide
  charts/stable/zerotier/Chart.yaml
  charts/stable/zerotier/docs/How-To-Guide.md
  charts/stable/zerotier/docs/img/How-To-Step-1.png
  charts/stable/zerotier/docs/img/How-To-Step-2.png
  charts/stable/zerotier/docs/img/How-To-Step-3.png
  charts/stable/zerotier/docs/img/Network-ID.png
  charts/stable/zerotier/docs/img/Sysctl.png
  cspell.config.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#3702 feat(Orbital-Sync): Add Orbital Sync chart
  .github/ct-install.yaml
  charts/incubator/orbital-sync/.helmignore
  charts/incubator/orbital-sync/Chart.yaml
  charts/incubator/orbital-sync/README.md
  charts/incubator/orbital-sync/icon.png
  charts/incubator/orbital-sync/questions.yaml
  charts/incubator/orbital-sync/templates/_pihole-hosts.tpl
  charts/incubator/orbital-sync/templates/common.yaml
  charts/incubator/orbital-sync/values.yaml
  cspell.config.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3705 feat(qbitmanage): move to stable
  charts/stable/qbitmanage/.helmignore
  charts/stable/qbitmanage/CHANGELOG.md
  charts/stable/qbitmanage/Chart.yaml
  charts/stable/qbitmanage/README.md
  charts/stable/qbitmanage/icon.png
  charts/stable/qbitmanage/questions.yaml
  charts/stable/qbitmanage/templates/common.yaml
  charts/stable/qbitmanage/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3706 chore(deps): update renovatebot/github-action action to v32.190.4
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3707 feat(apt-cacher-ng): move to stable and add docs
  charts/incubator/orbital-sync/Chart.yaml
  charts/incubator/orbital-sync/values.yaml
  charts/stable/apt-cacher-ng/.helmignore
  charts/stable/apt-cacher-ng/CHANGELOG.md
  charts/stable/apt-cacher-ng/Chart.yaml
  charts/stable/apt-cacher-ng/README.md
  charts/stable/apt-cacher-ng/docs/how-to.md
  charts/stable/apt-cacher-ng/icon.png
  charts/stable/apt-cacher-ng/questions.yaml
  charts/stable/apt-cacher-ng/templates/common.yaml
  charts/stable/apt-cacher-ng/values.yaml
  cspell.config.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#3708 fix(authentik): use https://localhost:9443 for outposts
  charts/incubator/authentik/Chart.yaml
  charts/incubator/authentik/docs/installation_notes.md
  charts/incubator/authentik/questions.yaml
  charts/incubator/authentik/templates/_config.tpl
  charts/incubator/authentik/templates/_secret.tpl
  charts/incubator/authentik/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#3710 chore(deps): update docker general non-major
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/mariadb/values.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/mongodb/values.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/postgresql/values.yaml
  charts/incubator/cadquery-server/Chart.yaml
  charts/incubator/cadquery-server/values.yaml
  charts/incubator/cryptpad/Chart.yaml
  charts/incubator/cryptpad/values.yaml
  charts/incubator/factorio/Chart.yaml
  charts/incubator/factorio/values.yaml
  charts/incubator/googlephotossync/Chart.yaml
  charts/incubator/googlephotossync/values.yaml
  charts/incubator/neko/Chart.yaml
  charts/incubator/neko/values.yaml
  charts/incubator/rimgo/Chart.yaml
  charts/incubator/rimgo/values.yaml
  charts/incubator/vertex/Chart.yaml
  charts/incubator/vertex/values.yaml
  charts/incubator/virt-manager/Chart.yaml
  charts/incubator/virt-manager/values.yaml
  charts/stable/custom-app/Chart.yaml
  charts/stable/custom-app/ci/test-values.yaml
  charts/stable/custom-app/values.yaml
  charts/stable/cyberchef/Chart.yaml
  charts/stable/cyberchef/values.yaml
  charts/stable/homarr/Chart.yaml
  charts/stable/homarr/values.yaml
  charts/stable/icinga2/Chart.yaml
  charts/stable/icinga2/values.yaml
  charts/stable/jackett/Chart.yaml
  charts/stable/jackett/values.yaml
  charts/stable/kanboard/Chart.yaml
  charts/stable/kanboard/values.yaml
  charts/stable/lychee/Chart.yaml
  charts/stable/lychee/values.yaml
  charts/stable/minecraft-java/Chart.yaml
  charts/stable/minecraft-java/ci/j11-values.yaml
  charts/stable/minecraft-java/ci/j8-values.yaml
  charts/stable/minecraft-java/values.yaml
  charts/stable/nextcloud/Chart.yaml
  charts/stable/nextcloud/values.yaml
  charts/stable/openkm/Chart.yaml
  charts/stable/openkm/values.yaml
  charts/stable/outline/Chart.yaml
  charts/stable/outline/values.yaml
  charts/stable/pihole/Chart.yaml
  charts/stable/pihole/values.yaml
  charts/stable/prometheus/Chart.yaml
  charts/stable/prometheus/values.yaml
  charts/stable/rsshub/Chart.yaml
  charts/stable/rsshub/values.yaml
  charts/stable/uptime-kuma/Chart.yaml
  charts/stable/uptime-kuma/values.yaml
  charts/stable/wekan/Chart.yaml
  charts/stable/wekan/values.yaml
Labels: size/M, precommit:ok

#3712 chore(deps): update renovatebot/github-action action to v32.190.6
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3713 chore(deps): update renovatebot/github-action action to v32.192.3
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3714 fix(mealie): use the new var for defining db type
  charts/stable/mealie/Chart.yaml
  charts/stable/mealie/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3716 chore(deps): update renovatebot/github-action action to v32.194.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3721 chore(deps): update renovatebot/github-action action to v32.194.2
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3720 chore(deps): update container image tccr.io/truecharts/ombi to v4.25.1
  charts/stable/ombi/Chart.yaml
  charts/stable/ombi/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3724 fix(website): fix building
  charts/dependency/postgresql/CHANGELOG.md
  charts/dependency/postgresql/Chart.yaml
Labels: size/XS

#3725 chore(nextcloud): doc polishing
  charts/stable/nextcloud/Chart.yaml
  charts/stable/nextcloud/docs/installation.md
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3722 chore(traefik): move docs from website repo
  charts/stable/traefik/Chart.yaml
  charts/stable/traefik/docs/how-to.md
  cspell.config.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#3728 chore(deps): update ghcr.io/truecharts/devcontainer:v2.6.0 docker digest to cefec79
  .github/workflows/catalog-test.yaml
  .github/workflows/charts-release.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3730 chore(deps): update helm chart common to v10.5.8
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3729 chore(deps): update helm chart common to v10.5.8
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/promtail/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
Labels: size/S, lint:ok, precommit:ok

#3732 chore(tailscale): update docs a bit
  charts/stable/tailscale/Chart.yaml
  charts/stable/tailscale/docs/How-To-Guide.md
  cspell.config.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#3734 chore(deps): update renovatebot/github-action action to v32.194.4
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3737 chore(deps): update helm chart common to v10.5.9
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/promtail/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
Labels: size/S, lint:ok, precommit:ok

#3738 chore(deps): update helm chart common to v10.5.9
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3695 feat(metallb): update for v0.13
  charts/stable/metallb/Chart.yaml
  charts/stable/metallb/ci/ci-values.yaml
  charts/stable/metallb/crds/bgpadvertisment.yaml
  charts/stable/metallb/crds/bgppeer.yaml
  charts/stable/metallb/crds/community.yaml
  charts/stable/metallb/crds/ipaddresspool.yaml
  charts/stable/metallb/crds/l2advertisment.yaml
  charts/stable/metallb/questions.yaml
  charts/stable/metallb/templates/_bgpadvertisement.tpl
  charts/stable/metallb/templates/_community.tpl
  charts/stable/metallb/templates/_ipaddresspool.tpl
  charts/stable/metallb/templates/_l2advertisement.tpl
  charts/stable/metallb/templates/_peers.tpl
  charts/stable/metallb/templates/common.yaml
  charts/stable/metallb/values.yaml
  cspell.config.yaml
Labels: size/XL, precommit:failed, lint:ok

#3740 chore(metallb): cleanup and move to enterprise train
  charts/enterprise/metallb/.helmignore
  charts/enterprise/metallb/CHANGELOG.md
  charts/enterprise/metallb/Chart.yaml
  charts/enterprise/metallb/icon.png
  charts/enterprise/metallb/questions.yaml
  charts/enterprise/metallb/templates/bgpadvertisement.yaml
  charts/enterprise/metallb/templates/community.yaml
  charts/enterprise/metallb/templates/ipaddresspool.yaml
  charts/enterprise/metallb/templates/l2advertisement.yaml
  charts/enterprise/metallb/templates/peers.yaml
  charts/enterprise/metallb/values.yaml
  charts/stable/metallb/README.md
  charts/stable/metallb/ci/ci-values.yaml
  charts/stable/metallb/questions.yaml
  charts/stable/metallb/templates/_community.tpl
  charts/stable/metallb/templates/_ipaddresspool.tpl
  charts/stable/metallb/templates/common.yaml
  charts/stable/metallb/values.yaml
Labels: size/XL, install:ok, lint:ok, precommit:ok

#3744 chore(metallb): fix questions.yaml
  charts/enterprise/metallb/Chart.yaml
  charts/enterprise/metallb/questions.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3745 chore(deps): update renovatebot/github-action action to v32.194.5
  .github/workflows/renovate.yml
Labels: size/XS

#3746 chore(nextcloud); update UI label
  charts/stable/nextcloud/Chart.yaml
  charts/stable/nextcloud/questions.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3748 fix(typecho):Fix Env
  charts/stable/typecho/Chart.yaml
  charts/stable/typecho/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3754 fix(apps): add missing dicts on list items
  charts/enterprise/metallb/Chart.yaml
  charts/enterprise/metallb/questions.yaml
  charts/incubator/orbital-sync/Chart.yaml
  charts/incubator/orbital-sync/questions.yaml
  charts/stable/synapse/Chart.yaml
  charts/stable/synapse/questions.yaml
Labels: size/L

#3755 chore(deps): update docker general non-major
  charts/dependency/memcached/Chart.yaml
  charts/dependency/memcached/values.yaml
  charts/dependency/solr/Chart.yaml
  charts/dependency/solr/values.yaml
  charts/incubator/autoscan/Chart.yaml
  charts/incubator/autoscan/values.yaml
  charts/incubator/convos/Chart.yaml
  charts/incubator/convos/values.yaml
  charts/incubator/cryptpad/Chart.yaml
  charts/incubator/cryptpad/values.yaml
  charts/incubator/factorio/Chart.yaml
  charts/incubator/factorio/values.yaml
  charts/incubator/icloudpd/Chart.yaml
  charts/incubator/icloudpd/values.yaml
  charts/incubator/kdenlive/Chart.yaml
  charts/incubator/kdenlive/values.yaml
  charts/incubator/neko/Chart.yaml
  charts/incubator/neko/values.yaml
  charts/incubator/orbital-sync/Chart.yaml
  charts/incubator/orbital-sync/values.yaml
  charts/incubator/pyload-ng/Chart.yaml
  charts/incubator/pyload-ng/values.yaml
  charts/incubator/rimgo/Chart.yaml
  charts/incubator/rimgo/values.yaml
  charts/incubator/timetagger/Chart.yaml
  charts/incubator/timetagger/values.yaml
  charts/incubator/vertex/Chart.yaml
  charts/incubator/vertex/values.yaml
  charts/stable/boinc/Chart.yaml
  charts/stable/boinc/values.yaml
  charts/stable/custom-app/Chart.yaml
  charts/stable/custom-app/ci/test-values.yaml
  charts/stable/custom-app/values.yaml
  charts/stable/flaresolverr/Chart.yaml
  charts/stable/flaresolverr/values.yaml
  charts/stable/home-assistant/Chart.yaml
  charts/stable/home-assistant/values.yaml
  charts/stable/ispy-agent-dvr/Chart.yaml
  charts/stable/ispy-agent-dvr/values.yaml
  charts/stable/jackett/Chart.yaml
  charts/stable/jackett/values.yaml
  charts/stable/matomo/Chart.yaml
  charts/stable/matomo/values.yaml
  charts/stable/prometheus/Chart.yaml
  charts/stable/prometheus/values.yaml
  charts/stable/rsshub/Chart.yaml
  charts/stable/rsshub/values.yaml
Labels: size/M, precommit:ok

#3758 fix(metallb): one more additional_attrs -.-
  charts/enterprise/metallb/Chart.yaml
  charts/enterprise/metallb/questions.yaml
Labels: size/XS

#3760 chore(deps): update renovatebot/github-action action to v32.195.1
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3759 chore(deps): update helm chart memcached to v3.0.75
  charts/stable/gitea/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3764 fix(freshrss): fix tag scheme
  charts/stable/freshrss/Chart.yaml
  charts/stable/freshrss/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3766 chore(deps): update helm chart common to v10.5.10
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/promtail/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
Labels: size/S, lint:ok, precommit:ok

#3773 chore(deps): update renovatebot/github-action action to v32.195.3
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3768 chore(deps): update helm chart common to v10.5.10
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3774 fix(simply-shorten): move to stable.
  charts/stable/simply-shorten/.helmignore
  charts/stable/simply-shorten/CHANGELOG.md
  charts/stable/simply-shorten/Chart.yaml
  charts/stable/simply-shorten/README.md
  charts/stable/simply-shorten/docs/installation_notes.md
  charts/stable/simply-shorten/icon.png
  charts/stable/simply-shorten/questions.yaml
  charts/stable/simply-shorten/templates/common.yaml
  charts/stable/simply-shorten/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#3741 feat(tailscale): add common flags as fields
  charts/stable/tailscale/Chart.yaml
  charts/stable/tailscale/docs/How-To-Guide.md
  charts/stable/tailscale/questions.yaml
  charts/stable/tailscale/templates/_configmap.tpl
  charts/stable/tailscale/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#3776 chore(deps): update actions/stale digest to 99b6c70
  .github/workflows/stale.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3777 fix(metallb): indent issue with L2 advertisements
  charts/enterprise/metallb/Chart.yaml
  charts/enterprise/metallb/questions.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#3775 fix(rcon-webadmin): move to stable.
  charts/incubator/rcon-webadmin/questions.yaml
  charts/incubator/rcon-webadmin/values.yaml
  charts/stable/rcon-webadmin/.helmignore
  charts/stable/rcon-webadmin/CHANGELOG.md
  charts/stable/rcon-webadmin/Chart.yaml
  charts/stable/rcon-webadmin/README.md
  charts/stable/rcon-webadmin/docs/installation.md
  charts/stable/rcon-webadmin/icon.png
  charts/stable/rcon-webadmin/questions.yaml
  charts/stable/rcon-webadmin/templates/common.yaml
  charts/stable/rcon-webadmin/values.yaml
  cspell.config.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3781 fix(autobrr): move to stable.
  charts/stable/autobrr/.helmignore
  charts/stable/autobrr/CHANGELOG.md
  charts/stable/autobrr/Chart.yaml
  charts/stable/autobrr/README.md
  charts/stable/autobrr/icon.png
  charts/stable/autobrr/questions.yaml
  charts/stable/autobrr/templates/common.yaml
  charts/stable/autobrr/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3780 chore(deps): update renovatebot/github-action action to v32.195.5
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3717 feat(umami): Add umami
  charts/incubator/umami/.helmignore
  charts/incubator/umami/Chart.yaml
  charts/incubator/umami/README.md
  charts/incubator/umami/icon.png
  charts/incubator/umami/questions.yaml
  charts/incubator/umami/templates/_secret.tpl
  charts/incubator/umami/templates/common.yaml
  charts/incubator/umami/values.yaml
  cspell.config.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3779 chore(redis): remove unneeded element from UI
  charts/dependency/redis/Chart.yaml
  charts/dependency/redis/questions.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3783 Update prometheus chart
  charts/stable/prometheus/Chart.yaml
  charts/stable/prometheus/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3785 chore(deps): update github/codeql-action digest to 6a38b7d
  .github/workflows/general.security-scan.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3787 chore(deps): update docker general non-major
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/collabora-online/values.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/memcached/values.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/postgresql/values.yaml
  charts/dependency/solr/Chart.yaml
  charts/dependency/solr/values.yaml
  charts/incubator/chromium/Chart.yaml
  charts/incubator/chromium/values.yaml
  charts/incubator/cryptpad/Chart.yaml
  charts/incubator/cryptpad/values.yaml
  charts/incubator/external-ip/Chart.yaml
  charts/incubator/external-ip/values.yaml
  charts/incubator/filestash/Chart.yaml
  charts/incubator/filestash/values.yaml
  charts/incubator/twonky-server/Chart.yaml
  charts/incubator/twonky-server/values.yaml
  charts/incubator/virt-manager/Chart.yaml
  charts/incubator/virt-manager/values.yaml
  charts/stable/adguard-home/Chart.yaml
  charts/stable/adguard-home/values.yaml
  charts/stable/bookstack/Chart.yaml
  charts/stable/bookstack/values.yaml
  charts/stable/digikam/Chart.yaml
  charts/stable/digikam/values.yaml
  charts/stable/docker-compose/Chart.yaml
  charts/stable/docker-compose/values.yaml
  charts/stable/filezilla/Chart.yaml
  charts/stable/filezilla/values.yaml
  charts/stable/ispy-agent-dvr/Chart.yaml
  charts/stable/ispy-agent-dvr/values.yaml
  charts/stable/minecraft-java/Chart.yaml
  charts/stable/minecraft-java/ci/j11-values.yaml
  charts/stable/minecraft-java/ci/j8-values.yaml
  charts/stable/minecraft-java/values.yaml
  charts/stable/n8n/Chart.yaml
  charts/stable/n8n/values.yaml
  charts/stable/nextcloud/Chart.yaml
  charts/stable/nextcloud/values.yaml
  charts/stable/rsshub/Chart.yaml
  charts/stable/rsshub/values.yaml
  charts/stable/theme-park/Chart.yaml
  charts/stable/theme-park/values.yaml
  charts/stable/weblate/Chart.yaml
  charts/stable/weblate/values.yaml
Labels: size/M, precommit:ok

#3786 feat(restreamer): Add all the options!
  charts/incubator/restreamer/Chart.yaml
  charts/incubator/restreamer/docs/installation.md
  charts/incubator/restreamer/questions.yaml
  charts/incubator/restreamer/templates/_config.tpl
  charts/incubator/restreamer/templates/_secret.tpl
  charts/incubator/restreamer/templates/common.yaml
  charts/incubator/restreamer/values.yaml
  cspell.config.yaml
Labels: size/XL, install:ok, lint:ok, precommit:ok

#3788 chore(deps): update github/codeql-action digest to 904260d
  .github/workflows/general.security-scan.yaml
Labels: size/XS

#3604 fix(plextraktsync): add docs and persistence
  charts/incubator/plextraktsync/Chart.yaml
  charts/incubator/plextraktsync/questions.yaml
  charts/incubator/plextraktsync/templates/_cronjob.tpl
  charts/incubator/plextraktsync/templates/common.yaml
  charts/incubator/plextraktsync/values.yaml
  cspell.config.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#3791 chore(deps): update container image tccr.io/truecharts/dokuwiki to v20220731.1.0
  charts/stable/dokuwiki/Chart.yaml
  charts/stable/dokuwiki/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3794 chore(questions.yaml): Disabled by default autoPermissions
  templates/questions/persistence/persistenceList.yaml
Labels: size/XS

#3799 chore(deps): update renovatebot/github-action action to v32.197.0
  .github/workflows/renovate.yml
Labels: size/XS

#3801 chore(deps): update renovatebot/github-action action to v32.197.1
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3616 feat(jupyter): Add Jupyter
  charts/incubator/jupyter/.helmignore
  charts/incubator/jupyter/CHANGELOG.md
  charts/incubator/jupyter/Chart.yaml
  charts/incubator/jupyter/README.md
  charts/incubator/jupyter/icon.png
  charts/incubator/jupyter/questions.yaml
  charts/incubator/jupyter/templates/common.yaml
  charts/incubator/jupyter/values.yaml
  cspell.config.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3803 chore(apps): add gui option
  charts/stable/dashdot/Chart.yaml
  charts/stable/dashdot/questions.yaml
  charts/stable/dashdot/values.yaml
  cspell.config.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3809 feat(linkwallet): add linkwallet
  charts/incubator/linkwallet/.helmignore
  charts/incubator/linkwallet/Chart.yaml
  charts/incubator/linkwallet/README.md
  charts/incubator/linkwallet/icon.png
  charts/incubator/linkwallet/questions.yaml
  charts/incubator/linkwallet/templates/common.yaml
  charts/incubator/linkwallet/values.yaml
  cspell.config.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3811 fix(plextraktsync): cron type does not work
  charts/incubator/plextraktsync/Chart.yaml
  charts/incubator/plextraktsync/questions.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3805 feat(batnoter): add batnoter
  charts/incubator/batnoter/.helmignore
  charts/incubator/batnoter/Chart.yaml
  charts/incubator/batnoter/README.md
  charts/incubator/batnoter/icon.png
  charts/incubator/batnoter/questions.yaml
  charts/incubator/batnoter/templates/common.yaml
  charts/incubator/batnoter/values.yaml
  cspell.config.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#3804 feat(flatnotes): add flatnotes
  charts/incubator/flatnotes/.helmignore
  charts/incubator/flatnotes/Chart.yaml
  charts/incubator/flatnotes/README.md
  charts/incubator/flatnotes/icon.png
  charts/incubator/flatnotes/questions.yaml
  charts/incubator/flatnotes/templates/_secrets.tpl
  charts/incubator/flatnotes/templates/common.yaml
  charts/incubator/flatnotes/values.yaml
  cspell.config.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3806 feat(homepage): add homepage
  charts/incubator/homepage/.helmignore
  charts/incubator/homepage/Chart.yaml
  charts/incubator/homepage/README.md
  charts/incubator/homepage/icon.png
  charts/incubator/homepage/questions.yaml
  charts/incubator/homepage/templates/common.yaml
  charts/incubator/homepage/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#3808 feat(flemarr): add flemarr
  charts/incubator/flemarr/.helmignore
  charts/incubator/flemarr/Chart.yaml
  charts/incubator/flemarr/README.md
  charts/incubator/flemarr/ci/ci-values.yaml
  charts/incubator/flemarr/docs/validation.md
  charts/incubator/flemarr/icon.png
  charts/incubator/flemarr/questions.yaml
  charts/incubator/flemarr/templates/_configMap.tpl
  charts/incubator/flemarr/templates/common.yaml
  charts/incubator/flemarr/values.yaml
  cspell.config.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3813 chore(deps): update renovatebot/github-action action to v32.198.1
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3814 feat(docs): metallb basic setup guide
  charts/enterprise/metallb/Chart.yaml
  charts/enterprise/metallb/docs/img/metallb_guide_addresspool_basic.png
  charts/enterprise/metallb/docs/img/metallb_guide_disableLB.png
  charts/enterprise/metallb/docs/img/metallb_guide_l2advertisement.png
  charts/enterprise/metallb/docs/img/metallb_guide_specifyIP.png
  charts/enterprise/metallb/docs/setup-guide.md
Labels: install:ok, lint:ok, size/M, precommit:ok

#3810 feat(wbo): add wbo
  charts/incubator/wbo/.helmignore
  charts/incubator/wbo/Chart.yaml
  charts/incubator/wbo/README.md
  charts/incubator/wbo/icon.png
  charts/incubator/wbo/questions.yaml
  charts/incubator/wbo/templates/_configmap.tpl
  charts/incubator/wbo/templates/_secret.tpl
  charts/incubator/wbo/templates/common.yaml
  charts/incubator/wbo/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3797 chore(prometheus): Expose prometheus configuration options in Scale GUI
  charts/stable/prometheus/Chart.yaml
  charts/stable/prometheus/questions.yaml
  charts/stable/prometheus/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3807 feat(bender): add bender
  charts/incubator/bender/.helmignore
  charts/incubator/bender/Chart.yaml
  charts/incubator/bender/README.md
  charts/incubator/bender/icon.png
  charts/incubator/bender/questions.yaml
  charts/incubator/bender/templates/common.yaml
  charts/incubator/bender/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3820 chore(deps): update renovatebot/github-action action to v32.199.1
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3819 chore(deps): update helm chart common to v10.5.10
  charts/incubator/jupyter/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3825 chore(services): move last apps to LB from simple
  charts/incubator/batnoter/Chart.yaml
  charts/incubator/batnoter/questions.yaml
  charts/incubator/flatnotes/Chart.yaml
  charts/incubator/flatnotes/questions.yaml
  charts/incubator/homepage/Chart.yaml
  charts/incubator/homepage/questions.yaml
  charts/incubator/jupyter/Chart.yaml
  charts/incubator/jupyter/questions.yaml
  charts/incubator/linkwallet/Chart.yaml
  charts/incubator/linkwallet/questions.yaml
Labels: size/S

#3824 fix(n8n): parse as int when comparing with 0
  charts/stable/n8n/Chart.yaml
  charts/stable/n8n/templates/_configmap.tpl
Labels: size/S, install:ok, lint:ok, precommit:ok

#3828 chore(deps): update renovatebot/github-action action to v32.201.1
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3829 fix(universal-media-server): fix port and code
  charts/incubator/universal-media-server/Chart.yaml
  charts/incubator/universal-media-server/questions.yaml
  charts/incubator/universal-media-server/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#3831 fix(grafana): pre-create tmp dir
  charts/stable/grafana/Chart.yaml
  charts/stable/grafana/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3833 chore(deps): update helm chart common to v10.5.11
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3835 Fix, correct 404 URL
  .github/README.md
Labels: size/XS

#3832 chore(deps): update helm chart common to v10.5.11
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/redis/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3834 chore(deps): update renovatebot/github-action action to v32.201.2
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3838 chore(deps): update github/codeql-action digest to 86f3159
  .github/workflows/general.security-scan.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3840 chore(deps): update actions/stale action to v6
  .github/workflows/stale.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3839 chore(deps): update docker general non-major
  charts/dependency/memcached/Chart.yaml
  charts/dependency/memcached/values.yaml
  charts/dependency/solr/Chart.yaml
  charts/dependency/solr/values.yaml
  charts/incubator/appsmith/Chart.yaml
  charts/incubator/appsmith/values.yaml
  charts/incubator/cops/Chart.yaml
  charts/incubator/cops/values.yaml
  charts/incubator/filestash/Chart.yaml
  charts/incubator/filestash/values.yaml
  charts/incubator/googlephotossync/Chart.yaml
  charts/incubator/googlephotossync/values.yaml
  charts/incubator/neko/Chart.yaml
  charts/incubator/neko/values.yaml
  charts/incubator/rimgo/Chart.yaml
  charts/incubator/rimgo/values.yaml
  charts/incubator/searxng/Chart.yaml
  charts/incubator/searxng/values.yaml
  charts/incubator/virt-manager/Chart.yaml
  charts/incubator/virt-manager/values.yaml
  charts/incubator/zabbix-server/Chart.yaml
  charts/incubator/zabbix-server/values.yaml
  charts/stable/custom-app/Chart.yaml
  charts/stable/custom-app/ci/test-values.yaml
  charts/stable/custom-app/values.yaml
  charts/stable/jackett/Chart.yaml
  charts/stable/jackett/values.yaml
  charts/stable/littlelink/Chart.yaml
  charts/stable/littlelink/values.yaml
  charts/stable/outline/Chart.yaml
  charts/stable/outline/values.yaml
  charts/stable/rsshub/Chart.yaml
  charts/stable/rsshub/values.yaml
  charts/stable/tailscale/Chart.yaml
  charts/stable/tailscale/values.yaml
Labels: lint:ok, size/M, precommit:ok

#3841 chore(charts): fix prometheus annotations
  charts/incubator/authentik/Chart.yaml
  charts/incubator/authentik/templates/common.yaml
  charts/incubator/restreamer/Chart.yaml
  charts/incubator/restreamer/templates/common.yaml
  charts/stable/traefik/Chart.yaml
  charts/stable/traefik/templates/common.yaml
Labels: size/XS

#3842 chore(deps): update helm chart common to v10.5.12
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/promtail/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
Labels: size/S, lint:ok, precommit:ok

#3735 feat(blocky): add blocky
  charts/incubator/blocky/.helmignore
  charts/incubator/blocky/Chart.yaml
  charts/incubator/blocky/README.md
  charts/incubator/blocky/ci/k8sgateway-values.yaml
  charts/incubator/blocky/ci/standalone-values.yaml
  charts/incubator/blocky/docs/installation-notes.md
  charts/incubator/blocky/icon.png
  charts/incubator/blocky/questions.yaml
  charts/incubator/blocky/templates/_blockyConfig.tpl
  charts/incubator/blocky/templates/_k8sgateway.tpl
  charts/incubator/blocky/templates/_webui.tpl
  charts/incubator/blocky/templates/common.yaml
  charts/incubator/blocky/values.yaml
  cspell.config.yaml
Labels: size/XL, install:ok, lint:ok, precommit:ok

#3844 chore(deps): update renovatebot/github-action action to v32.202.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3845 chore(deps): update tj-actions/branch-names action to v6
  .github/workflows/pr-metadata.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3847 fix(minecraft-bedrock): Allow minimum 0 player idle timeout to disable feature on server
  charts/stable/minecraft-bedrock/Chart.yaml
  charts/stable/minecraft-bedrock/questions.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3843 chore(deps): update helm chart common to v10.5.12
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3853 chore(deps): update renovatebot/github-action action to v32.202.1
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3856 fix(onlyoffice); set redis password
  charts/stable/onlyoffice-document-server/Chart.yaml
  charts/stable/onlyoffice-document-server/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3857 chore(deps): update renovatebot/github-action action to v32.202.3
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3851 chore(deps): update container image tccr.io/truecharts/zwavejs2mqtt to v8.0.0
  charts/stable/zwavejs2mqtt/Chart.yaml
  charts/stable/zwavejs2mqtt/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3858 feat(mealie): Adapt to the new multi container upstream release
  charts/stable/mealie/Chart.yaml
  charts/stable/mealie/questions.yaml
  charts/stable/mealie/templates/_api.tpl
  charts/stable/mealie/templates/_configmap.tpl
  charts/stable/mealie/templates/_secret.tpl
  charts/stable/mealie/templates/common.yaml
  charts/stable/mealie/values.yaml
  cspell.config.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3864 (fix) update description + bump
  charts/stable/transmission/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3863 (fix)Allows Minecraft to utilize all cores available by allowing 0 as an option
  charts/stable/minecraft-bedrock/Chart.yaml
  charts/stable/minecraft-bedrock/questions.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3859 feat(portainer): add portainer
  charts/incubator/portainer-ce/.helmignore
  charts/incubator/portainer-ce/Chart.yaml
  charts/incubator/portainer-ce/README.md
  charts/incubator/portainer-ce/icon.png
  charts/incubator/portainer-ce/questions.yaml
  charts/incubator/portainer-ce/templates/_args.tpl
  charts/incubator/portainer-ce/templates/common.yaml
  charts/incubator/portainer-ce/values.yaml
  cspell.config.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3860 chore(deps): update docker general non-major
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/mariadb/values.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/mongodb/values.yaml
  charts/incubator/authentik/Chart.yaml
  charts/incubator/authentik/values.yaml
  charts/incubator/blocky/Chart.yaml
  charts/incubator/blocky/values.yaml
  charts/incubator/crafty-4/Chart.yaml
  charts/incubator/crafty-4/values.yaml
  charts/incubator/crypto-exchanges-gateway/Chart.yaml
  charts/incubator/crypto-exchanges-gateway/values.yaml
  charts/incubator/cryptpad/Chart.yaml
  charts/incubator/cryptpad/values.yaml
  charts/incubator/rimgo/Chart.yaml
  charts/incubator/rimgo/values.yaml
  charts/incubator/searxng/Chart.yaml
  charts/incubator/searxng/values.yaml
  charts/incubator/tracks/Chart.yaml
  charts/incubator/tracks/values.yaml
  charts/incubator/traktarr/Chart.yaml
  charts/incubator/traktarr/values.yaml
  charts/incubator/ts-dnsserver/Chart.yaml
  charts/incubator/ts-dnsserver/values.yaml
  charts/incubator/virt-manager/Chart.yaml
  charts/incubator/virt-manager/values.yaml
  charts/stable/autobrr/Chart.yaml
  charts/stable/autobrr/values.yaml
  charts/stable/boinc/Chart.yaml
  charts/stable/boinc/values.yaml
  charts/stable/cyberchef/Chart.yaml
  charts/stable/cyberchef/values.yaml
  charts/stable/dokuwiki/Chart.yaml
  charts/stable/dokuwiki/values.yaml
  charts/stable/flexget/Chart.yaml
  charts/stable/flexget/values.yaml
  charts/stable/grafana/Chart.yaml
  charts/stable/grafana/values.yaml
  charts/stable/logitech-media-server/Chart.yaml
  charts/stable/logitech-media-server/values.yaml
  charts/stable/prometheus/Chart.yaml
  charts/stable/prometheus/values.yaml
  charts/stable/recipes/Chart.yaml
  charts/stable/recipes/values.yaml
  charts/stable/theme-park/Chart.yaml
  charts/stable/theme-park/values.yaml
  charts/stable/traefik/Chart.yaml
  charts/stable/traefik/values.yaml
Labels: size/M, precommit:ok

#3867 chore(deps): update stefanzweifel/git-auto-commit-action digest to 6c32682
  .github/workflows/charts-changelog.yaml
  .github/workflows/charts-release.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3862 chore(deps): update container image tccr.io/truecharts/sourcegraph to v4.0.0
  charts/incubator/sourcegraph/Chart.yaml
  charts/incubator/sourcegraph/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3861 chore(deps): update container image tccr.io/truecharts/alist to v3.0.1
  charts/stable/alist/Chart.yaml
  charts/stable/alist/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3869 chore(deps): update helm chart common to v10.6.0
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3868 chore(deps): update helm chart common to v10.6.0
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/promtail/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
Labels: size/S, lint:ok, precommit:ok

#3866 fix(blocky): Finish up UI
  charts/incubator/blocky/Chart.yaml
  charts/incubator/blocky/questions.yaml
  charts/incubator/blocky/templates/_blockyConfig.tpl
  charts/incubator/blocky/templates/_k8sgateway.tpl
Labels: install:ok, lint:ok, size/L, precommit:ok

#3875 chore(blocky): move blocky to enterprise
  charts/enterprise/blocky/.helmignore
  charts/enterprise/blocky/CHANGELOG.md
  charts/enterprise/blocky/Chart.yaml
  charts/enterprise/blocky/README.md
  charts/enterprise/blocky/ci/k8sgateway-values.yaml
  charts/enterprise/blocky/ci/standalone-values.yaml
  charts/enterprise/blocky/docs/installation-notes.md
  charts/enterprise/blocky/icon.png
  charts/enterprise/blocky/questions.yaml
  charts/enterprise/blocky/templates/_blockyConfig.tpl
  charts/enterprise/blocky/templates/_k8sgateway.tpl
  charts/enterprise/blocky/templates/_webui.tpl
  charts/enterprise/blocky/templates/common.yaml
  charts/enterprise/blocky/values.yaml
  charts/incubator/blocky/README.md
Labels: precommit:failed, lint:ok, size/M

#3879 chore(timetagger): add missing icon
  charts/incubator/timetagger/Chart.yaml
  charts/incubator/timetagger/icon.png
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3880 chore(traefik): regex redirect docs
  charts/stable/traefik/Chart.yaml
  charts/stable/traefik/docs/img/traefik-regex-redirect-app.png
  charts/stable/traefik/docs/img/traefik-regex-redirect-fields.png
  charts/stable/traefik/docs/redirect-regex-middleware.md
  charts/stable/traefik/docs/theme-park-middleware.md
Labels: size/S

#3882 chore(deps): update renovatebot/github-action action to v32.202.4
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3885 fix(blocky): set defaults to some durations
  charts/enterprise/blocky/Chart.yaml
  charts/enterprise/blocky/questions.yaml
Labels: size/XS
