Repository trueforge-org/truecharts, pull requests merged in 2022-12, with the labels that each got.

#5035 Update container image tccr.io/truecharts/storj-node to v1.68.2
  charts/stable/storj-node/Chart.yaml
  charts/stable/storj-node/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5032 Update container image tccr.io/truecharts/doplarr to v3.6.2
  charts/stable/doplarr/Chart.yaml
  charts/stable/doplarr/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5031 Update container image tccr.io/truecharts/lancache-monolithic to latest
  charts/stable/lancache-monolithic/Chart.yaml
  charts/stable/lancache-monolithic/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5034 Update container image tccr.io/truecharts/homepage to v0.5.3
  charts/stable/homepage/Chart.yaml
  charts/stable/homepage/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5030 Update container image tccr.io/truecharts/lancache-dns to latest
  charts/stable/lancache-dns/Chart.yaml
  charts/stable/lancache-dns/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5033 Update container image tccr.io/truecharts/home-assistant to v2022.11.5
  charts/stable/home-assistant/Chart.yaml
  charts/stable/home-assistant/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5039 Update container image tccr.io/truecharts/ghost to v5.24.2
  charts/incubator/ghost/Chart.yaml
  charts/incubator/ghost/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5041 Update container image tccr.io/truecharts/sickchill to 2022.10.13
  charts/stable/sickchill/Chart.yaml
  charts/stable/sickchill/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5042 Update container image tccr.io/truecharts/jdownloader-2 to v22.11.2
  charts/stable/jdownloader2/Chart.yaml
  charts/stable/jdownloader2/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5043 Update container image tccr.io/truecharts/strapi to v4.5.3
  charts/stable/strapi/Chart.yaml
  charts/stable/strapi/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5044 Update container image tccr.io/truecharts/crafty-4 to v4.0.18
  charts/stable/crafty-4/Chart.yaml
  charts/stable/crafty-4/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5046 fix(ci): fix changelog path
  .github/scripts/build-catalog.sh
Labels: size/XS

#5038 Update container image tccr.io/truecharts/obs-ndi to latest
  charts/incubator/obs-ndi/Chart.yaml
  charts/incubator/obs-ndi/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#5050 chore(deps): update container image tccr.io/truecharts/synclounge to 5.2.5
  charts/stable/synclounge/Chart.yaml
  charts/stable/synclounge/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5047 chore(deps): update container image tccr.io/truecharts/plexripper to latest
  charts/incubator/plexripper/Chart.yaml
  charts/incubator/plexripper/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5049 chore(deps): update container image tccr.io/truecharts/raneto to latest
  charts/incubator/raneto/Chart.yaml
  charts/incubator/raneto/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5048 chore(deps): update container image tccr.io/truecharts/pyload-ng to latest
  charts/incubator/pyload-ng/Chart.yaml
  charts/incubator/pyload-ng/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5051 fix(ci): don't delete website repo too early
  .github/workflows/charts-release.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#5058 fix(ci): no need to `cd -`
  .github/workflows/charts-release.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#5055 chore(deps): update container image tccr.io/truecharts/cloudflared to v2022.11.1
  charts/stable/cloudflared/Chart.yaml
  charts/stable/cloudflared/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5052 chore(deps): update container image tccr.io/truecharts/beets to v1.6.0
  charts/stable/beets/Chart.yaml
  charts/stable/beets/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5057 chore(deps): update container image tccr.io/truecharts/esphome to v2022.11.4
  charts/stable/esphome/Chart.yaml
  charts/stable/esphome/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5053 chore(deps): update container image tccr.io/truecharts/grocy to 3.3.2
  charts/stable/grocy/Chart.yaml
  charts/stable/grocy/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5056 chore(deps): update container image tccr.io/truecharts/czkawka to v22.11.2
  charts/stable/czkawka/Chart.yaml
  charts/stable/czkawka/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5040 feat(channels-dvr) Add TV Everywhere image option
  charts/incubator/channels-dvr/Chart.yaml
  charts/incubator/channels-dvr/ci/basic-values.yaml
  charts/incubator/channels-dvr/ci/tve-values.yaml
  charts/incubator/channels-dvr/questions.yaml
  charts/incubator/channels-dvr/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#5061 chore(deps): update container image tccr.io/truecharts/archiveteam-warrior to latest
  charts/incubator/archiveteam-warrior/Chart.yaml
  charts/incubator/archiveteam-warrior/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5063 chore(deps): update container image tccr.io/truecharts/freshrss to 1.20.1
  charts/stable/freshrss/Chart.yaml
  charts/stable/freshrss/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5068 fix(libremdb) axios settings fixes
  charts/incubator/libremdb/Chart.yaml
  charts/incubator/libremdb/questions.yaml
  charts/incubator/libremdb/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#5062 chore(deps): update container image tccr.io/truecharts/backuppc to latest
  charts/incubator/backuppc/Chart.yaml
  charts/incubator/backuppc/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5066 chore(deps): update container image tccr.io/truecharts/homer to v22.11.2
  charts/stable/homer/Chart.yaml
  charts/stable/homer/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5067 chore(deps): update container image tccr.io/truecharts/prometheus to v2.40.5
  charts/stable/prometheus/Chart.yaml
  charts/stable/prometheus/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5064 chore(deps): update container image tccr.io/truecharts/appsmith to v1.8.11
  charts/incubator/appsmith/Chart.yaml
  charts/incubator/appsmith/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5071 chore(deps): update container image tccr.io/truecharts/czkawka to v22.12.1
  charts/stable/czkawka/Chart.yaml
  charts/stable/czkawka/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5072 chore(deps): update container image tccr.io/truecharts/jdownloader-2 to v22.12.1
  charts/stable/jdownloader2/Chart.yaml
  charts/stable/jdownloader2/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5070 chore(deps): update container image tccr.io/truecharts/artifactory-oss to v7.47.10
  charts/incubator/artifactory-oss/Chart.yaml
  charts/incubator/artifactory-oss/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5073 chore(deps): update container image tccr.io/truecharts/nocodb to v0.100.1
  charts/stable/nocodb/Chart.yaml
  charts/stable/nocodb/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5054 chore(deps): update github/codeql-action digest to b2a92eb
  .github/workflows/general.security-scan.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#5060 chore(deps): update renovatebot/github-action action to v34.44.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#5069 chore(deps): update container image tccr.io/truecharts/filezilla to 3.59.0
  charts/stable/filezilla/Chart.yaml
  charts/stable/filezilla/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#5036 fix(discordgsm) activity type | Whitelist Guilds
  charts/incubator/discordgsm/Chart.yaml
  charts/incubator/discordgsm/docs/installation_notes.md
  charts/incubator/discordgsm/questions.yaml
  charts/incubator/discordgsm/templates/_secret.tpl
  charts/incubator/discordgsm/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#5074 chore(deps): update container image tccr.io/truecharts/ombi to v4.33.0
  charts/stable/ombi/Chart.yaml
  charts/stable/ombi/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5077 chore(deps): update container image tccr.io/truecharts/tinymediamanager to v4.3.7
  charts/stable/tinymediamanager/Chart.yaml
  charts/stable/tinymediamanager/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5078 chore(deps): update container image tccr.io/truecharts/trilium-notes to v0.57.2
  charts/stable/trilium-notes/Chart.yaml
  charts/stable/trilium-notes/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5076 chore(deps): update container image tccr.io/truecharts/redmine to v5.0.4
  charts/stable/redmine/Chart.yaml
  charts/stable/redmine/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5081 chore(deps): update container image tccr.io/truecharts/zigbee2mqtt to v1.28.4
  charts/stable/zigbee2mqtt/Chart.yaml
  charts/stable/zigbee2mqtt/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5080 chore(deps): update container image tccr.io/truecharts/qinglong to v2.15.2
  charts/stable/qinglong/Chart.yaml
  charts/stable/qinglong/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5082 chore(deps): update container image tccr.io/truecharts/audiobookshelf to v2.2.8
  charts/stable/audiobookshelf/Chart.yaml
  charts/stable/audiobookshelf/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5084 chore(deps): update container image tccr.io/truecharts/grafana to v9.3.1
  charts/stable/grafana/Chart.yaml
  charts/stable/grafana/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5083 chore(deps): update container image tccr.io/truecharts/domoticz to v2022.2.20221201
  charts/stable/domoticz/Chart.yaml
  charts/stable/domoticz/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5085 chore(deps): update container image tccr.io/truecharts/nocodb to v0.100.2
  charts/stable/nocodb/Chart.yaml
  charts/stable/nocodb/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5086 chore(deps): update container image tccr.io/truecharts/paperless-ng to v1.10.1
  charts/stable/paperless-ng/Chart.yaml
  charts/stable/paperless-ng/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5087 Update container image tccr.io/truecharts/factorio to vstable
  charts/incubator/factorio/Chart.yaml
  charts/incubator/factorio/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5089 Update container image tccr.io/truecharts/twonky-server to latest
  charts/incubator/twonky-server/Chart.yaml
  charts/incubator/twonky-server/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5088 Update container image tccr.io/truecharts/snapdrop to latest
  charts/stable/snapdrop/Chart.yaml
  charts/stable/snapdrop/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5091 Update container image tccr.io/truecharts/clickhouse to v22.11.2.30
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/clickhouse/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5093 Update container image tccr.io/truecharts/yacreaderlibraryserver to latest
  charts/incubator/yacreaderlibraryserver/Chart.yaml
  charts/incubator/yacreaderlibraryserver/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5098 Update container image tccr.io/truecharts/flexget to v3.5.6
  charts/stable/flexget/Chart.yaml
  charts/stable/flexget/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5096 Update container image tccr.io/truecharts/authentik-ldap to v2022.11.2
  charts/stable/authentik/Chart.yaml
  charts/stable/authentik/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5095 Update container image tccr.io/truecharts/authentik to v2022.11.2
  charts/stable/authentik/Chart.yaml
  charts/stable/authentik/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5100 Update container image tccr.io/truecharts/trilium-notes to v0.57.3
  charts/stable/trilium-notes/Chart.yaml
  charts/stable/trilium-notes/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5099 Update container image tccr.io/truecharts/grist to v1.0.5
  charts/stable/grist/Chart.yaml
  charts/stable/grist/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5102 Update container image tccr.io/truecharts/misskey to v12.119.1
  charts/incubator/misskey/Chart.yaml
  charts/incubator/misskey/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5101 Update container image tccr.io/truecharts/authentik-ldap to v2022.11.3
  charts/stable/authentik/Chart.yaml
  charts/stable/authentik/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5108 Update container image tccr.io/truecharts/minio-console to v0.22.0
  charts/stable/minio-console/Chart.yaml
  charts/stable/minio-console/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5104 Update container image tccr.io/truecharts/chromium to latest
  charts/incubator/chromium/Chart.yaml
  charts/incubator/chromium/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5107 Update container image tccr.io/truecharts/gotify-server to v2.2.0
  charts/stable/gotify/Chart.yaml
  charts/stable/gotify/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5105 Update container image tccr.io/truecharts/misskey to v12.119.2
  charts/incubator/misskey/Chart.yaml
  charts/incubator/misskey/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5106 Update container image tccr.io/truecharts/ghost to v5.25.0
  charts/incubator/ghost/Chart.yaml
  charts/incubator/ghost/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5110 Update container image tccr.io/truecharts/xenorchestra to v5.107.1
  charts/stable/xen-orchestra/Chart.yaml
  charts/stable/xen-orchestra/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5109 Update container image tccr.io/truecharts/n8n to v0.205.0
  charts/stable/n8n/Chart.yaml
  charts/stable/n8n/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5111 Update container image tccr.io/truecharts/apprise-api to latest
  charts/incubator/apprise-api/Chart.yaml
  charts/incubator/apprise-api/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5075 Update renovatebot/github-action action to v34.48.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#5114 Update container image tccr.io/truecharts/shlink-web-client to v3.8.0
  charts/stable/shlink-web-client/Chart.yaml
  charts/stable/shlink-web-client/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5112 Update container image tccr.io/truecharts/medusa to 1.0.9
  charts/stable/medusa/Chart.yaml
  charts/stable/medusa/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5113 Update container image tccr.io/truecharts/mstream to v5.11.4
  charts/stable/mstream/Chart.yaml
  charts/stable/mstream/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5115 Update container image tccr.io/truecharts/recyclarr to v3.0.0
  charts/stable/recyclarr/Chart.yaml
  charts/stable/recyclarr/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/major

#5117 Update container image tccr.io/truecharts/authentik to v2022.11.3
  charts/stable/authentik/Chart.yaml
  charts/stable/authentik/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5118 Update renovatebot/github-action action to v34.48.3
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#5119 Update container image tccr.io/truecharts/prometheus to 2.40.5
  charts/stable/prometheus/Chart.yaml
  charts/stable/prometheus/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5124 Update container image tccr.io/truecharts/grafana to 9.3.1
  charts/stable/grafana/Chart.yaml
  charts/stable/grafana/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5126 Update container image tccr.io/truecharts/qbitmanage to v3.4.0
  charts/stable/qbitmanage/Chart.yaml
  charts/stable/qbitmanage/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5125 Update container image tccr.io/truecharts/paperless-ng to v1.10.2
  charts/stable/paperless-ng/Chart.yaml
  charts/stable/paperless-ng/values.yaml
Labels: size/XS, automerge, update/docker/general/non-major

#5128 Update container image tccr.io/truecharts/fluidd to v1.22.0
  charts/stable/fluidd/Chart.yaml
  charts/stable/fluidd/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5127 Update container image tccr.io/truecharts/bazarr to v1.1.3
  charts/stable/bazarr/Chart.yaml
  charts/stable/bazarr/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5122 feat(ubuntu-xrdp): Fix port + reorder values.yaml
  charts/incubator/ubuntu-xrdp/Chart.yaml
  charts/incubator/ubuntu-xrdp/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#5121 feat(debian-bullseye): Fix main port / order values better
  charts/incubator/debian-bullseye/Chart.yaml
  charts/incubator/debian-bullseye/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#5092 feat(Splunk): Change to upstream *Breaking change*
  charts/incubator/splunk/Chart.yaml
  charts/incubator/splunk/questions.yaml
  charts/incubator/splunk/templates/_config.tpl
  charts/incubator/splunk/templates/common.yaml
  charts/incubator/splunk/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#5129 Update renovatebot/github-action action to v34.48.4
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#5132 chore(deps): update container image tccr.io/truecharts/booksonic-air to v2201.1.0
  charts/stable/booksonic-air/Chart.yaml
  charts/stable/booksonic-air/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5133 chore(deps): update container image tccr.io/truecharts/kdenlive to latest
  charts/incubator/kdenlive/Chart.yaml
  charts/incubator/kdenlive/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5131 chore(deps): update container image tccr.io/truecharts/babybuddy to 1.13.2
  charts/stable/babybuddy/Chart.yaml
  charts/stable/babybuddy/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5137 chore(deps): update container image tccr.io/truecharts/ddns-go to v4.2.2
  charts/stable/ddns-go/Chart.yaml
  charts/stable/ddns-go/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5138 chore(deps): update container image tccr.io/truecharts/deconz to v2.19.03
  charts/stable/deconz/Chart.yaml
  charts/stable/deconz/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5139 Qbit Doc Update VPN Section
  charts/stable/qbittorrent/Chart.yaml
  charts/stable/qbittorrent/docs/installation.md
Labels: size/S, install:ok, lint:ok, precommit:ok

#5141 chore(deps): update container image tccr.io/truecharts/wifi-card to latest
  charts/incubator/wifi-card/Chart.yaml
  charts/incubator/wifi-card/values.yaml
Labels: size/XS, automerge, update/docker/general/non-major

#5140 chore(deps): update container image tccr.io/truecharts/deconz to 2.19.03
  charts/stable/deconz/Chart.yaml
  charts/stable/deconz/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#4764 feat(Wordpress): Add Wordpress
  charts/incubator/wordpress/.helmignore
  charts/incubator/wordpress/Chart.yaml
  charts/incubator/wordpress/README.md
  charts/incubator/wordpress/icon.png
  charts/incubator/wordpress/questions.yaml
  charts/incubator/wordpress/templates/_env.tpl
  charts/incubator/wordpress/templates/common.yaml
  charts/incubator/wordpress/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#5134 chore(deps): update container image tccr.io/truecharts/rdesktop to latest
  charts/incubator/rdesktop/Chart.yaml
  charts/incubator/rdesktop/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#5130 chore(deps): update container image tccr.io/truecharts/acestream to latest
  charts/incubator/acestream/Chart.yaml
  charts/incubator/acestream/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#4666 fix(ps3netsrv) code cleanup, perms, persistence.
  charts/incubator/ps3netsrv/Chart.yaml
  charts/incubator/ps3netsrv/questions.yaml
  charts/incubator/ps3netsrv/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#5146 chore(deps): update container image tccr.io/truecharts/homepage to v0.5.4
  charts/stable/homepage/Chart.yaml
  charts/stable/homepage/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5147 chore(deps): update container image tccr.io/truecharts/netdata to v1.37.1
  charts/stable/netdata/Chart.yaml
  charts/stable/netdata/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5145 chore(deps): update container image tccr.io/truecharts/xwiki to 14.10.0-postgres
  charts/stable/xwiki/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#5150 feat(wordpress): Add user to configmap
  charts/incubator/wordpress/Chart.yaml
  charts/incubator/wordpress/templates/_env.tpl
Labels: size/XS, install:ok, lint:ok, precommit:ok

#5151 chore(deps): update container image tccr.io/truecharts/docker-hub-rss to latest
  charts/incubator/docker-hub-rss/Chart.yaml
  charts/incubator/docker-hub-rss/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5153 chore(deps): update container image tccr.io/truecharts/zabbix-agent2 to v6.2.6
  charts/incubator/zabbix/Chart.yaml
  charts/incubator/zabbix/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5155 chore(deps): update container image tccr.io/truecharts/zabbix-server to v6.2.6
  charts/incubator/zabbix/Chart.yaml
  charts/incubator/zabbix/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5156 chore(deps): update container image tccr.io/truecharts/zabbix-snmptraps to v6.2.6
  charts/incubator/zabbix/Chart.yaml
  charts/incubator/zabbix/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5148 chore(deps): update renovatebot/github-action action to v34.49.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#5090 chore(deps): update container image plausible/analytics to v1.5.1
  charts/incubator/plausible/Chart.yaml
  charts/incubator/plausible/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#5161 feat(Wordpress): Fix quotes
  charts/incubator/wordpress/Chart.yaml
  charts/incubator/wordpress/templates/_env.tpl
Labels: size/XS, install:ok, lint:ok, precommit:ok

#5164 fix(frigate): fix typos
  charts/incubator/frigate/Chart.yaml
  charts/incubator/frigate/templates/_configmap.tpl
Labels: size/XS, install:ok, lint:ok, precommit:ok

#5169 chore(deps): update container image tccr.io/truecharts/alist to v3.6.0
  charts/stable/alist/Chart.yaml
  charts/stable/alist/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5170 chore(deps): update container image tccr.io/truecharts/code-server to v4.9.0
  charts/stable/code-server/Chart.yaml
  charts/stable/code-server/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5172 chore(deps): update container image tccr.io/truecharts/unifi to v7.3.76
  charts/stable/unifi/Chart.yaml
  charts/stable/unifi/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5166 chore(deps): update container image tccr.io/truecharts/redmine to 5.0.4
  charts/stable/redmine/Chart.yaml
  charts/stable/redmine/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5171 chore(deps): update container image tccr.io/truecharts/synapse to v1.73.0
  charts/stable/synapse/Chart.yaml
  charts/stable/synapse/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5167 Update Helm chart common to v11.0.5
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/promtail/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
  charts/dependency/subchart/Chart.yaml
Labels: size/S, lint:ok, precommit:ok

#5177 chore(deps): update container image tccr.io/truecharts/wifi-card to latest
  charts/incubator/wifi-card/Chart.yaml
  charts/incubator/wifi-card/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5173 chore(deps): update container image tccr.io/truecharts/cloudbeaver to latest
  charts/incubator/cloudbeaver/Chart.yaml
  charts/incubator/cloudbeaver/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5176 chore(deps): update container image tccr.io/truecharts/unifi to 7.3.76
  charts/stable/unifi/Chart.yaml
  charts/stable/unifi/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5175 chore(deps): update container image tccr.io/truecharts/redmine to 5.0.4
  charts/stable/redmine/Chart.yaml
  charts/stable/redmine/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5178 chore(deps): update container image tccr.io/truecharts/wordpress to 6.1.1
  charts/incubator/wordpress/Chart.yaml
  charts/incubator/wordpress/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5174 chore(deps): update container image tccr.io/truecharts/ghost to 5.25.0
  charts/incubator/ghost/Chart.yaml
  charts/incubator/ghost/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5180 Update container image tccr.io/truecharts/artifactory-oss to v7.47.11
  charts/incubator/artifactory-oss/Chart.yaml
  charts/incubator/artifactory-oss/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#5182 Update container image tccr.io/truecharts/redmine to 5.0.4
  charts/stable/redmine/Chart.yaml
  charts/stable/redmine/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5181 Update renovatebot/github-action action to v34.50.1
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#5168 Update Helm chart common to v11.0.5
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#5183 Update Helm chart common to v11.0.6
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/promtail/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
  charts/dependency/subchart/Chart.yaml
Labels: size/S, lint:ok, precommit:ok, update/helm/dependency/non-major

#5186 chore(deps): update helm chart common to v11.0.6
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#5179 feat(wordpress): Add https + reverse-proxy
  charts/incubator/wordpress/Chart.yaml
  charts/incubator/wordpress/questions.yaml
  charts/incubator/wordpress/templates/_env.tpl
  charts/incubator/wordpress/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#5185 chore(deps): update container image tccr.io/truecharts/minio-console to v0.22.1
  charts/stable/minio-console/Chart.yaml
  charts/stable/minio-console/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5184 chore(deps): update container image tccr.io/truecharts/ghost to v5.25.1
  charts/incubator/ghost/Chart.yaml
  charts/incubator/ghost/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#5188 chore(deps): update container image tccr.io/truecharts/nginx to 1.23.2
  charts/stable/inventree/Chart.yaml
  charts/stable/inventree/values.yaml
  charts/stable/recipes/Chart.yaml
  charts/stable/recipes/values.yaml
  charts/stable/vikunja/Chart.yaml
  charts/stable/vikunja/values.yaml
  charts/stable/wger/Chart.yaml
  charts/stable/wger/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#5190 chore(deps): update container image tccr.io/truecharts/satisfactory to v1.3.4
  charts/stable/satisfactory/Chart.yaml
  charts/stable/satisfactory/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5191 chore(deps): update container image tccr.io/truecharts/shlink-web-client to v3.8.1
  charts/stable/shlink-web-client/Chart.yaml
  charts/stable/shlink-web-client/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5192 chore(deps): update container image tccr.io/truecharts/kms to vminimal
  charts/stable/kms/Chart.yaml
  charts/stable/kms/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5193 chore(deps): update container image tccr.io/truecharts/adguard-home to v0.107.20
  charts/stable/adguard-home/Chart.yaml
  charts/stable/adguard-home/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5194 chore(deps): update container image tccr.io/truecharts/n8n to v0.206.1
  charts/stable/n8n/Chart.yaml
  charts/stable/n8n/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5196 fix(frigate): render parent max_frames only when at least one child has value
  charts/incubator/frigate/Chart.yaml
  charts/incubator/frigate/templates/_configmap.tpl
Labels: size/XS

#5199 chore(deps): update container image tccr.io/truecharts/bazarr to 1.1.3
  charts/stable/bazarr/Chart.yaml
  charts/stable/bazarr/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5202 chore(deps): update container image tccr.io/truecharts/satisfactory to v1.4.1
  charts/stable/satisfactory/Chart.yaml
  charts/stable/satisfactory/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5201 chore(deps): update container image tccr.io/truecharts/home-assistant to v2022.12.0
  charts/stable/home-assistant/Chart.yaml
  charts/stable/home-assistant/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5204 fix(frigate): quote all floats in values.yaml. because questions.yaml…
  charts/incubator/frigate/Chart.yaml
  charts/incubator/frigate/values.yaml
Labels: size/XS

#5198 chore(deps): update renovatebot/github-action action to v34.51.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#5206 chore(deps): update container image tccr.io/truecharts/impostor-server to v1.7.3
  charts/stable/impostor-server/Chart.yaml
  charts/stable/impostor-server/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5209 chore(deps): update container image tccr.io/truecharts/freshrss to v1.20.2
  charts/stable/freshrss/Chart.yaml
  charts/stable/freshrss/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5212 chore(deps): update container image tccr.io/truecharts/sourcegraph to v4.2.1
  charts/incubator/sourcegraph/Chart.yaml
  charts/incubator/sourcegraph/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5211 chore(deps): update container image tccr.io/truecharts/ispy-agent-dvr to v4.4.3.0
  charts/stable/ispy-agent-dvr/Chart.yaml
  charts/stable/ispy-agent-dvr/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5208 chore(deps): update container image tccr.io/truecharts/authelia to v4.37.3
  charts/stable/authelia/Chart.yaml
  charts/stable/authelia/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major
