Repository trueforge-org/truecharts, pull requests merged in 2022-03, with the labels that each got.

#2005 fix(common): fix TZ being wrongly defined in common and remove its references from some remaining Apps
  charts/library/common/Chart.yaml
  charts/library/common/templates/lib/controller/_container.tpl
  charts/library/common/values.yaml
  charts/stable/appdaemon/values.yaml
  charts/stable/calibre-web/values.yaml
  charts/stable/custom-app/ci/test-values.yaml
  charts/stable/firefox-syncserver/values.yaml
  charts/stable/gotify/values.yaml
  charts/stable/heimdall/values.yaml
  charts/stable/tvheadend/values.yaml
  tests/library/common/container_spec.rb
Labels: bug

#2034 add(homebridge): Add homebridge app
  charts/incubator/homebridge/.helmignore
  charts/incubator/homebridge/Chart.yaml
  charts/incubator/homebridge/questions.yaml
  charts/incubator/homebridge/templates/common.yaml
  charts/incubator/homebridge/values.yaml
  docs/apps/app-requests.md
  docs/manual/default-ports.md
Labels: New App Request

#2039 feat(common): allow more PUID/UID types to sync with GUID/GID
  charts/library/common/Chart.yaml
  charts/library/common/templates/lib/controller/_container.tpl
  tests/library/common/container_spec.rb
Labels: enhancement

#2038 add(openHAB): add openHAB
  charts/incubator/openhab/.helmignore
  charts/incubator/openhab/Chart.yaml
  charts/incubator/openhab/questions.yaml
  charts/incubator/openhab/templates/_configmap.tpl
  charts/incubator/openhab/templates/common.yaml
  charts/incubator/openhab/values.yaml
  docs/manual/default-ports.md
Labels: New App Request

#2363 chore(wekan): use other port and fix docs
  charts/stable/wekan/Chart.yaml
  charts/stable/wekan/questions.yaml
  charts/stable/wekan/values.yaml
  docs/_static/img/appicons/meshcentral.png
  docs/manual/default-ports.md
Labels: size/XL, install:ok, lint:ok, precommit:ok

#2364 fix(mosdns): Remove portal
  charts/incubator/mosdns/Chart.yaml
  charts/incubator/mosdns/questions.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#2331 feat(ipfs): Use official image BREAKING CHANGE
  charts/stable/ipfs/Chart.yaml
  charts/stable/ipfs/questions.yaml
  charts/stable/ipfs/templates/common.yaml
  charts/stable/ipfs/values.yaml
  docs/apps/stable/ipfs/notes.md
  docs/manual/default-ports.md
Labels: install:ok, lint:ok, size/L, precommit:ok

#2356 fix(gitea): set user and group to 1000
  charts/stable/gitea/Chart.yaml
  charts/stable/gitea/questions.yaml
  charts/stable/gitea/values.yaml
Labels: bug, size/XS, install:ok, lint:ok, precommit:ok
