Repository trueforge-org/truecharts, pull requests merged in 2022-05, with the labels that each got.

#2593 fix(vaultwarden): correct ws service definition
  charts/stable/vaultwarden/Chart.yaml
  charts/stable/vaultwarden/templates/common.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2591 fix(meshcentral): fix config file generation
  charts/incubator/meshcentral/Chart.yaml
  charts/incubator/meshcentral/questions.yaml
  charts/incubator/meshcentral/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#2582 [DNM] Synapse Matrix Fixes
  charts/stable/synapse/Chart.yaml
  charts/stable/synapse/questions.yaml
  charts/stable/synapse/templates/_configmap.tpl
  charts/stable/synapse/templates/_secret.tpl
Labels: install:ok, lint:ok, size/M, precommit:ok

#2595 feat(netdata): add netdata
  charts/incubator/netdata/Chart.yaml
  charts/incubator/netdata/questions.yaml
  charts/incubator/netdata/templates/common.yaml
  charts/incubator/netdata/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#2596 fix(netdata): make host mounts readonly
  charts/incubator/netdata/Chart.yaml
  charts/incubator/netdata/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#2600 chore(netdata): add pod/namespace/node env's
  charts/incubator/netdata/Chart.yaml
  charts/incubator/netdata/questions.yaml
  charts/incubator/netdata/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#2601 chore(netdata): use configmap for readability and extendability
  charts/incubator/netdata/Chart.yaml
  charts/incubator/netdata/templates/common.yaml
  charts/incubator/netdata/templates/configmap.yaml
  charts/incubator/netdata/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#2602 fix(synapse): fix loadCustomConfig
  charts/stable/synapse/Chart.yaml
  charts/stable/synapse/templates/_configmap.tpl
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2604 feat(Traefik) add support for forwarded headers
  charts/core/traefik/Chart.yaml
  charts/core/traefik/questions.yaml
  charts/core/traefik/templates/_args.tpl
  charts/core/traefik/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#2613 feat(tdarr): spawn internal node and some cleanup on tdarr-node
  charts/incubator/tdarr-node/Chart.yaml
  charts/incubator/tdarr-node/questions.yaml
  charts/incubator/tdarr-node/values.yaml
  charts/incubator/tdarr/Chart.yaml
  charts/incubator/tdarr/questions.yaml
  charts/incubator/tdarr/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#2609 feat(traefik): Add support for JSON format logs
  charts/core/traefik/Chart.yaml
  charts/core/traefik/questions.yaml
  charts/core/traefik/templates/_args.tpl
  charts/core/traefik/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#2614 feat(cups-server): add cups-server
  charts/incubator/cups-server/Chart.yaml
  charts/incubator/cups-server/questions.yaml
  charts/incubator/cups-server/templates/common.yaml
  charts/incubator/cups-server/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#2615 feat(tdarr(-node)): Move to stable and cleanup
  charts/stable/tdarr-node/.helmignore
  charts/stable/tdarr-node/CHANGELOG.md
  charts/stable/tdarr-node/CONFIG.md
  charts/stable/tdarr-node/Chart.yaml
  charts/stable/tdarr-node/README.md
  charts/stable/tdarr-node/helm-values.md
  charts/stable/tdarr-node/questions.yaml
  charts/stable/tdarr-node/security.md
  charts/stable/tdarr-node/templates/common.yaml
  charts/stable/tdarr-node/values.yaml
  charts/stable/tdarr/.helmignore
  charts/stable/tdarr/CHANGELOG.md
  charts/stable/tdarr/CONFIG.md
  charts/stable/tdarr/Chart.yaml
  charts/stable/tdarr/README.md
  charts/stable/tdarr/helm-values.md
  charts/stable/tdarr/questions.yaml
  charts/stable/tdarr/security.md
  charts/stable/tdarr/templates/common.yaml
  charts/stable/tdarr/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#2616 feat(adguard-home): add adguard-home
  charts/incubator/adguard-home/Chart.yaml
  charts/incubator/adguard-home/questions.yaml
  charts/incubator/adguard-home/templates/common.yaml
  charts/incubator/adguard-home/values.yaml
Labels: size/XL, install:ok, lint:ok, precommit:ok

#2603 feat(synapse) registration support
  charts/stable/synapse/Chart.yaml
  charts/stable/synapse/questions.yaml
  charts/stable/synapse/templates/_configmap.tpl
Labels: install:ok, lint:ok, size/M, precommit:ok

#2618 fix(inventree): re-add nginx
  charts/incubator/inventree/Chart.yaml
  charts/incubator/inventree/questions.yaml
  charts/incubator/inventree/templates/common.yaml
  charts/incubator/inventree/templates/configmap.yaml
  charts/incubator/inventree/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#2621 fix(rsshub): digest pin to latest
  charts/stable/rsshub/Chart.yaml
  charts/stable/rsshub/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2623 chore(adguard-home): expose data persistence
  charts/incubator/adguard-home/Chart.yaml
  charts/incubator/adguard-home/questions.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#2627 feat(mkvtoolnix): add mkvtoolnix
  charts/incubator/mkvtoolnix/Chart.yaml
  charts/incubator/mkvtoolnix/questions.yaml
  charts/incubator/mkvtoolnix/templates/common.yaml
  charts/incubator/mkvtoolnix/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#2630 feat(kopia): add kopia
  charts/incubator/kopia/Chart.yaml
  charts/incubator/kopia/questions.yaml
  charts/incubator/kopia/templates/common.yaml
  charts/incubator/kopia/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#2631 chore(ghost): move to incubator, because upstream does not support mariadb
  charts/incubator/ghost/CHANGELOG.md
  charts/incubator/ghost/CONFIG.md
  charts/incubator/ghost/Chart.yaml
  charts/incubator/ghost/README.md
  charts/incubator/ghost/helm-values.md
  charts/incubator/ghost/questions.yaml
  charts/incubator/ghost/security.md
  charts/incubator/ghost/templates/common.yaml
  charts/incubator/ghost/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2637 chore(satisfactory): Rename s`t`atisfacoty to satisfactory
  charts/games/satisfactory/.helmignore
  charts/games/satisfactory/CHANGELOG.md
  charts/games/satisfactory/CONFIG.md
  charts/games/satisfactory/Chart.yaml
  charts/games/satisfactory/README.md
  charts/games/satisfactory/helm-values.md
  charts/games/satisfactory/questions.yaml
  charts/games/satisfactory/security.md
  charts/games/satisfactory/templates/common.yaml
  charts/games/satisfactory/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2636 feat(mkvtoolnix): move to stable
  charts/incubator/authentik/values.yaml
  charts/incubator/baserow/values.yaml
  charts/incubator/cups-server/values.yaml
  charts/incubator/inventree/values.yaml
  charts/incubator/netdata/values.yaml
  charts/stable/mkvtoolnix/CHANGELOG.md
  charts/stable/mkvtoolnix/Chart.yaml
  charts/stable/mkvtoolnix/README.md
  charts/stable/mkvtoolnix/questions.yaml
  charts/stable/mkvtoolnix/security.md
  charts/stable/mkvtoolnix/templates/common.yaml
  charts/stable/mkvtoolnix/values.yaml
Labels: size/S, lint:ok, precommit:ok

#2638 Hotfix/synapse 3pid template
  charts/stable/synapse/Chart.yaml
  charts/stable/synapse/templates/_configmap.tpl
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2635 fix (trafik) IngressClass and namespace configuration
  charts/core/traefik/templates/_args.tpl
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2643 chore(deepstack): add threadcount gui option
  charts/stable/deepstack/Chart.yaml
  charts/stable/deepstack/questions.yaml
  charts/stable/deepstack/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2646 Hotfix/synapse requires 3pid
  charts/stable/synapse/Chart.yaml
  charts/stable/synapse/templates/_configmap.tpl
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2669 fix(firefox-syncserver): fix to use PostgreSQL instead of SQLite
  charts/stable/firefox-syncserver/Chart.yaml
  charts/stable/firefox-syncserver/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2685 fix(traefik) Fix null pointer error, move ingressClass quote
  charts/core/traefik/Chart.yaml
  charts/core/traefik/questions.yaml
  charts/core/traefik/templates/_args.tpl
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2442 feat(fancyindex): Add Fancyindex
  charts/incubator/fancyindex/Chart.yaml
  charts/incubator/fancyindex/questions.yaml
  charts/incubator/fancyindex/templates/common.yaml
  charts/incubator/fancyindex/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#2709 Update Koel Docker URL
  charts/stable/koel/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2716 fix(tt-rss): Add persistence
  charts/stable/tt-rss/Chart.yaml
  charts/stable/tt-rss/questions.yaml
  charts/stable/tt-rss/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#2705 feat(mattermost): Add mattermost
  charts/incubator/mattermost/.helmignore
  charts/incubator/mattermost/Chart.yaml
  charts/incubator/mattermost/questions.yaml
  charts/incubator/mattermost/templates/common.yaml
  charts/incubator/mattermost/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#2719 fix(mattermost): Fix URL
  charts/incubator/mattermost/Chart.yaml
  charts/incubator/mattermost/questions.yaml
  charts/incubator/mattermost/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2738 fix(ipfs): missing sections of UI
  charts/stable/ipfs/Chart.yaml
  charts/stable/ipfs/questions.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2739 fix(ipfs): remove multiple persistence sections
  charts/stable/ipfs/Chart.yaml
  charts/stable/ipfs/questions.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#2752 fix(outline): set default redisuser
  charts/stable/outline/Chart.yaml
  charts/stable/outline/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2764 fix(traefik): set trustedIPs to string
  charts/core/traefik/Chart.yaml
  charts/core/traefik/questions.yaml
  charts/stable/kms/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2773 fix(n8n): duplicate security variable
  charts/stable/n8n/Chart.yaml
  charts/stable/n8n/questions.yaml
  charts/stable/n8n/templates/_configmap.tpl
  charts/stable/n8n/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#2779 feat(homarr): add homarr
  charts/incubator/homarr/Chart.yaml
  charts/incubator/homarr/questions.yaml
  charts/incubator/homarr/templates/common.yaml
  charts/incubator/homarr/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#2781 feat(jellyseerr): add jellyseerr
  charts/incubator/jellyseerr/Chart.yaml
  charts/incubator/jellyseerr/questions.yaml
  charts/incubator/jellyseerr/templates/common.yaml
  charts/incubator/jellyseerr/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#2782 feat(fileflows): add fileflows
  charts/incubator/fileflows/Chart.yaml
  charts/incubator/fileflows/questions.yaml
  charts/incubator/fileflows/templates/common.yaml
  charts/incubator/fileflows/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#2780 feat(commento-plusplus): Add commento-plusplus
  charts/incubator/commento-plusplus/Chart.yaml
  charts/incubator/commento-plusplus/questions.yaml
  charts/incubator/commento-plusplus/templates/common.yaml
  charts/incubator/commento-plusplus/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#2783 feat(meshroom): add meshroom
  charts/incubator/meshroom/Chart.yaml
  charts/incubator/meshroom/questions.yaml
  charts/incubator/meshroom/templates/common.yaml
  charts/incubator/meshroom/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#2784 feat(apps): move apps to stable
  charts/stable/baserow/CHANGELOG.md
  charts/stable/baserow/Chart.yaml
  charts/stable/baserow/README.md
  charts/stable/baserow/questions.yaml
  charts/stable/baserow/security.md
  charts/stable/baserow/templates/_secrets.tpl
  charts/stable/baserow/templates/common.yaml
  charts/stable/baserow/values.yaml
  charts/stable/kopia/CHANGELOG.md
  charts/stable/kopia/Chart.yaml
  charts/stable/kopia/README.md
  charts/stable/kopia/questions.yaml
  charts/stable/kopia/security.md
  charts/stable/kopia/templates/common.yaml
  charts/stable/kopia/values.yaml
  charts/stable/netdata/CHANGELOG.md
  charts/stable/netdata/Chart.yaml
  charts/stable/netdata/README.md
  charts/stable/netdata/questions.yaml
  charts/stable/netdata/security.md
  charts/stable/netdata/templates/common.yaml
  charts/stable/netdata/templates/configmap.yaml
  charts/stable/netdata/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2787 feat(inventree): move to stable
  charts/stable/clarkson/Chart.yaml
  charts/stable/clarkson/questions.yaml
  charts/stable/clarkson/values.yaml
  charts/stable/inventree/CHANGELOG.md
  charts/stable/inventree/Chart.yaml
  charts/stable/inventree/README.md
  charts/stable/inventree/questions.yaml
  charts/stable/inventree/security.md
  charts/stable/inventree/templates/_secrets.tpl
  charts/stable/inventree/templates/common.yaml
  charts/stable/inventree/templates/configmap.yaml
  charts/stable/inventree/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2798 feat(mattermost): Move mattermost to stable
  charts/stable/mattermost/.helmignore
  charts/stable/mattermost/CHANGELOG.md
  charts/stable/mattermost/Chart.yaml
  charts/stable/mattermost/README.md
  charts/stable/mattermost/questions.yaml
  charts/stable/mattermost/security.md
  charts/stable/mattermost/templates/common.yaml
  charts/stable/mattermost/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2801 chore(satisfactory): update image refs
  charts/games/satisfactory/Chart.yaml
  charts/games/satisfactory/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2800 feat(theme-park): Add theme-park
  charts/incubator/theme-park/Chart.yaml
  charts/incubator/theme-park/questions.yaml
  charts/incubator/theme-park/templates/common.yaml
  charts/incubator/theme-park/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok
