Repository trueforge-org/truecharts, pull requests merged in 2022-06, with the labels that each got.

#2814 fix(homarr): fix image link
  charts/stable/homarr/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2819 chore(zabbix): update image refs
  charts/incubator/zabbix-server/Chart.yaml
  charts/incubator/zabbix-server/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2829 fix(grist): re-enable redis
  charts/stable/grist/Chart.yaml
  charts/stable/grist/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#2843 fix(ddclient): set readOnlyRootFilesystem to false
  charts/stable/ddclient/Chart.yaml
  charts/stable/ddclient/questions.yaml
  charts/stable/ddclient/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2851 chore(apps): update icons ref
  charts/dependency/memcached/Chart.yaml
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/promtail/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/stable/spotweb/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2865 chore(qbittorrent): update image
  charts/stable/qbittorrent/Chart.yaml
  charts/stable/qbittorrent/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2869 fix(tests): upgrade k3s version for tests
  .github/workflows/charts-test.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2868 fix(trilium-notes): BREAKING CHANGE. Backup your data from 3.0.2 and reinstall
  charts/stable/trilium-notes/Chart.yaml
  charts/stable/trilium-notes/questions.yaml
  charts/stable/trilium-notes/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#2870 fix(trilium-notes): BREAKING CHANGE
  charts/stable/trilium-notes/Chart.yaml
  charts/stable/trilium-notes/questions.yaml
  charts/stable/trilium-notes/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2871 fix(loki): render loki.yaml correctly
  charts/stable/loki/Chart.yaml
  charts/stable/loki/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2867 feat(apps): add dashdot and jump
  charts/incubator/dashdot/Chart.yaml
  charts/incubator/dashdot/questions.yaml
  charts/incubator/dashdot/templates/common.yaml
  charts/incubator/dashdot/values.yaml
  charts/incubator/jump/Chart.yaml
  charts/incubator/jump/questions.yaml
  charts/incubator/jump/templates/common.yaml
  charts/incubator/jump/values.yaml
Labels: size/XL, install:ok, lint:ok, precommit:ok

#2894 chore(snipe-it): enable redis
  charts/stable/snipe-it/Chart.yaml
  charts/stable/snipe-it/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2897 fix(dashdot): add cap and memory mapping
  charts/incubator/dashdot/questions.yaml
  charts/incubator/dashdot/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#2895 fix(homer): run as non root
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/promtail/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/stable/homer/Chart.yaml
  charts/stable/homer/questions.yaml
  charts/stable/homer/values.yaml
  charts/stable/spotweb/Chart.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#2900 chore(dashdot): bump
  charts/incubator/dashdot/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2896 feat:(awesome-ttrss): Add awesome ttrss
  charts/incubator/awesome-ttrss/.helmignore
  charts/incubator/awesome-ttrss/Chart.yaml
  charts/incubator/awesome-ttrss/questions.yaml
  charts/incubator/awesome-ttrss/templates/common.yaml
  charts/incubator/awesome-ttrss/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#2901 fix(dashdot): run privileged
  charts/incubator/dashdot/Chart.yaml
  charts/incubator/dashdot/questions.yaml
  charts/incubator/dashdot/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#2888 fix(scrutiny): BREAKING CHANGE: Use official image due to LSIO deprecation
  charts/incubator/awesome-ttrss/Chart.yaml
  charts/stable/scrutiny/questions.yaml
  charts/stable/scrutiny/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#2907 feat(senseai-server): add senseai-server
  charts/incubator/senseai-server/Chart.yaml
  charts/incubator/senseai-server/questions.yaml
  charts/incubator/senseai-server/templates/common.yaml
  charts/incubator/senseai-server/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#2909 chore(senseai-server): cleanup
  charts/incubator/senseai-server/Chart.yaml
  charts/incubator/senseai-server/questions.yaml
  charts/incubator/senseai-server/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#2910 fix(awesome): Fix persistence
  charts/incubator/awesome-ttrss/Chart.yaml
  charts/incubator/awesome-ttrss/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2912 chore(apps): update image refs
  charts/incubator/awesome-ttrss/Chart.yaml
  charts/incubator/awesome-ttrss/values.yaml
  charts/incubator/dashdot/Chart.yaml
  charts/incubator/dashdot/values.yaml
  charts/incubator/jump/Chart.yaml
  charts/incubator/jump/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2915 chore(scrutiny): update image ref
  charts/incubator/senseai-server/Chart.yaml
  charts/incubator/senseai-server/values.yaml
  charts/stable/scrutiny/Chart.yaml
  charts/stable/scrutiny/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2938 chore(scrutiny): add COLLECTOR_HOST_ID env
  charts/stable/scrutiny/Chart.yaml
  charts/stable/scrutiny/questions.yaml
  charts/stable/scrutiny/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2942 feat(dashdot): move to stable
  charts/incubator/dashdot/values.yaml
  charts/stable/dashdot/CHANGELOG.md
  charts/stable/dashdot/Chart.yaml
  charts/stable/dashdot/README.md
  charts/stable/dashdot/questions.yaml
  charts/stable/dashdot/security.md
  charts/stable/dashdot/templates/common.yaml
  charts/stable/dashdot/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#2945 chore(kopia): update image ref
  charts/stable/kopia/values.yaml
Labels: size/XS, install:ok, lint:ok

#2911 feat(jitsi): Add jitsi
  charts/incubator/jitsi/.helmignore
  charts/incubator/jitsi/Chart.yaml
  charts/incubator/jitsi/questions.yaml
  charts/incubator/jitsi/templates/common.yaml
  charts/incubator/jitsi/values.yaml
Labels: size/XL, install:ok, lint:ok, precommit:ok

#2968 fix(vikunja, librephotos): revert previous fix for rediscreds and apply a new
  charts/stable/librephotos/Chart.yaml
  charts/stable/librephotos/templates/common.yaml
  charts/stable/vikunja/Chart.yaml
  charts/stable/vikunja/templates/common.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2962 fix(linkace): convert to string envs inside secretEnv
  charts/stable/linkace/Chart.yaml
  charts/stable/linkace/questions.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2975 feat(wger): add wger
  charts/incubator/wger/Chart.yaml
  charts/incubator/wger/questions.yaml
  charts/incubator/wger/templates/_secrets.tpl
  charts/incubator/wger/templates/common.yaml
  charts/incubator/wger/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#2978 feat(openspeedtest): Add OpenSpeedTest
  charts/incubator/openspeedtest/.helmignore
  charts/incubator/openspeedtest/CHANGELOG.md
  charts/incubator/openspeedtest/CONFIG.md
  charts/incubator/openspeedtest/Chart.yaml
  charts/incubator/openspeedtest/README.md
  charts/incubator/openspeedtest/helm-values.md
  charts/incubator/openspeedtest/questions.yaml
  charts/incubator/openspeedtest/security.md
  charts/incubator/openspeedtest/templates/common.yaml
  charts/incubator/openspeedtest/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#2986 miniflux: make questions ADMIN_PASSWORD private
  charts/stable/miniflux/Chart.yaml
  charts/stable/miniflux/questions.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2991 gitea: change questions.yaml admin password to private
  charts/stable/gitea/Chart.yaml
  charts/stable/gitea/questions.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2990 fix(openspeedtest): fix port conflict
  charts/incubator/openspeedtest/Chart.yaml
  charts/incubator/openspeedtest/questions.yaml
  charts/incubator/openspeedtest/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2992 chore(dashdot): add 2 env vars in gui
  charts/stable/dashdot/Chart.yaml
  charts/stable/dashdot/questions.yaml
  charts/stable/dashdot/values.yaml
Labels: size/XS

#2994 feat(openspeedtest): move to stable
  charts/stable/openspeedtest/.helmignore
  charts/stable/openspeedtest/CHANGELOG.md
  charts/stable/openspeedtest/CONFIG.md
  charts/stable/openspeedtest/Chart.yaml
  charts/stable/openspeedtest/README.md
  charts/stable/openspeedtest/helm-values.md
  charts/stable/openspeedtest/questions.yaml
  charts/stable/openspeedtest/security.md
  charts/stable/openspeedtest/templates/common.yaml
  charts/stable/openspeedtest/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2983 feat(custom-app): Add custom command UI
  .github/scripts/build-catalog.sh
  charts/stable/custom-app/Chart.yaml
  charts/stable/custom-app/questions.yaml
  templates/questions/controllerExpertCommamd.yaml
  tools/build-release.sh
Labels: size/S, install:ok, lint:ok, precommit:ok

#2971 feat(privatebin): Add PrivateBin to incubator
  charts/incubator/privatebin/Chart.yaml
  charts/incubator/privatebin/questions.yaml
  charts/incubator/privatebin/templates/_configmap.tpl
  charts/incubator/privatebin/templates/_secrets.tpl
  charts/incubator/privatebin/templates/common.yaml
  charts/incubator/privatebin/values.yaml
Labels: size/XL, install:ok, lint:ok, precommit:ok

#3001 fix(privatebin): fix errors
  charts/incubator/privatebin/Chart.yaml
  charts/incubator/privatebin/questions.yaml
  charts/incubator/privatebin/templates/_configmap.tpl
  charts/incubator/privatebin/templates/_secrets.tpl
Labels: size/S, install:ok, lint:ok, precommit:ok

#3000 feat(libreddit, youtubedl-material): add libreddit and youtubedl-material
  charts/incubator/libreddit/Chart.yaml
  charts/incubator/libreddit/questions.yaml
  charts/incubator/libreddit/templates/common.yaml
  charts/incubator/libreddit/values.yaml
  charts/incubator/youtubedl-material/Chart.yaml
  charts/incubator/youtubedl-material/questions.yaml
  charts/incubator/youtubedl-material/templates/common.yaml
  charts/incubator/youtubedl-material/values.yaml
Labels: size/XL, install:ok, lint:ok, precommit:ok

#3010 fix(wger): try some fixes
  charts/incubator/wger/Chart.yaml
  charts/incubator/wger/questions.yaml
  charts/incubator/wger/values.yaml
  charts/stable/dashdot/Chart.yaml
  charts/stable/dashdot/questions.yaml
  charts/stable/dashdot/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#3011 fix(wger): another fix
  charts/incubator/wger/Chart.yaml
  charts/incubator/wger/questions.yaml
  charts/incubator/wger/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2982 feat(wg-easy): Add WG-Easy Chart
  charts/incubator/wg-easy/Chart.yaml
  charts/incubator/wg-easy/questions.yaml
  charts/incubator/wg-easy/templates/common.yaml
  charts/incubator/wg-easy/values.yaml
Labels: enhancement, help wanted, install:ok, lint:ok, size/L, precommit:ok

#3013 chore(emulatorjs): add ingress on webui aswell
  charts/incubator/wger/Chart.yaml
  charts/incubator/wger/questions.yaml
  charts/stable/emulatorjs/Chart.yaml
  charts/stable/emulatorjs/questions.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#3014 chore(linkace): bump linkace
  charts/stable/emulatorjs/Chart.yaml
  charts/stable/emulatorjs/values.yaml
  charts/stable/linkace/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3019 fix(apps): change some common references to tc.common
  charts/dependency/promtail/Chart.yaml
  charts/dependency/promtail/templates/_servicemonitor.tpl
  charts/stable/grafana/Chart.yaml
  charts/stable/grafana/templates/prometheusrules.yaml
  charts/stable/grafana/templates/servicemonitor.yaml
  charts/stable/loki/Chart.yaml
  charts/stable/loki/values.yaml
  charts/stable/promcord/Chart.yaml
  charts/stable/promcord/templates/prometheusrules.yaml
  charts/stable/promcord/templates/servicemonitor.yaml
  charts/stable/speedtest-exporter/Chart.yaml
  charts/stable/speedtest-exporter/templates/prometheusrules.yaml
  charts/stable/speedtest-exporter/templates/servicemonitor.yaml
  charts/stable/unpoller/Chart.yaml
  charts/stable/unpoller/templates/prometheusrules.yaml
  charts/stable/unpoller/templates/servicemonitor.yaml
  charts/stable/uptimerobot-prometheus/Chart.yaml
  charts/stable/uptimerobot-prometheus/templates/prometheusrules.yaml
  charts/stable/uptimerobot-prometheus/templates/servicemonitor.yaml
Labels: lint:ok, size/M, precommit:ok
