Repository trueforge-org/truecharts, pull requests merged in 2022-07, with the labels that each got.

#3027 feat(wg-easy): move to stable and add env-vars
  charts/stable/wg-easy/CHANGELOG.md
  charts/stable/wg-easy/Chart.yaml
  charts/stable/wg-easy/README.md
  charts/stable/wg-easy/questions.yaml
  charts/stable/wg-easy/security.md
  charts/stable/wg-easy/templates/common.yaml
  charts/stable/wg-easy/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#3037 feat(cloudflareddns): Add CloudflareDDNS to incubator
  charts/incubator/cloudflareddns/Chart.yaml
  charts/incubator/cloudflareddns/questions.yaml
  charts/incubator/cloudflareddns/templates/common.yaml
  charts/incubator/cloudflareddns/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3039 fix(openspeedtest, libreddit): fix port conflicts with prometheus and…
  charts/stable/libreddit/CHANGELOG.md
  charts/stable/libreddit/Chart.yaml
  charts/stable/libreddit/README.md
  charts/stable/libreddit/questions.yaml
  charts/stable/libreddit/security.md
  charts/stable/libreddit/templates/common.yaml
  charts/stable/libreddit/values.yaml
  charts/stable/openspeedtest/Chart.yaml
  charts/stable/openspeedtest/questions.yaml
  charts/stable/openspeedtest/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3040 chore(apps): update image refs
  charts/incubator/privatebin/Chart.yaml
  charts/incubator/privatebin/values.yaml
  charts/incubator/youtubedl-material/Chart.yaml
  charts/incubator/youtubedl-material/values.yaml
  charts/stable/libreddit/Chart.yaml
  charts/stable/libreddit/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3029 feat(cloudflared): add cloudflared
  charts/incubator/cloudflared/Chart.yaml
  charts/incubator/cloudflared/ci/test-values.yaml
  charts/incubator/cloudflared/questions.yaml
  charts/incubator/cloudflared/templates/common.yaml
  charts/incubator/cloudflared/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3045 fix(audiobookshelf): add temp dir for .npm
  charts/stable/audiobookshelf/Chart.yaml
  charts/stable/audiobookshelf/questions.yaml
  charts/stable/audiobookshelf/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#3030 feat(radicale): add Radicale to incubator
  charts/incubator/radicale/Chart.yaml
  charts/incubator/radicale/questions.yaml
  charts/incubator/radicale/templates/_configmap.tpl
  charts/incubator/radicale/templates/_secret.tpl
  charts/incubator/radicale/templates/common.yaml
  charts/incubator/radicale/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3047 chore(cronjob): update to v1 from v1beta
  charts/incubator/authentik/Chart.yaml
  charts/incubator/authentik/templates/_cronjob.tpl
  charts/stable/clamav/Chart.yaml
  charts/stable/clamav/templates/_cronjob.tpl
Labels: size/XS

#3050 fix(linkace): set fsGroup to www-data (82)
  charts/stable/linkace/Chart.yaml
  charts/stable/linkace/questions.yaml
  charts/stable/linkace/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3051 fix(radicale): add missing `auth.type` Radicale setting
  charts/incubator/radicale/Chart.yaml
  charts/incubator/radicale/templates/_configmap.tpl
  charts/incubator/radicale/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3054 fix(Cloudflareddns): Fix CF_ZONES env var
  charts/incubator/cloudflareddns/Chart.yaml
  charts/incubator/cloudflareddns/questions.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3044 chore(renovate): remove dead trains and add regex versioning for photoprism
  .github/renovate.json5
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3063 fix(cloudflareddns): fix DETECTION_MODE
  charts/incubator/cloudflareddns/Chart.yaml
  charts/incubator/cloudflareddns/values.yaml
Labels: size/XS

#3067 feat(Czkawka): Add Czkawka app to Incubator attempt 2
  charts/incubator/czkawka/Chart.yaml
  charts/incubator/czkawka/questions.yaml
  charts/incubator/czkawka/templates/common.yaml
  charts/incubator/czkawka/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3069 fix(guacamole-client): adjust initcontainer with new image and fix typo in customCommand template
  charts/incubator/czkawka/Chart.yaml
  charts/incubator/czkawka/values.yaml
  charts/stable/custom-app/Chart.yaml
  charts/stable/guacamole-client/Chart.yaml
  charts/stable/guacamole-client/values.yaml
  templates/questions/controllerExpertCommand.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#3085 fix(nextcloud): change nginx redirect options to not add port to query
  charts/stable/nextcloud/Chart.yaml
  charts/stable/nextcloud/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3093 fix(nextcloud): bypass hpb domain check
  charts/stable/nextcloud/Chart.yaml
  charts/stable/nextcloud/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3100 chore(dashdot): add some envs
  charts/stable/dashdot/Chart.yaml
  charts/stable/dashdot/questions.yaml
  charts/stable/dashdot/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3098 feat(Ariang): add Ariang
  charts/incubator/ariang/Chart.yaml
  charts/incubator/ariang/questions.yaml
  charts/incubator/ariang/templates/common.yaml
  charts/incubator/ariang/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3097 feat(nextcloud/collabora): Add collabora as a nextcloud dependency
  charts/dependency/collabora-online/CHANGELOG.md
  charts/dependency/collabora-online/CONFIG.md
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/collabora-online/README.md
  charts/dependency/collabora-online/helm-values.md
  charts/dependency/collabora-online/questions.yaml
  charts/dependency/collabora-online/security.md
  charts/dependency/collabora-online/templates/common.yaml
  charts/dependency/collabora-online/values.yaml
  charts/stable/collabora-online/values.yaml
  charts/stable/nextcloud/Chart.yaml
  charts/stable/nextcloud/questions.yaml
  charts/stable/nextcloud/templates/_configmap.tpl
  charts/stable/nextcloud/templates/_hpb.tpl
  charts/stable/nextcloud/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#3102 fix(nextcloud): fix HPB service polling url
  charts/stable/nextcloud/Chart.yaml
  charts/stable/nextcloud/templates/_hpb.tpl
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3103 chore(projectsend): some UI fixes
  charts/stable/projectsend/Chart.yaml
  charts/stable/projectsend/questions.yaml
  charts/stable/projectsend/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#3109 fix(nextcloud): improve upload performance and predictability
  charts/stable/nextcloud/Chart.yaml
  charts/stable/nextcloud/questions.yaml
  charts/stable/nextcloud/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#3114 fix(guacd): run rootless
  charts/stable/guacd/Chart.yaml
  charts/stable/guacd/questions.yaml
  charts/stable/guacd/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3119 fix(apps): revert combine ports
  charts/incubator/adguard-home/Chart.yaml
  charts/incubator/adguard-home/questions.yaml
  charts/incubator/adguard-home/values.yaml
  charts/incubator/technitium/Chart.yaml
  charts/incubator/technitium/questions.yaml
  charts/incubator/technitium/values.yaml
  charts/stable/deluge/Chart.yaml
  charts/stable/deluge/questions.yaml
  charts/stable/deluge/values.yaml
  charts/stable/ipfs/Chart.yaml
  charts/stable/ipfs/questions.yaml
  charts/stable/ipfs/values.yaml
  charts/stable/logitech-media-server/Chart.yaml
  charts/stable/logitech-media-server/questions.yaml
  charts/stable/logitech-media-server/values.yaml
  charts/stable/pihole/Chart.yaml
  charts/stable/pihole/questions.yaml
  charts/stable/pihole/values.yaml
  charts/stable/qbittorrent/Chart.yaml
  charts/stable/qbittorrent/questions.yaml
  charts/stable/qbittorrent/templates/_configmap.tpl
  charts/stable/qbittorrent/values.yaml
  charts/stable/resilio-sync/Chart.yaml
  charts/stable/resilio-sync/questions.yaml
  charts/stable/resilio-sync/values.yaml
  charts/stable/storj-node/Chart.yaml
  charts/stable/storj-node/questions.yaml
  charts/stable/storj-node/values.yaml
  charts/stable/syncthing/Chart.yaml
  charts/stable/syncthing/questions.yaml
  charts/stable/syncthing/values.yaml
  charts/stable/transmission/Chart.yaml
  charts/stable/transmission/questions.yaml
  charts/stable/transmission/values.yaml
  charts/stable/verysync/Chart.yaml
  charts/stable/verysync/questions.yaml
  charts/stable/verysync/values.yaml
Labels: lint:ok, size/L, precommit:ok

#3060 feat(clickhouse): Add ClickHouse
  charts/incubator/clickhouse/Chart.yaml
  charts/incubator/clickhouse/questions.yaml
  charts/incubator/clickhouse/templates/common.yaml
  charts/incubator/clickhouse/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3121 fix(guacd): rootfs writable
  charts/stable/guacd/Chart.yaml
  charts/stable/guacd/questions.yaml
  charts/stable/guacd/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3122 fix(nextcloud): increase nginx fpm forwarding timeouts
  charts/stable/nextcloud/Chart.yaml
  charts/stable/nextcloud/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3124 chore(n8n): clean ui a bit and add more envs
  charts/stable/n8n/Chart.yaml
  charts/stable/n8n/questions.yaml
  charts/stable/n8n/templates/_configmap.tpl
  charts/stable/n8n/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3120 feat(solr): add solr as dep
  charts/dependency/solr/Chart.yaml
  charts/dependency/solr/questions.yaml
  charts/dependency/solr/templates/common.yaml
  charts/dependency/solr/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3126 feat(editorconfig): Add EditorConfig
  .editorconfig
  .vscode/extensions.json
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3134 fix(clickhouse): Fix ClickHouse upstream repo
  charts/incubator/clickhouse/Chart.yaml
  charts/incubator/clickhouse/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3135 chore(apps): update image refs
  charts/incubator/avidemux/Chart.yaml
  charts/incubator/avidemux/values.yaml
  charts/incubator/cloudflared/Chart.yaml
  charts/incubator/cloudflared/values.yaml
  charts/incubator/cloudflareddns/Chart.yaml
  charts/incubator/cloudflareddns/values.yaml
  charts/incubator/dupeguru/Chart.yaml
  charts/incubator/dupeguru/values.yaml
  charts/incubator/filebot/Chart.yaml
  charts/incubator/filebot/values.yaml
  charts/incubator/mediainfo/Chart.yaml
  charts/incubator/mediainfo/values.yaml
  charts/incubator/mkvcleaver/Chart.yaml
  charts/incubator/mkvcleaver/values.yaml
  charts/incubator/putty/Chart.yaml
  charts/incubator/putty/values.yaml
  charts/incubator/qdirstat/Chart.yaml
  charts/incubator/qdirstat/values.yaml
  charts/incubator/radicale/Chart.yaml
  charts/incubator/radicale/values.yaml
Labels: lint:ok, size/M, precommit:ok

#3136 fix(clickhouse): Upgrade common lib
  charts/incubator/clickhouse/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3127 feat(mineOS): add mineOS
  charts/incubator/mineos/Chart.yaml
  charts/incubator/mineos/questions.yaml
  charts/incubator/mineos/templates/common.yaml
  charts/incubator/mineos/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3138 fix(clickhouse): Upgrade common lib
  charts/incubator/clickhouse/Chart.yaml
Labels: size/XS, lint:ok, precommit:ok

#3140 chore(docs): add markdownlint and cpell config files (and apply some linting)
  .github/README.md
  .markdownlint.yaml
  .vscode/extensions.json
  charts/dependency/collabora-online/docs/installation_notes.md
  charts/dependency/collabora-online/questions.yaml
  charts/incubator/avidemux/docs/installation_notes.md
  charts/incubator/dupeguru/docs/installation_notes.md
  charts/incubator/filebot/docs/installation_notes.md
  charts/incubator/mediainfo/docs/installation_notes.md
  charts/incubator/mkvcleaver/docs/installation_notes.md
  charts/incubator/qdirstat/docs/installation_notes.md
  charts/incubator/tsmuxer/docs/installation_notes.md
  charts/stable/deepstack/docs/installation_notes.md
  charts/stable/duplicati/docs/ingress.md
  charts/stable/fireflyiii/docs/installation_notes.md
  charts/stable/handbrake/docs/installation_notes.md
  charts/stable/jdownloader2/docs/installation_notes.md
  charts/stable/makemkv/docs/installation_notes.md
  charts/stable/meshroom/docs/installation_notes.md
  charts/stable/minecraft-java/docs/community-guide.md
  charts/stable/nextcloud/docs/installation_notes.md
  cspell.config.yaml
  mkdocs.yml
Labels: lint:ok, size/L, precommit:ok

#3141 chore(postgresql): Bump common lib in postgresql
  charts/dependency/postgresql/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3142 fix(ubooquity): make root fs writable
  charts/stable/ubooquity/Chart.yaml
  charts/stable/ubooquity/questions.yaml
  charts/stable/ubooquity/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3055 feat(plausible): Add Plausible Analytics
  charts/incubator/plausible/Chart.yaml
  charts/incubator/plausible/icon.png
  charts/incubator/plausible/questions.yaml
  charts/incubator/plausible/templates/_env.tpl
  charts/incubator/plausible/templates/common.yaml
  charts/incubator/plausible/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3143 feat(lancache-monolithic): Add lancache-monolithic
  charts/incubator/lancache-monolithic/Chart.yaml
  charts/incubator/lancache-monolithic/icon.png
  charts/incubator/lancache-monolithic/questions.yaml
  charts/incubator/lancache-monolithic/templates/common.yaml
  charts/incubator/lancache-monolithic/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3153 chore(docs): changes to CI doc generation
  .chglog/CHANGELOG.tpl.md
  .github/workflows/charts-release.yaml
  templates/docs/README.md.gotmpl
Labels: size/S, install:ok, lint:ok, precommit:ok

#3155 chore(ci): fix rm on chart-release
  .github/workflows/charts-release.yaml
  charts/stable/minecraft-java/docs/community-guide.md
  charts/stable/minecraft-java/docs/img/dynmap.png
  charts/stable/minecraft-java/docs/img/mc-modports1.png
  charts/stable/minecraft-java/docs/img/mc-modports2.png
  charts/stable/minecraft-java/docs/img/mc-plugins.png
  charts/stable/minecraft-java/docs/img/mc-server1.png
  charts/stable/minecraft-java/docs/img/mc-server2.png
  cspell.config.yaml
Labels: size/S

#3154 feat(lancache-dns): Add lancache-dns
  charts/incubator/lancache-dns/Chart.yaml
  charts/incubator/lancache-dns/icon.png
  charts/incubator/lancache-dns/questions.yaml
  charts/incubator/lancache-dns/templates/common.yaml
  charts/incubator/lancache-dns/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3158 fix variable value on lancache-monolithic
  charts/incubator/lancache-monolithic/Chart.yaml
  charts/incubator/lancache-monolithic/questions.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3160 chore(apps): update some last icons
  charts/dependency/collabora-online/Chart.yaml
  charts/incubator/czkawka/docs/installation_notes.md
  charts/incubator/lancache-dns/Chart.yaml
  charts/incubator/lancache-monolithic/Chart.yaml
  charts/incubator/putty/docs/installation_notes.md
  charts/stable/code-server/Chart.yaml
  cspell.config.yaml
Labels: lint:ok, size/M, precommit:ok

#3168 fix(apps): make root fs writable on several LSIO apps
  charts/stable/embystat/Chart.yaml
  charts/stable/embystat/questions.yaml
  charts/stable/embystat/values.yaml
  charts/stable/lazylibrarian/Chart.yaml
  charts/stable/lazylibrarian/questions.yaml
  charts/stable/lazylibrarian/values.yaml
  charts/stable/mylar/Chart.yaml
  charts/stable/mylar/questions.yaml
  charts/stable/mylar/values.yaml
  charts/stable/synclounge/Chart.yaml
  charts/stable/synclounge/questions.yaml
  charts/stable/synclounge/values.yaml
  charts/stable/znc/Chart.yaml
  charts/stable/znc/questions.yaml
  charts/stable/znc/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#3173 fix(apps): disable HTTP probes temporarily
  charts/stable/authelia/Chart.yaml
  charts/stable/authelia/values.yaml
  charts/stable/traefik/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#3163 feat(k8s-gateway): deploy k8s-gateway in HA mode
  charts/stable/k8s-gateway/Chart.yaml
  charts/stable/k8s-gateway/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3178 update/fix plex-meta-manager
  charts/incubator/plex-meta-manager/Chart.yaml
  charts/incubator/plex-meta-manager/questions.yaml
  charts/incubator/plex-meta-manager/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#3191 fix(foldingathome): make root fs writable
  charts/stable/foldingathome/Chart.yaml
  charts/stable/foldingathome/questions.yaml
  charts/stable/foldingathome/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3194 chore(ghost): remove duplice gui entry
  charts/incubator/ghost/Chart.yaml
  charts/incubator/ghost/questions.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3196 feat(Docs): Add installation_notes for cloudflared
  charts/incubator/cloudflared/docs/installation_notes.md
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3197 feat(Docs): Add Setup-Guide for cloudflareddns
  charts/incubator/cloudflareddns/docs/setup-guide.md
Labels: precommit:failed, install:ok, lint:ok, size/M

#3200 chore(docs): extend linter and apply lint
  .markdownlint.yaml
  charts/incubator/cloudflared/Chart.yaml
  charts/incubator/cloudflared/docs/installation_notes.md
  charts/incubator/cloudflareddns/Chart.yaml
  charts/incubator/cloudflareddns/docs/setup-guide.md
  cspell.config.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#3202 chore(docs): lint
  charts/incubator/cloudflareddns/docs/setup-guide.md
  cspell.config.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3207 fix(cloudflareddns): Modify description
  charts/stable/cloudflareddns/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3206 fix(plex-meta-manager): Change upstream image, update env, add docs
  charts/incubator/plex-meta-manager/Chart.yaml
  charts/incubator/plex-meta-manager/docs/installation_notes.md
  charts/incubator/plex-meta-manager/questions.yaml
  charts/incubator/plex-meta-manager/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#3212 feat(mosquitto): Create setup-guide.md
  charts/stable/mosquitto/docs/setup-guide.md
Labels: size/S, install:ok, lint:ok, precommit:ok

#3213 fix(cloudflareddns): Updated How-To for more complete setup
  charts/stable/cloudflareddns/docs/img/cloudflare-api-keys.png
  charts/stable/cloudflareddns/docs/img/cloudflare-config.png
  charts/stable/cloudflareddns/docs/img/cloudflare-dns.png
  charts/stable/cloudflareddns/docs/img/cloudflare-name.png
  charts/stable/cloudflareddns/docs/img/cloudflare-ns.png
  charts/stable/cloudflareddns/docs/img/cloudflare-token.png
  charts/stable/cloudflareddns/docs/setup-guide.md
Labels: size/S, install:ok, lint:ok, precommit:ok

#3209 fix(intentree): partial fixup
  charts/stable/cloudflareddns/Chart.yaml
  charts/stable/cloudflareddns/docs/setup-guide.md
  charts/stable/inventree/Chart.yaml
  charts/stable/inventree/questions.yaml
  charts/stable/inventree/values.yaml
  charts/stable/mosquitto/Chart.yaml
Labels: lint:ok, size/M, precommit:ok

#3217 chore(docs): fix headers for better table of contents
  templates/docs/README.md.gotmpl
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3221 fix(CI): Update repo in renovate
  .github/renovate-config.js
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3220 feat(wg-easy): Add How-To or setup guide
  charts/stable/wg-easy/Chart.yaml
  charts/stable/wg-easy/docs/img/wg-easy-chart-config.png
  charts/stable/wg-easy/docs/img/wg-easy-firewall-ex1.png
  charts/stable/wg-easy/docs/img/wg-easy-firewall-ex2.png
  charts/stable/wg-easy/docs/img/wg-easy-gui.png
  charts/stable/wg-easy/docs/img/wg-easy-networking.png
  charts/stable/wg-easy/docs/img/wg-easy-sysctl.png
  charts/stable/wg-easy/docs/setup-guide.md
  cspell.config.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#3226 feat(ci): force the use of TCCR in CI
  .github/workflows/charts-test.yaml
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/mariadb/values.yaml
  charts/dependency/memcached/values.yaml
  charts/dependency/mongodb/values.yaml
  charts/dependency/postgresql/values.yaml
  charts/dependency/promtail/Chart.yaml
  charts/dependency/redis/values.yaml
Labels: size/S, lint:ok, precommit:ok

#3229 feat: Add E-Rang of UnRaid Ports
  charts/dev/eco/.helmignore
  charts/dev/eco/Chart.yaml
  charts/dev/eco/icon.png
  charts/dev/eco/questions.yaml
  charts/dev/eco/templates/common.yaml
  charts/dev/eco/values.yaml
  charts/dev/ecodms/.helmignore
  charts/dev/ecodms/Chart.yaml
  charts/dev/ecodms/icon.png
  charts/dev/ecodms/questions.yaml
  charts/dev/ecodms/templates/common.yaml
  charts/dev/ecodms/values.yaml
  charts/dev/electrum/.helmignore
  charts/dev/electrum/Chart.yaml
  charts/dev/electrum/icon.png
  charts/dev/electrum/questions.yaml
  charts/dev/electrum/templates/common.yaml
  charts/dev/electrum/values.yaml
  charts/dev/emby-sync/.helmignore
  charts/dev/emby-sync/Chart.yaml
  charts/dev/emby-sync/icon.png
  charts/dev/emby-sync/questions.yaml
  charts/dev/emby-sync/templates/common.yaml
  charts/dev/emby-sync/values.yaml
  charts/dev/ethercalc/.helmignore
  charts/dev/ethercalc/Chart.yaml
  charts/dev/ethercalc/icon.png
  charts/dev/ethercalc/questions.yaml
  charts/dev/ethercalc/templates/common.yaml
  charts/dev/ethercalc/values.yaml
  charts/dev/euterpe/.helmignore
  charts/dev/euterpe/Chart.yaml
  charts/dev/euterpe/icon.png
  charts/dev/euterpe/questions.yaml
  charts/dev/euterpe/templates/common.yaml
  charts/dev/euterpe/values.yaml
  charts/dev/explainshell/.helmignore
  charts/dev/explainshell/Chart.yaml
  charts/dev/explainshell/icon.png
  charts/dev/explainshell/questions.yaml
  charts/dev/explainshell/templates/common.yaml
  charts/dev/explainshell/values.yaml
  charts/dev/external-ip/.helmignore
  charts/dev/external-ip/Chart.yaml
  charts/dev/external-ip/icon.png
  charts/dev/external-ip/questions.yaml
  charts/dev/external-ip/templates/common.yaml
  charts/dev/external-ip/values.yaml
Labels: lint:ok, size/XXL, precommit:ok

#3245 feat(treafik): Adds theme.park middleware and remove Traefik pilot
  charts/stable/traefik/Chart.yaml
  charts/stable/traefik/questions.yaml
  charts/stable/traefik/templates/_args.tpl
  charts/stable/traefik/templates/middlewares/theme-park.yaml
  charts/stable/traefik/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#3251 fix(jellyseerr): Add app description
  charts/stable/jellyseerr/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3261 chore(apps): update image refs
  charts/dependency/solr/Chart.yaml
  charts/dependency/solr/values.yaml
  charts/incubator/lancache-dns/Chart.yaml
  charts/incubator/lancache-dns/values.yaml
  charts/incubator/lancache-monolithic/Chart.yaml
  charts/incubator/lancache-monolithic/values.yaml
  charts/incubator/wger/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#3246 feat(traefik) update theme.park integration
  charts/stable/traefik/Chart.yaml
  charts/stable/traefik/questions.yaml
  charts/stable/traefik/templates/_args.tpl
  charts/stable/traefik/templates/middlewares/theme-park.yaml
  charts/stable/traefik/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#3257 feat(bungeecord): Add bungeecord
  charts/incubator/minecraft-bungeecord/Chart.yaml
  charts/incubator/minecraft-bungeecord/ci/base-values.yaml
  charts/incubator/minecraft-bungeecord/ci/j11-values.yaml
  charts/incubator/minecraft-bungeecord/ci/j8-values.yaml
  charts/incubator/minecraft-bungeecord/docs/installation_notes.md
  charts/incubator/minecraft-bungeecord/icon.png
  charts/incubator/minecraft-bungeecord/questions.yaml
  charts/incubator/minecraft-bungeecord/templates/common.yaml
  charts/incubator/minecraft-bungeecord/values.yaml
  cspell.config.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3262 Fixed Readme links
  templates/docs/README.md.gotmpl
Labels: size/XS

#3263 fix(minecraft-bungeecord): fix typo
  charts/incubator/minecraft-bungeecord/Chart.yaml
  charts/incubator/minecraft-bungeecord/questions.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3305 fix(charts): Fix inline comments that break linting
  charts/stable/airsonic/values.yaml
  charts/stable/deconz/values.yaml
  charts/stable/loki/values.yaml
  charts/stable/octoprint/values.yaml
  charts/stable/scrutiny/values.yaml
  charts/stable/synapse/values.yaml
  charts/stable/vaultwarden/ci/ingress-values.yaml
  charts/stable/vaultwarden/values.yaml
Labels: size/S

#3293 feat(ztcuui-aio): Add ztcuui-aio
  charts/incubator/ztcuui-aio/.helmignore
  charts/incubator/ztcuui-aio/Chart.yaml
  charts/incubator/ztcuui-aio/README.md
  charts/incubator/ztcuui-aio/icon.png
  charts/incubator/ztcuui-aio/questions.yaml
  charts/incubator/ztcuui-aio/templates/common.yaml
  charts/incubator/ztcuui-aio/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3306 fix(ztncui-aio): Fix some miss
  charts/incubator/ztcuui-aio/questions.yaml
  charts/incubator/ztcuui-aio/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#3314 feat(ztcuui-aio): Fix scale permission
  charts/incubator/ztcuui-aio/Chart.yaml
  charts/incubator/ztcuui-aio/questions.yaml
  charts/incubator/ztcuui-aio/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#3319 fix(nextcloud): also apply the php var fix to UI
  charts/stable/nextcloud/Chart.yaml
  charts/stable/nextcloud/questions.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3315 feat(Nextcloud): Improved installation_notes
  charts/stable/nextcloud/docs/installation_notes.md
  charts/stable/nextcloud/docs/migration_guide.md
Labels: size/S, install:ok, lint:ok, precommit:ok

#3309 feat(autobrr): Add autobrr
  charts/incubator/autobrr/Chart.yaml
  charts/incubator/autobrr/README.md
  charts/incubator/autobrr/icon.png
  charts/incubator/autobrr/questions.yaml
  charts/incubator/autobrr/templates/common.yaml
  charts/incubator/autobrr/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3320 feat(docs): add theme-park middleware docs
  charts/stable/traefik/Chart.yaml
  charts/stable/traefik/docs/img/traefik-theme-after.png
  charts/stable/traefik/docs/img/traefik-theme-app.png
  charts/stable/traefik/docs/img/traefik-theme-before.png
  charts/stable/traefik/docs/img/traefik-theme-fields.png
  charts/stable/traefik/docs/theme-park-middleware.md
Labels: size/S, install:ok, lint:ok, precommit:ok

#3321 fix(docs): correct links to TrueCharts documentation and spelling errors
  .github/README.md
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3323 feat(ts3-manager): Add ts3-manager
  charts/incubator/ts3-manager/Chart.yaml
  charts/incubator/ts3-manager/README.md
  charts/incubator/ts3-manager/icon.png
  charts/incubator/ts3-manager/questions.yaml
  charts/incubator/ts3-manager/templates/common.yaml
  charts/incubator/ts3-manager/values.yaml
  cspell.config.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3324 chore(apps): update image refs
  charts/incubator/autobrr/Chart.yaml
  charts/incubator/autobrr/values.yaml
  charts/incubator/frigate/Chart.yaml
  charts/incubator/frigate/values.yaml
  charts/incubator/jitsi/Chart.yaml
  charts/incubator/jitsi/values.yaml
  charts/incubator/ztcuui-aio/Chart.yaml
  charts/incubator/ztcuui-aio/values.yaml
  charts/stable/meshroom/Chart.yaml
  charts/stable/meshroom/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#3327 feat(anki-sync-server): Add anki sync server
  charts/incubator/anki-sync-server/.helmignore
  charts/incubator/anki-sync-server/Chart.yaml
  charts/incubator/anki-sync-server/README.md
  charts/incubator/anki-sync-server/icon.png
  charts/incubator/anki-sync-server/questions.yaml
  charts/incubator/anki-sync-server/templates/common.yaml
  charts/incubator/anki-sync-server/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3328 chore(outline): remove ALLOWED_DOMAINS var
  charts/stable/outline/Chart.yaml
  charts/stable/outline/questions.yaml
  charts/stable/outline/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3329 chore(guacamole-client): prepare env's for next update and add proxy options
  charts/stable/guacamole-client/Chart.yaml
  charts/stable/guacamole-client/questions.yaml
  charts/stable/guacamole-client/templates/_configmap.tpl
  charts/stable/guacamole-client/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#3330 fix(cleanarr): cleanup Cleanarr
  charts/incubator/cleanarr/Chart.yaml
  charts/incubator/cleanarr/questions.yaml
  charts/incubator/cleanarr/values.yaml
  charts/incubator/ts3-manager/Chart.yaml
  charts/incubator/ts3-manager/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#3335 chore(docs): auto update home on chart.yaml
  .github/scripts/gen-docs.sh
  tools/build-release.sh
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3336 feat(ci): Auto add/update/replace `sources` with TC git repo link
  .github/scripts/gen-docs.sh
  tools/build-release.sh
Labels: size/S, install:ok, lint:ok, precommit:ok

#3337 feat(zusam,sheetable): add zusam,sheetable
  charts/incubator/sheetable/.helmignore
  charts/incubator/sheetable/Chart.yaml
  charts/incubator/sheetable/README.md
  charts/incubator/sheetable/icon.png
  charts/incubator/sheetable/questions.yaml
  charts/incubator/sheetable/templates/_secrets.tpl
  charts/incubator/sheetable/templates/common.yaml
  charts/incubator/sheetable/values.yaml
  charts/incubator/zusam/.helmignore
  charts/incubator/zusam/Chart.yaml
  charts/incubator/zusam/README.md
  charts/incubator/zusam/icon.png
  charts/incubator/zusam/questions.yaml
  charts/incubator/zusam/templates/common.yaml
  charts/incubator/zusam/values.yaml
Labels: size/XL, install:ok, lint:ok, precommit:ok

#3340 feat(timetagger): add timetagger
  charts/incubator/timetagger/.helmignore
  charts/incubator/timetagger/Chart.yaml
  charts/incubator/timetagger/README.md
  charts/incubator/timetagger/questions.yaml
  charts/incubator/timetagger/templates/common.yaml
  charts/incubator/timetagger/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3341 feat(ci): autogen icon link and add some logging
  .github/scripts/gen-docs.sh
  tools/build-release.sh
Labels: size/S, install:ok, lint:ok, precommit:ok

#3342 fix(fireshare): cleanup
  charts/incubator/fireshare/Chart.yaml
  charts/incubator/fireshare/questions.yaml
  charts/incubator/fireshare/templates/_secrets.tpl
  charts/incubator/fireshare/templates/common.yaml
  charts/incubator/fireshare/values.yaml
  cspell.config.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#3343 fix(ci): yq requires -y for in place changes
  .github/scripts/gen-docs.sh
  tools/build-release.sh
Labels: size/S, install:ok, lint:ok, precommit:ok

#3344 fix(gokapi): cleanup
  charts/incubator/gokapi/Chart.yaml
  charts/incubator/gokapi/questions.yaml
  charts/incubator/gokapi/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#3345 chore(ci): print yq version
  .github/scripts/gen-docs.sh
  tools/build-release.sh
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3347 chore(gokapi): bump
  charts/incubator/gokapi/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3353 feat(kitchenowl): add kitchenowl
  charts/incubator/kitchenowl/.helmignore
  charts/incubator/kitchenowl/Chart.yaml
  charts/incubator/kitchenowl/README.md
  charts/incubator/kitchenowl/icon.png
  charts/incubator/kitchenowl/questions.yaml
  charts/incubator/kitchenowl/templates/_secrets.tpl
  charts/incubator/kitchenowl/templates/common.yaml
  charts/incubator/kitchenowl/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#3358 fix(docs): Fixed the manual reference for the Catalog items
  .github/scripts/build-catalog.sh
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3361 feat(ztncui-aio): move to stable
  charts/stable/ztcuui-aio/.helmignore
  charts/stable/ztcuui-aio/CHANGELOG.md
  charts/stable/ztcuui-aio/Chart.yaml
  charts/stable/ztcuui-aio/README.md
  charts/stable/ztcuui-aio/icon.png
  charts/stable/ztcuui-aio/questions.yaml
  charts/stable/ztcuui-aio/templates/common.yaml
  charts/stable/ztcuui-aio/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3351 fix(ci): use go-yq
  .github/scripts/gen-docs.sh
  .github/workflows/catalog-test.yaml
  .github/workflows/charts-release.yaml
  tools/build-release.sh
Labels: install:ok, lint:ok, size/M, precommit:ok

#3363 chore(gokapi): bump to test ci
  charts/incubator/gokapi/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3364 fix(ci): remove go-yq check
  .github/scripts/gen-docs.sh
  .github/workflows/catalog-test.yaml
  .github/workflows/charts-release.yaml
  tools/build-release.sh
Labels: install:ok, lint:ok, size/M, precommit:ok

#3365 chore(gokapi): bump for ci test
  charts/incubator/gokapi/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#3366 chore(ci): cleanup ci
  .github/scripts/gen-docs.sh
  tools/build-release.sh
Labels: size/S, install:ok, lint:ok, precommit:ok
