Repository trueforge-org/truecharts, pull requests merged in 2022-04, with the labels that each got.

#2373 fix(meshcentral): Fix port type
  charts/incubator/meshcentral/Chart.yaml
  charts/incubator/meshcentral/questions.yaml
  charts/incubator/meshcentral/templates/_configmap.tpl
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2367 feat(ferdi-server): Add ferdi-server
  charts/incubator/ferdi-server/Chart.yaml
  charts/incubator/ferdi-server/questions.yaml
  charts/incubator/ferdi-server/templates/_secrets.tpl
  charts/incubator/ferdi-server/templates/common.yaml
  charts/incubator/ferdi-server/values.yaml
  docs/_static/img/appicons/ferdi-server.png
  docs/manual/default-ports.md
Labels: install:ok, lint:ok, size/L, precommit:ok

#2374 feat:(typecho): Add typecho
  charts/incubator/typecho/.helmignore
  charts/incubator/typecho/Chart.yaml
  charts/incubator/typecho/questions.yaml
  charts/incubator/typecho/templates/common.yaml
  charts/incubator/typecho/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#2377 fix(meshcentral): HTTPS for main service
  charts/incubator/meshcentral/Chart.yaml
  charts/incubator/meshcentral/values.yaml
Labels: size/XS

#2379 feat(xwiki): add xwiki
  charts/incubator/xwiki/Chart.yaml
  charts/incubator/xwiki/questions.yaml
  charts/incubator/xwiki/templates/common.yaml
  charts/incubator/xwiki/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#2381 feat(picoshare): add picoshare
  charts/incubator/picoshare/Chart.yaml
  charts/incubator/picoshare/questions.yaml
  charts/incubator/picoshare/templates/_secrets.tpl
  charts/incubator/picoshare/templates/common copy.yaml
  charts/incubator/picoshare/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#2382 feat(linkding): Add linkding
  charts/incubator/linkding/Chart.yaml
  charts/incubator/linkding/questions.yaml
  charts/incubator/linkding/templates/common.yaml
  charts/incubator/linkding/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#2385 chore(heimdall): Update digest
  charts/stable/heimdall/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2388 fix(outline): Use correct secret length and reduce code for init
  charts/stable/outline/Chart.yaml
  charts/stable/outline/questions.yaml
  charts/stable/outline/templates/_secrets.tpl
  charts/stable/outline/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#2390 chore(app): bump version
  charts/incubator/linkding/Chart.yaml
  charts/incubator/meshcentral/Chart.yaml
  charts/incubator/picoshare/Chart.yaml
  charts/incubator/typecho/Chart.yaml
  charts/incubator/xwiki/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2391 fix(zigbee2mqtt): wrong default on dropdown
  charts/stable/zigbee2mqtt/Chart.yaml
  charts/stable/zigbee2mqtt/questions.yaml
Labels: size/XS

#2394 fix(outline): don't b64enc secret
  charts/stable/outline/Chart.yaml
  charts/stable/outline/templates/_secrets.tpl
Labels: size/XS

#2396 fix(outline): use stringData
  charts/stable/outline/Chart.yaml
  charts/stable/outline/templates/_secrets.tpl
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2401 Update Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
Labels: size/XS

#2402 Update Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/postgresql/Chart.yaml
Labels: size/XS

#2403 chore(app): bump version
  charts/incubator/meshcentral/Chart.yaml
  charts/incubator/picoshare/Chart.yaml
  charts/incubator/typecho/Chart.yaml
  charts/incubator/xwiki/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2404 fix(deluge): fix versioning scheme
  charts/stable/deluge/Chart.yaml
  charts/stable/deluge/values.yaml
Labels: size/XS

#2407 chore(meshcentral): bump meshcentral version alone
  charts/incubator/meshcentral/Chart.yaml
Labels: size/XS

#2405 fix(outline): fix secret
  charts/stable/outline/Chart.yaml
  charts/stable/outline/templates/_secrets.tpl
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2411 chore(apps): update image refs
  charts/incubator/ferdi-server/Chart.yaml
  charts/incubator/ferdi-server/values.yaml
  charts/incubator/linkding/Chart.yaml
  charts/incubator/linkding/values.yaml
  charts/incubator/meshcentral/Chart.yaml
  charts/incubator/meshcentral/values.yaml
  charts/incubator/typecho/Chart.yaml
  charts/incubator/typecho/values.yaml
  charts/incubator/xwiki/Chart.yaml
  charts/incubator/xwiki/values.yaml
  charts/stable/mosdns/.helmignore
  charts/stable/mosdns/CHANGELOG.md
  charts/stable/mosdns/CONFIG.md
  charts/stable/mosdns/Chart.yaml
  charts/stable/mosdns/README.md
  charts/stable/mosdns/helm-values.md
  charts/stable/mosdns/questions.yaml
  charts/stable/mosdns/security.md
  charts/stable/mosdns/templates/common.yaml
  charts/stable/mosdns/values.yaml
Labels: size/S

#2389 fix(wireshark): rw root fs / hostnet
  charts/stable/heimdall/Chart.yaml
  charts/stable/sqlitebrowser/Chart.yaml
  charts/stable/sqlitebrowser/questions.yaml
  charts/stable/sqlitebrowser/values.yaml
  charts/stable/wireshark/Chart.yaml
  charts/stable/wireshark/questions.yaml
  charts/stable/wireshark/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#2412 chore(meshcentral): Adjust description
  charts/incubator/meshcentral/Chart.yaml
  charts/incubator/meshcentral/questions.yaml
Labels: size/XS

#2395 feat(zigbee2mqtt): allow use of custom config file BREAKING CHANGE
  charts/stable/zigbee2mqtt/Chart.yaml
  charts/stable/zigbee2mqtt/questions.yaml
  charts/stable/zigbee2mqtt/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#2415 feat(apps): move to stable
  charts/incubator/picoshare/templates/_secrets.tpl
  charts/incubator/picoshare/templates/common copy.yaml
  charts/stable/ferdi-server/CHANGELOG.md
  charts/stable/ferdi-server/CONFIG.md
  charts/stable/ferdi-server/Chart.yaml
  charts/stable/ferdi-server/README.md
  charts/stable/ferdi-server/helm-values.md
  charts/stable/ferdi-server/questions.yaml
  charts/stable/ferdi-server/security.md
  charts/stable/ferdi-server/templates/_secrets.tpl
  charts/stable/ferdi-server/templates/common.yaml
  charts/stable/ferdi-server/values.yaml
  charts/stable/picoshare/CHANGELOG.md
  charts/stable/picoshare/CONFIG.md
  charts/stable/picoshare/Chart.yaml
  charts/stable/picoshare/README.md
  charts/stable/picoshare/helm-values.md
  charts/stable/picoshare/questions.yaml
  charts/stable/picoshare/security.md
  charts/stable/picoshare/templates/common.yaml
  charts/stable/picoshare/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#2418 Update action.yaml
  .github/actions/collect-changes/action.yaml
Labels: size/XS

#2417 fix(linkding): create initial user
  charts/incubator/linkding/questions.yaml
  charts/incubator/linkding/values.yaml
  charts/stable/xwiki/CHANGELOG.md
  charts/stable/xwiki/CONFIG.md
  charts/stable/xwiki/Chart.yaml
  charts/stable/xwiki/README.md
  charts/stable/xwiki/helm-values.md
  charts/stable/xwiki/questions.yaml
  charts/stable/xwiki/security.md
  charts/stable/xwiki/templates/common.yaml
  charts/stable/xwiki/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#2420 chore(linkding): bump
  charts/incubator/linkding/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2422 feat(traefik): Add stripPrefixRegex
  charts/core/traefik/Chart.yaml
  charts/core/traefik/questions.yaml
  charts/core/traefik/templates/middlewares/stripPrefixRegex.yaml
  charts/core/traefik/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#2425 fix(code-server): correctly set the run-as-root things
  charts/stable/code-server/Chart.yaml
  charts/stable/code-server/questions.yaml
  charts/stable/code-server/values.yaml
Labels: precommit:failed, size/XS, lint:ok

#2426 Update stripPrefixRegex.yaml
  charts/core/traefik/Chart.yaml
  charts/core/traefik/questions.yaml
  charts/core/traefik/templates/middlewares/stripPrefixRegex.yaml
  charts/core/traefik/values.yaml
Labels: size/S, lint:ok, precommit:ok

#2428 chore(openvsvode-server): make connectionToken optional
  charts/stable/openvscode-server/Chart.yaml
  charts/stable/openvscode-server/questions.yaml
  charts/stable/openvscode-server/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2436 feat(ci): deal with bigger test numbers on CI
  .github/workflows/charts-lint.yaml
  .github/workflows/charts-test.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#2443 fix(traefik/redirectRegex): `permanent` is not required; can be `false`
  charts/core/traefik/Chart.yaml
  charts/core/traefik/questions.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2437 feat(apps): Unraid Port - digits
  .github/actions/collect-changes/action.yaml
  .github/ct-install.yaml
  .github/ct-lint.yaml
  .github/workflows/charts-lint.yaml
  .github/workflows/charts-release.yaml
  .gitignore
  charts/dev/server-7daystodie/.helmignore
  charts/dev/server-7daystodie/Chart.yaml
  charts/dev/server-7daystodie/icon.png
  charts/dev/server-7daystodie/questions.yaml
  charts/dev/server-7daystodie/readme.md
  charts/dev/server-7daystodie/templates/common.yaml
  charts/dev/server-7daystodie/values.yaml
Labels: size/XL, install:ok, lint:ok, precommit:ok

#2449 fix(ci): ensure ghcr is used when running tests
  .github/workflows/charts-test.yaml
  charts/dev/backuppc/README.md
  charts/dev/backuppc/readme.md
  charts/dev/baikal/README.md
  charts/dev/baikal/readme.md
  charts/dev/barcodebuddy/README.md
  charts/dev/barcodebuddy/readme.md
  charts/dev/barotrauma/README.md
  charts/dev/barotrauma/readme.md
  charts/dev/bitcoin-node/README.md
  charts/dev/bitcoin-node/readme.md
  charts/dev/bitcoind/README.md
  charts/dev/bitcoind/readme.md
  charts/dev/bitcoinunlimited/README.md
  charts/dev/bitcoinunlimited/readme.md
  charts/dev/bitcoinwalletgui/README.md
  charts/dev/bitcoinwalletgui/readme.md
  charts/dev/blender-desktop-g3/README.md
  charts/dev/blender-desktop-g3/readme.md
  charts/dev/blender/README.md
  charts/dev/blender/readme.md
  charts/dev/breitbandmessung-de/README.md
  charts/dev/breitbandmessung-de/readme.md
  charts/dev/btdex/README.md
  charts/dev/btdex/readme.md
  charts/dev/bwapp/README.md
  charts/dev/bwapp/readme.md
  charts/dev/server-7daystodie/Chart.yaml
  charts/dev/server-7daystodie/README.md
  charts/dev/server-7daystodie/readme.md
Labels: lint:ok, size/L, precommit:ok

#2452 fix(ispy-dvr-agent): fix rofs
  charts/stable/ispy-agent-dvr/Chart.yaml
  charts/stable/ispy-agent-dvr/questions.yaml
  charts/stable/ispy-agent-dvr/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2456 fix(traefik/redirectRegex): redirection does not have to be permanent
  charts/core/traefik/Chart.yaml
  charts/core/traefik/questions.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2462 fix(linkace): Remove init containers, upstream made some changes to s…
  charts/stable/linkace/Chart.yaml
  charts/stable/linkace/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#2469 fix(collabora-online): remove domains var as it's no longer used.
  charts/stable/collabora-online/Chart.yaml
  charts/stable/collabora-online/questions.yaml
  charts/stable/collabora-online/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2485 fix(ubooquity): fix admin portal button
  charts/stable/ubooquity/Chart.yaml
  charts/stable/ubooquity/questions.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2493 feat(apps): Add apps
  charts/incubator/appsmith/Chart.yaml
  charts/incubator/appsmith/questions.yaml
  charts/incubator/appsmith/templates/common.yaml
  charts/incubator/appsmith/values.yaml
  charts/incubator/cyberchef/Chart.yaml
  charts/incubator/cyberchef/questions.yaml
  charts/incubator/cyberchef/templates/common.yaml
  charts/incubator/cyberchef/values.yaml
  charts/incubator/drawio/Chart.yaml
  charts/incubator/drawio/questions.yaml
  charts/incubator/drawio/templates/common.yaml
  charts/incubator/drawio/values.yaml
  charts/incubator/metube/Chart.yaml
  charts/incubator/metube/questions.yaml
  charts/incubator/metube/templates/common.yaml
  charts/incubator/metube/values.yaml
  charts/incubator/pinry/Chart.yaml
  charts/incubator/pinry/questions.yaml
  charts/incubator/pinry/templates/_secrets.tpl
  charts/incubator/pinry/templates/common.yaml
  charts/incubator/pinry/values.yaml
  charts/incubator/snapdrop/Chart.yaml
  charts/incubator/snapdrop/questions.yaml
  charts/incubator/snapdrop/templates/common.yaml
  charts/incubator/snapdrop/values.yaml
  charts/incubator/vikunja/Chart.yaml
  charts/incubator/vikunja/questions.yaml
  charts/incubator/vikunja/templates/_secrets.tpl
  charts/incubator/vikunja/templates/common.yaml
  charts/incubator/vikunja/values.yaml
  charts/stable/duckdns/values.yaml
Labels: lint:ok, size/XXL, precommit:ok

#2496 chore(snipe-it): add force tls gui option
  charts/dev/appsmith/.helmignore
  charts/dev/appsmith/CHANGELOG.md
  charts/dev/appsmith/Chart.yaml
  charts/dev/appsmith/README.md
  charts/dev/appsmith/icon.png
  charts/dev/appsmith/questions.yaml
  charts/dev/appsmith/readme.md
  charts/dev/appsmith/security.md
  charts/dev/appsmith/templates/common.yaml
  charts/dev/appsmith/values.yaml
  charts/incubator/appsmith/Chart.yaml
  charts/incubator/appsmith/values.yaml
  charts/stable/snipe-it/Chart.yaml
  charts/stable/snipe-it/questions.yaml
Labels: size/XL, install:ok, lint:ok, precommit:ok

#2498 feat(apps): add 2 apps
  charts/incubator/ntfy/Chart.yaml
  charts/incubator/ntfy/questions.yaml
  charts/incubator/ntfy/templates/common.yaml
  charts/incubator/ntfy/values.yaml
  charts/incubator/website-shot/Chart.yaml
  charts/incubator/website-shot/questions.yaml
  charts/incubator/website-shot/templates/common.yaml
  charts/incubator/website-shot/values.yaml
Labels: size/XL, install:ok, lint:ok, precommit:ok

#2499 chore(vaultwarden): replace UI code with tempalte (advanced)
  charts/stable/vaultwarden/Chart.yaml
  charts/stable/vaultwarden/questions.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#2500 feat(dokuwiki): BREAKING CHANGE - Switch to bitnami image
  charts/stable/dokuwiki/Chart.yaml
  charts/stable/dokuwiki/questions.yaml
  charts/stable/dokuwiki/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#2506 chore(apps): bump 2 apps
  charts/incubator/nocodb/Chart.yaml
  charts/incubator/vikunja/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2474 feat(zabbix-server): Init work for zabbix-server
  charts/incubator/zabbix-server/Chart.yaml
  charts/incubator/zabbix-server/questions.yaml
  charts/incubator/zabbix-server/templates/common.yaml
  charts/incubator/zabbix-server/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#2511 fix(apps): use proxy on vikunja and fix nocodb request body size
  charts/incubator/nocodb/Chart.yaml
  charts/incubator/nocodb/questions.yaml
  charts/incubator/nocodb/templates/_secrets.tpl
  charts/incubator/nocodb/templates/common.yaml
  charts/incubator/nocodb/values.yaml
  charts/incubator/vikunja/Chart.yaml
  charts/incubator/vikunja/templates/_secrets.tpl
  charts/incubator/vikunja/templates/common.yaml
  charts/incubator/vikunja/templates/configmap.yaml
  charts/incubator/vikunja/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#2514 fix(n8n): try to fix n8n gui issue not loading edit
  charts/incubator/zabbix-server/Chart.yaml
  charts/stable/n8n/Chart.yaml
  charts/stable/n8n/questions.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2516 chore(n8n): improve configmap
  charts/stable/n8n/Chart.yaml
  charts/stable/n8n/templates/_configmap.tpl
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2517 feat(apps): move apps to stable and update image refs
  charts/incubator/vikunja/templates/configmap.yaml
  charts/incubator/vikunja/values.yaml
  charts/stable/ddns-updater/Chart.yaml
  charts/stable/ddns-updater/values.yaml
  charts/stable/fluidd/Chart.yaml
  charts/stable/fluidd/values.yaml
  charts/stable/nocodb/CHANGELOG.md
  charts/stable/nocodb/Chart.yaml
  charts/stable/nocodb/README.md
  charts/stable/nocodb/questions.yaml
  charts/stable/nocodb/security.md
  charts/stable/nocodb/templates/_configmap.tpl
  charts/stable/nocodb/templates/_secrets.tpl
  charts/stable/nocodb/templates/common.yaml
  charts/stable/nocodb/values.yaml
  charts/stable/rss-bridge/Chart.yaml
  charts/stable/rss-bridge/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#2519 chore(vikunja): bump
  charts/incubator/vikunja/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2520 fix(vikunja): different ports between proxy and frontend
  charts/incubator/vikunja/Chart.yaml
  charts/incubator/vikunja/templates/configmap.yaml
  charts/incubator/vikunja/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2521 fix(vikunja): port
  charts/incubator/vikunja/Chart.yaml
  charts/incubator/vikunja/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2513 fix(traefik): Fix custom chain middleware settings
  charts/core/traefik/Chart.yaml
  charts/core/traefik/templates/middlewares/chain.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2523 chore(vikunja): bump vikunja
  charts/incubator/vikunja/Chart.yaml
  charts/stable/synapse/Chart.yaml
  charts/stable/synapse/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2527 fix(vikunja): try to fix port again
  charts/incubator/vikunja/Chart.yaml
  charts/incubator/vikunja/templates/configmap.yaml
  charts/incubator/vikunja/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2526 fix(meshcentral): BREAKING CHANGE - rewrite config generation
  charts/incubator/meshcentral/Chart.yaml
  charts/incubator/meshcentral/questions.yaml
  charts/incubator/meshcentral/templates/_configmap.tpl
  charts/incubator/meshcentral/templates/common.yaml
  charts/incubator/meshcentral/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#2529 feat(baserow): add baserow
  charts/incubator/baserow/Chart.yaml
  charts/incubator/baserow/questions.yaml
  charts/incubator/baserow/templates/_secrets.tpl
  charts/incubator/baserow/templates/common.yaml
  charts/incubator/baserow/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#2533 chore(meshcentral): update image ref
  charts/incubator/meshcentral/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2535 feat(authentik): add authentik
  charts/incubator/authentik/Chart.yaml
  charts/incubator/authentik/questions.yaml
  charts/incubator/authentik/templates/_cronjob.tpl
  charts/incubator/authentik/templates/_secrets.tpl
  charts/incubator/authentik/templates/common.yaml
  charts/incubator/authentik/values.yaml
Labels: size/XL, install:ok, lint:ok, precommit:ok

#2540 chore(authentik): update db name
  charts/incubator/authentik/Chart.yaml
  charts/incubator/authentik/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2537 chore(apps): fix small mistakes
  charts/stable/kutt/Chart.yaml
  charts/stable/kutt/templates/common.yaml
  charts/stable/synapse/Chart.yaml
  charts/stable/synapse/templates/_helpers.tpl
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2505 feat(mongodb): run in single replicaset (take3)
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/mongodb/questions.yaml
  charts/dependency/mongodb/templates/common.yaml
  charts/dependency/mongodb/templates/create-oplog-user.yaml
  charts/dependency/mongodb/templates/secret.yaml
  charts/dependency/mongodb/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#2546 fix(duckdns): rofs false
  charts/stable/duckdns/Chart.yaml
  charts/stable/duckdns/questions.yaml
  charts/stable/duckdns/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2549 fix(minisatip): rofs false
  charts/stable/minisatip/Chart.yaml
  charts/stable/minisatip/questions.yaml
  charts/stable/minisatip/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2548 chore(mongodb): bump common
  charts/dependency/mongodb/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2551 chore(mongodb): bump common
  charts/dependency/mongodb/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2552 chore(duckdns): add logfile option in gui
  charts/stable/duckdns/Chart.yaml
  charts/stable/duckdns/questions.yaml
  charts/stable/duckdns/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2547 feat(wekan, meshcentral): Use mongodb with replicaset. BREAKING CHANGE
  charts/incubator/meshcentral/Chart.yaml
  charts/incubator/meshcentral/values.yaml
  charts/stable/wekan/Chart.yaml
  charts/stable/wekan/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2555 fix(mongodb): set advertised hostname
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/mongodb/values.yaml
  charts/stable/wekan/Chart.yaml
  charts/stable/wekan/questions.yaml
  charts/stable/wekan/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2556 chore(wekan, meshcentral): bump
  charts/incubator/meshcentral/Chart.yaml
  charts/stable/wekan/Chart.yaml
Labels: size/XS, lint:ok, precommit:ok

#2557 fix(mongodb): dont set initial primary host
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/mongodb/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2559 fix(mongodb): make advertisedhostname configurable
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/mongodb/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2560 fix(mongodb): set advertised hostname
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/mongodb/templates/create-oplog-user.yaml
  charts/dependency/mongodb/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2563 fix(mongodb): fix
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/mongodb/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2567 revert(mongodb): revert replicaset
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/mongodb/questions.yaml
  charts/dependency/mongodb/templates/common.yaml
  charts/dependency/mongodb/templates/create-oplog-user.yaml
  charts/dependency/mongodb/templates/secret.yaml
  charts/dependency/mongodb/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#2569 chore(mongodb): bump common
  charts/dependency/mongodb/Chart.yaml
Labels: lint:ok, precommit:ok

#2558 chore(wekan, meshcentral): bump
  charts/incubator/meshcentral/Chart.yaml
  charts/incubator/meshcentral/values.yaml
  charts/stable/wekan/Chart.yaml
  charts/stable/wekan/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2575 fix(plex): Adjust the description
  charts/stable/plex/Chart.yaml
  charts/stable/plex/questions.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#2583 fix(templates): fix type for ingressadvanced
  templates/questions/advanced.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok
