Repository trueforge-org/truecharts, pull requests merged in 2023-05, with the labels that each got.

#8649 chore(deps): update container image tccr.io/truecharts/portainer-ce to v2.18.1
  charts/stable/portainer-ce/Chart.yaml
  charts/stable/portainer-ce/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#8652 chore(deps): update container image tccr.io/truecharts/prowlarr to v1.4.0.3230
  charts/stable/prowlarr/Chart.yaml
  charts/stable/prowlarr/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8653 chore(deps): update container image tccr.io/truecharts/putty to v23.03.1
  charts/stable/putty/Chart.yaml
  charts/stable/putty/values.yaml
Labels: install:failed, size/XS, lint:ok, precommit:ok, automerge

#8655 chore(deps): update container image tccr.io/truecharts/qbitmanage to v3.6.2
  charts/stable/qbitmanage/Chart.yaml
  charts/stable/qbitmanage/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#8656 chore(deps): update container image tccr.io/truecharts/qdirstat to v23.03.1
  charts/stable/qdirstat/Chart.yaml
  charts/stable/qdirstat/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#8659 chore(deps): update container image tccr.io/truecharts/ring-mqtt to v5.2.2
  charts/stable/ring-mqtt/Chart.yaml
  charts/stable/ring-mqtt/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#8658 chore(deps): update container image tccr.io/truecharts/recyclarr to v4.4.1
  charts/stable/recyclarr/Chart.yaml
  charts/stable/recyclarr/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#8663 chore(deps): update container image tccr.io/truecharts/sabnzbd to v4.0.0
  charts/stable/sabnzbd/Chart.yaml
  charts/stable/sabnzbd/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/major

#8635 chore(templates): hostnet+dnsconfig behind expert
  templates/questions/general/podOptions.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#8650 docs(wg-easy): Update docs for PUID issue
  charts/stable/wg-easy/Chart.yaml
  charts/stable/wg-easy/docs/img/wg-easy-PUID.png
  charts/stable/wg-easy/docs/installation-notes.md
  charts/stable/wg-easy/docs/setup-guide.md
Labels: size/S, install:ok, lint:ok, precommit:ok

#8642 chore(deps): update helm chart common to 12.6.4
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
Labels: size/S, lint:ok, precommit:ok, automerge

#8645 chore(deps): update helm chart common to 12.6.4
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#8678 chore(deps): update container image tccr.io/truecharts/passwordpusherephemeral to latest
  charts/incubator/passwordpusherephemeral/Chart.yaml
  charts/incubator/passwordpusherephemeral/values.yaml
Labels: size/XS, lint:failed, precommit:ok, automerge

#8682 chore(deps): update rdesktop
  charts/stable/rdesktop/Chart.yaml
  charts/stable/rdesktop/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok, automerge

#8670 chore(deps): update container image tccr.io/truecharts/dns-doh-companion to latest
  charts/incubator/dns-doh-companion/Chart.yaml
  charts/incubator/dns-doh-companion/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8665 chore(deps): update container image tccr.io/truecharts/alertmanager to 0.25.0
  charts/enterprise/prometheus/Chart.yaml
  charts/enterprise/prometheus/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8671 chore(deps): update container image tccr.io/truecharts/duckdns to latest
  charts/stable/duckdns/Chart.yaml
  charts/stable/duckdns/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8679 chore(deps): update container image tccr.io/truecharts/postgresql to 14.7.0
  charts/stable/postgresql/Chart.yaml
  charts/stable/postgresql/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8674 chore(deps): update container image tccr.io/truecharts/lazylibrarian to latest
  charts/stable/lazylibrarian/Chart.yaml
  charts/stable/lazylibrarian/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8673 chore(deps): update container image tccr.io/truecharts/grocy to 3.3.2
  charts/stable/grocy/Chart.yaml
  charts/stable/grocy/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8672 chore(deps): update container image tccr.io/truecharts/embystat to v0.2.0
  charts/stable/embystat/Chart.yaml
  charts/stable/embystat/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8667 chore(deps): update container image tccr.io/truecharts/cops to latest
  charts/stable/cops/Chart.yaml
  charts/stable/cops/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8669 chore(deps): update container image tccr.io/truecharts/dillinger to v3.39.1
  charts/stable/dillinger/Chart.yaml
  charts/stable/dillinger/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8681 chore(deps): update container image tccr.io/truecharts/rsshub to latest
  charts/stable/rsshub/Chart.yaml
  charts/stable/rsshub/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8666 chore(deps): update container image tccr.io/truecharts/budge to v0.0.9
  charts/stable/budge/Chart.yaml
  charts/stable/budge/values.yaml
Labels: precommit:failed, size/XS, install:ok, lint:ok, automerge

#8596 chore(deps): update container image tccr.io/truecharts/makemkv to v23.04.1
  charts/stable/makemkv/Chart.yaml
  charts/stable/makemkv/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8598 chore(deps): update container image tccr.io/truecharts/mediainfo to v23.04.1
  charts/stable/mediainfo/Chart.yaml
  charts/stable/mediainfo/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8602 chore(deps): update container image tccr.io/truecharts/mkvtoolnix to v23.03.2
  charts/stable/mkvtoolnix/Chart.yaml
  charts/stable/mkvtoolnix/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8609 chore(deps): update container image tccr.io/truecharts/nocodb to v0.106.1
  charts/stable/nocodb/Chart.yaml
  charts/stable/nocodb/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8686 chore(deps): update helm general non-major
  charts/stable/makemkv/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8657 feat(Incubator): Add idrac-fan-controller
  charts/incubator/dell-idrac-fan-controller/.helmignore
  charts/incubator/dell-idrac-fan-controller/CHANGELOG.md
  charts/incubator/dell-idrac-fan-controller/Chart.yaml
  charts/incubator/dell-idrac-fan-controller/README.md
  charts/incubator/dell-idrac-fan-controller/icon.png
  charts/incubator/dell-idrac-fan-controller/questions.yaml
  charts/incubator/dell-idrac-fan-controller/templates/NOTES.txt
  charts/incubator/dell-idrac-fan-controller/templates/common.yaml
  charts/incubator/dell-idrac-fan-controller/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#8696 chore(deps): update container image tccr.io/truecharts/webtop-alpine-i3 to latest
  charts/stable/webtop/Chart.yaml
  charts/stable/webtop/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#8706 chore(deps): update webtop
  charts/stable/webtop/Chart.yaml
  charts/stable/webtop/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8705 chore(deps): update rdesktop
  charts/stable/rdesktop/Chart.yaml
  charts/stable/rdesktop/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8668 chore(deps): update container image tccr.io/truecharts/cyberchef to 10.4.0
  charts/stable/cyberchef/Chart.yaml
  charts/stable/cyberchef/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8700 chore(deps): update container image tccr.io/truecharts/littlelink-server to latest
  charts/stable/littlelink/Chart.yaml
  charts/stable/littlelink/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8699 chore(deps): update container image tccr.io/truecharts/libreddit to latest
  charts/stable/libreddit/Chart.yaml
  charts/stable/libreddit/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8680 chore(deps): update container image tccr.io/truecharts/pyload-ng to latest
  charts/incubator/pyload-ng/Chart.yaml
  charts/incubator/pyload-ng/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8675 chore(deps): update container image tccr.io/truecharts/libremdb to latest
  charts/stable/libremdb/Chart.yaml
  charts/stable/libremdb/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8701 chore(deps): update container image tccr.io/truecharts/pwndrop to v1.0.1
  charts/stable/pwndrop/Chart.yaml
  charts/stable/pwndrop/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8702 chore(deps): update container image tccr.io/truecharts/quassel-core to v0.14.0
  charts/stable/quassel-core/Chart.yaml
  charts/stable/quassel-core/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8683 chore(deps): update container image tccr.io/truecharts/nginx to v1.23.4
  charts/stable/vikunja/Chart.yaml
  charts/stable/vikunja/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8577 chore(deps): update container image tccr.io/truecharts/gitea to v1.19.2
  charts/stable/gitea/Chart.yaml
  charts/stable/gitea/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8704 chore(deps): update neko
  charts/incubator/neko/Chart.yaml
  charts/incubator/neko/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok, automerge

#8676 chore(deps): update container image tccr.io/truecharts/minecraft-java19 to latest
  charts/stable/minecraft-java/Chart.yaml
  charts/stable/minecraft-java/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8710 chore(deps): update container image tccr.io/truecharts/stationeers to latest
  charts/incubator/stationeers/Chart.yaml
  charts/incubator/stationeers/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8711 chore(deps): update renovatebot/github-action action to v36.0.4
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#8693 chore(deps): update helm general non-major
  charts/stable/unifi/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8716 chore(deps): update container image tccr.io/truecharts/redis to 7.0.11
  charts/dependency/redis/Chart.yaml
  charts/dependency/redis/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8713 fix(questions): fix some duplicate entries
  charts/incubator/ghost/Chart.yaml
  charts/incubator/ghost/questions.yaml
  charts/incubator/technitium/Chart.yaml
  charts/incubator/technitium/questions.yaml
  charts/incubator/traefik-forward-auth/Chart.yaml
  charts/incubator/traefik-forward-auth/questions.yaml
  charts/stable/deepstack/Chart.yaml
  charts/stable/deepstack/questions.yaml
  charts/stable/grist/Chart.yaml
  charts/stable/grist/questions.yaml
  charts/stable/ntfy/Chart.yaml
  charts/stable/ntfy/questions.yaml
  charts/stable/synapse/Chart.yaml
  charts/stable/synapse/questions.yaml
  charts/stable/weblate/Chart.yaml
  charts/stable/weblate/questions.yaml
Labels: lint:ok, size/M, precommit:ok

#8717 chore(deps): update container image tccr.io/truecharts/calibre to 6.17.0
  charts/stable/calibre/Chart.yaml
  charts/stable/calibre/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#8719 chore(ci): disable container updates on incubator
  .github/renovate.json5
Labels: size/XS

#8718 fix(multiple): fix some invalid questions.yaml
  charts/incubator/ghost/questions.yaml
  charts/incubator/technitium/questions.yaml
  charts/incubator/traefik-forward-auth/questions.yaml
  charts/stable/grist/questions.yaml
  charts/stable/synapse/questions.yaml
Labels: size/M

#8212 chore(deps): update container image tccr.io/truecharts/eclipse-mosquitto to 2.0.15
  charts/stable/mosquitto/Chart.yaml
  charts/stable/mosquitto/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8737 chore(deps): update webtop
  charts/stable/webtop/Chart.yaml
  charts/stable/webtop/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok, automerge

#8221 chore(deps): update container image tccr.io/truecharts/filezilla to v
  charts/stable/filezilla/Chart.yaml
  charts/stable/filezilla/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8199 chore(deps): update container image tccr.io/truecharts/darktable to v
  charts/stable/darktable/Chart.yaml
  charts/stable/darktable/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8236 chore(deps): update container image tccr.io/truecharts/habridge to v5.4.1
  charts/stable/habridge/Chart.yaml
  charts/stable/habridge/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8222 chore(deps): update container image tccr.io/truecharts/firefox to v
  charts/stable/firefox/Chart.yaml
  charts/stable/firefox/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8242 chore(deps): update container image tccr.io/truecharts/invidious to latest
  charts/stable/invidious/Chart.yaml
  charts/stable/invidious/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8247 chore(deps): update container image tccr.io/truecharts/koel to latest
  charts/stable/koel/Chart.yaml
  charts/stable/koel/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8727 chore(deps): update container image tccr.io/truecharts/memcached to 1.6.19
  charts/dependency/memcached/Chart.yaml
  charts/dependency/memcached/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8728 chore(deps): update container image tccr.io/truecharts/mongodb to 6.0.5
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/mongodb/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8342 chore(deps): update container image tccr.io/truecharts/plexanisync to latest
  charts/stable/plexanisync/Chart.yaml
  charts/stable/plexanisync/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8252 chore(deps): update container image tccr.io/truecharts/libreoffice to v
  charts/stable/libreoffice/Chart.yaml
  charts/stable/libreoffice/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8339 chore(deps): update container image tccr.io/truecharts/pidgin to v
  charts/stable/pidgin/Chart.yaml
  charts/stable/pidgin/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8338 chore(deps): update container image tccr.io/truecharts/pialert to latest
  charts/stable/pialert/Chart.yaml
  charts/stable/pialert/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8595 chore(deps): update container image tccr.io/truecharts/loki to v2.8.1
  charts/stable/loki/Chart.yaml
  charts/stable/loki/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8732 chore(deps): update container image tccr.io/truecharts/rsshub to latest
  charts/stable/rsshub/Chart.yaml
  charts/stable/rsshub/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8735 chore(deps): update container image tccr.io/truecharts/thanos to 0.31.0
  charts/enterprise/prometheus/Chart.yaml
  charts/enterprise/prometheus/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8456 chore(deps): update container image tccr.io/truecharts/icinga2 to v2.13.7
  charts/stable/icinga2/Chart.yaml
  charts/stable/icinga2/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8418 chore(deps): update container image tccr.io/truecharts/wireshark to v
  charts/stable/wireshark/Chart.yaml
  charts/stable/wireshark/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8564 chore(deps): update container image tccr.io/truecharts/deconz to v2.22.00
  charts/stable/deconz/Chart.yaml
  charts/stable/deconz/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8651 chore(deps): update container image tccr.io/truecharts/protonmail-bridge to v3.1.2
  charts/stable/protonmail-bridge/Chart.yaml
  charts/stable/protonmail-bridge/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8479 chore(deps): update container image tccr.io/truecharts/linkace to v1.11.4
  charts/stable/linkace/Chart.yaml
  charts/stable/linkace/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8561 chore(deps): update container image tccr.io/truecharts/cloudflared to v2023.4.2
  charts/stable/cloudflared/Chart.yaml
  charts/stable/cloudflared/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8477 chore(deps): update container image tccr.io/truecharts/leantime to v2.3.20
  charts/stable/leantime/Chart.yaml
  charts/stable/leantime/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8451 chore(deps): update container image tccr.io/truecharts/guacamole-client to v1.5.1
  charts/stable/guacamole-client/Chart.yaml
  charts/stable/guacamole-client/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8637 chore(deps): update container image tccr.io/truecharts/pihole to v2023.03.1
  charts/stable/pihole/Chart.yaml
  charts/stable/pihole/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8576 chore(deps): update container image tccr.io/truecharts/ghost to v5.45.1
  charts/incubator/ghost/Chart.yaml
  charts/incubator/ghost/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8430 chore(deps): update authentik to v2023.2.3 (patch)
  charts/stable/authentik/Chart.yaml
  charts/stable/authentik/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8458 chore(deps): update container image tccr.io/truecharts/joplin-server to v2.10.10
  charts/stable/joplin-server/Chart.yaml
  charts/stable/joplin-server/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8416 chore(deps): update container image tccr.io/truecharts/wger to latest
  charts/stable/wger/Chart.yaml
  charts/stable/wger/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8259 chore(deps): update container image tccr.io/truecharts/snipe-it to v6.1.0
  charts/stable/snipe-it/Chart.yaml
  charts/stable/snipe-it/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8537 chore(deps): update container image tccr.io/truecharts/youtrack to v2022.3.65379
  charts/stable/youtrack/Chart.yaml
  charts/stable/youtrack/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8419 chore(deps): update container image tccr.io/truecharts/wordpress to v
  charts/stable/wordpress/Chart.yaml
  charts/stable/wordpress/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8450 chore(deps): update container image tccr.io/truecharts/grist to v1.0.9
  charts/stable/grist/Chart.yaml
  charts/stable/grist/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8573 chore(deps): update container image tccr.io/truecharts/focalboard to v7.10.0
  charts/stable/focalboard/Chart.yaml
  charts/stable/focalboard/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8263 chore(deps): update container image tccr.io/truecharts/synapse to v1.82.0
  charts/stable/synapse/Chart.yaml
  charts/stable/synapse/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8288 chore(deps): update penpot to v1.18.1 (minor)
  charts/stable/penpot/Chart.yaml
  charts/stable/penpot/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8733 chore(deps): update container image tccr.io/truecharts/synclounge to 5.2.5
  charts/stable/synclounge/Chart.yaml
  charts/stable/synclounge/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8740 chore(deps): update container image tccr.io/truecharts/matomo to 4.14.2
  charts/stable/matomo/Chart.yaml
  charts/stable/matomo/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8594 chore(deps): update container image tccr.io/truecharts/linkace to v1.12.0
  charts/stable/linkace/Chart.yaml
  charts/stable/linkace/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8306 chore(deps): update container image tccr.io/truecharts/youtrack to v2023.1.9031
  charts/stable/youtrack/Chart.yaml
  charts/stable/youtrack/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8545 chore(deps): update authentik to v2023.4.1 (minor)
  charts/stable/authentik/Chart.yaml
  charts/stable/authentik/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8743 chore(deps): update renovatebot/github-action action to v36.1.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#8745 fix(questions): fix questions.yaml
  charts/incubator/technitium/Chart.yaml
  charts/incubator/traefik-forward-auth/Chart.yaml
  charts/stable/grist/Chart.yaml
  charts/stable/grist/questions.yaml
  charts/stable/synapse/Chart.yaml
  charts/stable/synapse/questions.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#8754 chore(deps): update container image tccr.io/truecharts/minetest to 5.7.0
  charts/stable/minetest/Chart.yaml
  charts/stable/minetest/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#8751 fix(idrac-fan): Clean up questions
  charts/incubator/dell-idrac-fan-controller/Chart.yaml
  charts/incubator/dell-idrac-fan-controller/questions.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#8758 chore(deps): update container image tccr.io/truecharts/lancache-monolithic to latest
  charts/stable/lancache-monolithic/Chart.yaml
  charts/stable/lancache-monolithic/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#8707 fix(lancache-dns) fix options not being loaded.
  charts/stable/lancache-dns/Chart.yaml
  charts/stable/lancache-dns/questions.yaml
  charts/stable/lancache-dns/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#8766 chore(deps): update container image tccr.io/truecharts/cura-novnc to latest
  charts/stable/cura-novnc/Chart.yaml
  charts/stable/cura-novnc/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#8768 fix(Portainer): fix rbac
  charts/stable/portainer/Chart.yaml
  charts/stable/portainer/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#8769 chore(deps): update container image tccr.io/truecharts/mosdns to 5.1.3
  charts/stable/mosdns/Chart.yaml
  charts/stable/mosdns/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#8777 chore(deps): update container image tccr.io/truecharts/rdesktop-arch-kde to latest
  charts/stable/rdesktop/Chart.yaml
  charts/stable/rdesktop/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#8772 chore(deps): update container image tccr.io/truecharts/mariadb to 10.11.2
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/mariadb/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#8775 chore(deps): update container image tccr.io/truecharts/postgresql to 14.7.0
  charts/stable/postgresql/Chart.yaml
  charts/stable/postgresql/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#8770 chore(deps): update container image tccr.io/truecharts/adminer to latest
  charts/stable/adminer/Chart.yaml
  charts/stable/adminer/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#8776 chore(deps): update container image tccr.io/truecharts/prusaslicer-novnc to latest
  charts/stable/prusaslicer-novnc/Chart.yaml
  charts/stable/prusaslicer-novnc/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#8779 chore(deps): update container image tccr.io/truecharts/scratch to latest
  charts/enterprise/cert-manager/Chart.yaml
  charts/enterprise/cert-manager/values.yaml
  charts/enterprise/metallb/Chart.yaml
  charts/enterprise/metallb/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/enterprise/patch

#8778 chore(deps): update container image tccr.io/truecharts/rsshub to latest
  charts/stable/rsshub/Chart.yaml
  charts/stable/rsshub/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#8774 chore(deps): update container image tccr.io/truecharts/omada-controller to 5.9.0
  charts/stable/omada-controller/Chart.yaml
  charts/stable/omada-controller/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#8781 chore(deps): update container image tccr.io/truecharts/snapdrop to latest
  charts/stable/snapdrop/Chart.yaml
  charts/stable/snapdrop/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8771 chore(deps): update container image tccr.io/truecharts/littlelink-server to latest
  charts/stable/littlelink/Chart.yaml
  charts/stable/littlelink/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8773 chore(deps): update container image tccr.io/truecharts/minecraft-java19 to latest
  charts/stable/minecraft-java/Chart.yaml
  charts/stable/minecraft-java/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8787 chore(deps): update container image ghcr.io/truecharts/devcontainer to v3.1.10
  .github/workflows/catalog-test.yaml
  .github/workflows/charts-release.yaml
  .github/workflows/daily.yaml
  .github/workflows/renovate-bump.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#8789 Update ct-lint.yaml
  .github/ct-install.yaml
  .github/ct-lint.yaml
  .github/scripts/fetch_helm_deps.sh
  .github/workflows/charts-lint.yaml
  charts/stable/jackett/Chart.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#8785 chore(deps): update helm chart common to 12.6.6
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
Labels: size/S, lint:ok, precommit:ok, automerge

#8786 chore(deps): update helm chart common to 12.6.6
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#8795 chore(deps): update renovatebot/github-action action to v36.1.1
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#8792 feat(apps): Add podOptions in questions.yaml
  charts/stable/home-assistant/Chart.yaml
  charts/stable/home-assistant/questions.yaml
  charts/stable/omada-controller/Chart.yaml
  charts/stable/omada-controller/questions.yaml
  charts/stable/zerotier/Chart.yaml
  charts/stable/zerotier/questions.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#8791 fix(portainer) portainer requires automountServiceAccountToken true
  charts/stable/portainer/Chart.yaml
  charts/stable/portainer/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#8790 fix(deconz): Breaking change port to new common
  charts/stable/deconz/Chart.yaml
  charts/stable/deconz/ci/test-values.yaml
  charts/stable/deconz/templates/common.yaml
  charts/stable/deconz/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#8797 feat(dell-idrac-fan-controller): Move stable + docs
  charts/stable/dell-idrac-fan-controller/.helmignore
  charts/stable/dell-idrac-fan-controller/CHANGELOG.md
  charts/stable/dell-idrac-fan-controller/Chart.yaml
  charts/stable/dell-idrac-fan-controller/README.md
  charts/stable/dell-idrac-fan-controller/docs/img/OStoiDracPassThrough.png
  charts/stable/dell-idrac-fan-controller/docs/install-notes.md
  charts/stable/dell-idrac-fan-controller/icon.png
  charts/stable/dell-idrac-fan-controller/questions.yaml
  charts/stable/dell-idrac-fan-controller/templates/NOTES.txt
  charts/stable/dell-idrac-fan-controller/templates/common.yaml
  charts/stable/dell-idrac-fan-controller/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#8784 fix(homeassistant): Ensure appended config files start on new line.
  charts/stable/home-assistant/Chart.yaml
  charts/stable/home-assistant/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#8803 fix(custom-app): fix probes indent and re-hide port
  charts/stable/custom-app/questions.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#8808 fix(custom-app): bump
  charts/stable/custom-app/Chart.yaml
  charts/stable/custom-app/questions.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#8811 chore(deps): update container image tccr.io/truecharts/nextpvr to latest
  charts/stable/nextpvr/Chart.yaml
  charts/stable/nextpvr/values.yaml
Labels: size/XS, automerge, update/docker/general/non-major

#8812 chore(deps): update container image tccr.io/truecharts/anonaddy to v0.14.1
  charts/stable/anonaddy/Chart.yaml
  charts/stable/anonaddy/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#8813 chore(deps): update container image tccr.io/truecharts/audiobookshelf to v2.2.20
  charts/stable/audiobookshelf/Chart.yaml
  charts/stable/audiobookshelf/values.yaml
Labels: size/XS, automerge, update/docker/general/non-major

#8814 chore(deps): update container image tccr.io/truecharts/clickhouse to v23.4.2.11
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/clickhouse/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#8815 chore(deps): update container image tccr.io/truecharts/domoticz to v2023.1.20230504
  charts/stable/domoticz/Chart.yaml
  charts/stable/domoticz/values.yaml
Labels: size/XS, automerge, update/docker/general/non-major

#8810 fix(ci): don't fail if directory exists
  .github/workflows/charts-release.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#8816 chore(deps): update container image tccr.io/truecharts/drawio to v21.2.9
  charts/stable/drawio/Chart.yaml
  charts/stable/drawio/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#8817 chore(deps): update container image tccr.io/truecharts/esphome to v2023.4.4
  charts/stable/esphome/Chart.yaml
  charts/stable/esphome/values.yaml
Labels: size/XS, automerge, update/docker/general/non-major

#8818 chore(deps): update container image tccr.io/truecharts/filebot to v23.04.2
  charts/stable/filebot/Chart.yaml
  charts/stable/filebot/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#8819 chore(deps): update container image tccr.io/truecharts/flexget to v3.6.7
  charts/stable/flexget/Chart.yaml
  charts/stable/flexget/values.yaml
Labels: size/XS, automerge, update/docker/general/non-major

#8820 chore(deps): update container image tccr.io/truecharts/gitea to v1.19.3
  charts/stable/gitea/Chart.yaml
  charts/stable/gitea/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#8821 fix(mongo-express): Fix persistence question error
  charts/incubator/mongo-express/Chart.yaml
  charts/incubator/mongo-express/questions.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#8823 chore(deps): update container image tccr.io/truecharts/ipfs to v0.19.2
  charts/stable/ipfs/Chart.yaml
  charts/stable/ipfs/values.yaml
Labels: size/XS, automerge, update/docker/general/non-major

#8822 chore(deps): update container image tccr.io/truecharts/homepage to v0.6.17
  charts/stable/homepage/Chart.yaml
  charts/stable/homepage/values.yaml
Labels: size/XS, automerge, update/docker/general/non-major

#8824 chore(deps): update container image tccr.io/truecharts/kavita to v0.7.2
  charts/stable/kavita/Chart.yaml
  charts/stable/kavita/values.yaml
Labels: size/XS, automerge, update/docker/general/non-major

#8829 chore(deps): update container image tccr.io/truecharts/makemkv to v23.04.2
  charts/stable/makemkv/Chart.yaml
  charts/stable/makemkv/values.yaml
Labels: size/XS, automerge, update/docker/general/non-major

#8830 chore(deps): update container image tccr.io/truecharts/mediainfo to v23.04.2
  charts/stable/mediainfo/Chart.yaml
  charts/stable/mediainfo/values.yaml
Labels: size/XS, automerge, update/docker/general/non-major

#8832 chore(deps): update container image tccr.io/truecharts/minio-console to v0.26.4
  charts/stable/minio-console/Chart.yaml
  charts/stable/minio-console/values.yaml
Labels: size/XS, automerge, update/docker/general/non-major

#8833 chore(deps): update container image tccr.io/truecharts/n8n to v0.226.2
  charts/stable/n8n/Chart.yaml
  charts/stable/n8n/values.yaml
Labels: size/XS, automerge, update/docker/general/non-major

#8834 chore(deps): update container image tccr.io/truecharts/outline to v0.69.2
  charts/stable/outline/Chart.yaml
  charts/stable/outline/values.yaml
Labels: size/XS, automerge, update/docker/general/non-major

#8836 chore(deps): update container image tccr.io/truecharts/portainer-ce to v2.18.2
  charts/stable/portainer/Chart.yaml
  charts/stable/portainer/values.yaml
Labels: size/XS, automerge, update/docker/general/non-major

#8835 chore(deps): update container image tccr.io/truecharts/paperless-ng to v1.14.4
  charts/stable/paperless-ngx/Chart.yaml
  charts/stable/paperless-ngx/values.yaml
Labels: size/XS, automerge, update/docker/general/non-major

#8838 chore(deps): update container image tccr.io/truecharts/prowlarr to v1.4.1.3258
  charts/stable/prowlarr/Chart.yaml
  charts/stable/prowlarr/values.yaml
Labels: size/XS, automerge, update/docker/general/non-major
