Repository trueforge-org/truecharts, pull requests merged in 2023-02, with the labels that each got.

#6808 fix(ci): Chart.yaml update bugs
  .github/workflows/daily.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#6820 chore(deps): update kitchenowl
  charts/stable/kitchenowl/Chart.yaml
  charts/stable/kitchenowl/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#6819 chore(kasm): Add basic Kasm installation information
  charts/stable/kasm/Chart.yaml
  charts/stable/kasm/docs/installation_notes.md
Labels: size/S, lint:failed, precommit:ok

#6743 feat(Factorio): Add proper Env Vars/Ports before Stable
  charts/incubator/factorio/Chart.yaml
  charts/incubator/factorio/questions.yaml
  charts/incubator/factorio/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#6610 fix(plexripper) cleanup gui and code BREAKING CHANGES removed persistence of extra dirs.
  charts/incubator/plexripper/Chart.yaml
  charts/incubator/plexripper/questions.yaml
  charts/incubator/plexripper/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#6850 chore(deps): update container image tccr.io/truecharts/dokuwiki to 20220731.1.0
  charts/stable/dokuwiki/Chart.yaml
  charts/stable/dokuwiki/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6851 chore(deps): update container image tccr.io/truecharts/factorio to vstable
  charts/incubator/factorio/Chart.yaml
  charts/incubator/factorio/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6889 chore(deps): update container image tccr.io/truecharts/rsshub to latest
  charts/stable/rsshub/Chart.yaml
  charts/stable/rsshub/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6861 chore(deps): update container image tccr.io/truecharts/jenkins to 2.388.0
  charts/incubator/jenkins/Chart.yaml
  charts/incubator/jenkins/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6859 chore(deps): update container image tccr.io/truecharts/heimdall to 2.5.5
  charts/stable/heimdall/Chart.yaml
  charts/stable/heimdall/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6844 chore(deps): update container image tccr.io/truecharts/cyberchef to 9.55.0
  charts/stable/cyberchef/Chart.yaml
  charts/stable/cyberchef/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6843 chore(deps): update container image tccr.io/truecharts/cups-server to latest
  charts/incubator/cups-server/Chart.yaml
  charts/incubator/cups-server/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6869 chore(deps): update container image tccr.io/truecharts/memcached to 1.6.18
  charts/dependency/memcached/Chart.yaml
  charts/dependency/memcached/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6836 chore(deps): update container image tccr.io/truecharts/check-mk-raw to v2.1.0
  charts/incubator/checkmk/Chart.yaml
  charts/incubator/checkmk/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6839 chore(deps): update container image tccr.io/truecharts/cloudcommander to latest
  charts/incubator/cloudcommander/Chart.yaml
  charts/incubator/cloudcommander/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6866 chore(deps): update container image tccr.io/truecharts/littlelink-server to latest
  charts/stable/littlelink/Chart.yaml
  charts/stable/littlelink/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6849 chore(deps): update container image tccr.io/truecharts/docker-in-docker to 20.10.23
  charts/stable/docker-compose/Chart.yaml
  charts/stable/docker-compose/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6868 chore(deps): update container image tccr.io/truecharts/mariadb to 10.10.2
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/mariadb/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6867 chore(deps): update container image tccr.io/truecharts/logitechmediaserver to 8.4.0
  charts/stable/logitech-media-server/Chart.yaml
  charts/stable/logitech-media-server/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6842 chore(deps): update container image tccr.io/truecharts/cryptpad to latest
  charts/incubator/cryptpad/Chart.yaml
  charts/incubator/cryptpad/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6880 chore(deps): update container image tccr.io/truecharts/postgresql to 14.6.0
  charts/dependency/postgresql/Chart.yaml
  charts/dependency/postgresql/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6875 chore(deps): update container image tccr.io/truecharts/openspeedtest to latest
  charts/stable/openspeedtest/Chart.yaml
  charts/stable/openspeedtest/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6822 chore(deps): update container image tccr.io/truecharts/solr to 9.1.1
  charts/dependency/solr/Chart.yaml
  charts/dependency/solr/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6818 chore(deps): update container image tccr.io/truecharts/rstudio to v4.2.2
  charts/incubator/rstudio/Chart.yaml
  charts/incubator/rstudio/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6905 chore(deps): update container image tccr.io/truecharts/fluidd to v1.23.1
  charts/stable/fluidd/Chart.yaml
  charts/stable/fluidd/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6894 chore(deps): update container image tccr.io/truecharts/snapdrop to latest
  charts/stable/snapdrop/Chart.yaml
  charts/stable/snapdrop/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6899 chore(deps): update container image tccr.io/truecharts/tubearchivist-redisjson to latest
  charts/incubator/tubearchivist-redisjson/Chart.yaml
  charts/incubator/tubearchivist-redisjson/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6902 chore(deps): update container image tccr.io/truecharts/posterr to latest
  charts/stable/posterr/Chart.yaml
  charts/stable/posterr/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6903 chore(deps): update container image tccr.io/truecharts/collabora to v22.05.10.1.1
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/collabora-online/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6890 chore(deps): update container image tccr.io/truecharts/scprime to latest
  charts/incubator/scprime/Chart.yaml
  charts/incubator/scprime/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6901 chore(deps): update container image tccr.io/truecharts/vertex to vstable
  charts/incubator/vertex/Chart.yaml
  charts/incubator/vertex/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6907 chore(deps): update container image tccr.io/truecharts/jellyseerr to v1.4.1
  charts/stable/jellyseerr/Chart.yaml
  charts/stable/jellyseerr/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6912 chore(deps): update container image tccr.io/truecharts/sourcegraph to v4.4.2
  charts/incubator/sourcegraph/Chart.yaml
  charts/incubator/sourcegraph/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6810 chore(deps): update container image tccr.io/truecharts/minio-console to v0.23.0
  charts/stable/minio-console/Chart.yaml
  charts/stable/minio-console/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6873 chore(deps): update container image tccr.io/truecharts/nginx-unprivileged to 1.23.3
  charts/stable/nextcloud/Chart.yaml
  charts/stable/nextcloud/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6919 chore(deps): update container image tccr.io/truecharts/jenkins to v2.389.0
  charts/incubator/jenkins/Chart.yaml
  charts/incubator/jenkins/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6908 chore(deps): update container image tccr.io/truecharts/loki to v2.7.3
  charts/stable/loki/Chart.yaml
  charts/stable/loki/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6811 chore(deps): update container image tccr.io/truecharts/picoshare to v1.3.1
  charts/stable/picoshare/Chart.yaml
  charts/stable/picoshare/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6911 chore(deps): update container image tccr.io/truecharts/qinglong to v2.15.6
  charts/stable/qinglong/Chart.yaml
  charts/stable/qinglong/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6823 chore(deps): update container image tccr.io/truecharts/matomo to 4.13.3
  charts/stable/matomo/Chart.yaml
  charts/stable/matomo/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6916 chore(deps): update zabbix to v6.2.7 (patch)
  charts/incubator/zabbix/Chart.yaml
  charts/incubator/zabbix/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6812 chore(deps): update container image tccr.io/truecharts/misskey to v13.2.6
  charts/incubator/misskey/Chart.yaml
  charts/incubator/misskey/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6872 chore(deps): update container image tccr.io/truecharts/netbox to 3.4.3
  charts/incubator/netbox/Chart.yaml
  charts/incubator/netbox/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6922 chore(deps): update container image tccr.io/truecharts/zigbee2mqtt to v1.30.0
  charts/stable/zigbee2mqtt/Chart.yaml
  charts/stable/zigbee2mqtt/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6876 chore(deps): update container image tccr.io/truecharts/passwordpusherephemeral to latest
  charts/incubator/passwordpusherephemeral/Chart.yaml
  charts/incubator/passwordpusherephemeral/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6855 chore(deps): update container image tccr.io/truecharts/goaccess-npm-logs to latest
  charts/incubator/goaccess-npm-logs/Chart.yaml
  charts/incubator/goaccess-npm-logs/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6835 chore(deps): update container image tccr.io/truecharts/calibre-web to 0.6.19
  charts/stable/calibre-web/Chart.yaml
  charts/stable/calibre-web/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6898 chore(deps): update container image tccr.io/truecharts/ts-dnsserver to latest
  charts/incubator/ts-dnsserver/Chart.yaml
  charts/incubator/ts-dnsserver/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6886 chore(deps): update container image tccr.io/truecharts/red-discordbot to vfull
  charts/incubator/red-discordbot/Chart.yaml
  charts/incubator/red-discordbot/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6877 chore(deps): update container image tccr.io/truecharts/pialert to latest
  charts/stable/pialert/Chart.yaml
  charts/stable/pialert/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6807 chore(deps): update container image tccr.io/truecharts/omada-controller to 5.8.0
  charts/stable/omada-controller/Chart.yaml
  charts/stable/omada-controller/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6918 chore(deps): update container image tccr.io/truecharts/home-assistant to v2023.2.1
  charts/stable/home-assistant/Chart.yaml
  charts/stable/home-assistant/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6838 chore(deps): update container image tccr.io/truecharts/chromium-desktop-g3 to latest
  charts/incubator/chromium-desktop-g3/Chart.yaml
  charts/incubator/chromium-desktop-g3/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6824 chore(deps): update container image tccr.io/truecharts/guide2go to latest
  charts/incubator/guide2go/Chart.yaml
  charts/incubator/guide2go/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6942 chore(deps): update container image ghcr.io/truecharts/promtail to v2.7.3
  charts/dependency/promtail/Chart.yaml
  charts/dependency/promtail/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6933 chore(deps): update container image tccr.io/truecharts/wifi-card to latest
  charts/incubator/wifi-card/Chart.yaml
  charts/incubator/wifi-card/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6853 chore(deps): update container image tccr.io/truecharts/firefox-desktop-g3 to latest
  charts/incubator/firefox-desktop-g3/Chart.yaml
  charts/incubator/firefox-desktop-g3/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6931 chore(deps): update container image tccr.io/truecharts/webp-server to latest
  charts/incubator/webp-server/Chart.yaml
  charts/incubator/webp-server/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6929 chore(deps): update container image tccr.io/truecharts/ra-rom-processor to latest
  charts/incubator/ra-rom-processor/Chart.yaml
  charts/incubator/ra-rom-processor/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6927 chore(deps): update container image tccr.io/truecharts/flexget to 3.5.21
  charts/stable/flexget/Chart.yaml
  charts/stable/flexget/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6930 chore(deps): update container image tccr.io/truecharts/virt-manager to latest
  charts/incubator/virt-manager/Chart.yaml
  charts/incubator/virt-manager/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6833 chore(deps): update container image tccr.io/truecharts/briefkasten to latest
  charts/incubator/briefkasten/Chart.yaml
  charts/incubator/briefkasten/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6943 chore(deps): update container image tccr.io/truecharts/adguard-home to v0.107.23
  charts/stable/adguard-home/Chart.yaml
  charts/stable/adguard-home/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6928 chore(deps): update container image tccr.io/truecharts/nitter to latest
  charts/incubator/nitter/Chart.yaml
  charts/incubator/nitter/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6846 chore(deps): update container image tccr.io/truecharts/dashy to 2.1.1
  charts/incubator/dashy/Chart.yaml
  charts/incubator/dashy/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6900 chore(deps): update container image tccr.io/truecharts/twonky-server to latest
  charts/incubator/twonky-server/Chart.yaml
  charts/incubator/twonky-server/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6945 chore(deps): update container image tccr.io/truecharts/drawio to v20.8.15
  charts/stable/drawio/Chart.yaml
  charts/stable/drawio/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6949 chore(deps): update container image tccr.io/truecharts/pingvin-share to v0.9.0
  charts/incubator/pingvin-share/Chart.yaml
  charts/incubator/pingvin-share/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6947 chore(deps): update jitsi to v8252 (patch)
  charts/incubator/jitsi/Chart.yaml
  charts/incubator/jitsi/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6944 chore(deps): update container image tccr.io/truecharts/audiobookshelf to v2.2.14
  charts/stable/audiobookshelf/Chart.yaml
  charts/stable/audiobookshelf/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6946 chore(deps): update container image tccr.io/truecharts/grist to v1.0.7
  charts/stable/grist/Chart.yaml
  charts/stable/grist/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6938 chore(deps): update minecraft-java
  charts/stable/minecraft-java/Chart.yaml
  charts/stable/minecraft-java/ci/j11-values.yaml
  charts/stable/minecraft-java/ci/j11j9-values.yaml
  charts/stable/minecraft-java/ci/j8-values.yaml
  charts/stable/minecraft-java/ci/j8j9-values.yaml
  charts/stable/minecraft-java/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6939 chore(deps): update neko
  charts/incubator/neko/Chart.yaml
  charts/incubator/neko/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok, automerge

#6948 chore(deps): update container image tccr.io/truecharts/onlyoffice-ds to v7.3.0
  charts/stable/onlyoffice-document-server/Chart.yaml
  charts/stable/onlyoffice-document-server/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6935 chore(deps): update container image tccr.io/truecharts/wordpress to 6.1.1
  charts/stable/wordpress/Chart.yaml
  charts/stable/wordpress/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6921 chore(deps): update container image tccr.io/truecharts/prometheus to v2.42.0
  charts/enterprise/prometheus/Chart.yaml
  charts/enterprise/prometheus/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#6940 chore(deps): update rdesktop
  charts/stable/rdesktop/Chart.yaml
  charts/stable/rdesktop/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok, automerge

#6941 chore(deps): update webtop
  charts/stable/webtop/Chart.yaml
  charts/stable/webtop/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok, automerge

#6829 chore(deps): update container image tccr.io/truecharts/beets to v1.6.0
  charts/stable/beets/Chart.yaml
  charts/stable/beets/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6840 chore(deps): update container image tccr.io/truecharts/cloudflareddns to latest
  charts/stable/cloudflareddns/Chart.yaml
  charts/stable/cloudflareddns/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6834 chore(deps): update container image tccr.io/truecharts/calibre to 6.11.0
  charts/stable/calibre/Chart.yaml
  charts/stable/calibre/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6854 chore(deps): update container image tccr.io/truecharts/freshrss to 1.20.2
  charts/stable/freshrss/Chart.yaml
  charts/stable/freshrss/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6871 chore(deps): update container image tccr.io/truecharts/mongodb to 6.0.4
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/mongodb/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6841 chore(deps): update container image tccr.io/truecharts/cops to latest
  charts/stable/cops/Chart.yaml
  charts/stable/cops/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6848 chore(deps): update container image tccr.io/truecharts/dillinger to v3.39.1
  charts/stable/dillinger/Chart.yaml
  charts/stable/dillinger/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6817 chore(deps): update container image tccr.io/truecharts/telethon-downloader to latest
  charts/incubator/telethon-downloader/Chart.yaml
  charts/incubator/telethon-downloader/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6837 chore(deps): update container image tccr.io/truecharts/chromium to latest
  charts/incubator/chromium/Chart.yaml
  charts/incubator/chromium/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6879 chore(deps): update container image tccr.io/truecharts/plextraktsync to latest
  charts/incubator/plextraktsync/Chart.yaml
  charts/incubator/plextraktsync/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6870 chore(deps): update container image tccr.io/truecharts/minio to latest
  charts/stable/minio/Chart.yaml
  charts/stable/minio/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6887 chore(deps): update container image tccr.io/truecharts/redis to 7.0.8
  charts/dependency/redis/Chart.yaml
  charts/dependency/redis/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6830 chore(deps): update container image tccr.io/truecharts/blender to latest
  charts/incubator/blender/Chart.yaml
  charts/incubator/blender/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6857 chore(deps): update container image tccr.io/truecharts/habridge to v5.4.1
  charts/stable/habridge/Chart.yaml
  charts/stable/habridge/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6831 chore(deps): update container image tccr.io/truecharts/blog to latest
  charts/stable/blog/Chart.yaml
  charts/stable/blog/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6937 chore(deps): update jupyter
  charts/stable/jupyter/Chart.yaml
  charts/stable/jupyter/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6906 chore(deps): update container image tccr.io/truecharts/homepage to v0.6.6
  charts/stable/homepage/Chart.yaml
  charts/stable/homepage/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6883 chore(deps): update container image tccr.io/truecharts/qflood to latest
  charts/incubator/qflood/Chart.yaml
  charts/incubator/qflood/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6891 chore(deps): update container image tccr.io/truecharts/searx to latest
  charts/incubator/searx/Chart.yaml
  charts/incubator/searx/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6863 chore(deps): update container image tccr.io/truecharts/lazylibrarian to latest
  charts/stable/lazylibrarian/Chart.yaml
  charts/stable/lazylibrarian/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6874 chore(deps): update container image tccr.io/truecharts/ombi to 4.35.3
  charts/stable/ombi/Chart.yaml
  charts/stable/ombi/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6893 chore(deps): update container image tccr.io/truecharts/sia-daemon to vmaster
  charts/incubator/sia-daemon/Chart.yaml
  charts/incubator/sia-daemon/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6858 chore(deps): update container image tccr.io/truecharts/hedgedoc to 1.9.6
  charts/stable/hedgedoc/Chart.yaml
  charts/stable/hedgedoc/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6897 chore(deps): update container image tccr.io/truecharts/tracks to latest
  charts/incubator/tracks/Chart.yaml
  charts/incubator/tracks/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6860 chore(deps): update container image tccr.io/truecharts/invidious to latest
  charts/stable/invidious/Chart.yaml
  charts/stable/invidious/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6862 chore(deps): update container image tccr.io/truecharts/kdenlive to latest
  charts/incubator/kdenlive/Chart.yaml
  charts/incubator/kdenlive/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6888 chore(deps): update container image tccr.io/truecharts/rimgo to latest
  charts/incubator/rimgo/Chart.yaml
  charts/incubator/rimgo/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6856 chore(deps): update container image tccr.io/truecharts/grocy to 3.3.2
  charts/stable/grocy/Chart.yaml
  charts/stable/grocy/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6904 chore(deps): update container image tccr.io/truecharts/domoticz to v2022.2.20230202
  charts/stable/domoticz/Chart.yaml
  charts/stable/domoticz/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6910 chore(deps): update container image tccr.io/truecharts/prowlarr to v1.1.2.2453
  charts/stable/prowlarr/Chart.yaml
  charts/stable/prowlarr/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6813 chore(deps): update container image tccr.io/truecharts/plex-utills to latest
  charts/stable/plex-utills/Chart.yaml
  charts/stable/plex-utills/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6936 chore(deps): update container image tccr.io/truecharts/yacy to latest
  charts/incubator/yacy/Chart.yaml
  charts/incubator/yacy/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6934 chore(deps): update container image tccr.io/truecharts/wireshark to 3.6.5
  charts/stable/wireshark/Chart.yaml
  charts/stable/wireshark/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6864 chore(deps): update container image tccr.io/truecharts/libremdb to latest
  charts/stable/libremdb/Chart.yaml
  charts/stable/libremdb/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6909 chore(deps): update container image tccr.io/truecharts/overseerr to v1.32.5
  charts/stable/overseerr/Chart.yaml
  charts/stable/overseerr/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6896 chore(deps): update container image tccr.io/truecharts/speedtest-tracker to latest
  charts/incubator/speedtest-tracker/Chart.yaml
  charts/incubator/speedtest-tracker/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6914 chore(deps): update container image tccr.io/truecharts/youtrack to v2022.3.65369
  charts/stable/youtrack/Chart.yaml
  charts/stable/youtrack/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6920 chore(deps): update container image tccr.io/truecharts/money-balancer to v1.3.0
  charts/incubator/money-balancer/Chart.yaml
  charts/incubator/money-balancer/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6884 chore(deps): update container image tccr.io/truecharts/quassel-core to v0.14.0
  charts/stable/quassel-core/Chart.yaml
  charts/stable/quassel-core/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6917 chore(deps): update container image tccr.io/truecharts/ghost to v5.33.5
  charts/incubator/ghost/Chart.yaml
  charts/incubator/ghost/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6954 chore(deps): update immich to v1.44.0 (minor)
  charts/stable/immich/Chart.yaml
  charts/stable/immich/values.yaml
Labels: size/XS, automerge, update/docker/general/non-major

#6955 chore(deps): update container image tccr.io/truecharts/dashdot to v4.8.3
  charts/stable/dashdot/Chart.yaml
  charts/stable/dashdot/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#6952 chore(deps): pin dessant/lock-threads action to
  .github/workflows/daily.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#6692 docs(plex) add community migration guide
  charts/stable/plex/Chart.yaml
  charts/stable/plex/docs/img/media-dataset-perms.png
  charts/stable/plex/docs/img/plex-503-error.png
  charts/stable/plex/docs/img/plex-config-volume-hostpath.png
  charts/stable/plex/docs/img/truetool-mount-list.png
  charts/stable/plex/docs/migration_guide.md
Labels: install:ok, lint:ok, size/L, precommit:ok

#6957 chore(deps): update container image tccr.io/truecharts/openvscode-server to 1.75.0
  charts/stable/openvscode-server/Chart.yaml
  charts/stable/openvscode-server/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#6960 chore(deps): update container image tccr.io/truecharts/poste to latest
  charts/incubator/poste/Chart.yaml
  charts/incubator/poste/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#6959 chore(deps): update container image tccr.io/truecharts/jenkins to 2.389.0
  charts/incubator/jenkins/Chart.yaml
  charts/incubator/jenkins/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#6964 chore(deps): update container image tccr.io/truecharts/xwiki to v15.0.0
  charts/stable/xwiki/Chart.yaml
  charts/stable/xwiki/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/major

#6961 feat(NextPVR): Add missing UDP ports
  charts/stable/nextpvr/Chart.yaml
  charts/stable/nextpvr/questions.yaml
  charts/stable/nextpvr/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#6962 chore(deps): update renovatebot/github-action action to v34.122.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#6966 chore(deps): update container image tccr.io/truecharts/monica to v4.0.0
  charts/stable/monica/Chart.yaml
  charts/stable/monica/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6968 feat(Tailscale): More info in How-To
  charts/stable/tailscale/Chart.yaml
  charts/stable/tailscale/docs/How-To-Guide.md
Labels: size/XS, install:ok, lint:ok, precommit:ok

#6969 chore(deps): update renovatebot/github-action action to v34.124.1
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#6975 chore(deps): update container image tccr.io/truecharts/ghost to v5.33.6
  charts/incubator/ghost/Chart.yaml
  charts/incubator/ghost/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6980 chore(deps): update container image tccr.io/truecharts/fileshelter to latest
  charts/incubator/fileshelter/Chart.yaml
  charts/incubator/fileshelter/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#6981 chore(deps): update container image tccr.io/truecharts/mysql-workbench to 8.0.32
  charts/stable/mysql-workbench/Chart.yaml
  charts/stable/mysql-workbench/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#6978 chore(deps): update container image tccr.io/truecharts/netbox to v3.4.4
  charts/incubator/netbox/Chart.yaml
  charts/incubator/netbox/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6989 chore(deps): update container image tccr.io/truecharts/prowlarr to v1.1.3.2521
  charts/stable/prowlarr/Chart.yaml
  charts/stable/prowlarr/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#6987 chore(deps): update container image tccr.io/truecharts/ispy-agent-dvr to v4.4.9.0
  charts/stable/ispy-agent-dvr/Chart.yaml
  charts/stable/ispy-agent-dvr/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#6988 chore(deps): update container image tccr.io/truecharts/navidrome to v0.49.1
  charts/stable/navidrome/Chart.yaml
  charts/stable/navidrome/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#6992 chore(deps): update container image tccr.io/truecharts/mediainfo to v23.02.1
  charts/stable/mediainfo/Chart.yaml
  charts/stable/mediainfo/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#6993 chore(deps): update container image tccr.io/truecharts/mkvtoolnix to v23.02.1
  charts/stable/mkvtoolnix/Chart.yaml
  charts/stable/mkvtoolnix/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#6996 chore(deps): update container image tccr.io/truecharts/qdirstat to v23.02.1
  charts/stable/qdirstat/Chart.yaml
  charts/stable/qdirstat/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#6997 chore(deps): update container image tccr.io/truecharts/tsmuxer to v23.02.1
  charts/stable/tsmuxer/Chart.yaml
  charts/stable/tsmuxer/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#6991 chore(deps): update container image tccr.io/truecharts/jdownloader-2 to v23.02.1
  charts/stable/jdownloader2/Chart.yaml
  charts/stable/jdownloader2/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#6995 chore(deps): update container image tccr.io/truecharts/putty to v23.02.1
  charts/stable/putty/Chart.yaml
  charts/stable/putty/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#6990 chore(deps): update container image tccr.io/truecharts/focalboard to v7.8.0
  charts/stable/focalboard/Chart.yaml
  charts/stable/focalboard/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#6998 chore(deps): update container image tccr.io/truecharts/xenorchestra to v5.109.0
  charts/stable/xen-orchestra/Chart.yaml
  charts/stable/xen-orchestra/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#6994 chore(deps): update container image tccr.io/truecharts/n8n to v0.214.0
  charts/stable/n8n/Chart.yaml
  charts/stable/n8n/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#7000 chore(deps): update container image tccr.io/truecharts/clickhouse to v23.1.3.5
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/clickhouse/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#7001 chore(deps): update container image tccr.io/truecharts/misskey to v13.4.0
  charts/incubator/misskey/Chart.yaml
  charts/incubator/misskey/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#7002 chore(deps): update container image tccr.io/truecharts/bookstack to v23.01.20230131
  charts/stable/bookstack/Chart.yaml
  charts/stable/bookstack/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge
