Repository trueforge-org/truecharts, pull requests merged in 2023-04, with the labels that each got.

#7866 Stablefixesport
  charts/stable/fireflyiii/values.yaml
  charts/stable/guacamole-client/values.yaml
  charts/stable/joplin-server/values.yaml
  charts/stable/lidarr/values.yaml
  charts/stable/n8n/values.yaml
  charts/stable/onlyoffice-document-server/values.yaml
  charts/stable/radarr/values.yaml
  charts/stable/readarr/values.yaml
  charts/stable/rtmpserver/values.yaml
  charts/stable/scrutiny/values.yaml
  charts/stable/sdtd/values.yaml
  charts/stable/shiori/values.yaml
  charts/stable/shlink-web-client/values.yaml
  charts/stable/shlink/values.yaml
  charts/stable/shoko-server/values.yaml
  charts/stable/shorturl/values.yaml
  charts/stable/statping-ng/values.yaml
  charts/stable/weblate/values.yaml
  charts/stable/wikijs/values.yaml
Labels: size/M, precommit:ok

#7872 Chore(CI): disable renovate on everything but enterprise/dependency train
  .github/renovate.json5
Labels: size/S

#7894 chore(deps): update renovatebot/github-action action to v36.0.2
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#7893 chore(deps): update helm chart common to 12.2.32
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#7892 chore(deps): update actions/stale action to v8
  .github/workflows/stale.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#7891 chore(deps): update tj-actions/branch-names action to v6.5
  .github/workflows/pr-metadata.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#7885 chore(deps): update actions/checkout action to v3.5.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#7878 chore(deps): update container image tccr.io/truecharts/grafana to v
  charts/enterprise/grafana/Chart.yaml
  charts/enterprise/grafana/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#7880 chore(deps): update container image tccr.io/truecharts/scratch to latest
  charts/enterprise/cert-manager/Chart.yaml
  charts/enterprise/cert-manager/values.yaml
  charts/enterprise/metallb/Chart.yaml
  charts/enterprise/metallb/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#7883 chore(deps): update container image tccr.io/truecharts/traefik to v2.9.9
  charts/enterprise/traefik/Chart.yaml
  charts/enterprise/traefik/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#7884 chore(deps): update dawidd6/action-download-artifact action to v2.26.1
  .github/workflows/meta-label-pr-ci-status.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#7875 chore(deps): update actions/delete-package-versions digest to 0d39a63
  .github/workflows/prune.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#7874 chore(deps): update actions/checkout digest to 8f4b7f8
  .github/workflows/catalog-test.yaml
  .github/workflows/charts-changelog.yaml
  .github/workflows/charts-lint.yaml
  .github/workflows/charts-release.yaml
  .github/workflows/charts-test.yaml
  .github/workflows/daily.yaml
  .github/workflows/meta-label-pr-ci-status.yaml
  .github/workflows/metadata-label-commenter.yaml
  .github/workflows/pr-metadata.yaml
  .github/workflows/pr-validate.yaml
  .github/workflows/prune.yaml
  .github/workflows/renovate-bump.yaml
  .github/workflows/schedule-sync-labels.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#7873 chore(deps): pin dependencies
  .github/workflows/daily.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#7886 chore(deps): update container image tccr.io/truecharts/grafana to v9.4.7
  charts/enterprise/grafana/Chart.yaml
  charts/enterprise/grafana/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#7887 chore(deps): update container image tccr.io/truecharts/prometheus to v2.43.0
  charts/enterprise/prometheus/Chart.yaml
  charts/enterprise/prometheus/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#7895 chore(deps): update helm chart common to 12.3.0
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/solr/Chart.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#7896 chore(deps): update helm chart common to 12.3.0
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#7901 feat(stable): Questions.yaml A-B indents
  charts/stable/actualserver/questions.yaml
  charts/stable/adguard-home/questions.yaml
  charts/stable/adminer/questions.yaml
  charts/stable/airdcpp-webclient/questions.yaml
  charts/stable/airsonic/questions.yaml
  charts/stable/alist/questions.yaml
  charts/stable/amcrest2mqtt/questions.yaml
  charts/stable/amule/questions.yaml
  charts/stable/appdaemon/questions.yaml
  charts/stable/ariang/questions.yaml
  charts/stable/audacity/questions.yaml
  charts/stable/automatic-music-downloader/questions.yaml
  charts/stable/autoscan/questions.yaml
  charts/stable/baserow/questions.yaml
  charts/stable/bazarr/questions.yaml
  charts/stable/beets/questions.yaml
  charts/stable/blog/questions.yaml
  charts/stable/booksonic-air/questions.yaml
  charts/stable/browserless-chrome/questions.yaml
Labels: size/XL, precommit:failed

#7902 feat(Stable) Redo A-B in tmp/stable
  charts/stable/actualserver/questions.yaml
  charts/stable/adguard-home/questions.yaml
  charts/stable/adminer/questions.yaml
  tmp/stable/actualserver/questions.yaml
  tmp/stable/adguard-home/questions.yaml
  tmp/stable/adminer/questions.yaml
  tmp/stable/airdcpp-webclient/questions.yaml
  tmp/stable/airsonic/questions.yaml
  tmp/stable/alist/questions.yaml
  tmp/stable/amcrest2mqtt/questions.yaml
  tmp/stable/amule/questions.yaml
  tmp/stable/appdaemon/questions.yaml
  tmp/stable/ariang/questions.yaml
  tmp/stable/audacity/questions.yaml
  tmp/stable/automatic-music-downloader/questions.yaml
  tmp/stable/autoscan/questions.yaml
  tmp/stable/baserow/questions.yaml
  tmp/stable/bazarr/questions.yaml
  tmp/stable/beets/questions.yaml
  tmp/stable/blog/questions.yaml
  tmp/stable/booksonic-air/questions.yaml
  tmp/stable/browserless-chrome/questions.yaml
Labels: size/XL, precommit:ok

#7907 chore(deps): update helm general non-major
  charts/enterprise/authelia/Chart.yaml
  charts/enterprise/blocky/Chart.yaml
  charts/enterprise/cert-manager/Chart.yaml
  charts/enterprise/grafana/Chart.yaml
  charts/enterprise/metallb/Chart.yaml
  charts/enterprise/prometheus/Chart.yaml
  charts/enterprise/traefik/Chart.yaml
  charts/enterprise/vaultwarden/Chart.yaml
Labels: size/S, lint:ok, precommit:ok, update/helm/general/non-major

#7909 feat(docs): metallb - add note about stopped state
  charts/enterprise/metallb/docs/setup-guide.md
Labels: size/XS, install:ok, lint:ok, precommit:ok

#7915 feat(Stable): Fix Dev Charts questions A-K
  charts/dev/airsonic-advanced/questions.yaml
  charts/dev/anonaddy/questions.yaml
  charts/dev/apache-musicindex/questions.yaml
  charts/dev/apt-cacher-ng/questions.yaml
  charts/dev/aria2/questions.yaml
  charts/dev/audiobookshelf/questions.yaml
  charts/dev/authentik/questions.yaml
  charts/dev/autobrr/questions.yaml
  charts/dev/avidemux/questions.yaml
  charts/dev/babybuddy/questions.yaml
  charts/dev/boinc/questions.yaml
  charts/dev/bookstack/questions.yaml
  charts/dev/budge/questions.yaml
  charts/dev/calibre/questions.yaml
  charts/dev/clamav/questions.yaml
  charts/dev/clarkson/questions.yaml
  charts/dev/cloudflared/questions.yaml
  charts/dev/commento-plusplus/questions.yaml
  charts/dev/cops/questions.yaml
  charts/dev/darktable/questions.yaml
  charts/dev/deconz/questions.yaml
  charts/dev/digikam/questions.yaml
  charts/dev/docker-compose/questions.yaml
  charts/dev/docusaurus/questions.yaml
  charts/dev/domoticz/questions.yaml
  charts/dev/dsmr-reader/questions.yaml
  charts/dev/dupeguru/questions.yaml
  charts/dev/filebot/questions.yaml
  charts/dev/filerun/questions.yaml
  charts/dev/filezilla/questions.yaml
  charts/dev/firefox-syncserver/questions.yaml
  charts/dev/firefox/questions.yaml
  charts/dev/flaresolverr/questions.yaml
  charts/dev/flashpaper/questions.yaml
  charts/dev/freeradius/questions.yaml
  charts/dev/freshrss/questions.yaml
  charts/dev/friendica/questions.yaml
  charts/dev/grav/questions.yaml
  charts/dev/grocy/questions.yaml
  charts/dev/guacamole-client/questions.yaml
  charts/dev/guacd/questions.yaml
  charts/dev/habridge/questions.yaml
  charts/dev/hammond/questions.yaml
  charts/dev/handbrake/questions.yaml
  charts/dev/healthchecks/questions.yaml
  charts/dev/icinga2/questions.yaml
  charts/dev/impostor-server/questions.yaml
  charts/dev/jdownloader2/questions.yaml
  charts/dev/joplin-server/questions.yaml
  charts/dev/kanboard/questions.yaml
  charts/dev/kimai/questions.yaml
  charts/dev/kodi-headless/questions.yaml
  charts/dev/koel/questions.yaml
  charts/dev/kopia/questions.yaml
  charts/dev/kutt/questions.yaml
Labels: precommit:failed, size/XXL

#7918 feat(stable): Port questions L - Z apps
  charts/dev/lancache-dns/questions.yaml
  charts/dev/lancache-monolithic/questions.yaml
  charts/dev/librephotos/questions.yaml
  charts/dev/linkace/questions.yaml
  charts/dev/lychee/questions.yaml
  charts/dev/makemkv/questions.yaml
  charts/dev/mattermost/questions.yaml
  charts/dev/mediainfo/questions.yaml
  charts/dev/minecraft-bungeecord/questions.yaml
  charts/dev/minecraft-java/questions.yaml
  charts/dev/miniflux/questions.yaml
  charts/dev/mkvcleaver/questions.yaml
  charts/dev/mkvtoolnix/questions.yaml
  charts/dev/ml-workspace/questions.yaml
  charts/dev/monica/questions.yaml
  charts/dev/nextpvr/questions.yaml
  charts/dev/nocodb/questions.yaml
  charts/dev/ntfy/questions.yaml
  charts/dev/onlyoffice-document-server/questions.yaml
  charts/dev/openldap/questions.yaml
  charts/dev/owncloud-ocis/questions.yaml
  charts/dev/photoview/questions.yaml
  charts/dev/phpldapadmin/questions.yaml
  charts/dev/projectsend/questions.yaml
  charts/dev/putty/questions.yaml
  charts/dev/pydio-cells/questions.yaml
  charts/dev/pylon/questions.yaml
  charts/dev/qdirstat/questions.yaml
  charts/dev/recipes/questions.yaml
  charts/dev/satisfactory/questions.yaml
  charts/dev/sdtd/questions.yaml
  charts/dev/snipe-it/questions.yaml
  charts/dev/spotweb/questions.yaml
  charts/dev/tsmuxer/questions.yaml
  charts/dev/tt-rss/questions.yaml
  charts/dev/typecho/questions.yaml
  charts/dev/ubooquity/questions.yaml
  charts/dev/unpoller/questions.yaml
  charts/dev/uptimerobot-prometheus/questions.yaml
  charts/dev/valheim/questions.yaml
  charts/dev/wekan/questions.yaml
  charts/dev/wg-easy/questions.yaml
  charts/dev/whoogle/questions.yaml
  charts/dev/zerotier/questions.yaml
  charts/dev/zusam/questions.yaml
Labels: size/XXL, precommit:ok

#7921 fix(tailscale): Primary service account
  charts/stable/tailscale/Chart.yaml
  charts/stable/tailscale/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#7922 fix(external-service): protocol -> lower
  charts/stable/external-service/Chart.yaml
  charts/stable/external-service/questions.yaml
  charts/stable/external-service/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#7931 chore(deps): update helm chart common to 12.4.3
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#7929 chore(deps): update helm general non-major
  charts/enterprise/authelia/Chart.yaml
  charts/enterprise/blocky/Chart.yaml
  charts/enterprise/cert-manager/Chart.yaml
  charts/enterprise/grafana/Chart.yaml
  charts/enterprise/metallb/Chart.yaml
  charts/enterprise/prometheus/Chart.yaml
  charts/enterprise/traefik/Chart.yaml
  charts/enterprise/vaultwarden/Chart.yaml
Labels: size/S

#7933 Tailscale - Update common.yaml
  charts/stable/tailscale/Chart.yaml
  charts/stable/tailscale/templates/common.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#7935 fix(transmission,kms,sonarr,radarr): probe fixes
  charts/stable/kms/Chart.yaml
  charts/stable/kms/values.yaml
  charts/stable/plex/values.yaml
  charts/stable/radarr/Chart.yaml
  charts/stable/radarr/ci/basicauth-values.yaml
  charts/stable/radarr/values.yaml
  charts/stable/sonarr/Chart.yaml
  charts/stable/sonarr/ci/basicauth-values.yaml
  charts/stable/sonarr/values.yaml
  charts/stable/transmission/Chart.yaml
  charts/stable/transmission/ci/auth-values.yaml
  charts/stable/transmission/templates/common.yaml
  charts/stable/transmission/values.yaml
Labels: precommit:failed, size/M, lint:failed

#7954 fix(templates): Reverts previous change of GPU section and applies a workaround for UI bug
  templates/questions/general/resources.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#7957 fix(home-assistant): add an empty line after each concat
  charts/stable/home-assistant/Chart.yaml
  charts/stable/home-assistant/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#7958 chore(deps): bump common on dep train
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
Labels: size/S, lint:ok, precommit:ok

#7960 chore(deps): update helm chart common to 12.4.6
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#7869 fix(lldap): lldap fixes and refactor
  charts/incubator/lldap/Chart.yaml
  charts/incubator/lldap/docs/installation-notes.md
  charts/incubator/lldap/questions.yaml
  charts/incubator/lldap/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#7966 chore(deps): update helm general non-major
  charts/enterprise/authelia/Chart.yaml
  charts/enterprise/blocky/Chart.yaml
  charts/enterprise/cert-manager/Chart.yaml
  charts/enterprise/grafana/Chart.yaml
  charts/enterprise/metallb/Chart.yaml
  charts/enterprise/prometheus/Chart.yaml
  charts/enterprise/traefik/Chart.yaml
  charts/enterprise/vaultwarden/Chart.yaml
Labels: size/S, lint:ok, precommit:ok

#7979 fix(youtubedl-material): fix identation
  charts/stable/youtubedl-material/Chart.yaml
  charts/stable/youtubedl-material/questions.yaml
  charts/stable/youtubedl-material/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#7974 fix(lldap): ldap port fix
  charts/incubator/lldap/Chart.yaml
  charts/incubator/lldap/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#7981 fix(templates): fix externalInterfaces UI
  templates/questions/service/serviceExpert.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#7978 fix(tailscale): mount service account token and fix secret
  charts/stable/tailscale/Chart.yaml
  charts/stable/tailscale/templates/common.yaml
  charts/stable/tailscale/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#7989 chore(deps): update helm chart common to 12.4.9
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#7993 fix(home-assistant): put new lines everywhere...
  charts/stable/home-assistant/Chart.yaml
  charts/stable/home-assistant/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#7994 chore(deps): update helm general non-major
  charts/stable/home-assistant/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#7997 chore(deps): update helm chart common to 12.4.10
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#7953 chore(deps): update actions/checkout action to v3.5.2
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#7986 chore(deps): update dawidd6/action-download-artifact action to v2.27.0
  .github/workflows/meta-label-pr-ci-status.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#7952 chore(deps): update actions/checkout digest to 8e5e7e5
  .github/workflows/catalog-test.yaml
  .github/workflows/charts-changelog.yaml
  .github/workflows/charts-lint.yaml
  .github/workflows/charts-release.yaml
  .github/workflows/charts-test.yaml
  .github/workflows/daily.yaml
  .github/workflows/meta-label-pr-ci-status.yaml
  .github/workflows/metadata-label-commenter.yaml
  .github/workflows/pr-metadata.yaml
  .github/workflows/pr-validate.yaml
  .github/workflows/prune.yaml
  .github/workflows/renovate-bump.yaml
  .github/workflows/schedule-sync-labels.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#7996 chore(deps): update helm chart common to 12.4.10
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
Labels: size/S, lint:ok, precommit:ok

#8015 docs(LLDAP): Revamp docs with Authelia guide
  charts/incubator/lldap/docs/authelia.md
  charts/incubator/lldap/docs/installation-notes.md
Labels: install:ok, lint:ok, size/M, precommit:ok

#8016 fix(templates): fix protocol in service list
  templates/questions/service/serviceList.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#8027 chore(deps): update helm chart common to 12.4.12
  templates/chart/Chart.yaml
Labels: size/XS

#8025 feat(lldap): LLDAP move to stable
  charts/stable/lldap/.helmignore
  charts/stable/lldap/Chart.yaml
  charts/stable/lldap/NOTES.txt
  charts/stable/lldap/README.md
  charts/stable/lldap/ci/default-values.yaml
  charts/stable/lldap/docs/authelia.md
  charts/stable/lldap/docs/installation-notes.md
  charts/stable/lldap/questions.yaml
  charts/stable/lldap/templates/_secrets.tpl
  charts/stable/lldap/templates/common.yaml
  charts/stable/lldap/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#8024 fix(paperless-ngx): disable varrun persistence
  charts/stable/paperless-ngx/Chart.yaml
  charts/stable/paperless-ngx/values.yaml
  templates/questions/addons/vpn.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#8026 chore(deps): update helm chart common to 12.4.12
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
Labels: size/S, lint:ok, precommit:ok

#8031 docs: update .github/README.md [skip ci]
  .github/README.md
Labels: size/XS

#8032 docs: update .github/README.md [skip ci]
  .all-contributorsrc
  .github/README.md
Labels: size/XS

#8033 All contributors/add commander starhump
  .all-contributorsrc
  .github/README.md
Labels: size/XS

#8029 fix(blocky): fix additional bootstap dns
  charts/enterprise/blocky/Chart.yaml
  charts/enterprise/blocky/questions.yaml
  charts/enterprise/blocky/templates/_blockyConfig.tpl
  charts/enterprise/blocky/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#8036 chore(deps): update helm chart common to 12.4.13
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#8035 chore(deps): update helm chart common to 12.4.13
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
Labels: size/S, lint:ok, precommit:ok, update/helm/dependency/non-major

#8038 fix(template): fix static ip config
  templates/questions/service/serviceExpert.yaml
Labels: size/M

#8044 chore(blocky): bump
  charts/enterprise/blocky/Chart.yaml
  charts/enterprise/blocky/values.yaml
Labels: size/XS

#8046 chore(deps): update helm chart common to 12.4.14
  templates/chart/Chart.yaml
Labels: size/XS

#8045 chore(deps): update helm chart common to 12.4.14
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
Labels: size/S

#8049 docs: update .github/README.md [skip ci]
  .all-contributorsrc
  .github/README.md
Labels: size/XS

#8050 chore(deps): update helm chart common to 12.4.15
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
Labels: size/S, lint:ok, precommit:ok

#8051 chore(deps): update helm chart common to 12.4.15
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#8053 fix(template): fix ipam `staticIPConfigurations` indentation
  templates/questions/service/serviceExpert.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#8058 All contributors/add fnichol
  .all-contributorsrc
  .github/README.md
Labels: size/XS

#8060 All contributors/add fnichol
  .all-contributorsrc
  .github/README.md
Labels: size/XS

#8057 fix(syncthing,traefik,blocky): fix probes, protocol, config structure
  charts/enterprise/blocky/Chart.yaml
  charts/enterprise/blocky/templates/_blockyConfig.tpl
  charts/enterprise/traefik/Chart.yaml
  charts/enterprise/traefik/questions.yaml
  charts/stable/syncthing/Chart.yaml
  charts/stable/syncthing/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#8064 chore(deps): update helm chart common to 12.4.20
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
Labels: size/S, lint:ok, precommit:ok

#8065 chore(deps): update helm chart common to 12.4.20
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#8066 fix(meshcentral): fixup/port meshcentral
  charts/stable/meshcentral/Chart.yaml
  charts/stable/meshcentral/ci/ci-values.yaml
  charts/stable/meshcentral/questions.yaml
  charts/stable/meshcentral/templates/_secret.tpl
  charts/stable/meshcentral/templates/common.yaml
  charts/stable/meshcentral/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#8079 fix(speedtest-exporter): set scrape interval to 1h
  charts/stable/speedtest-exporter/Chart.yaml
  charts/stable/speedtest-exporter/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#8084 docs(cert-manager): Add How-To guide
  charts/enterprise/cert-manager/docs/how-to.md
  charts/enterprise/cert-manager/docs/img/cert-manager1.png
  charts/enterprise/cert-manager/docs/img/cert-manager2.png
  charts/enterprise/cert-manager/docs/img/cert-manager3.png
  charts/enterprise/cert-manager/docs/img/cert-manager4.png
  charts/enterprise/cert-manager/docs/img/cert-manager5.png
Labels: install:ok, lint:ok, size/M, precommit:ok

#8083 fix(webgrabplus): Disable probes + update upstream
  charts/stable/webgrabplus/Chart.yaml
  charts/stable/webgrabplus/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#8077 feat(scale): template for podOptions
  templates/questions/general/podOptions.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#8086 chore(deps): update helm chart common to 12.4.21
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
Labels: size/S, update/helm/dependency/non-major

#8088 chore(deps): update helm chart common to 12.4.21
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#8089 Add prerequisite
  charts/enterprise/cert-manager/docs/how-to.md
Labels: size/XS, install:ok, lint:ok, precommit:ok

#8095 fix(apps): fix various issues
  charts/stable/browserless-chrome/Chart.yaml
  charts/stable/browserless-chrome/questions.yaml
  charts/stable/browserless-chrome/values.yaml
  charts/stable/deepstack/Chart.yaml
  charts/stable/deepstack/questions.yaml
  charts/stable/deepstack/values.yaml
  charts/stable/doublecommander/Chart.yaml
  charts/stable/doublecommander/values.yaml
  charts/stable/impostor-server/Chart.yaml
  charts/stable/impostor-server/questions.yaml
  charts/stable/impostor-server/values.yaml
  charts/stable/jupyter/Chart.yaml
  charts/stable/jupyter/questions.yaml
  charts/stable/jupyter/values.yaml
  charts/stable/lama-cleaner/Chart.yaml
  charts/stable/lama-cleaner/questions.yaml
  charts/stable/lama-cleaner/values.yaml
  charts/stable/minecraft-bungeecord/Chart.yaml
  charts/stable/minecraft-bungeecord/questions.yaml
  charts/stable/minecraft-bungeecord/values.yaml
  charts/stable/minecraft-java/Chart.yaml
  charts/stable/minecraft-java/questions.yaml
  charts/stable/minecraft-java/values.yaml
  charts/stable/paperless-ngx/Chart.yaml
  charts/stable/paperless-ngx/templates/_secrets.tpl
  charts/stable/paperless-ngx/values.yaml
  charts/stable/radarr/Chart.yaml
  charts/stable/radarr/values.yaml
  charts/stable/rdesktop/Chart.yaml
  charts/stable/rdesktop/questions.yaml
  charts/stable/rdesktop/values.yaml
  charts/stable/transmission/Chart.yaml
  charts/stable/transmission/templates/common.yaml
  charts/stable/tvheadend/values.yaml
  charts/stable/webtop/Chart.yaml
  charts/stable/webtop/questions.yaml
  charts/stable/webtop/values.yaml
Labels: lint:ok, size/L, precommit:ok

#8100 fix(tvheadend): Bump to push yesterdays fix
  charts/stable/tvheadend/Chart.yaml
Labels: size/XS

#8101 fix(tvheadend): Change probes to tcp
  charts/stable/tvheadend/Chart.yaml
  charts/stable/tvheadend/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#8109 feat(enterprise, dependency and tailscale): add podOptions to SCALE GUI
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/clickhouse/questions.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/mariadb/questions.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/memcached/questions.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/mongodb/questions.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/redis/questions.yaml
  charts/dependency/solr/Chart.yaml
  charts/dependency/solr/questions.yaml
  charts/enterprise/authelia/Chart.yaml
  charts/enterprise/authelia/questions.yaml
  charts/enterprise/blocky/Chart.yaml
  charts/enterprise/blocky/questions.yaml
  charts/enterprise/cert-manager/Chart.yaml
  charts/enterprise/grafana/Chart.yaml
  charts/enterprise/grafana/questions.yaml
  charts/enterprise/metallb/Chart.yaml
  charts/enterprise/prometheus/Chart.yaml
  charts/enterprise/traefik/Chart.yaml
  charts/enterprise/traefik/questions.yaml
  charts/enterprise/vaultwarden/Chart.yaml
  charts/enterprise/vaultwarden/questions.yaml
  charts/stable/tailscale/Chart.yaml
  charts/stable/tailscale/questions.yaml
  tools/bump.sh
Labels: size/S

#8097 fix(resilio-sync): Fix probe
  charts/stable/resilio-sync/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#8102 chore(deps): update actions/setup-python digest to 57ded4d
  .github/workflows/charts-lint.yaml
  .github/workflows/charts-test.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#8116 chore(deps): update renovatebot/github-action action to v36.0.3
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#8001 chore(deps): update actions/github-script digest to d7906e4
  .github/workflows/meta-label-pr-ci-status.yaml
Labels: size/XS

#7889 chore(deps): update helm/chart-testing-action action to v2.4.0
  .github/workflows/charts-lint.yaml
  .github/workflows/charts-test.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#7876 chore(deps): update container image ghcr.io/truecharts/devcontainer to v3.1.1
  .github/workflows/catalog-test.yaml
  .github/workflows/charts-release.yaml
  .github/workflows/daily.yaml
  .github/workflows/renovate-bump.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#8119 chore(deps): update container image tccr.io/truecharts/grafana to 9.4.7
  charts/enterprise/grafana/Chart.yaml
  charts/enterprise/grafana/values.yaml
Labels: update/docker/enterprise/patch

#8120 chore(deps): update container image tccr.io/truecharts/prometheus to 2.43.0
  charts/enterprise/prometheus/Chart.yaml
  charts/enterprise/prometheus/values.yaml
Labels: update/docker/enterprise/patch

#8121 chore(deps): update container image tccr.io/truecharts/thanos to 0.31.0
  charts/enterprise/prometheus/Chart.yaml
  charts/enterprise/prometheus/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#8123 fix(docs): Update setup-guide
  charts/enterprise/metallb/Chart.yaml
  charts/enterprise/metallb/docs/setup-guide.md
Labels: size/XS, install:ok, lint:ok, precommit:ok

#8128 fix(external-service): don't use slices on scale and dont hardcode ta…
  charts/stable/external-service/Chart.yaml
  charts/stable/external-service/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#8129 chore(deps): update helm chart common to 12.5.1
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
Labels: size/S, lint:ok, precommit:ok

#8130 chore(deps): update helm chart common to 12.5.1
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#8131 chore(deps): update container image tccr.io/truecharts/traefik to 2.9.9
  charts/enterprise/traefik/Chart.yaml
  charts/enterprise/traefik/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#8137 chore(deps): update container image tccr.io/truecharts/k8s_gateway to v0.3.4
  charts/enterprise/blocky/Chart.yaml
  charts/enterprise/blocky/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#8139 fix(docs): update metallb loadbalancerIP behavior
  charts/enterprise/metallb/Chart.yaml
  charts/enterprise/metallb/docs/setup-guide.md
Labels: size/XS, install:ok, lint:ok, precommit:ok

#8141 chore(deps): update container image tccr.io/truecharts/traefik to v2.9.10
  charts/enterprise/traefik/Chart.yaml
  charts/enterprise/traefik/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#8142 chore(deps): update container image tccr.io/truecharts/vaultwarden to v1.28.1
  charts/enterprise/vaultwarden/Chart.yaml
  charts/enterprise/vaultwarden/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#8148 chore(deps): update container image tccr.io/truecharts/traefik to v2.10.0
  charts/enterprise/traefik/Chart.yaml
  charts/enterprise/traefik/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#8154 chore(deps): update helm chart common to 12.6.1
  templates/chart/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#8159 chore(deps): update all-contributors-cli to 6.25.0
  package.json
  yarn.lock
Labels: size/XS, install:ok, lint:ok, precommit:ok

#8144 add all supported versions and correct spelling
  .github/SUPPORT.md
Labels: size/XS, install:ok, lint:ok, precommit:ok

#8161 chore(deps): update container image ghcr.io/jens-maus/raspberrymatic to latest
  charts/incubator/raspberrymatic/Chart.yaml
  charts/incubator/raspberrymatic/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8163 chore(deps): update container image tccr.io/truecharts/alertmanager to 0.25.0
  charts/enterprise/prometheus/Chart.yaml
  charts/enterprise/prometheus/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#8167 chore(deps): update container image tccr.io/truecharts/adminer to latest
  charts/stable/adminer/Chart.yaml
  charts/stable/adminer/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8164 chore(deps): update container image tccr.io/truecharts/grafana to 9.4.7
  charts/enterprise/grafana/Chart.yaml
  charts/enterprise/grafana/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#8172 chore(deps): update container image tccr.io/truecharts/autoscan to latest
  charts/stable/autoscan/Chart.yaml
  charts/stable/autoscan/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8173 chore(deps): update container image tccr.io/truecharts/babybuddy to v
  charts/stable/babybuddy/Chart.yaml
  charts/stable/babybuddy/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8176 chore(deps): update container image tccr.io/truecharts/beets to v1.6.0
  charts/stable/beets/Chart.yaml
  charts/stable/beets/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8179 chore(deps): update container image tccr.io/truecharts/boinc to latest
  charts/stable/boinc/Chart.yaml
  charts/stable/boinc/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8180 chore(deps): update container image tccr.io/truecharts/booksonic-air to v2201.1.0
  charts/stable/booksonic-air/Chart.yaml
  charts/stable/booksonic-air/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8183 chore(deps): update container image tccr.io/truecharts/budge to v0.0.9
  charts/stable/budge/Chart.yaml
  charts/stable/budge/values.yaml
Labels: size/XS, automerge

#8184 chore(deps): update container image tccr.io/truecharts/calibre to v
  charts/stable/calibre/Chart.yaml
  charts/stable/calibre/values.yaml
Labels: size/XS, automerge

#8283 chore(deps): update minecraft-java (minor)
  charts/stable/minecraft-java/Chart.yaml
  charts/stable/minecraft-java/values.yaml
Labels: size/S, automerge

#8238 chore(deps): update container image tccr.io/truecharts/heimdall to v
  charts/stable/heimdall/Chart.yaml
  charts/stable/heimdall/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8185 chore(deps): update container image tccr.io/truecharts/calibre-web to v
  charts/stable/calibre-web/Chart.yaml
  charts/stable/calibre-web/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8193 chore(deps): update container image tccr.io/truecharts/cloudflareddns to latest
  charts/stable/cloudflareddns/Chart.yaml
  charts/stable/cloudflareddns/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8194 chore(deps): update container image tccr.io/truecharts/cops to latest
  charts/stable/cops/Chart.yaml
  charts/stable/cops/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8201 chore(deps): update container image tccr.io/truecharts/ddclient to 3.10.0
  charts/stable/ddclient/Chart.yaml
  charts/stable/ddclient/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8203 chore(deps): update container image tccr.io/truecharts/deluge to v2.1.1
  charts/stable/deluge/Chart.yaml
  charts/stable/deluge/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8204 chore(deps): update container image tccr.io/truecharts/dillinger to v3.39.1
  charts/stable/dillinger/Chart.yaml
  charts/stable/dillinger/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8209 chore(deps): update container image tccr.io/truecharts/dokuwiki to 20220731.1.0
  charts/stable/dokuwiki/Chart.yaml
  charts/stable/dokuwiki/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8210 chore(deps): update container image tccr.io/truecharts/duckdns to latest
  charts/stable/duckdns/Chart.yaml
  charts/stable/duckdns/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8214 chore(deps): update container image tccr.io/truecharts/emby to 4.7.11.0
  charts/stable/emby/Chart.yaml
  charts/stable/emby/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8215 chore(deps): update container image tccr.io/truecharts/embystat to v0.2.0
  charts/stable/embystat/Chart.yaml
  charts/stable/embystat/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8216 chore(deps): update container image tccr.io/truecharts/emulatorjs to v1.7.2
  charts/stable/emulatorjs/Chart.yaml
  charts/stable/emulatorjs/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8224 chore(deps): update container image tccr.io/truecharts/fleet to 2.3.3
  charts/stable/fleet/Chart.yaml
  charts/stable/fleet/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8227 chore(deps): update container image tccr.io/truecharts/foldingathome to v7.6.21
  charts/stable/foldingathome/Chart.yaml
  charts/stable/foldingathome/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8229 chore(deps): update container image tccr.io/truecharts/freshrss to v
  charts/stable/freshrss/Chart.yaml
  charts/stable/freshrss/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8235 chore(deps): update container image tccr.io/truecharts/grocy to 3.3.2
  charts/stable/grocy/Chart.yaml
  charts/stable/grocy/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8237 chore(deps): update container image tccr.io/truecharts/hedgedoc to 1.9.7
  charts/stable/hedgedoc/Chart.yaml
  charts/stable/hedgedoc/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8240 chore(deps): update container image tccr.io/truecharts/impostor-server-nightly to vnightly
  charts/stable/impostor-server/Chart.yaml
  charts/stable/impostor-server/ci/values.yaml
  charts/stable/impostor-server/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8282 chore(deps): update jupyter to v2023-04 (minor)
  charts/stable/jupyter/Chart.yaml
  charts/stable/jupyter/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8246 chore(deps): update container image tccr.io/truecharts/kiwix-serve to 3.4.0
  charts/stable/kiwix-serve/Chart.yaml
  charts/stable/kiwix-serve/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8256 chore(deps): update container image tccr.io/truecharts/scrutiny to v0.7.1
  charts/stable/scrutiny/Chart.yaml
  charts/stable/scrutiny/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8175 chore(deps): update container image tccr.io/truecharts/bazarr to v
  charts/stable/bazarr/Chart.yaml
  charts/stable/bazarr/values.yaml
Labels: install:failed, size/XS, lint:ok, precommit:ok, automerge

#8177 chore(deps): update container image tccr.io/truecharts/blender to latest
  charts/incubator/blender/Chart.yaml
  charts/incubator/blender/values.yaml
Labels: size/XS, lint:failed, precommit:ok, automerge

#8323 chore(deps): update container image tccr.io/truecharts/mysql-workbench to v
  charts/stable/mysql-workbench/Chart.yaml
  charts/stable/mysql-workbench/values.yaml
Labels: size/XS, automerge

#8345 chore(deps): update container image tccr.io/truecharts/posterr to latest
  charts/stable/posterr/Chart.yaml
  charts/stable/posterr/values.yaml
Labels: size/XS, automerge

#8250 chore(deps): update container image tccr.io/truecharts/libreddit to latest
  charts/stable/libreddit/Chart.yaml
  charts/stable/libreddit/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8253 chore(deps): update container image tccr.io/truecharts/lidarr to v
  charts/stable/lidarr/Chart.yaml
  charts/stable/lidarr/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8251 chore(deps): update container image tccr.io/truecharts/libremdb to latest
  charts/stable/libremdb/Chart.yaml
  charts/stable/libremdb/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8254 chore(deps): update container image tccr.io/truecharts/littlelink-server to latest
  charts/stable/littlelink/Chart.yaml
  charts/stable/littlelink/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8309 chore(deps): update container image tccr.io/truecharts/logitechmediaserver to 8.4.0
  charts/stable/logitech-media-server/Chart.yaml
  charts/stable/logitech-media-server/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#8312 chore(deps): update container image tccr.io/truecharts/medusa to v
  charts/stable/medusa/Chart.yaml
  charts/stable/medusa/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge
