Repository trueforge-org/truecharts, pull requests merged in 2023-06, with the labels that each got.

#9320 chore(deps): update container image tccr.io/truecharts/owncast to v0.1.0
  charts/stable/owncast/Chart.yaml
  charts/stable/owncast/values.yaml
Labels: automerge, update/docker/general/non-major

#9319 chore(deps): update container image tccr.io/truecharts/node-exporter to v1.6.0
  charts/dependency/node-exporter/Chart.yaml
  charts/dependency/node-exporter/values.yaml
Labels: automerge, update/docker/general/non-major

#9299 chore(deps): update helm chart common to 12.10.10
  charts/dependency/node-exporter/Chart.yaml
Labels: automerge

#9321 chore(deps): update container image tccr.io/truecharts/openspeedtest to latest
  charts/stable/openspeedtest/Chart.yaml
  charts/stable/openspeedtest/values.yaml
Labels: automerge, update/docker/general/non-major

#9322 chore(deps): update container image tccr.io/truecharts/audiobookshelf to v2.2.22
  charts/stable/audiobookshelf/Chart.yaml
  charts/stable/audiobookshelf/values.yaml
Labels: automerge, update/docker/general/non-major

#9323 chore(deps): update container image tccr.io/truecharts/qbitmanage to v3.6.4
  charts/stable/qbitmanage/Chart.yaml
  charts/stable/qbitmanage/values.yaml
Labels: automerge, update/docker/general/non-major

#9325 chore(deps): update container image tccr.io/truecharts/homebox to v0.9.2
  charts/stable/homebox/Chart.yaml
  charts/stable/homebox/values.yaml
Labels: automerge, update/docker/general/non-major

#9324 chore(deps): update container image tccr.io/truecharts/esphome to v2023.5.5
  charts/stable/esphome/Chart.yaml
  charts/stable/esphome/values.yaml
Labels: automerge, update/docker/general/non-major

#9326 chore(deps): update container image tccr.io/truecharts/qbittorrent to v4.5.3
  charts/stable/qbittorrent/Chart.yaml
  charts/stable/qbittorrent/values.yaml
Labels: automerge, update/docker/general/non-major

#9327 chore(deps): update container image tccr.io/truecharts/pihole to v2023.05.2
  charts/stable/pihole/Chart.yaml
  charts/stable/pihole/values.yaml
Labels: automerge, update/docker/general/non-major

#8147 chore(minecraft-java): Add AUTO_CURSEFORGE options
  charts/stable/minecraft-java/Chart.yaml
  charts/stable/minecraft-java/questions.yaml
  charts/stable/minecraft-java/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#9315 chore(deps): update immich to v1.59.1 (minor)
  charts/stable/immich/Chart.yaml
  charts/stable/immich/values.yaml
Labels: automerge

#9329 chore(deps): update container image tccr.io/truecharts/flaresolverr to v3.2.0
  charts/stable/flaresolverr/Chart.yaml
  charts/stable/flaresolverr/values.yaml
Labels: automerge, update/docker/general/non-major

#9335 chore(deps): update container image tccr.io/truecharts/libreddit to latest
  charts/stable/libreddit/Chart.yaml
  charts/stable/libreddit/values.yaml
Labels: automerge, update/docker/general/non-major

#9338 chore(deps): update container image tccr.io/truecharts/node-exporter to v1.6.0
  charts/dependency/node-exporter/Chart.yaml
  charts/dependency/node-exporter/values.yaml
Labels: automerge, update/docker/general/non-major

#9342 chore(deps): update container image tccr.io/truecharts/openvscode-server to v1.78.2
  charts/stable/openvscode-server/Chart.yaml
  charts/stable/openvscode-server/values.yaml
Labels: automerge, update/docker/general/non-major

#9343 chore(deps): update container image tccr.io/truecharts/invidious to latest
  charts/stable/invidious/Chart.yaml
  charts/stable/invidious/values.yaml
Labels: automerge, update/docker/general/non-major

#9333 chore(deps): update helm chart common to 12.12.0
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/kube-state-metrics/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/node-exporter/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
Labels: automerge

#9348 chore(deps): update helm chart common to 12.12.1
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/kube-state-metrics/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/node-exporter/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
Labels: automerge

#9374 chore(deps): update container image tccr.io/truecharts/memcached to v1.6.20
  charts/dependency/memcached/Chart.yaml
  charts/dependency/memcached/values.yaml
Labels: automerge, update/docker/general/non-major

#9376 chore(deps): update container image tccr.io/truecharts/mongodb to v6.0.6
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/mongodb/values.yaml
Labels: automerge, update/docker/general/non-major

#9392 chore(deps): update rdesktop
  charts/stable/rdesktop/Chart.yaml
  charts/stable/rdesktop/values.yaml
Labels: automerge, update/docker/general/non-major

#9357 chore(deps): update container image tccr.io/truecharts/babybuddy to v1.16.0
  charts/stable/babybuddy/Chart.yaml
  charts/stable/babybuddy/values.yaml
Labels: automerge, update/docker/general/non-major

#9364 chore(deps): update container image tccr.io/truecharts/embystat to v0.2.0
  charts/stable/embystat/Chart.yaml
  charts/stable/embystat/values.yaml
Labels: automerge, update/docker/general/non-major

#9371 chore(deps): update container image tccr.io/truecharts/libremdb to latest
  charts/stable/libremdb/Chart.yaml
  charts/stable/libremdb/values.yaml
Labels: automerge, update/docker/general/non-major

#9358 chore(deps): update container image tccr.io/truecharts/beets to v1.6.0
  charts/stable/beets/Chart.yaml
  charts/stable/beets/values.yaml
Labels: automerge, update/docker/general/non-major

#9373 chore(deps): update container image tccr.io/truecharts/mariadb to v10.11.3
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/mariadb/values.yaml
Labels: automerge, update/docker/general/non-major

#9362 chore(deps): update container image tccr.io/truecharts/dillinger to v3.39.1
  charts/stable/dillinger/Chart.yaml
  charts/stable/dillinger/values.yaml
Labels: automerge, update/docker/general/non-major

#9379 chore(deps): update container image tccr.io/truecharts/prometheus to v2.44.0
  charts/enterprise/prometheus/Chart.yaml
  charts/enterprise/prometheus/values.yaml
Labels: automerge, update/docker/enterprise/patch

#9384 chore(deps): update container image tccr.io/truecharts/sickgear to latest
  charts/stable/sickgear/Chart.yaml
  charts/stable/sickgear/values.yaml
Labels: automerge, update/docker/general/non-major

#9385 chore(deps): update container image tccr.io/truecharts/snapdrop to latest
  charts/stable/snapdrop/Chart.yaml
  charts/stable/snapdrop/values.yaml
Labels: automerge, update/docker/general/non-major

#9380 chore(deps): update container image tccr.io/truecharts/prusaslicer-novnc to latest
  charts/stable/prusaslicer-novnc/Chart.yaml
  charts/stable/prusaslicer-novnc/values.yaml
Labels: automerge, update/docker/general/non-major

#9378 chore(deps): update container image tccr.io/truecharts/mylar3 to v0.7.2
  charts/stable/mylar/Chart.yaml
  charts/stable/mylar/values.yaml
Labels: automerge, update/docker/general/non-major

#9381 chore(deps): update container image tccr.io/truecharts/pwndrop to v1.0.1
  charts/stable/pwndrop/Chart.yaml
  charts/stable/pwndrop/values.yaml
Labels: automerge, update/docker/general/non-major

#9369 chore(deps): update container image tccr.io/truecharts/lazylibrarian to latest
  charts/stable/lazylibrarian/Chart.yaml
  charts/stable/lazylibrarian/values.yaml
Labels: automerge, update/docker/general/non-major

#9386 chore(deps): update container image tccr.io/truecharts/solr to v9.2.1
  charts/dependency/solr/Chart.yaml
  charts/dependency/solr/values.yaml
Labels: automerge, update/docker/general/non-major

#9360 chore(deps): update container image tccr.io/truecharts/booksonic-air to v2201.1.0
  charts/stable/booksonic-air/Chart.yaml
  charts/stable/booksonic-air/values.yaml
Labels: automerge, update/docker/general/non-major

#9388 chore(deps): update container image tccr.io/truecharts/ubooquity to v2.1.2
  charts/stable/ubooquity/Chart.yaml
  charts/stable/ubooquity/values.yaml
Labels: automerge, update/docker/general/non-major

#9390 chore(deps): update container image tccr.io/truecharts/znc to v1.8.2
  charts/stable/znc/Chart.yaml
  charts/stable/znc/values.yaml
Labels: automerge, update/docker/general/non-major

#9370 chore(deps): update container image tccr.io/truecharts/libreddit to latest
  charts/stable/libreddit/Chart.yaml
  charts/stable/libreddit/values.yaml
Labels: automerge, update/docker/general/non-major

#9366 chore(deps): update container image tccr.io/truecharts/grav to v1.7.41
  charts/stable/grav/Chart.yaml
  charts/stable/grav/values.yaml
Labels: automerge, update/docker/general/non-major

#9368 chore(deps): update container image tccr.io/truecharts/kitchenowl-backend to latest
  charts/stable/kitchenowl/Chart.yaml
  charts/stable/kitchenowl/values.yaml
Labels: automerge

#9391 chore(deps): update jupyter
  charts/stable/jupyter/Chart.yaml
  charts/stable/jupyter/values.yaml
Labels: automerge

#9363 chore(deps): update container image tccr.io/truecharts/docker-in-docker to v23.0.6
  charts/stable/docker-compose/Chart.yaml
  charts/stable/docker-compose/values.yaml
Labels: automerge

#9389 chore(deps): update container image tccr.io/truecharts/wordpress to v6.2.2
  charts/stable/wordpress/Chart.yaml
  charts/stable/wordpress/values.yaml
Labels: automerge

#9387 chore(deps): update container image tccr.io/truecharts/tvheadend to latest
  charts/stable/tvheadend/Chart.yaml
  charts/stable/tvheadend/values.yaml
Labels: automerge

#9359 chore(deps): update container image tccr.io/truecharts/boinc to latest
  charts/stable/boinc/Chart.yaml
  charts/stable/boinc/values.yaml
Labels: automerge

#9383 chore(deps): update container image tccr.io/truecharts/rsshub to latest
  charts/stable/rsshub/Chart.yaml
  charts/stable/rsshub/values.yaml
Labels: automerge

#9361 chore(deps): update container image tccr.io/truecharts/budge to v0.0.9
  charts/stable/budge/Chart.yaml
  charts/stable/budge/values.yaml
Labels: automerge

#9382 chore(deps): update container image tccr.io/truecharts/quassel-core to v0.14.0
  charts/stable/quassel-core/Chart.yaml
  charts/stable/quassel-core/values.yaml
Labels: automerge

#9372 chore(deps): update container image tccr.io/truecharts/littlelink-server to latest
  charts/stable/littlelink/Chart.yaml
  charts/stable/littlelink/values.yaml
Labels: automerge

#9367 chore(deps): update container image tccr.io/truecharts/impostor-server-nightly to vnightly
  charts/stable/impostor-server/Chart.yaml
  charts/stable/impostor-server/ci/values.yaml
  charts/stable/impostor-server/values.yaml
Labels: automerge

#9365 chore(deps): update container image tccr.io/truecharts/grafana to v9.5.2
  charts/enterprise/grafana/Chart.yaml
  charts/enterprise/grafana/values.yaml
Labels: automerge

#9377 chore(deps): update container image tccr.io/truecharts/mstream to v5.11.4
  charts/stable/mstream/Chart.yaml
  charts/stable/mstream/values.yaml
Labels: automerge

#9394 chore(deps): update helm chart common to 12.12.2
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/kube-state-metrics/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/node-exporter/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
Labels: automerge, update/helm/dependency/non-major

#9399 chore(deps): update container image tccr.io/truecharts/plex to v1.32.2.7100
  charts/stable/plex/Chart.yaml
  charts/stable/plex/values.yaml
Labels: automerge, update/docker/general/non-major

#9412 chore(deps): update rdesktop
  charts/stable/rdesktop/Chart.yaml
  charts/stable/rdesktop/values.yaml
Labels: automerge, update/docker/general/non-major

#9413 chore(deps): update webtop
  charts/stable/webtop/Chart.yaml
  charts/stable/webtop/values.yaml
Labels: automerge, update/docker/general/non-major

#9405 chore(deps): update container image tccr.io/truecharts/duckdns to latest
  charts/stable/duckdns/Chart.yaml
  charts/stable/duckdns/values.yaml
Labels: automerge, update/docker/general/non-major

#9406 chore(deps): update container image tccr.io/truecharts/embystat to v0.2.0
  charts/stable/embystat/Chart.yaml
  charts/stable/embystat/values.yaml
Labels: automerge, update/docker/general/non-major

#9409 chore(deps): update container image tccr.io/truecharts/libremdb to latest
  charts/stable/libremdb/Chart.yaml
  charts/stable/libremdb/values.yaml
Labels: automerge, update/docker/general/non-major

#9411 chore(deps): update container image tccr.io/truecharts/rsshub to latest
  charts/stable/rsshub/Chart.yaml
  charts/stable/rsshub/values.yaml
Labels: automerge, update/docker/general/non-major

#9408 chore(deps): update container image tccr.io/truecharts/libreddit to latest
  charts/stable/libreddit/Chart.yaml
  charts/stable/libreddit/values.yaml
Labels: automerge, update/docker/general/non-major

#9417 chore(deps): update container image tccr.io/truecharts/postgresql to 14.7.0
  charts/stable/postgresql/Chart.yaml
  charts/stable/postgresql/values.yaml
Labels: automerge, update/docker/general/non-major

#9428 chore(deps): update container image tccr.io/truecharts/webtop-alpine-i3 to latest
  charts/stable/webtop/Chart.yaml
  charts/stable/webtop/values.yaml
Labels: automerge, update/docker/general/non-major

#9442 chore(deps): update rdesktop
  charts/stable/rdesktop/Chart.yaml
  charts/stable/rdesktop/values.yaml
Labels: automerge, update/docker/general/non-major

#9435 chore(deps): update container image tccr.io/truecharts/mongodb to v6.0.6
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/mongodb/values.yaml
Labels: automerge, update/docker/general/non-major

#9431 chore(deps): update container image tccr.io/truecharts/grafana to v9.5.2
  charts/enterprise/grafana/Chart.yaml
  charts/enterprise/grafana/values.yaml
Labels: automerge, update/docker/enterprise/patch

#9433 chore(deps): update container image tccr.io/truecharts/mariadb to v10.11.3
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/mariadb/values.yaml
Labels: automerge, update/docker/general/non-major

#9443 chore(deps): update webtop
  charts/stable/webtop/Chart.yaml
  charts/stable/webtop/values.yaml
Labels: automerge, update/docker/general/non-major

#9436 chore(deps): update container image tccr.io/truecharts/node-exporter to v1.6.0
  charts/dependency/node-exporter/Chart.yaml
  charts/dependency/node-exporter/values.yaml
Labels: automerge, update/docker/general/non-major

#9439 chore(deps): update container image tccr.io/truecharts/rsshub to latest
  charts/stable/rsshub/Chart.yaml
  charts/stable/rsshub/values.yaml
Labels: automerge, update/docker/general/non-major

#9432 chore(deps): update container image tccr.io/truecharts/littlelink-server to latest
  charts/stable/littlelink/Chart.yaml
  charts/stable/littlelink/values.yaml
Labels: automerge, update/docker/general/non-major

#9440 chore(deps): update container image tccr.io/truecharts/solr to v9.2.1
  charts/dependency/solr/Chart.yaml
  charts/dependency/solr/values.yaml
Labels: automerge, update/docker/general/non-major

#9437 chore(deps): update container image tccr.io/truecharts/pwndrop to v1.0.1
  charts/stable/pwndrop/Chart.yaml
  charts/stable/pwndrop/values.yaml
Labels: automerge, update/docker/general/non-major

#9441 chore(deps): update container image tccr.io/truecharts/wordpress to v6.2.2
  charts/stable/wordpress/Chart.yaml
  charts/stable/wordpress/values.yaml
Labels: automerge, update/docker/general/non-major

#9444 chore(deps): update helm chart common to 12.12.3
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/kube-state-metrics/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/node-exporter/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
  templates/chart/Chart.yaml
Labels: automerge

#9451 chore(deps): update container image tccr.io/truecharts/ubooquity to v2.1.2
  charts/stable/ubooquity/Chart.yaml
  charts/stable/ubooquity/values.yaml
Labels: automerge, update/docker/general/non-major

#9449 chore(deps): update container image tccr.io/truecharts/boinc to latest
  charts/stable/boinc/Chart.yaml
  charts/stable/boinc/values.yaml
Labels: automerge, update/docker/general/non-major

#9452 chore(deps): update container image tccr.io/truecharts/wordpress to v6.2.2
  charts/stable/wordpress/Chart.yaml
  charts/stable/wordpress/values.yaml
Labels: automerge, update/docker/general/non-major

#9274 chore(deps): update container image tccr.io/truecharts/nocodb to v0.107.5
  charts/stable/nocodb/Chart.yaml
  charts/stable/nocodb/values.yaml
Labels: automerge

#9454 chore(deps): update helm chart common to 12.12.4
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/kube-state-metrics/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/node-exporter/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
  templates/chart/Chart.yaml
Labels: automerge, update/helm/dependency/non-major

#9456 chore(deps): update helm chart common to 12.13.0
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/kube-state-metrics/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/node-exporter/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
  templates/chart/Chart.yaml
Labels: automerge

#9459 chore(deps): update helm general non-major
  charts/enterprise/authelia/Chart.yaml
  charts/enterprise/blocky/Chart.yaml
  charts/enterprise/prometheus/Chart.yaml
  charts/incubator/etesync/Chart.yaml
  charts/incubator/servas/Chart.yaml
  charts/stable/anonaddy/Chart.yaml
  charts/stable/baserow/Chart.yaml
  charts/stable/bookstack/Chart.yaml
  charts/stable/chevereto/Chart.yaml
  charts/stable/clarkson/Chart.yaml
  charts/stable/fireflyiii/Chart.yaml
  charts/stable/fleet/Chart.yaml
  charts/stable/friendica/Chart.yaml
  charts/stable/gitea/Chart.yaml
  charts/stable/immich/Chart.yaml
  charts/stable/libremdb/Chart.yaml
  charts/stable/matomo/Chart.yaml
  charts/stable/meshcentral/Chart.yaml
  charts/stable/mongo-express/Chart.yaml
  charts/stable/monica/Chart.yaml
  charts/stable/n8n/Chart.yaml
  charts/stable/nginx-proxy-manager/Chart.yaml
  charts/stable/nocodb/Chart.yaml
  charts/stable/onlyoffice-document-server/Chart.yaml
  charts/stable/outline/Chart.yaml
  charts/stable/paperless-ngx/Chart.yaml
  charts/stable/papermerge/Chart.yaml
  charts/stable/photoprism/Chart.yaml
  charts/stable/projectsend/Chart.yaml
  charts/stable/romm/Chart.yaml
  charts/stable/rsshub/Chart.yaml
  charts/stable/shlink/Chart.yaml
  charts/stable/vikunja/Chart.yaml
  charts/stable/weblate/Chart.yaml
  charts/stable/wekan/Chart.yaml
  charts/stable/wordpress/Chart.yaml
  charts/stable/youtubedl-material/Chart.yaml
Labels: automerge, update/helm/general/non-major

#9450 chore(deps): update container image tccr.io/truecharts/rsshub to latest
  charts/stable/rsshub/Chart.yaml
  charts/stable/rsshub/values.yaml
Labels: automerge

#9464 chore(deps): update container image tccr.io/truecharts/rsnapshot to v1.4.5
  charts/stable/rsnapshot/Chart.yaml
  charts/stable/rsnapshot/values.yaml
Labels: automerge, update/docker/general/non-major

#9472 chore(deps): update container image tccr.io/truecharts/mstream to v5.11.4
  charts/stable/mstream/Chart.yaml
  charts/stable/mstream/values.yaml
Labels: automerge, update/docker/general/non-major

#9471 chore(deps): update container image tccr.io/truecharts/libremdb to latest
  charts/stable/libremdb/Chart.yaml
  charts/stable/libremdb/values.yaml
Labels: automerge, update/docker/general/non-major

#9474 chore(deps): update container image tccr.io/truecharts/rsshub to latest
  charts/stable/rsshub/Chart.yaml
  charts/stable/rsshub/values.yaml
Labels: automerge, update/docker/general/non-major

#9470 chore(deps): update container image tccr.io/truecharts/booksonic-air to v2201.1.0
  charts/stable/booksonic-air/Chart.yaml
  charts/stable/booksonic-air/values.yaml
Labels: automerge, update/docker/general/non-major

#9473 chore(deps): update container image tccr.io/truecharts/prometheus to v2.44.0
  charts/enterprise/prometheus/Chart.yaml
  charts/enterprise/prometheus/values.yaml
Labels: automerge

#9484 chore(deps): update container image tccr.io/truecharts/mongodb to v6.0.6
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/mongodb/values.yaml
Labels: automerge

#9483 chore(deps): update container image tccr.io/truecharts/memcached to v1.6.20
  charts/dependency/memcached/Chart.yaml
  charts/dependency/memcached/values.yaml
Labels: automerge

#9490 chore(deps): update container image tccr.io/truecharts/solr to v9.2.1
  charts/dependency/solr/Chart.yaml
  charts/dependency/solr/values.yaml
Labels: automerge

#9489 chore(deps): update container image tccr.io/truecharts/sickgear to latest
  charts/stable/sickgear/Chart.yaml
  charts/stable/sickgear/values.yaml
Labels: automerge

#9488 chore(deps): update container image tccr.io/truecharts/rsshub to latest
  charts/stable/rsshub/Chart.yaml
  charts/stable/rsshub/values.yaml
Labels: automerge

#9482 chore(deps): update container image tccr.io/truecharts/lazylibrarian to latest
  charts/stable/lazylibrarian/Chart.yaml
  charts/stable/lazylibrarian/values.yaml
Labels: automerge

#9496 chore(deps): update container image tccr.io/truecharts/drawio to v21.3.7
  charts/stable/drawio/Chart.yaml
  charts/stable/drawio/values.yaml
Labels: automerge

#9487 chore(deps): update container image tccr.io/truecharts/prusaslicer-novnc to latest
  charts/stable/prusaslicer-novnc/Chart.yaml
  charts/stable/prusaslicer-novnc/values.yaml
Labels: automerge

#9493 chore(deps): update kitchenowl
  charts/stable/kitchenowl/Chart.yaml
  charts/stable/kitchenowl/values.yaml
Labels: automerge

#9485 chore(deps): update container image tccr.io/truecharts/mylar3 to v0.7.2
  charts/stable/mylar/Chart.yaml
  charts/stable/mylar/values.yaml
Labels: automerge

#9491 chore(deps): update container image tccr.io/truecharts/wordpress to v6.2.2
  charts/stable/wordpress/Chart.yaml
  charts/stable/wordpress/values.yaml
Labels: automerge

#9494 chore(deps): update container image tccr.io/truecharts/deconz to v2.22.01
  charts/stable/deconz/Chart.yaml
  charts/stable/deconz/values.yaml
Labels: automerge

#9497 chore(deps): update container image tccr.io/truecharts/grafana to v9.5.3
  charts/enterprise/grafana/Chart.yaml
  charts/enterprise/grafana/values.yaml
Labels: automerge

#9492 chore(deps): update container image tccr.io/truecharts/znc to v1.8.2
  charts/stable/znc/Chart.yaml
  charts/stable/znc/values.yaml
Labels: automerge

#9480 chore(deps): update container image tccr.io/truecharts/sshwifty to vlatest
  charts/stable/sshwifty/Chart.yaml
  charts/stable/sshwifty/values.yaml
Labels: automerge

#9495 chore(deps): update container image tccr.io/truecharts/domoticz to v2023.1.20230608
  charts/stable/domoticz/Chart.yaml
  charts/stable/domoticz/values.yaml
Labels: automerge

#9517 chore(deps): update container image tccr.io/truecharts/zigbee2mqtt to v1.31.2
  charts/stable/zigbee2mqtt/Chart.yaml
  charts/stable/zigbee2mqtt/values.yaml
Labels: automerge

#9502 chore(deps): update container image tccr.io/truecharts/filebot to v23.06.1
  charts/stable/filebot/Chart.yaml
  charts/stable/filebot/values.yaml
Labels: automerge

#9501 chore(deps): update container image tccr.io/truecharts/ddns-updater to v2.5.0
  charts/stable/ddns-updater/Chart.yaml
  charts/stable/ddns-updater/values.yaml
Labels: automerge

#9316 chore(deps): update container image tccr.io/truecharts/kube-state-metrics to v2.9.2
  charts/dependency/kube-state-metrics/Chart.yaml
  charts/dependency/kube-state-metrics/values.yaml
Labels: automerge

#9513 chore(deps): update container image tccr.io/truecharts/ring-mqtt to v5.3.0
  charts/stable/ring-mqtt/Chart.yaml
  charts/stable/ring-mqtt/values.yaml
Labels: automerge

#9514 chore(deps): update container image tccr.io/truecharts/tsmuxer to v23.06.1
  charts/stable/tsmuxer/Chart.yaml
  charts/stable/tsmuxer/values.yaml
Labels: automerge

#9507 chore(deps): update container image tccr.io/truecharts/minio-console to v0.29.0
  charts/stable/minio-console/Chart.yaml
  charts/stable/minio-console/values.yaml
Labels: automerge

#9506 chore(deps): update container image tccr.io/truecharts/mediainfo to v23.06.1
  charts/stable/mediainfo/Chart.yaml
  charts/stable/mediainfo/values.yaml
Labels: automerge

#9504 chore(deps): update container image tccr.io/truecharts/jdownloader-2 to v23.06.1
  charts/stable/jdownloader2/Chart.yaml
  charts/stable/jdownloader2/values.yaml
Labels: automerge

#9508 chore(deps): update container image tccr.io/truecharts/mkvtoolnix to v23.06.1
  charts/stable/mkvtoolnix/Chart.yaml
  charts/stable/mkvtoolnix/values.yaml
Labels: automerge

#9505 chore(deps): update container image tccr.io/truecharts/makemkv to v23.06.1
  charts/stable/makemkv/Chart.yaml
  charts/stable/makemkv/values.yaml
Labels: automerge

#9515 chore(deps): update container image tccr.io/truecharts/xenorchestra to v5.116.3
  charts/stable/xen-orchestra/Chart.yaml
  charts/stable/xen-orchestra/values.yaml
Labels: automerge

#9512 chore(deps): update container image tccr.io/truecharts/qdirstat to v23.06.1
  charts/stable/qdirstat/Chart.yaml
  charts/stable/qdirstat/values.yaml
Labels: automerge

#9511 chore(deps): update container image tccr.io/truecharts/putty to v23.06.1
  charts/stable/putty/Chart.yaml
  charts/stable/putty/values.yaml
Labels: automerge

#9518 chore(deps): update jupyter to v2023-06 (minor)
  charts/stable/jupyter/Chart.yaml
  charts/stable/jupyter/values.yaml
Labels: automerge

#9510 chore(deps): update container image tccr.io/truecharts/photoprism to v230607
  charts/stable/photoprism/Chart.yaml
  charts/stable/photoprism/values.yaml
Labels: automerge

#9519 chore(deps): update container image tccr.io/truecharts/fileflows to v23.06.1
  charts/stable/fileflows/Chart.yaml
  charts/stable/fileflows/values.yaml
Labels: automerge

#9520 chore(deps): update container image tccr.io/truecharts/firefox to v113.0.2
  charts/stable/firefox/Chart.yaml
  charts/stable/firefox/values.yaml
Labels: automerge

#9500 chore(deps): update helm chart common to 12.13.1
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/kube-state-metrics/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/node-exporter/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
  templates/chart/Chart.yaml
Labels: automerge

#9526 chore(deps): update container image tccr.io/truecharts/mariadb to v10.11.4
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/mariadb/values.yaml
Labels: automerge, update/docker/general/non-major

#9523 chore(deps): update container image tccr.io/truecharts/minio to latest
  charts/stable/minio/Chart.yaml
  charts/stable/minio/values.yaml
Labels: automerge, update/docker/general/non-major

#9529 chore(deps): update container image tccr.io/truecharts/prowlarr to v1.5.2.3484
  charts/stable/prowlarr/Chart.yaml
  charts/stable/prowlarr/values.yaml
Labels: automerge, update/docker/general/non-major

#9531 chore(deps): update container image tccr.io/truecharts/sabnzbd to v4.0.2
  charts/stable/sabnzbd/Chart.yaml
  charts/stable/sabnzbd/values.yaml
Labels: automerge, update/docker/general/non-major

#9528 chore(deps): update container image tccr.io/truecharts/plex to v1.32.3.7162
  charts/stable/plex/Chart.yaml
  charts/stable/plex/values.yaml
Labels: automerge, update/docker/general/non-major

#9522 chore(deps): update container image tccr.io/truecharts/libremdb to latest
  charts/stable/libremdb/Chart.yaml
  charts/stable/libremdb/values.yaml
Labels: automerge, update/docker/general/non-major

#9530 chore(deps): update container image tccr.io/truecharts/readarr to v0.1.7.1882
  charts/stable/readarr/Chart.yaml
  charts/stable/readarr/values.yaml
Labels: automerge, update/docker/general/non-major

#9536 chore(deps): update container image tccr.io/truecharts/czkawka to v23.06.1
  charts/stable/czkawka/Chart.yaml
  charts/stable/czkawka/values.yaml
Labels: automerge, update/docker/general/non-major

#9537 chore(deps): update container image tccr.io/truecharts/thelounge to v4.4.0
  charts/stable/thelounge/Chart.yaml
  charts/stable/thelounge/values.yaml
Labels: automerge, update/docker/general/non-major

#9535 chore(deps): update helm general non-major
  charts/stable/thelounge/Chart.yaml
Labels: automerge

#9498 chore(deps): update container image tccr.io/truecharts/hedgedoc to v1.9.8
  charts/stable/hedgedoc/Chart.yaml
  charts/stable/hedgedoc/values.yaml
Labels: automerge

#9527 chore(deps): update container image tccr.io/truecharts/n8n to v0.230.3
  charts/stable/n8n/Chart.yaml
  charts/stable/n8n/values.yaml
Labels: automerge

#9407 chore(deps): update container image tccr.io/truecharts/invidious to latest
  charts/stable/invidious/Chart.yaml
  charts/stable/invidious/values.yaml
Labels: automerge

#9534 chore(deps): update container image tccr.io/truecharts/wikijs to v2.5.299
  charts/stable/wikijs/Chart.yaml
  charts/stable/wikijs/values.yaml
Labels: automerge

#9499 chore(deps): update container image tccr.io/truecharts/kanboard to v1.2.30
  charts/stable/kanboard/Chart.yaml
  charts/stable/kanboard/values.yaml
Labels: automerge

#9532 chore(deps): update container image tccr.io/truecharts/shlink to v3.6.2
  charts/stable/shlink/Chart.yaml
  charts/stable/shlink/values.yaml
Labels: automerge

#9516 chore(deps): update container image tccr.io/truecharts/xwiki to v15.4.0
  charts/stable/xwiki/Chart.yaml
  charts/stable/xwiki/values.yaml
Labels: automerge

#9438 chore(deps): update container image tccr.io/truecharts/quassel-core to v0.14.0
  charts/stable/quassel-core/Chart.yaml
  charts/stable/quassel-core/values.yaml
Labels: automerge

#9509 chore(deps): update container image tccr.io/truecharts/n8n to v0.232.0
  charts/stable/n8n/Chart.yaml
  charts/stable/n8n/values.yaml
Labels: automerge

#9545 chore(deps): update container image tccr.io/truecharts/watchyourlan to v0.9.3
  charts/stable/watchyourlan/Chart.yaml
  charts/stable/watchyourlan/values.yaml
Labels: automerge, update/docker/general/non-major

#9544 chore(deps): update container image tccr.io/truecharts/emby to v4.7.13.0
  charts/stable/emby/Chart.yaml
  charts/stable/emby/values.yaml
Labels: automerge, update/docker/general/non-major

#9546 chore(deps): update container image tccr.io/truecharts/syncthing to v1.23.5
  charts/stable/syncthing/Chart.yaml
  charts/stable/syncthing/values.yaml
Labels: automerge, update/docker/general/non-major

#9547 chore(deps): update container image tccr.io/truecharts/flexget to v3.7.4
  charts/stable/flexget/Chart.yaml
  charts/stable/flexget/values.yaml
Labels: automerge, update/docker/general/non-major

#9548 chore(deps): update immich to v1.60.0 (minor)
  charts/stable/immich/Chart.yaml
  charts/stable/immich/values.yaml
Labels: automerge
