Repository trueforge-org/truecharts, pull requests merged in 2023-01, with the labels that each got.

#5918 chore(deps): update container image tccr.io/truecharts/lancache-dns to latest
  charts/stable/lancache-dns/Chart.yaml
  charts/stable/lancache-dns/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5920 chore(deps): update container image tccr.io/truecharts/lancache-monolithic to latest
  charts/stable/lancache-monolithic/Chart.yaml
  charts/stable/lancache-monolithic/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5919 chore(deps): update container image tccr.io/truecharts/fleet to 2.3.3
  charts/stable/fleet/Chart.yaml
  charts/stable/fleet/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#5923 chore(deps): update container image tccr.io/truecharts/quassel-core to v0.14.0
  charts/stable/quassel-core/Chart.yaml
  charts/stable/quassel-core/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5921 fix(appdaemon) fix port + gui upkeep + docs
  charts/stable/appdaemon/Chart.yaml
  charts/stable/appdaemon/docs/installation_guide.md
  charts/stable/appdaemon/questions.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#5924 chore(deps): update renovatebot/github-action action to v34.77.1
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#5930 chore(deps): update container image tccr.io/truecharts/homepage to v0.5.9
  charts/stable/homepage/Chart.yaml
  charts/stable/homepage/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5926 chore(deps): update container image tccr.io/truecharts/goaccess-npm-logs to latest
  charts/incubator/goaccess-npm-logs/Chart.yaml
  charts/incubator/goaccess-npm-logs/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5925 chore(deps): update container image tccr.io/truecharts/dillinger to v3.39.1
  charts/stable/dillinger/Chart.yaml
  charts/stable/dillinger/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5933 chore(deps): update container image tccr.io/truecharts/prowlarr to v1.0.1.2210
  charts/stable/prowlarr/Chart.yaml
  charts/stable/prowlarr/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5928 chore(deps): update container image tccr.io/truecharts/bazarr to v1.1.4
  charts/stable/bazarr/Chart.yaml
  charts/stable/bazarr/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5929 chore(deps): update container image tccr.io/truecharts/flexget to v3.5.15
  charts/stable/flexget/Chart.yaml
  charts/stable/flexget/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5934 chore(deps): update container image tccr.io/truecharts/artifactory-oss to v7.49.3
  charts/incubator/artifactory-oss/Chart.yaml
  charts/incubator/artifactory-oss/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5932 chore(deps): update container image tccr.io/truecharts/paperless-ng to v1.11.2
  charts/stable/paperless-ng/Chart.yaml
  charts/stable/paperless-ng/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5935 chore(deps): update container image tccr.io/truecharts/authentik to v2022.12.1
  charts/stable/authentik/Chart.yaml
  charts/stable/authentik/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#5937 chore(deps): update container image tccr.io/truecharts/dashdot to v4.6.0
  charts/stable/dashdot/Chart.yaml
  charts/stable/dashdot/values.yaml
Labels: size/XS, automerge, update/docker/general/non-major

#5927 chore(deps): update container image tccr.io/truecharts/xenorchestra to 5.107.5
  charts/stable/xen-orchestra/Chart.yaml
  charts/stable/xen-orchestra/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#5931 chore(deps): update container image tccr.io/truecharts/leantime to v2.3.3
  charts/stable/leantime/Chart.yaml
  charts/stable/leantime/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#5945 fix(wordpress) update php-config variable
  charts/stable/wordpress/Chart.yaml
  charts/stable/wordpress/templates/_env.tpl
Labels: size/XS, install:ok, lint:ok, precommit:ok

#5949 fix(arksurvivalevolved) fix configmap
  charts/incubator/arksurvivalevolved/Chart.yaml
  charts/incubator/arksurvivalevolved/questions.yaml
  charts/incubator/arksurvivalevolved/templates/_secret.tpl
Labels: size/XS, install:ok, lint:ok, precommit:ok

#5946 fix(appdaemon) valid_chars for long | lat
  charts/stable/appdaemon/Chart.yaml
  charts/stable/appdaemon/docs/validation.md
  charts/stable/appdaemon/questions.yaml
  charts/stable/appdaemon/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#5948 fix(terraria) code clean up + gui overhaul
  charts/incubator/terraria-tshock/Chart.yaml
  charts/incubator/terraria-tshock/questions.yaml
  charts/incubator/terraria-tshock/templates/_secret.tpl
  charts/incubator/terraria-tshock/templates/common.yaml
  charts/incubator/terraria-tshock/values.yaml
Labels: size/L

#5963 chore(deps): update container image tccr.io/truecharts/apprise-api to latest
  charts/incubator/apprise-api/Chart.yaml
  charts/incubator/apprise-api/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#5977 chore(deps): update container image tccr.io/truecharts/rustpad to latest
  charts/incubator/rustpad/Chart.yaml
  charts/incubator/rustpad/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#5966 chore(deps): update container image tccr.io/truecharts/ddclient to 3.10.0
  charts/stable/ddclient/Chart.yaml
  charts/stable/ddclient/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#5967 chore(deps): update container image tccr.io/truecharts/dokuwiki to 20220731.1.0
  charts/stable/dokuwiki/Chart.yaml
  charts/stable/dokuwiki/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#5961 chore(deps): update container image tccr.io/truecharts/adguardhome-sync to latest
  charts/incubator/adguardhome-sync/Chart.yaml
  charts/incubator/adguardhome-sync/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#5964 chore(deps): update container image tccr.io/truecharts/auto-yt-dl to latest
  charts/incubator/auto-yt-dl/Chart.yaml
  charts/incubator/auto-yt-dl/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#5980 chore(deps): update container image tccr.io/truecharts/synclounge to 5.2.5
  charts/stable/synclounge/Chart.yaml
  charts/stable/synclounge/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#5973 chore(deps): update container image tccr.io/truecharts/passwordpusherephemeral to latest
  charts/incubator/passwordpusherephemeral/Chart.yaml
  charts/incubator/passwordpusherephemeral/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#5974 chore(deps): update container image tccr.io/truecharts/pialert to latest
  charts/incubator/pialert/Chart.yaml
  charts/incubator/pialert/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#5970 chore(deps): update container image tccr.io/truecharts/medusa to 1.0.10
  charts/stable/medusa/Chart.yaml
  charts/stable/medusa/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#5962 chore(deps): update container image tccr.io/truecharts/alertmanager to 0.25.0
  charts/stable/prometheus/Chart.yaml
  charts/stable/prometheus/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#5971 chore(deps): update container image tccr.io/truecharts/mongodb to 6.0.3
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/mongodb/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#5988 chore(deps): update container image tccr.io/truecharts/watchyourlan to v0.8.3
  charts/stable/watchyourlan/Chart.yaml
  charts/stable/watchyourlan/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#5991 chore(deps): update container image tccr.io/truecharts/pihole to v2022.12.1
  charts/stable/pihole/Chart.yaml
  charts/stable/pihole/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#5976 chore(deps): update container image tccr.io/truecharts/redis to 7.0.7
  charts/dependency/redis/Chart.yaml
  charts/dependency/redis/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#5985 chore(deps): update container image tccr.io/truecharts/znc to v1.8.2
  charts/stable/znc/Chart.yaml
  charts/stable/znc/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#5983 chore(deps): update container image tccr.io/truecharts/wireshark to 3.6.5
  charts/stable/wireshark/Chart.yaml
  charts/stable/wireshark/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#5972 chore(deps): update container image tccr.io/truecharts/nitter to latest
  charts/incubator/nitter/Chart.yaml
  charts/incubator/nitter/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#5979 chore(deps): update container image tccr.io/truecharts/speedtest-tracker to latest
  charts/incubator/speedtest-tracker/Chart.yaml
  charts/incubator/speedtest-tracker/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#5965 chore(deps): update container image tccr.io/truecharts/dashy to 2.1.1
  charts/incubator/dashy/Chart.yaml
  charts/incubator/dashy/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#5968 chore(deps): update container image tccr.io/truecharts/invidious to latest
  charts/incubator/invidious/Chart.yaml
  charts/incubator/invidious/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#5982 chore(deps): update container image tccr.io/truecharts/wger to latest
  charts/stable/wger/Chart.yaml
  charts/stable/wger/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#5987 chore(deps): update container image tccr.io/truecharts/paperless-ng to v1.11.3
  charts/stable/paperless-ng/Chart.yaml
  charts/stable/paperless-ng/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#5984 chore(deps): update container image tccr.io/truecharts/wordpress to 6.1.1
  charts/stable/wordpress/Chart.yaml
  charts/stable/wordpress/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#5992 chore(deps): update renovatebot/github-action action to v34.83.1
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#5999 fix(prometheus): fix doc separator
  charts/stable/prometheus/Chart.yaml
  charts/stable/prometheus/templates/prometheus/_additionalScrapeJobs.tpl
Labels: size/XS, install:ok, lint:ok, precommit:ok

#5995 feat(cloudflareddns): BREAKING CHANGE - Rewrite GUI
  charts/stable/cloudflareddns/Chart.yaml
  charts/stable/cloudflareddns/docs/validation.md
  charts/stable/cloudflareddns/questions.yaml
  charts/stable/cloudflareddns/templates/_secret.tpl
  charts/stable/cloudflareddns/templates/common.yaml
  charts/stable/cloudflareddns/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#5947 feat(youtrack) add youtrack
  charts/incubator/youtrack/.helmignore
  charts/incubator/youtrack/Chart.yaml
  charts/incubator/youtrack/README.md
  charts/incubator/youtrack/docs/default_credentials.md
  charts/incubator/youtrack/icon.png
  charts/incubator/youtrack/questions.yaml
  charts/incubator/youtrack/templates/_init.tpl
  charts/incubator/youtrack/templates/common.yaml
  charts/incubator/youtrack/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#6000 fix(cloudflareddns) fix variable key
  charts/stable/cloudflareddns/Chart.yaml
  charts/stable/cloudflareddns/questions.yaml
  charts/stable/cloudflareddns/templates/_secret.tpl
Labels: size/XS, install:ok, lint:ok, precommit:ok

#5997 fix(gotify): BREAKING CHANGE - Rewrite app
  charts/stable/gotify/Chart.yaml
  charts/stable/gotify/questions.yaml
  charts/stable/gotify/templates/_configmap.tpl
  charts/stable/gotify/templates/_secret.tpl
  charts/stable/gotify/templates/common.yaml
  charts/stable/gotify/values.yaml
  cspell.config.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#6001 fix(cloudflareddns) fix record type variable list
  charts/stable/cloudflareddns/Chart.yaml
  charts/stable/cloudflareddns/questions.yaml
  charts/stable/cloudflareddns/values.yaml
Labels: size/S, precommit:failed, lint:ok

#5953 fix(jenkins) jenkins add configmap
  charts/incubator/jenkins/Chart.yaml
  charts/incubator/jenkins/questions.yaml
  charts/incubator/jenkins/templates/_secret.tpl
  charts/incubator/jenkins/templates/common.yaml
  charts/incubator/jenkins/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#6008 chore(deps): update container image tccr.io/truecharts/adminer to latest
  charts/stable/adminer/Chart.yaml
  charts/stable/adminer/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6040 chore(deps): update container image tccr.io/truecharts/jupyter-datascience to v
  charts/stable/jupyter/Chart.yaml
  charts/stable/jupyter/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6016 chore(deps): update container image tccr.io/truecharts/calibre-web to 0.6.19
  charts/stable/calibre-web/Chart.yaml
  charts/stable/calibre-web/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6017 chore(deps): update container image tccr.io/truecharts/cloudbeaver to latest
  charts/incubator/cloudbeaver/Chart.yaml
  charts/incubator/cloudbeaver/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6031 chore(deps): update container image tccr.io/truecharts/googlephotossync to latest
  charts/incubator/googlephotossync/Chart.yaml
  charts/incubator/googlephotossync/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6018 chore(deps): update container image tccr.io/truecharts/cops to latest
  charts/incubator/cops/Chart.yaml
  charts/incubator/cops/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6009 chore(deps): update container image tccr.io/truecharts/alertmanager to 0.25.0
  charts/stable/prometheus/Chart.yaml
  charts/stable/prometheus/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6035 chore(deps): update container image tccr.io/truecharts/hedgedoc to 1.9.6
  charts/stable/hedgedoc/Chart.yaml
  charts/stable/hedgedoc/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6012 chore(deps): update container image tccr.io/truecharts/boinc to latest
  charts/stable/boinc/Chart.yaml
  charts/stable/boinc/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6027 chore(deps): update container image tccr.io/truecharts/duckdns to latest
  charts/stable/duckdns/Chart.yaml
  charts/stable/duckdns/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6013 chore(deps): update container image tccr.io/truecharts/booksonic-air to v2201.1.0
  charts/stable/booksonic-air/Chart.yaml
  charts/stable/booksonic-air/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6015 chore(deps): update container image tccr.io/truecharts/calibre to 6.10.0
  charts/stable/calibre/Chart.yaml
  charts/stable/calibre/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6051 chore(deps): update container image tccr.io/truecharts/littlelink-server to latest
  charts/stable/littlelink/Chart.yaml
  charts/stable/littlelink/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6026 chore(deps): update container image tccr.io/truecharts/dokuwiki to 20220731.1.0
  charts/stable/dokuwiki/Chart.yaml
  charts/stable/dokuwiki/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6019 chore(deps): update container image tccr.io/truecharts/cryptpad to latest
  charts/incubator/cryptpad/Chart.yaml
  charts/incubator/cryptpad/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6011 chore(deps): update container image tccr.io/truecharts/blender to latest
  charts/incubator/blender/Chart.yaml
  charts/incubator/blender/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6010 chore(deps): update container image tccr.io/truecharts/babybuddy to 1.13.2
  charts/stable/babybuddy/Chart.yaml
  charts/stable/babybuddy/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6032 chore(deps): update container image tccr.io/truecharts/grafana to 9.3.2
  charts/stable/grafana/Chart.yaml
  charts/stable/grafana/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6028 chore(deps): update container image tccr.io/truecharts/farmos to latest
  charts/incubator/farmos/Chart.yaml
  charts/incubator/farmos/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6021 chore(deps): update container image tccr.io/truecharts/cura-novnc to latest
  charts/stable/cura-novnc/Chart.yaml
  charts/stable/cura-novnc/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6033 chore(deps): update container image tccr.io/truecharts/grocy to 3.3.2
  charts/stable/grocy/Chart.yaml
  charts/stable/grocy/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6064 chore(deps): update container image tccr.io/truecharts/observium to latest
  charts/incubator/observium/Chart.yaml
  charts/incubator/observium/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6055 chore(deps): update container image tccr.io/truecharts/memcached to 1.6.17
  charts/dependency/memcached/Chart.yaml
  charts/dependency/memcached/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6048 chore(deps): update container image tccr.io/truecharts/lazylibrarian to latest
  charts/stable/lazylibrarian/Chart.yaml
  charts/stable/lazylibrarian/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6060 chore(deps): update container image tccr.io/truecharts/mylar3 to 0.7.0
  charts/stable/mylar/Chart.yaml
  charts/stable/mylar/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6058 chore(deps): update container image tccr.io/truecharts/mongodb to 6.0.3
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/mongodb/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6053 chore(deps): update container image tccr.io/truecharts/mariadb to 10.10.2
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/mariadb/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6061 chore(deps): update container image tccr.io/truecharts/mysql-workbench to 8.0.31
  charts/stable/mysql-workbench/Chart.yaml
  charts/stable/mysql-workbench/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6046 chore(deps): update container image tccr.io/truecharts/kdenlive to latest
  charts/incubator/kdenlive/Chart.yaml
  charts/incubator/kdenlive/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6038 chore(deps): update container image tccr.io/truecharts/invidious to latest
  charts/incubator/invidious/Chart.yaml
  charts/incubator/invidious/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6059 chore(deps): update container image tccr.io/truecharts/monica to v3.7.0
  charts/stable/monica/Chart.yaml
  charts/stable/monica/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6054 chore(deps): update container image tccr.io/truecharts/matomo to 4.13.0
  charts/stable/matomo/Chart.yaml
  charts/stable/matomo/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6062 chore(deps): update container image tccr.io/truecharts/neko-firefox to latest
  charts/incubator/neko/Chart.yaml
  charts/incubator/neko/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6057 chore(deps): update container image tccr.io/truecharts/minecraft-java8-openj9 to latest
  charts/stable/minecraft-java/Chart.yaml
  charts/stable/minecraft-java/ci/j8-values.yaml
  charts/stable/minecraft-java/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6006 chore(deps): update actions/checkout digest to ac59398
  .github/workflows/catalog-test.yaml
  .github/workflows/charts-changelog.yaml
  .github/workflows/charts-lint.yaml
  .github/workflows/charts-release.yaml
  .github/workflows/charts-test.yaml
  .github/workflows/daily.yaml
  .github/workflows/meta-label-pr-ci-status.yaml
  .github/workflows/metadata-label-commenter.yaml
  .github/workflows/pr-metadata.yaml
  .github/workflows/pr-validate.yaml
  .github/workflows/prune.yaml
  .github/workflows/renovate-bump.yaml
  .github/workflows/schedule-sync-labels.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#6007 chore(deps): update actions/upload-artifact digest to 0b7f8ab
  .github/workflows/pr-metadata.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#6020 chore(deps): update container image tccr.io/truecharts/cups-server to latest
  charts/incubator/cups-server/Chart.yaml
  charts/incubator/cups-server/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6025 chore(deps): update container image tccr.io/truecharts/docker-in-docker to 20.10.22
  charts/stable/docker-compose/Chart.yaml
  charts/stable/docker-compose/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6036 chore(deps): update container image tccr.io/truecharts/icloudpd to latest
  charts/incubator/icloudpd/Chart.yaml
  charts/incubator/icloudpd/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6043 chore(deps): update container image tccr.io/truecharts/jupyter-r to v
  charts/stable/jupyter/Chart.yaml
  charts/stable/jupyter/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6037 chore(deps): update container image tccr.io/truecharts/impostor-server-nightly to vnightly
  charts/stable/impostor-server/Chart.yaml
  charts/stable/impostor-server/ci/values.yaml
  charts/stable/impostor-server/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6052 chore(deps): update container image tccr.io/truecharts/logitechmediaserver to 8.4.0
  charts/stable/logitech-media-server/Chart.yaml
  charts/stable/logitech-media-server/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6063 chore(deps): update container image tccr.io/truecharts/obs-ndi to latest
  charts/incubator/obs-ndi/Chart.yaml
  charts/incubator/obs-ndi/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6050 chore(deps): update container image tccr.io/truecharts/libreoffice to 7.2.7
  charts/stable/libreoffice/Chart.yaml
  charts/stable/libreoffice/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6030 chore(deps): update container image tccr.io/truecharts/firefox to 101.0.1
  charts/stable/firefox/Chart.yaml
  charts/stable/firefox/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6023 chore(deps): update container image tccr.io/truecharts/darktable to 3.8.1
  charts/stable/darktable/Chart.yaml
  charts/stable/darktable/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6029 chore(deps): update container image tccr.io/truecharts/filezilla to 3.59.0
  charts/stable/filezilla/Chart.yaml
  charts/stable/filezilla/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6034 chore(deps): update container image tccr.io/truecharts/habridge to v5.4.1
  charts/stable/habridge/Chart.yaml
  charts/stable/habridge/questions.yaml
  charts/stable/habridge/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6120 chore(deps): update dawidd6/action-download-artifact action to v2.24.3
  .github/workflows/meta-label-pr-ci-status.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#6134 chore(deps): update renovatebot/github-action action to v34.92.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#6133 chore(deps): update helm/chart-releaser-action action to v1.5.0
  .github/workflows/charts-release.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#6122 chore(deps): update actions/checkout action to v3.3.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#6090 chore(deps): update container image tccr.io/truecharts/rdesktop-arch-icewm to latest
  charts/stable/rdesktop/Chart.yaml
  charts/stable/rdesktop/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6077 chore(deps): update container image tccr.io/truecharts/plextraktsync to latest
  charts/incubator/plextraktsync/Chart.yaml
  charts/incubator/plextraktsync/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6079 chore(deps): update container image tccr.io/truecharts/prometheus to 2.41.0
  charts/stable/prometheus/Chart.yaml
  charts/stable/prometheus/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6103 chore(deps): update container image tccr.io/truecharts/rsnapshot to 1.4.4
  charts/stable/rsnapshot/Chart.yaml
  charts/stable/rsnapshot/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6105 chore(deps): update container image tccr.io/truecharts/searxng to latest
  charts/incubator/searxng/Chart.yaml
  charts/incubator/searxng/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6116 chore(deps): update container image tccr.io/truecharts/webp-server to latest
  charts/incubator/webp-server/Chart.yaml
  charts/incubator/webp-server/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6082 chore(deps): update container image tccr.io/truecharts/raneto to latest
  charts/incubator/raneto/Chart.yaml
  charts/incubator/raneto/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6102 chore(deps): update container image tccr.io/truecharts/rimgo to latest
  charts/incubator/rimgo/Chart.yaml
  charts/incubator/rimgo/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6080 chore(deps): update container image tccr.io/truecharts/pyload-ng to latest
  charts/incubator/pyload-ng/Chart.yaml
  charts/incubator/pyload-ng/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6107 chore(deps): update container image tccr.io/truecharts/sickchill to 2022.10.13
  charts/stable/sickchill/Chart.yaml
  charts/stable/sickchill/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6131 chore(deps): update container image tccr.io/truecharts/jupyter-tensorflow to v2022-12
  charts/stable/jupyter/Chart.yaml
  charts/stable/jupyter/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6106 chore(deps): update container image tccr.io/truecharts/shoko-server to vdaily
  charts/incubator/shoko-server/Chart.yaml
  charts/incubator/shoko-server/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6109 chore(deps): update container image tccr.io/truecharts/tasmocompiler to latest
  charts/incubator/tasmocompiler/Chart.yaml
  charts/incubator/tasmocompiler/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6112 chore(deps): update container image tccr.io/truecharts/tvheadend to latest
  charts/stable/tvheadend/Chart.yaml
  charts/stable/tvheadend/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6119 chore(deps): update container image tccr.io/truecharts/prowlarr to v1.0.1.2220
  charts/stable/prowlarr/Chart.yaml
  charts/stable/prowlarr/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6114 chore(deps): update container image tccr.io/truecharts/universal-media-server to latest
  charts/incubator/universal-media-server/Chart.yaml
  charts/incubator/universal-media-server/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6110 chore(deps): update container image tccr.io/truecharts/tracks to latest
  charts/incubator/tracks/Chart.yaml
  charts/incubator/tracks/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6132 chore(deps): update container image tccr.io/truecharts/ombi to v4.35.1
  charts/stable/ombi/Chart.yaml
  charts/stable/ombi/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6108 chore(deps): update container image tccr.io/truecharts/solr to 9.1.0
  charts/dependency/solr/Chart.yaml
  charts/dependency/solr/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6123 chore(deps): update container image jenkins/jenkins to v2.385
  charts/incubator/jenkins/Chart.yaml
  charts/incubator/jenkins/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6113 chore(deps): update container image tccr.io/truecharts/twonky-server to latest
  charts/incubator/twonky-server/Chart.yaml
  charts/incubator/twonky-server/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6115 chore(deps): update container image tccr.io/truecharts/vertex to vstable
  charts/incubator/vertex/Chart.yaml
  charts/incubator/vertex/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6104 chore(deps): update container image tccr.io/truecharts/rsshub to latest
  charts/stable/rsshub/Chart.yaml
  charts/stable/rsshub/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6117 chore(deps): update container image tccr.io/truecharts/wordpress to 6.1.1
  charts/stable/wordpress/Chart.yaml
  charts/stable/wordpress/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6144 chore(deps): update container image tccr.io/truecharts/serpbear to latest
  charts/incubator/serpbear/Chart.yaml
  charts/incubator/serpbear/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6142 chore(deps): update container image tccr.io/truecharts/jupyter-scipy to v2023-01
  charts/stable/jupyter/Chart.yaml
  charts/stable/jupyter/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6111 chore(deps): update container image tccr.io/truecharts/ts-dnsserver to latest
  charts/incubator/ts-dnsserver/Chart.yaml
  charts/incubator/ts-dnsserver/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6137 chore(deps): update container image tccr.io/truecharts/jupyter-base to v2023-01
  charts/stable/jupyter/Chart.yaml
  charts/stable/jupyter/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6081 chore(deps): update container image tccr.io/truecharts/ra-rom-processor to latest
  charts/incubator/ra-rom-processor/Chart.yaml
  charts/incubator/ra-rom-processor/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6145 chore(deps): update container image tccr.io/truecharts/virt-manager to latest
  charts/incubator/virt-manager/Chart.yaml
  charts/incubator/virt-manager/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge

#6151 chore(deps): update container image tccr.io/truecharts/rdesktop-fedora-openbox to latest
  charts/stable/rdesktop/Chart.yaml
  charts/stable/rdesktop/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#6146 chore(deps): update container image tccr.io/truecharts/impostor-server-nightly to vnightly
  charts/stable/impostor-server/Chart.yaml
  charts/stable/impostor-server/ci/values.yaml
  charts/stable/impostor-server/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#6074 fix(Docs): Update SUPPORT.md to remove 22.02.4
  .github/SUPPORT.md
Labels: size/XS, install:ok, lint:ok, precommit:ok

#6153 chore(deps): update renovatebot/github-action action to v34.92.1
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#6157 chore(deps): update renovatebot/github-action action to v34.93.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#6154 fix(metube): BREAKING CHANGES - separate config/download dirs.
  charts/stable/metube/Chart.yaml
  charts/stable/metube/questions.yaml
  charts/stable/metube/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#6156 Fix documentation manual link
  .github/README.md
Labels: size/XS, install:ok, lint:ok, precommit:ok

#6159 docs: update .github/README.md [skip ci]
  .all-contributorsrc
  .github/README.md
Labels: size/L

#6155 fix(plex-meta-manager) add configmap + gui options
  charts/incubator/plex-meta-manager/Chart.yaml
  charts/incubator/plex-meta-manager/questions.yaml
  charts/incubator/plex-meta-manager/templates/_secret.tpl
  charts/incubator/plex-meta-manager/templates/common.yaml
  charts/incubator/plex-meta-manager/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#6161 feat (invidious): move to stable
  charts/stable/invidious/.helmignore
  charts/stable/invidious/CHANGELOG.md
  charts/stable/invidious/Chart.yaml
  charts/stable/invidious/README.md
  charts/stable/invidious/docs/validation.md
  charts/stable/invidious/icon.png
  charts/stable/invidious/questions.yaml
  charts/stable/invidious/templates/_config.tpl
  charts/stable/invidious/templates/_dbseed.tpl
  charts/stable/invidious/templates/common.yaml
  charts/stable/invidious/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#6162 chore(deps): update renovatebot/github-action action to v34.94.0
  .github/workflows/renovate.yml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#6158 WIP feat(checkmk): add checkmk
  charts/incubator/checkmk/.helmignore
  charts/incubator/checkmk/CHANGELOG.md
  charts/incubator/checkmk/Chart.yaml
  charts/incubator/checkmk/README.md
  charts/incubator/checkmk/icon.png
  charts/incubator/checkmk/questions.yaml
  charts/incubator/checkmk/templates/_secret.tpl
  charts/incubator/checkmk/templates/common.yaml
  charts/incubator/checkmk/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#6163 chore(deps): update container image tccr.io/truecharts/uptime-kuma to v1.19.3
  charts/stable/uptime-kuma/Chart.yaml
  charts/stable/uptime-kuma/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major

#6166 chore(deps): update container image tccr.io/truecharts/plex-meta-manager to v1.18.2
  charts/incubator/plex-meta-manager/Chart.yaml
  charts/incubator/plex-meta-manager/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok, automerge, update/docker/general/non-major
