Repository trueforge-org/truecharts, pull requests merged in 2023-03, with the labels that each got.

#7746 fix(dependency): update dependency common linking
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/clickhouse/ci/basic-values.yaml
  charts/dependency/clickhouse/values.yaml
  charts/dependency/collabora-online/.helmignore
  charts/dependency/collabora-online/CHANGELOG.md
  charts/dependency/collabora-online/Chart.yaml
  charts/dependency/collabora-online/README.md
  charts/dependency/collabora-online/docs/installation_notes.md
  charts/dependency/collabora-online/docs/validation.md
  charts/dependency/collabora-online/icon.png
  charts/dependency/collabora-online/questions.yaml
  charts/dependency/collabora-online/templates/NOTES.txt
  charts/dependency/collabora-online/templates/common.yaml
  charts/dependency/collabora-online/values.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/mariadb/ci/basic-values.yaml
  charts/dependency/mariadb/values.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/memcached/values.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/mongodb/ci/basic-values.yaml
  charts/dependency/mongodb/values.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/redis/ci/basic-values.yaml
  charts/dependency/redis/values.yaml
  charts/dependency/solr/Chart.yaml
  charts/dependency/solr/ci/basic-values.yaml
  charts/dependency/solr/values.yaml
  charts/dependency/subchart/Chart.yaml
Labels: size/XL, lint:ok, precommit:ok

#7747 chore(enterprise): bump common and enterprise train for stability
  charts/enterprise/authelia/Chart.yaml
  charts/enterprise/blocky/Chart.yaml
  charts/enterprise/cert-manager/Chart.yaml
  charts/enterprise/grafana/Chart.yaml
  charts/enterprise/metallb/Chart.yaml
  charts/enterprise/prometheus/Chart.yaml
  charts/enterprise/traefik/Chart.yaml
  charts/enterprise/vaultwarden/Chart.yaml
Labels: size/S, lint:failed, precommit:ok

#7748 chore(dependency): bump dependency train
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
  charts/dependency/subchart/Chart.yaml
Labels: size/S, lint:ok, precommit:ok

#7749 chore(enterprise): bump common and dependencies
  charts/enterprise/authelia/Chart.yaml
  charts/enterprise/authelia/templates/common.yaml
  charts/enterprise/blocky/Chart.yaml
  charts/enterprise/blocky/questions.yaml
  charts/enterprise/cert-manager/Chart.yaml
  charts/enterprise/grafana/Chart.yaml
  charts/enterprise/metallb/Chart.yaml
  charts/enterprise/prometheus/Chart.yaml
  charts/enterprise/traefik/Chart.yaml
  charts/enterprise/vaultwarden/Chart.yaml
Labels: lint:ok, size/M, precommit:ok

#7752 fix(blocky/grafana): minor fixes
  charts/enterprise/blocky/Chart.yaml
  charts/enterprise/blocky/templates/_k8sgateway.tpl
  charts/enterprise/blocky/templates/common.yaml
  charts/enterprise/grafana/Chart.yaml
  charts/enterprise/grafana/questions.yaml
Labels: install:failed, lint:ok, size/M, precommit:ok

#7755 fix(prometheus): fix tpl error
  charts/enterprise/prometheus/Chart.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#7758 fix(Common): Fix fsGroup of dependency train
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/clickhouse/questions.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/mariadb/questions.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/memcached/questions.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/mongodb/questions.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/redis/questions.yaml
  charts/dependency/solr/Chart.yaml
  charts/dependency/solr/questions.yaml
Labels: size/S, lint:ok, precommit:ok

#7754 fix(cert-manager) fix ACME ClusterIssuer support
  charts/enterprise/cert-manager/Chart.yaml
  charts/enterprise/cert-manager/templates/clusterissuer/_ACME.tpl
Labels: size/XS, install:ok, lint:ok, precommit:ok

#7760 feat(blocky): add support for more query logging options, including postgresql
  charts/enterprise/blocky/Chart.yaml
  charts/enterprise/blocky/ci/postgresql-values.yaml
  charts/enterprise/blocky/questions.yaml
  charts/enterprise/blocky/templates/_blockyConfig.tpl
  charts/enterprise/blocky/templates/common.yaml
  charts/enterprise/blocky/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#7762 fix(enterprise): misc fixes from common and prometheus storageclass p…
  charts/enterprise/authelia/Chart.yaml
  charts/enterprise/blocky/Chart.yaml
  charts/enterprise/cert-manager/Chart.yaml
  charts/enterprise/grafana/Chart.yaml
  charts/enterprise/metallb/Chart.yaml
  charts/enterprise/prometheus/Chart.yaml
  charts/enterprise/prometheus/templates/alertmanager/_alertmanager.tpl
  charts/enterprise/prometheus/templates/prometheus/_prometheus.tpl
  charts/enterprise/traefik/Chart.yaml
  charts/enterprise/vaultwarden/Chart.yaml
Labels: size/S

#7763 fix(traefik): actually fix labels
  charts/enterprise/traefik/Chart.yaml
  charts/enterprise/traefik/templates/_ingressclass.tpl
Labels: size/XS, install:ok, lint:ok, precommit:ok

#7764 fix(authelia): fix broken fetching of old values on authelia
  charts/enterprise/authelia/Chart.yaml
  charts/enterprise/authelia/templates/_configmap.tpl
  charts/enterprise/authelia/templates/_secrets.tpl
  charts/enterprise/authelia/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#7768 chore(authelia): cleanup secret a bit
  charts/enterprise/authelia/Chart.yaml
  charts/enterprise/authelia/questions.yaml
  charts/enterprise/authelia/templates/_secrets.tpl
  cspell.config.yaml
  templates/questions/container/containerBasic.yaml
  templates/questions/workload/replicas1.yaml
  templates/questions/workload/replicas2.yaml
  templates/questions/workload/replicas3.yaml
  templates/questions/workload/workloadDaemonset.yaml
  templates/questions/workload/workloadDeployment.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#7770 fix(authelia): indent priv key
  charts/enterprise/authelia/Chart.yaml
  charts/enterprise/authelia/templates/_secrets.tpl
Labels: size/XS, install:ok, lint:ok, precommit:ok

#7774 Template(Configmap) Uncertainty Configmap changes (Bulk work)
  charts/stable/focalboard/templates/_configmap.tpl
  charts/stable/focalboard/templates/common.yaml
  charts/stable/immich/templates/_configmap.tpl
  charts/stable/immich/templates/common.yaml
  charts/stable/inventree/templates/_configmap.tpl
  charts/stable/inventree/templates/common.yaml
  charts/stable/k8s-gateway/templates/_configmap.tpl
  charts/stable/k8s-gateway/templates/common.yaml
  charts/stable/mealie/templates/_configmap.tpl
  charts/stable/mealie/templates/common.yaml
  charts/stable/nextcloud/templates/_configmap.tpl
  charts/stable/nextcloud/templates/common.yaml
  charts/stable/nocodb/templates/_configmap.tpl
  charts/stable/nocodb/templates/common.yaml
  charts/stable/statping-ng/templates/_configmap.tpl
  charts/stable/statping-ng/templates/common.yaml
  charts/stable/synapse/templates/_configmap.tpl
  charts/stable/synapse/templates/common.yaml
  charts/stable/tailscale/templates/_configmap.tpl
  charts/stable/tailscale/templates/common.yaml
  charts/stable/wbo/templates/_configmap.tpl
  charts/stable/wbo/templates/common.yaml
  charts/stable/wger/templates/_configmap.tpl
  charts/stable/wger/templates/common.yaml
  charts/stable/wireguard/templates/_configmap.tpl
  charts/stable/wireguard/templates/common.yaml
Labels: size/L, precommit:ok

#7776 cert-manager: show correct fields for DigitalOcean and RFC2136 Cluster Issuers
  charts/enterprise/cert-manager/Chart.yaml
  charts/enterprise/cert-manager/questions.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#7778 feat(Stable): Attempt at some secrets/configmaps
  charts/stable/cloudflareddns/templates/common.yaml
  charts/stable/discordgsm/templates/_secret.tpl
  charts/stable/discordgsm/templates/common.yaml
  charts/stable/penpot/templates/_secret.tpl
  charts/stable/penpot/templates/common.yaml
Labels: size/S, precommit:ok

#7787 fix(cert-manager): Do validation earlier, and add missing `---` before PodMonitor, causing objects to merge
  charts/enterprise/cert-manager/Chart.yaml
  charts/enterprise/cert-manager/templates/_metrics.tpl
  charts/enterprise/cert-manager/templates/clusterissuer/_ACME.tpl
Labels: size/S, install:ok, lint:ok, precommit:ok

#7785 feat(traefik): generate a service monitor
  charts/enterprise/traefik/Chart.yaml
  charts/enterprise/traefik/questions.yaml
  charts/enterprise/traefik/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#7780 feat(port/stable): More config map/secrets fixes
  charts/stable/audiobookshelf/templates/_secrets.tpl
  charts/stable/audiobookshelf/templates/common.yaml
  charts/stable/baserow/templates/_secrets.tpl
  charts/stable/baserow/templates/common.yaml
  charts/stable/bookstack/templates/_secrets.tpl
  charts/stable/bookstack/templates/common.yaml
  charts/stable/ferdi-server/templates/_secrets.tpl
  charts/stable/ferdi-server/templates/common.yaml
  charts/stable/fireflyiii/templates/_secrets.tpl
  charts/stable/fireflyiii/templates/common.yaml
  charts/stable/gitea/templates/_configmap.tpl
  charts/stable/gitea/templates/_secrets.tpl
  charts/stable/gitea/templates/common.yaml
  charts/stable/gotify/templates/_secret.tpl
  charts/stable/gotify/templates/common.yaml
  charts/stable/grist/templates/_config.tpl
  charts/stable/grist/templates/_secret.tpl
  charts/stable/grist/templates/common.yaml
  charts/stable/homebox/templates/_secret.tpl
  charts/stable/homebox/templates/common.yaml
  charts/stable/invidious/templates/_config.tpl
  charts/stable/invidious/templates/common.yaml
  charts/stable/outline/templates/_secrets.tpl
  charts/stable/outline/templates/common.yaml
  charts/stable/owncloud-ocis/templates/_secrets.tpl
  charts/stable/owncloud-ocis/templates/common.yaml
  charts/stable/paperless-ng/templates/_sercrets.tpl
  charts/stable/paperless-ng/templates/common.yaml
  charts/stable/pialert/templates/_secret.tpl
  charts/stable/pialert/templates/common.yaml
  charts/stable/pinry/templates/_secrets.tpl
  charts/stable/pinry/templates/common.yaml
  charts/stable/plexanisync/templates/_secret.tpl
  charts/stable/plexanisync/templates/common.yaml
  charts/stable/recipes/templates/_secrets.tpl
  charts/stable/recipes/templates/_sercrets.tpl
  charts/stable/recipes/templates/common.yaml
  charts/stable/redmine/templates/_secrets.tpl
  charts/stable/redmine/templates/common.yaml
  charts/stable/snipe-it/templates/_secrets.tpl
  charts/stable/snipe-it/templates/common.yaml
  charts/stable/vikunja/templates/_secrets.tpl
  charts/stable/vikunja/templates/common.yaml
  charts/stable/wordpress/templates/_env.tpl
  charts/stable/wordpress/templates/common.yaml
Labels: size/XL, precommit:ok

#7783 feat(portainer-ce): add be image
  charts/stable/portainer-ce/Chart.yaml
  charts/stable/portainer-ce/questions.yaml
  charts/stable/portainer-ce/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#7789 chore(cert-manager): validate names that are also used for k8s objects
  charts/enterprise/cert-manager/Chart.yaml
  charts/enterprise/cert-manager/docs/validation.md
  charts/enterprise/cert-manager/questions.yaml
  charts/enterprise/cert-manager/templates/clusterissuer/_ACME.tpl
  charts/enterprise/cert-manager/templates/clusterissuer/_CA.tpl
  charts/enterprise/cert-manager/templates/clusterissuer/_selfSigned.tpl
Labels: size/S

#7790 fix(portainer-ce): Fix digest on portainer-be image
  charts/stable/portainer-ce/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#7801 Stable fixes
  charts/stable/airsonic-advanced/values.yaml
  charts/stable/aria2/values.yaml
  charts/stable/audiobookshelf/values.yaml
  charts/stable/babybuddy/values.yaml
  charts/stable/blog/values.yaml
  charts/stable/deconz/values.yaml
  charts/stable/dsmr-reader/values.yaml
  charts/stable/etherpad/values.yaml
  charts/stable/filerun/values.yaml
  charts/stable/hedgedoc/templates/_secrets.tpl
  charts/stable/hedgedoc/templates/common.yaml
  charts/stable/hedgedoc/values.yaml
  charts/stable/home-assistant/values.yaml
  charts/stable/jupyter/values.yaml
  charts/stable/kanboard/values.yaml
  charts/stable/kutt/values.yaml
  charts/stable/lanraragi/values.yaml
  charts/stable/lychee/values.yaml
  charts/stable/nextcloud/values.yaml
  charts/stable/odoo/values.yaml
  charts/stable/paperless-ngx/values.yaml
  charts/stable/pialert/values.yaml
  charts/stable/prowlarr/values.yaml
  charts/stable/quassel-core/values.yaml
  charts/stable/recipes/values.yaml
  charts/stable/redmine/values.yaml
  charts/stable/spotweb/values.yaml
  charts/stable/strapi/values.yaml
  charts/stable/teedy/values.yaml
  charts/stable/traccar/values.yaml
  charts/stable/tt-rss/values.yaml
  charts/stable/xwiki/values.yaml
Labels: size/M

#7806 fix(github): Update SUPPORT.md for SCALE versions
  .github/SUPPORT.md
Labels: size/XS, install:ok, lint:ok, precommit:ok

#7808 Update README.md
  .github/README.md
Labels: size/XS, install:ok, lint:ok, precommit:ok

#7811 fix(traefik): fix portal button
  charts/enterprise/traefik/Chart.yaml
  charts/enterprise/traefik/questions.yaml
  charts/enterprise/traefik/templates/common.yaml
  charts/enterprise/traefik/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#7813 fix(cert-manager): add missing providers
  charts/enterprise/cert-manager/Chart.yaml
  charts/enterprise/cert-manager/templates/clusterissuer/_ACME.tpl
Labels: size/XS, install:ok, lint:ok, precommit:ok

#7818 feat(dependency): move solr, clickhouse and mongodb to deployment instead of statefullset
  charts/dependency/clickhouse/Chart.yaml
  charts/dependency/clickhouse/questions.yaml
  charts/dependency/clickhouse/values.yaml
  charts/dependency/mariadb/Chart.yaml
  charts/dependency/memcached/Chart.yaml
  charts/dependency/mongodb/Chart.yaml
  charts/dependency/mongodb/questions.yaml
  charts/dependency/mongodb/values.yaml
  charts/dependency/redis/Chart.yaml
  charts/dependency/solr/Chart.yaml
  charts/dependency/solr/questions.yaml
  charts/dependency/solr/values.yaml
Labels: size/S, lint:ok, precommit:ok

#7819 chore(enterprise): bump common and deps on enterprise train
  charts/enterprise/authelia/Chart.yaml
  charts/enterprise/blocky/Chart.yaml
  charts/enterprise/cert-manager/Chart.yaml
  charts/enterprise/grafana/Chart.yaml
  charts/enterprise/metallb/Chart.yaml
  charts/enterprise/prometheus/Chart.yaml
  charts/enterprise/traefik/Chart.yaml
  charts/enterprise/vaultwarden/Chart.yaml
Labels: size/S, lint:ok, precommit:ok

#7802 feat(lldap) add lldap
  charts/incubator/lldap/.helmignore
  charts/incubator/lldap/Chart.yaml
  charts/incubator/lldap/NOTES.txt
  charts/incubator/lldap/README.md
  charts/incubator/lldap/ci/default-values.yaml
  charts/incubator/lldap/questions.yaml
  charts/incubator/lldap/templates/_secrets.tpl
  charts/incubator/lldap/templates/common.yaml
  charts/incubator/lldap/values.yaml
Labels: install:ok, lint:ok, size/L, precommit:ok

#7823 bug(lldap) update image location
  charts/incubator/lldap/Chart.yaml
  charts/incubator/lldap/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#7816 feat(blocky): allow additional bootstrapdns
  charts/enterprise/blocky/questions.yaml
  charts/enterprise/blocky/templates/_blockyConfig.tpl
  charts/enterprise/blocky/values.yaml
Labels: install:ok, lint:ok, size/M, precommit:ok

#7824 feat(authelia): allow for NTP failure by default
  charts/enterprise/authelia/Chart.yaml
  charts/enterprise/authelia/templates/_configmap.tpl
  charts/enterprise/authelia/values.yaml
Labels: size/XS, install:ok, lint:ok, precommit:ok

#7810 fix(plausible): Remove deprecated config options
  charts/incubator/etesync/Chart.yaml
  charts/incubator/plausible/questions.yaml
  charts/incubator/plausible/templates/_env.tpl
  charts/incubator/plausible/values.yaml
Labels: size/S, precommit:ok

#7835 chore(docs): Update dev docs link in readme
  .github/README.md
Labels: size/XS, install:ok, lint:ok, precommit:ok

#7827 fix(traefik) Fix arguments to fix metrics
  charts/enterprise/traefik/Chart.yaml
  charts/enterprise/traefik/templates/_args.tpl
  charts/enterprise/traefik/values.yaml
Labels: size/S, install:ok, lint:ok, precommit:ok

#7841 fix(cert0manager): correctly reference r53 secret
  charts/enterprise/cert-manager/Chart.yaml
  charts/enterprise/cert-manager/templates/clusterissuer/_ACME.tpl
Labels: size/XS, install:ok, lint:ok, precommit:ok
